src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Compliance__c</fullName>
        <label>Customer Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US_ALTICE</fullName>
                </value>
                <value>
                    <fullName>US_AT&amp;T</fullName>
                </value>
                <value>
                    <fullName>US_Company</fullName>
                </value>
                <value>
                    <fullName>US_Cox</fullName>
                </value>
                <value>
                    <fullName>US_Govern</fullName>
                </value>
                <value>
                    <fullName>US_SCEC</fullName>
                </value>
                <value>
                    <fullName>US_Sprint</fullName>
                </value>
                <value>
                    <fullName>US_T-Mobile</fullName>
                </value>
                <value>
                    <fullName>US_VWireless</fullName>
                </value>
                <value>
                    <fullName>US_VWireline</fullName>
                </value>
                <value>
                    <fullName>unassign</fullName>
                    <default>true</default>
                    <label>Unassign</label>
                </value>
                <value>
                    <fullName>WD_NATO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Market North America</fullName>
                </value>
                <value>
                    <fullName>Market Latin America</fullName>
                </value>
                <value>
                    <fullName>Market Middle East and Africa</fullName>
                </value>
                <value>
                    <fullName>Market India</fullName>
                </value>
                <value>
                    <fullName>Market Greater China</fullName>
                </value>
                <value>
                    <fullName>Market Europe</fullName>
                </value>
                <value>
                    <fullName>Market Asia Pacific &amp; Japan</fullName>
                </value>
                <value>
                    <fullName>Market Other</fullName>
                </value>
                <value>
                    <fullName>Market NFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Legal_Entity</fullName>
        <active>true</active>
        <description>Legal Entity is for Nokia Internal Accounts</description>
        <label>Legal Entity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>HWS_ContractLeadTimeDuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Lead Time Duration</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_ContractLeadTimeUnit__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Lead Time Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_ContractLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Line Item</label>
        <referenceTo>ContractLineItem</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HWS_ExternalStatus__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>External Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_SourceSystem__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HWS_Covered_Part</fullName>
        <active>true</active>
        <description>This will be used for SRM project. Created as part of US.SRM.1290</description>
        <label>Covered Part</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_ServiceType__c.field-meta.xml
<CustomField>
    <fullName>CH_ServiceType__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
                <default>true</default>
                <label>Customer Support</label>
            </value>
            <value>
                <fullName>Internal Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Issue_Reported_By__r.Market__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CH_ContactType__c</fullName>
        <description>Contact Type Ref: 4989</description>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                    <default>true</default>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
                <value>
                    <fullName>Nokia Employee</fullName>
                </value>
                <value>
                    <fullName>Sub-Contractor</fullName>
                </value>
                <value>
                    <fullName>No Relationship</fullName>
                </value>
                <value>
                    <fullName>Secondary Account</fullName>
                </value>
                <value>
                    <fullName>Communication Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>Set the contact Active or Inactive</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Req #1313. Required for Marketo Sync</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MARKET NORTH AMERICA</fullName>
                </value>
                <value>
                    <fullName>MARKET EUROPE</fullName>
                </value>
                <value>
                    <fullName>MARKET GREATER CHINA</fullName>
                </value>
                <value>
                    <fullName>MARKET INDIA</fullName>
                </value>
                <value>
                    <fullName>MARKET LATIN AMERICA</fullName>
                </value>
                <value>
                    <fullName>MARKET MIDDLE EAST AND AFRICA</fullName>
                </value>
                <value>
                    <fullName>MARKET ASIA PACIFIC &amp; JAPAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContractLineItem.object
<CustomObject>
    <fields>
        <fullName>CH_BusinessHour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CDB will send the Salesforce Business Hours name and we need to do a lookup against the Salesforce Business Hours based on the Business Hours name.</description>
        <label>Business Hour</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_ServiceClassification__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Classification</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_ServiceType__c</fullName>
        <description>Service Type</description>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Internal Support</fullName>
                </value>
                <value>
                    <fullName>Advanced Exchange in Days</fullName>
                </value>
                <value>
                    <fullName>Advanced Exchange in Hours</fullName>
                </value>
                <value>
                    <fullName>Return for Repair or Replacement</fullName>
                </value>
                <value>
                    <fullName>Spare Part Sales</fullName>
                </value>
                <value>
                    <fullName>MVR Identical Repair</fullName>
                </value>
                <value>
                    <fullName>Return for Exchange</fullName>
                </value>
                <value>
                    <fullName>Identical Repair</fullName>
                </value>
                <value>
                    <fullName>Eco Repair</fullName>
                </value>
                <value>
                    <fullName>Return for Modification</fullName>
                </value>
                <value>
                    <fullName>Dead On Arrival, Advanced Exchange in Days</fullName>
                </value>
                <value>
                    <fullName>Dead on Arrival, Return for Repair or Replacement</fullName>
                </value>
                <value>
                    <fullName>Return for Upgrade</fullName>
                </value>
                <value>
                    <fullName>Return for Certification</fullName>
                </value>
                <value>
                    <fullName>MVR Return for Repair or Replacement</fullName>
                </value>
                <value>
                    <fullName>Commissioning Spares</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NCP_External_Status__c</fullName>
        <description>Nokia Support Portal specific field</description>
        <inlineHelpText>Nokia Support Portal specific field</inlineHelpText>
        <label>External Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/HWS_VersionItem__c.object
<CustomObject>
    <fields>
        <fullName>HWS_Hardware_Sellable_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hardware Part Item</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Version Items</relationshipLabel>
        <relationshipName>HWS_VersionItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HWS_Serial_Number_Traceable__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Serial Number Traceable</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_Source__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_Version_Code__c</fullName>
        <description>Created as the part of the US.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Version Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Version Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ISO_Country_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Country_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Country Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ISO Country Codes</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>HWS_Source__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>NCP_External_Status__c</fullName>
        <label>External Status SP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/HWS_Utilty_TEST.cls
@istest
public class HWS_Utilty_TEST {
	@testSetup static void testDataSetup(){
		Id customerAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.Customer);
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		Id assetRecordType = HWS_Utilty.getRecordTypeByName('Asset','HWS_Covered_Part');
		List<ISO_Country_Codes__c> listISO = new List<ISO_Country_Codes__c>();
		ISO_Country_Codes__c setting = new ISO_Country_Codes__c();
		setting.Name = 'IN';
		setting.Country_Name__c = 'India';
		setting.Market__c='Market India';
		listISO.add(setting);
		ISO_Country_Codes__c setting1 = new ISO_Country_Codes__c();
		setting1.Name = 'AG';
		setting1.Country_Name__c = 'Antigua And Barbuda';
		setting1.Market__c='Market Latin America';
		listISO.add(setting1);
		insert listISO;
		Account acc = HWS_DataFactory_TEST.insertAccount(); 
		acc.RecordTypeId =  customerAccountType;
		acc.Customer_Compliance__c = 'US_AT&T';
		insert acc;
		
		Account acc1 = HWS_DataFactory_TEST.insertAccount(); 
		acc1.RecordTypeId =  legalEntityAccountType;
		acc1.ParentId = acc.Id;
		acc1.Name = 'TestLE';
		insert acc1;
		
		Account logisticAcc = HWS_DataFactory_TEST.createLogisticAccount();
		logisticAcc.Name = 'Test Logistic Account';
		logisticAcc.ParentId = acc.Id;
		logisticAcc.AccountSource = 'eSpares';
		logisticAcc.Market__c = 'Market India';
		insert logisticAcc;
		Contact con = HWS_DataFactory_TEST.insertContact();
		con.AccountId = acc.Id;
		con.Contact_Status__c = 'Active';
		con.CH_ContactType__c = 'Customer';
		con.email='xyz@example.com';
		insert con;
		
		BusinessHours bhs=[select Id from BusinessHours where IsDefault=true];
		BusinessHours bhs1=[select Id from BusinessHours where IsDefault=false limit 1];
		Product2 prod = HWS_DataFactory_TEST.insertproduct2();   
		prod.ProductCode = 'ABCDEFGH';
		insert prod;			   
		
		PriceBook2 pb = HWS_DataFactory_TEST.createPriceBook(); 
		pb.IsActive = true;
		insert pb;   
		//Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];		
		PricebookEntry pbety = HWS_DataFactory_TEST.createPriceBookEntry(prod.id, pb.Id);		
		pbety.CurrencyIsoCode='EUR'; 
		pbety.UseStandardPrice = false;
		pbety.Pricebook2Id = Test.getStandardPricebookId();
		insert pbety;  
		
		ServiceContract sc = HWS_DataFactory_TEST.insertServiceContract(acc1);		
		sc.Pricebook2Id = Test.getStandardPricebookId();
		sc.NCP_External_Status__c = 'Active';
		sc.CurrencyIsoCode = 'EUR';
		insert sc;
		
		ContractLineItem cli = HWS_DataFactory_TEST.insertContractLineItem(sc,pbety);		
		cli.PricebookEntryId = pbety.id;  
		cli.CH_ServiceType__c = 'Advanced Exchange in Days';
		cli.NCP_External_Status__c='Active';
		cli.CH_ServiceClassification__c='HWS Service';
		cli.CH_BusinessHour__c = bhs1.Id;
		insert cli;
		
		Asset ast = HWS_DataFactory_TEST.insertAsset(acc1,prod);		
		ast.RecordTypeId = assetRecordType;	 
		ast.Product2Id = prod.Id;
		ast.HWS_SourceSystem__c = 'Puma1';
		ast.HWS_ContractLineItem__c = cli.Id;
		ast.HWS_ExternalStatus__c = 'Active';
		ast.HWS_ContractLeadTimeUnit__c = 'Business Days';
		ast.HWS_ContractLeadTimeDuration__c = '1';
		insert ast; 
		
		HWS_VersionItem__c hwsv = HWS_DataFactory_TEST.insertHwsversionitem();
		hwsv.HWS_Serial_Number_Traceable__c='';  
		hwsv.HWS_Hardware_Sellable_Item__c = prod.Id;
		hwsv.HWS_Source__c = 'PUMA1';
		hwsv.HWS_Version_Code__c = 'ABCDEFGH';
		insert hwsv;
		
		Entitlement ent = new Entitlement();
		ent.Name = 'HWS Advance Exchange in Hours';
		ent.AccountId = acc1.id;
		ent.AssetId = ast.Id;
		ent.CH_CDB_EntitlementId__c = '1234';
		ent.CH_ServiceMappingId__c = 'Advanced Exchange in Hours';
		insert ent;
		
		EntitlementContact entContact = new EntitlementContact();
		entContact.EntitlementId = ent.Id;
		entContact.ContactId = con.Id;
		insert entContact;
		
		Case parentCase = HWS_DataFactory_TEST.insertParentCase();
		parentCase.AccountId = acc1.id;
		insert parentCase;
	}
	
	public static testmethod void getTestMethods(){
		Account acc = [Select Id from Account where Name = 'TestLE'];
		Account logisticAcc = [Select Id from Account where Name = 'Test Logistic Account'];
		Contact cont = [Select Id from Contact limit 1];
		Set<Id> accIdSet = new Set<Id>();
		accIdSet.add(acc.Id);
		List<String> shiptoAddrList = new List<String>();
		shiptoAddrList.add(logisticAcc.Id);
		test.startTest();
		HWS_Utilty.getAccounts(accIdSet);
		HWS_Utilty.getAccountContactsRelation(cont.Id,acc.Id);
		HWS_Utilty.accountToShare(shiptoAddrList);
		HWS_Utilty.getEntitlementContact(cont.Id,acc.Id);
		test.stopTest();
	} 

	public static testmethod void getAllServiceTypesTest(){
		Account acc = [Select Id from Account where Name = 'TestLE'];
		Contact cont = [Select Id from Contact limit 1];
		Product2 prod = [Select Id from Product2 limit 1];
		Set<Id> accIdSet = new Set<Id>();
		accIdSet.add(acc.Id);
		Set<Id> prodIdSet = new Set<Id>();
		prodIdSet.add(prod.Id);
		Set<String> authServContrNumSet = new Set<String>();
		authServContrNumSet.add('abcd');
		test.startTest();
		HWS_Utilty.getAllServiceTypes(prodIdSet,accIdSet);
		HWS_Utilty.getAllServiceTypes(prodIdSet,accIdSet,'Advanced Exchange in Days','00000052',cont.Id, 'Slovakia');
		HWS_Utilty.getAllServiceTypesAuthLegalEntity(prodIdSet,accIdSet,'Advanced Exchange in Days','00000052',authServContrNumSet);
		test.stopTest();
	}
	
	public static testmethod void plannedDeliveryDateTimeTest(){
		BusinessHours bhs=[select Id from BusinessHours where IsDefault=true];
		List<BusinessHours> bHours=new List<BusinessHours>();
		Date dTest=Date.valueof(system.today());
		test.startTest();
		HWS_Utilty.plannedDeliveryDateTime(bhs.ID,'Business Days','10',dTest,null);
		HWS_Utilty.plannedDeliveryDateTime(bhs.ID,'Hours','10',dTest,null);
		HWS_Utilty.plannedDeliveryDateTime(bhs.ID,'Minutes','10',dTest,null);
		HWS_Utilty.plannedDeliveryDateTime(bhs.ID,'Business Days','10',dTest,'2:10');
		HWS_Utilty.plannedDeliveryDateTime(bhs.ID,'Calendar Days','10',dTest,'2:10');
		HWS_Utilty.plannedDeliveryDateTime(bhs.ID,'Calendar Days','10',dTest,null);
		test.stopTest();
	}
	
	public static testmethod void getVersionItemsTest(){
		HWS_VersionItem__c hvi = [Select Id from HWS_VersionItem__c limit 1];
		Product2 prod = [Select Id from Product2 limit 1];
		Set<Id> sellableItemIdSet = new Set<Id>();
		List<String> versionCodeList = new List<String>();
		sellableItemIdSet.add(prod.Id); 
		versionCodeList.add('test');
		test.startTest();
		HWS_Utilty.getVersionItems(sellableItemIdSet,'PUMA1',versionCodeList);
		HWS_Utilty.childRecordTypes('Advanced Exchange In Hours');
		test.stopTest();
	}
	
	public static testmethod void getserviceContractsTest(){
		Account acc = [Select Id from Account where Name = 'TestLE'];
		Contact cont = [Select Id from Contact limit 1];
		ContractLineItem cli = [Select Id from ContractLineItem limit 1];
		Product2 prod = [Select Id from Product2 limit 1];
		Set<Id> accIdSet = new Set<Id>();
		accIdSet.add(acc.Id);
		Set<Id> cliIdSet = new Set<Id>();
		cliIdSet.add(cli.Id);
		Set<Id> prodIdSet = new Set<Id>();
		prodIdSet.add(prod.Id);
		test.startTest();
		HWS_Utilty.getserviceContracts('00000052',accIdSet,'Advanced Exchange in Days','00000052',cont.Id);
		HWS_Utilty.getserviceContractsInactive('00000052',accIdSet,'Advanced Exchange in Days');
		HWS_Utilty.getserviceContractsPortal('00000052',acc.Id,'Advanced Exchange in Days','00000052',cont.Id);
		HWS_Utilty.getserviceContractsInactivePortal('00000052',acc.Id,'Advanced Exchange in Days');
		HWS_Utilty.getServiceTypes(cliIdSet);
		HWS_Utilty.getAllServiceTypesPortal(prodIdSet,acc.Id,'Advanced Exchange in Days','00000052',cont.Id, 'Slovakia');
		HWS_Utilty.getDependentMap(acc,'BillingCountryCode','BillingStateCode');
		test.stopTest();
	}
	
	public static testmethod void getContractlineItemsPartCodeRevisionTest(){
		Account acc = [Select Id from Account where Name = 'TestLE'];
		Contact cont = [Select Id from Contact limit 1];
		HWS_VersionItem__c hvi = [Select Id,HWS_Version_Code__c from HWS_VersionItem__c limit 1];
		List<Account> accList = new List<Account>();
		accList.add(acc);
		test.startTest();
		HWS_Utilty.getContractlineItemsPartCodeRevision(accList,'ABCDEFGH','Advanced Exchange in Days','00000052',cont.Id,'Portal', 'Slovakia');
		hvi.HWS_Version_Code__c = 'ANY';
		update hvi;
		HWS_Utilty.getContractlineItemsPartCodeRevision(accList,'ABCDEFGH','Advanced Exchange in Days','00000052',cont.Id,'Portal', 'Slovakia' );
		test.stopTest();
	}
	 /*@isTest
		public static void plannedDeliveryDateTimeBulkTest(){
		 
		 BusinessHours bhs=[select Id from BusinessHours where IsDefault=true];
			
		List<HWS_BulkUpload__c> buToInsertLst = new List<HWS_BulkUpload__c>();
		HWS_BulkUpload__c bu = new HWS_BulkUpload__c();
		bu.Part_Code_Part_Revision__c = '3HQ14903AAAAV1232019';
		bu.HWS_ServiceType__c = 'Advanced Exchange in Days';
		buToInsertLst.add(bu);
		Date dTest=Date.valueof(system.today());
			
		List<BusinessHours> brToInsertLst = new List<BusinessHours>();
	   BusinessHours br = new BusinessHours();
		  br.Name='VI | Mon-Fri 0800-1800 | America/Puerto_Rico | H';
		  br.TimeZoneSidKey='(GMT-04:00) Atlantic Standard Time (America/Puerto_Rico)';
		  brToInsertLst.add(br);
	   
			
		bu.Part_Code_Part_Revision__c = 'aDM5C00000000W8WAI';
		bu.HWS_ServiceType__c = 'Return for Repair or Replacement';
		bu.HWS_Asset__c	='02i5C000001rR6EQAU';
		bu.HWS_Contract_Line_Item__c  ='8115C000000LVU2QAO';
		buToInsertLst.add(bu);
		test.startTest();
			
		HWS_Utilty.plannedDeliveryDateTimeBulk(buToInsertLst);
	   
		test.stopTest();
	}*/
	public static testmethod void accountTimeZoneplannedDeliveryDateTimeTest(){
		List<BusinessHours> listBusinessHours = [SELECT Id,TimeZoneSidKey,Name FROM BusinessHours];
		Account acc1 = [Select Id from Account where Name = 'TestLE'];
		
		Account acc = [Select Id from Account where Name = 'Test Logistic Account'];
		Asset assetRec = [Select Id,HWS_ContractLineItem__r.CH_BusinessHour__c from Asset];
		Case childCasetoInsert = HWS_DataFactory_TEST.insertChildCase();
		childCasetoInsert.AssetId= assetRec.Id;
		List<Case>  listCase = new List<Case>();
		listCase.add(childCasetoInsert);
		test.startTest();
		//CollaborationGroup BHConversion = new CollaborationGroup(Name = 'Error - BH Conversion', CollaborationType = 'Private', CanHaveGuests = false, IsArchived = false, IsAutoArchiveDisabled = true );
		//insert BHConversion;
		HWS_Utilty.accountTimeZoneplannedDeliveryDateTime(listCase,'Asia/Kolkata');
		HWS_Utilty.accountTimeZoneplannedDeliveryDateTime(listCase,'America/Puerto_Rico');
		HWS_Utilty.updateTimeZone(acc.Id);
		HWS_Utilty.HWS_postGoogleErrorToChatter('Google Api Error!!!');
		test.stopTest();
	}
}