src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Cable Operator</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Large Enterprise</label>
                </value>
                <value>
                    <fullName>Small / Medium Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Small / Medium Enterprise</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CloneObject__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Req #1237,1239,1240</description>
    <fields>
        <fullName>Field_API__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Field API</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Object</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CloneRecord</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Role__c</fullName>
        <inlineHelpText>Here there is additional information on Account Role definitions:

http://nok.it/iDcjm-</inlineHelpText>
        <label>Account Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alliance Partner</fullName>
                    <label>Alliance</label>
                </value>
                <value>
                    <fullName>Disti+SPaaP</fullName>
                </value>
                <value>
                    <fullName>Disti+VAR</fullName>
                </value>
                <value>
                    <fullName>GPP Distributor Partner</fullName>
                    <label>Distributor</label>
                </value>
                <value>
                    <fullName>ENaSP</fullName>
                </value>
                <value>
                    <fullName>Global Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Industrial partner</fullName>
                    <label>Industrial Partner</label>
                </value>
                <value>
                    <fullName>Other PSA</fullName>
                    <label>Integrator</label>
                </value>
                <value>
                    <fullName>NFS-SPaaP</fullName>
                </value>
                <value>
                    <fullName>Project Specific</fullName>
                </value>
                <value>
                    <fullName>GPP SPAAP partner</fullName>
                    <label>SPaaP</label>
                </value>
                <value>
                    <fullName>GPP VAR partner</fullName>
                    <label>VAR</label>
                </value>
                <value>
                    <fullName>VAR+SPaaP</fullName>
                </value>
                <value>
                    <fullName>WaaP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Opportunity</fullName>
                </value>
                <value>
                    <fullName>Committed Upsell</fullName>
                </value>
                <value>
                    <fullName>Forecasting Only</fullName>
                    <isActive>false</isActive>
                    <label>Forecasting Only</label>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Large Enterprise</label>
                </value>
                <value>
                    <fullName>Opportunity with Pre-approved or contracted T&amp;Cs</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity with Pre-approved or contracted T&amp;Cs</label>
                </value>
                <value>
                    <fullName>Opportunity within a framework contract</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity within a framework contract</label>
                </value>
                <value>
                    <fullName>Opportunity within partner agreement w/o Offer Support</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity within partner agreement w/o Offer Support</label>
                </value>
                <value>
                    <fullName>Pre-approved Pice List for BG Presales</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Pice List for BG Presales</label>
                </value>
                <value>
                    <fullName>Pre-approved Pice List for Sales</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Pice List for Sales</label>
                </value>
                <value>
                    <fullName>Pre-approved Price List for Account Managers</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Price List for Account Managers</label>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                    <isActive>false</isActive>
                    <label>Service Provider</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Signing_Entity__c</fullName>
        <description>Req::802 This flag / field shall identify the Legal Entity</description>
        <inlineHelpText>Based on the ERP system used to execute/deliver the orders. 
For example - If Order execution/Customer invoicing is done using fNOK SAP P20 system then select fNOK otherwise, if using fALU SAP BPP system then select fALU.</inlineHelpText>
        <label>Contract Signing Entity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>fALU</fullName>
                </value>
                <value>
                    <fullName>fNOK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>G3_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G3 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G4_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G4 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G5_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Expected date for contract signing or other legally binding document (e.g. first PO)</inlineHelpText>
        <label>Win Declaration Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G6_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities
4372: Help text for G6 Planned Date</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>G6 Planned Date cannot be edited prior to G5 Approval.</inlineHelpText>
        <label>G6 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req 569: User will select Lead BG manually</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BU__c</fullName>
        <description>Selection of group within MN to lead on approvals. Mandatory selection from drop-down list if MN or ION are chosen as the Lead BG</description>
        <label>Lead BU</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_BG__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Business_Units</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityTeamMember.object
<CustomObject>
    <fields>
        <fullName>Additional_Team_Role__c</fullName>
        <description>Req 665: This will help to add user with different role</description>
        <label>Additional Team Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Account Manager (TRICORN Sales Case Owner (SCO))</fullName>
                </value>
                <value>
                    <fullName>BG Business Controller RBC</fullName>
                </value>
                <value>
                    <fullName>BG Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>BG Sales &amp; Business Development</fullName>
                </value>
                <value>
                    <fullName>Bid Manager</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                    <isActive>false</isActive>
                    <label>Business Development</label>
                </value>
                <value>
                    <fullName>Commercial Contract Manager (L&amp;C)</fullName>
                </value>
                <value>
                    <fullName>Commercial Contract Manager and Legal</fullName>
                    <isActive>false</isActive>
                    <label>Commercial Contract Manager and Legal</label>
                </value>
                <value>
                    <fullName>Commercial Deal Manager Commercial War Room</fullName>
                    <isActive>false</isActive>
                    <label>Commercial Deal Manager Commercial War Room</label>
                </value>
                <value>
                    <fullName>CT Head</fullName>
                </value>
                <value>
                    <fullName>Customer CTO</fullName>
                </value>
                <value>
                    <fullName>Customer Quality Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Supply Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Team Controller</fullName>
                    <isActive>false</isActive>
                    <label>Customer Team Controller</label>
                </value>
                <value>
                    <fullName>E2E Solution Manager</fullName>
                    <isActive>false</isActive>
                    <label>E2E Solution Manager</label>
                </value>
                <value>
                    <fullName>G3 Facilitator</fullName>
                </value>
                <value>
                    <fullName>G4 G5 Facilitator</fullName>
                    <isActive>false</isActive>
                    <label>G4 G5 Facilitator</label>
                </value>
                <value>
                    <fullName>Global Sales Support MU Lead</fullName>
                </value>
                <value>
                    <fullName>Head of Sales</fullName>
                    <isActive>false</isActive>
                    <label>Head of Sales</label>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Offer Controller</fullName>
                </value>
                <value>
                    <fullName>One Customer Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Partner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager (Lead)</fullName>
                </value>
                <value>
                    <fullName>Project Contract Manager</fullName>
                </value>
                <value>
                    <fullName>Project Execution Owner</fullName>
                    <isActive>false</isActive>
                    <label>Project Execution Owner</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/classes/CloneOpportunityTest.cls
@istest
Private class CloneOpportunityTest 
{
	private static List<File_Sharing_Custom_Setting__c> fileSharingCustomSettingList = new List<File_Sharing_Custom_Setting__c>();
	//private static List<CloneObject__c> CloneRecord = new List<CloneObject__c>();
	private static final Id directRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.DIRECT_OPPTY).getRecordTypeId();
	private static final Id inDirectRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.INDIRECT_OPPTY).getRecordTypeId();
	private static List<Opportunity> optyCreation = new list<Opportunity>();
	private static List<OpportunityTeamMember> optyTeamList= new List<OpportunityTeamMember>();
	
	static testMethod void cloneOptyForDirectTest()
	{
		//List<OpportunityTeamMember> optyTeamList= new List<OpportunityTeamMember>();
		List<user> userCreation = TestDataFactory.userCreation(2,'System Administrator');
		insert userCreation;
		System.runAs(userCreation[0])
		{			
			List<CloneObject__c> CloneRecord = new List<CloneObject__c>();
			CloneObject__c cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'CloseDate';
			cloneObj.Name = 'CloseDate';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Name';
			cloneObj.Name = 'Test1';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G3_Planned_Date__c';
			cloneObj.Name = 'G3_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G4_Planned_Date__c';
			cloneObj.Name = 'G4_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G5_Planned_Date__c';
			cloneObj.Name = 'G5_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G6_Planned_Date__c';
			cloneObj.Name = 'G6_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Amount';
			cloneObj.Name = 'Amount';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'AccountId';
			cloneObj.Name = 'AccountId';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Contract_Signing_Entity__c';
			cloneObj.Name = 'Contract_Signing_Entity__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Business_Type__c';
			cloneObj.Name = 'Business_Type__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'RecordTypeId';
			cloneObj.Name = 'RecordTypeId';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Lead_BG__c';
			cloneObj.Name = 'Lead_BG__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Lead_BU__c';
			cloneObj.Name = 'Lead_BU__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			database.insert(CloneRecord);
			Account accountCreation = TestDataFactory.createAccount(1)[0];
			insert accountCreation;
			optyCreation = TestDataFactory.OpportunityCreation(1,accountCreation);
			//optyCreation[0].Lead_BG__c=GlobalConstants.LEAD_BG_MN;
			optyCreation[0].recordTypeId = directRecordTypeId;
			insert optyCreation;
			
			optyTeamList = TestDataFactory.optyTeamMemberCreation(2,userCreation[1],optyCreation[0]);
			optyTeamList[0].UserId = userCreation[0].Id;
			//optyTeamList[0].Additional_Team_Role__c = GlobalConstants.TRICON_SCO_ROLE+GlobalConstants.Semicolon+'Business Development';
			optyTeamList[0].Additional_Team_Role__c = 'Account Manager (TRICORN Sales Case Owner (SCO))'+GlobalConstants.Semicolon+'Business Development';
			optyTeamList[0].TeamMemberRole = 'Bid Manager';
			insert(optyTeamList);
			Opportunity opp = TestDataFactory.OpportunityCreation(1,accountCreation)[0];
			database.insert(opp);
			test.startTest();
			CloneOpportunity.getCloneOpp(optyCreation[0].id);
			CloneOpportunity.cloneOpportunityTeam(opp.id,optyCreation[0].id);
			CloneOpportunity.cloneOpportunityTeam(null,optyCreation[0].id);  
			test.stopTest();
		}
		
	}
	static testMethod void cloneOptyForIndirectTest()
	{
		//List<OpportunityTeamMember> optyTeamList= new List<OpportunityTeamMember>();
		user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		System.runAs(userCreation)
		{			
			List<CloneObject__c> CloneRecord = new List<CloneObject__c>();
			CloneObject__c cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'CloseDate';
			cloneObj.Name = 'CloseDate';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Name';
			cloneObj.Name = 'Test1';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G3_Planned_Date__c';
			cloneObj.Name = 'G3_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G4_Planned_Date__c';
			cloneObj.Name = 'G4_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G5_Planned_Date__c';
			cloneObj.Name = 'G5_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G6_Planned_Date__c';
			cloneObj.Name = 'G6_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Amount';
			cloneObj.Name = 'Amount';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'AccountId';
			cloneObj.Name = 'AccountId';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Contract_Signing_Entity__c';
			cloneObj.Name = 'Contract_Signing_Entity__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Business_Type__c';
			cloneObj.Name = 'Business_Type__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'RecordTypeId';
			cloneObj.Name = 'RecordTypeId';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Lead_BG__c';
			cloneObj.Name = 'Lead_BG__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Lead_BU__c';
			cloneObj.Name = 'Lead_BU__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Account_Role__c';
			cloneObj.Name = 'Account_Role__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'End_Customer__c';
			cloneObj.Name = 'End_Customer__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Indirect';
			CloneRecord.add(cloneObj);
			database.insert(CloneRecord);
			Account accountCreation = TestDataFactory.createAccount(1)[0];
			insert accountCreation;
			optyCreation = TestDataFactory.OpportunityCreation(1,accountCreation);
			//optyCreation[0].Lead_BG__c=GlobalConstants.LEAD_BG_MN;
			optyCreation[0].recordTypeId = inDirectRecordTypeId;
			insert optyCreation;
			
			optyTeamList = TestDataFactory.optyTeamMemberCreation(1,userCreation,optyCreation[0]);			
			insert(optyTeamList);
			Opportunity opp = TestDataFactory.OpportunityCreation(1,accountCreation)[0];
			database.insert(opp);
			test.startTest();
			CloneOpportunity.getCloneOpp(optyCreation[0].id);
			CloneOpportunity.cloneOpportunityTeam(opp.id,optyCreation[0].id);	
			test.stopTest();
		}
		
	}
	
	
	static testMethod void cloneClosedOppty()
	{
		//List<OpportunityTeamMember> optyTeamList= new List<OpportunityTeamMember>();
		user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		System.runAs(userCreation)
		{			
			List<CloneObject__c> CloneRecord = new List<CloneObject__c>();
			CloneObject__c cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'CloseDate';
			cloneObj.Name = 'CloseDate';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Name';
			cloneObj.Name = 'Test1';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G3_Planned_Date__c';
			cloneObj.Name = 'G3_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G4_Planned_Date__c';
			cloneObj.Name = 'G4_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G5_Planned_Date__c';
			cloneObj.Name = 'G5_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'G6_Planned_Date__c';
			cloneObj.Name = 'G6_Planned_Date__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Amount';
			cloneObj.Name = 'Amount';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'AccountId';
			cloneObj.Name = 'AccountId';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Contract_Signing_Entity__c';
			cloneObj.Name = 'Contract_Signing_Entity__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Business_Type__c';
			cloneObj.Name = 'Business_Type__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'RecordTypeId';
			cloneObj.Name = 'RecordTypeId';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Lead_BG__c';
			cloneObj.Name = 'Lead_BG__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			cloneObj = new CloneObject__c();
			cloneObj.Field_API__c = 'Lead_BU__c';
			cloneObj.Name = 'Lead_BU__c';
			cloneObj.Object__c = 'Opportunity';
			cloneObj.Record_Type__c = 'Direct';
			CloneRecord.add(cloneObj);
			database.insert(CloneRecord);
			Account accountCreation = TestDataFactory.createAccount(1)[0];
			insert accountCreation;
			optyCreation = TestDataFactory.OpportunityCreation(1,accountCreation);
			optyCreation[0].recordTypeId = directRecordTypeId;
			optyCreation[0].Amount = 0;
			insert optyCreation;
			
			optyCreation[0].stageName = GlobalConstants.CANCELLED_BY_CUSTOMER;
			update optyCreation[0];
			
			test.startTest();
			CloneOpportunity.getCloneOpp(optyCreation[0].id);
			test.stopTest();
		}
		
	}
	
	
	static testMethod void cloneOptyTestNegative()
	{
		try
		{
			user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
			insert userCreation;
			system.runAs(userCreation)
			{  
	CloneOpportunity.getCloneOpp(null);
	CloneOpportunity.cloneOpportunityTeam(null,null);
			}
		}
		Catch(Exception ex){
			system.debug('Exception :: '  +  ex);
		}  
	}
	static testMethod void cloneOptyTestNonSalesProfile()
	{
		try
		{
			List<OpportunityTeamMember> optyTeamList= new List<OpportunityTeamMember>();
			user userCreation = TestDataFactory.userCreation(1,'Non-Sales User Profile')[0];
			insert userCreation;
			system.runAs(userCreation)
			{			
	Account accountCreation = TestDataFactory.createAccount(1)[0];
	insert accountCreation;
	list<Opportunity> optyCreation = TestDataFactory.OpportunityCreation(1,accountCreation);
	insert optyCreation;
	optyTeamList = TestDataFactory.optyTeamMemberCreation(1,userCreation,optyCreation[0]);
	insert(optyTeamList);
	//Updating oppty with PTA= True and stage to'Handover (Prepare for Delivery)'
	
	Opportunity opp = TestDataFactory.OpportunityCreation(1,accountCreation)[0];
	database.insert(opp);
	test.startTest();
	CloneOpportunity.getCloneOpp(optyCreation[0].id);
	CloneOpportunity.cloneOpportunityTeam(opp.id,optyCreation[0].id);	
	test.stopTest();
			}
			
		}   
		Catch(Exception ex)
		{
			system.debug('Exception :: '  +  ex); 
		}		
	}
}