src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Acc_No__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Account number-field as a copy of the AccountNumber-field to be used as external identifier in the integrations of related systems looking up account data in Salesforce. Projects involved: Case Handling and Support Portal.
Initially 2017 only used for data migration upsert capability.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Acc No</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Customer_Compliance__c</fullName>
        <label>Customer Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US_ALTICE</fullName>
                </value>
                <value>
                    <fullName>US_AT&amp;T</fullName>
                </value>
                <value>
                    <fullName>US_Company</fullName>
                </value>
                <value>
                    <fullName>US_Cox</fullName>
                </value>
                <value>
                    <fullName>US_Govern</fullName>
                </value>
                <value>
                    <fullName>US_SCEC</fullName>
                </value>
                <value>
                    <fullName>US_Sprint</fullName>
                </value>
                <value>
                    <fullName>US_T-Mobile</fullName>
                </value>
                <value>
                    <fullName>US_VWireless</fullName>
                </value>
                <value>
                    <fullName>US_VWireline</fullName>
                </value>
                <value>
                    <fullName>unassign</fullName>
                    <default>true</default>
                    <label>Unassign</label>
                </value>
                <value>
                    <fullName>WD_NATO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Send_Check__c</fullName>
        <description>Created as per the requirement in the US (HWST-1340)</description>
        <label>Email Preferences</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Order Confirmation</fullName>
                </value>
                <value>
                    <fullName>Shipment confirmation</fullName>
                </value>
                <value>
                    <fullName>ETA update</fullName>
                </value>
                <value>
                    <fullName>Reminder to send faulty part</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HWS_Address_Status__c</fullName>
        <label>Address Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Temporary Address</fullName>
                    <label>Temporary</label>
                </value>
                <value>
                    <fullName>Permanent Address</fullName>
                    <label>Permanent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P20_Logistic_ID__c</fullName>
        <description>P20 ID for Logistic accounts</description>
        <encryptionScheme>None</encryptionScheme>
        <label>P20 Logistic ID</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>HWS_SourceSystem__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HWS_Covered_Part</fullName>
        <active>true</active>
        <description>This will be used for SRM project. Created as part of US.SRM.1290</description>
        <label>Covered Part</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/HWS_Communication_Contact__c.field-meta.xml
<CustomField>
    <fullName>HWS_Communication_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created with reference to the User Story.</description>
    <label>Communication Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Support Ticket</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_Customer_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_Customer_Reference_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer&apos;s Own Identifier for the Service Request.</inlineHelpText>
    <label>Customer Reference Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Faulty_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_Faulty_Serial_Number__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Serial Number of the faulty Unit</inlineHelpText>
    <label>Faulty Unit Serial Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_FaultyUnitReceivedDate__c.field-meta.xml
<CustomField>
    <fullName>HWS_FaultyUnitReceivedDate__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date on which faulty material was received.</inlineHelpText>
    <label>Faulty Unit Received Date</label>
    <type>Date</type>
</CustomField>

src/objects/Case/fields/HWS_OrderConfirmationSent__c.field-meta.xml
<CustomField>
    <fullName>HWS_OrderConfirmationSent__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Order Confirmation Sent</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/HWS_ReturnAddressReceivedFromSOO__c.field-meta.xml
<CustomField>
    <fullName>HWS_ReturnAddressReceivedFromSOO__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created with reference to the User Story.</description>
    <label>Return Address Received From SOO</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/HWS_RMA_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_RMA_Number__c</fullName>
    <description>Created as the part of the US.SRM.1049</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RMA Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Sellable_Product__c.field-meta.xml
<CustomField>
    <fullName>HWS_Sellable_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created with the reference to the US.</description>
    <inlineHelpText>Sellable Item Description</inlineHelpText>
    <label>Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sellable Product</relationshipLabel>
    <relationshipName>Sellable_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Hws_Ship_to_Party_Address__c.field-meta.xml
<CustomField>
    <fullName>Hws_Ship_to_Party_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US.SRM.1363</description>
    <inlineHelpText>Select address for delivery of replacement Unit</inlineHelpText>
    <label>Ship to Party Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Logistic_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Support Tickets</relationshipLabel>
    <relationshipName>Hws_Ship_to_Part_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_ShipTopartyId__c.field-meta.xml
<CustomField>
    <fullName>HWS_ShipTopartyId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ship To Party Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/classes/HWS_OrderConfirmationNotificationTest.cls
@isTest
public class HWS_OrderConfirmationNotificationTest {
	@isTest
	static void testOrderConfirmationNotification(){
		
		Test.startTest();
			Id parentCase = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_PARENT_CASE);
			Id exchangeInHours = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_ADVANCE_EXCHANGE_IN_HOURS);
			Id childCaseReadonly=HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_CHILD_CASE_READ_ONLY);
			Id parentCaseReadOnly = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_PARENT_CASE_READ_ONLY);
			Id assetRecordType = HWS_Utilty.getRecordTypeByName('Asset','HWS_Covered_Part');
			//Customer Account
			Account acc = HWS_DataFactory_TEST.createAccountRec();			
			acc.Customer_Compliance__c = 'US_AT&T';	
			acc.Acc_No__c = '2345';
			acc.P20_Logistic_ID__c = '12340';
			acc.name='test';	 
			acc.HWS_Address_Status__c = 'Permanent Address';
			acc.BillingCountry = 'India';
			acc.BillingStreet = 'Test';
			acc.BillingCity ='Test';
			acc.BillingPostalCode = '1234';
			acc.Email_Send_Check__c = 'Order Confirmation';
			insert acc;
			
			System.assertEquals(acc.BillingPostalCode, '1234');
			
			//Logistic Account
			Account logAcc = HWS_DataFactory_TEST.createLogisticAccount(); 
			logAcc.Acc_No__c = '23456123';
			logAcc.P20_Logistic_ID__c = '12345';
			logAcc.name='test';	 
			logAcc.HWS_Address_Status__c = 'Permanent Address';
			logAcc.BillingCountry = 'India';
			logAcc.BillingStreet = 'Test';
			logAcc.BillingCity ='Test';
			logAcc.BillingPostalCode = '1234';
			logAcc.Email_Send_Check__c = 'Order Confirmation';
			insert logAcc; 
			
			
			
			//Legal Account
			Account legalAcc = HWS_DataFactory_TEST.insertAccount();
			legalAcc.ParentId = acc.Id;
			legalAcc.Acc_No__c = '234561200';			
			legalAcc.BillingCountry = 'India';
			legalAcc.BillingStreet = 'Test';
			legalAcc.BillingCity ='Test';
			legalAcc.BillingPostalCode = '1234';
			legalAcc.Email_Send_Check__c = 'Order Confirmation';
			insert legalAcc; 
			
			Contact con = HWS_DataFactory_TEST.createContactRec(acc);
			insert con;
			
			Id rtId = Schema.SObjectType.product2.getRecordTypeInfosByName().get('Sales Product').getRecordTypeId();
			Product2 prod = HWS_DataFactory_TEST.creteProduct(rtId);
			prod.ProductCode = 'xyz4567878';
			insert prod;
			
			Asset ast = HWS_DataFactory_TEST.insertAsset(legalAcc,prod);		
			ast.RecordTypeId = assetRecordType;
			ast.HWS_SourceSystem__c  = 'Puma1';
			ast.AccountId=legalAcc.Id;
			insert ast;
			
			Case parentCas=HWS_DataFactory_TEST.insertParentCase();
			parentCas.HWS_ReturnAddressReceivedFromSOO__c=True;
			parentCas.HWS_OrderConfirmationSent__c=true;
			parentCas.HWS_ShipTopartyId__c=null;
			parentCas.HWS_FaultyUnitReceivedDate__c = System.Today();
			parentCas.AccountId = legalAcc.Id;
			parentCas.ContactId = con.Id;
			parentCas.HWS_Communication_Contact__c = con.Id;
			parentCas.Origin = 'web';
			insert  parentCas;
			
			List<Case> childCaseList= new List<Case>();
			Case caserec = new Case();
			caserec.AccountId = legalAcc.Id;
			caserec.AssetId=ast.Id;
			caserec.RecordTypeId =childCaseReadonly;
			caserec.Status='Ordered';
			caserec.ParentId=parentCas.Id;
			caserec.HWS_RMA_Number__c='00019309-001';
			caserec.HWS_Customer_Reference_Number__c='232584';
			caserec.HWS_Faulty_Serial_Number__c='21234556';
			//caserec.HWS_ShipTopartyId__c='1234566';
			caserec.Hws_Ship_to_Party_Address__c=logAcc.Id;
			caserec.HWS_ShipTopartyId__c=null;
			caserec.HWS_FaultyUnitReceivedDate__c = System.Today();
			caserec.HWS_Sellable_Product__c = prod.Id;
			caserec.ContactId = con.Id;
			// caserec.HWS_OrderConfirmationSent__c=true;
			childCaseList.add(caserec);
			insert childCaseList;
			Set<Id> caseIdSet = new Set<Id>();
			for(Case c :childCaseList){
	caseIdSet.add(c.Id);
			}
	
			HWS_OrderConfirmationNotification.sendEmailNotificationForPDF(caseIdSet);

		Test.stopTest();	
	}
}