src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Compliance__c</fullName>
        <label>Customer Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US_ALTICE</fullName>
                </value>
                <value>
                    <fullName>US_AT&amp;T</fullName>
                </value>
                <value>
                    <fullName>US_Company</fullName>
                </value>
                <value>
                    <fullName>US_Cox</fullName>
                </value>
                <value>
                    <fullName>US_Govern</fullName>
                </value>
                <value>
                    <fullName>US_SCEC</fullName>
                </value>
                <value>
                    <fullName>US_Sprint</fullName>
                </value>
                <value>
                    <fullName>US_T-Mobile</fullName>
                </value>
                <value>
                    <fullName>US_VWireless</fullName>
                </value>
                <value>
                    <fullName>US_VWireline</fullName>
                </value>
                <value>
                    <fullName>unassign</fullName>
                    <default>true</default>
                    <label>Unassign</label>
                </value>
                <value>
                    <fullName>WD_NATO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_3rdPartySecurityGroup__c.field-meta.xml
<CustomField>
    <fullName>CH_3rdPartySecurityGroup__c</fullName>
    <description>NOKIASC-23511: To manage Support Ticket access by 3rd Party.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>3rd Party Security Group</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/CH_ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>CH_ContractNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ContractNumber</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/CH_SecurityRule__c.object
<CustomObject>
    <description>NOKIASC-25109: This holds the information needed for Case Security Group Assignment.</description>
    <fields>
        <fullName>CH_3rdPartySecurityGroup__c</fullName>
        <description>NOKIASC-25109</description>
        <encryptionScheme>None</encryptionScheme>
        <label>3rd Party Security Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>NOKIASC-25109</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CH_ContractNumber__c</fullName>
        <description>NOKIASC-25109</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_OrderofExecution__c</fullName>
        <description>NOKIASC-25109</description>
        <label>Order of Execution</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CH Security Rule</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>CH Security Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CH Security Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>CH_CDB_ContractId__c</fullName>
        <description>Used as a reference for checking service contracts in CDB</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CDB Contract ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_EntitlementScript__c</fullName>
        <description>Maps to agreements in CDB</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Entitlement Script</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NCP_External_Status__c</fullName>
        <label>External Status SP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CH_SecurityRuleTriggerTest.cls
/** 
 * About 
 * ----- 
 * @Description	  : Case Handling SecurityRule Trigger Test Class.
 * @Project		  : Case Handling.
 * @Modification Log : 
 *  Created  : 2019 11 18 – tiago.almeida@nokia.com
 * ----- 
**/
@isTest
public class CH_SecurityRuleTriggerTest {
	private static ServiceContract oServiceContract;
	
	private static void setupData1() {
		//create user
		User adminUser = CH_TestDataFactory.createUser('System Administrator', 'CH_KnowledgeHandler_TL' + 1);
		insert adminUser;
		//Assign Permission set CH_KB_Workgroup_Admin to created user
		PermissionSet oPermissionSet = [SELECT Id FROM PermissionSet WHERE Name = 'CH_KB_Workgroup_Admin'];
		system.assert(oPermissionSet !=null);
		system.runAs(adminUser){
			Boolean hasEntitlementScript = true;
			Account oCustomerParentAccount = new Account();
			Id accountRecordType1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
			oCustomerParentAccount.Name = 'Customer Parent Account';
			oCustomerParentAccount.RecordTypeId = accountRecordType1;
			oCustomerParentAccount.Customer_Compliance__c = 'US_Company';
			insert oCustomerParentAccount; 
			
			// Creation of Account
			Account oAccount = new Account();
			Id accountCustomerRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Legal Entity').getRecordTypeId();
			oAccount.Name = 'Parent Account';
			oAccount.RecordTypeId = accountCustomerRecordType;
			oAccount.ParentId = oCustomerParentAccount.id;
			oAccount.AccountNumber ='LE123';
			insert oAccount; 
			
			List<Product2> oProductList = CH_UTIL_TEST.createS2SProducts('testSolution', '12348', 'testProduct', '12350', 'testVariant', '12352');
			insert oProductList;
			
			PriceBookEntry oPriceBookEntry = new PriceBookEntry(
				Pricebook2Id = Test.getStandardPricebookId(),
				Product2Id = oProductList[0].id,
				UnitPrice = 0,
				CurrencyIsoCode = 'EUR',
				IsActive = true
			);
			insert oPriceBookEntry;
			
			// Create contract
			oServiceContract = new ServiceContract(
				AccountId = oAccount.Id, 
				Name = 'TestServiceContract',
				CH_CDB_ContractId__c = 'Test',
				CH_EntitlementScript__c = (hasEntitlementScript)?'Header Script':'',
				Pricebook2Id = Test.getStandardPricebookId(),
				NCP_External_Status__c = 'Active'
			);
			insert oServiceContract;
			System.debug('#####'+oServiceContract);
			
			// Create contract
			List<Group> oGroupList = new List<Group>{
				new Group(
					Name = 'SEC||TEST1||',
					DeveloperName = 'SEC_TEST1',
					Type  = 'Regular'
				),
				new Group(
					Name = 'SEC||TEST2||',
					DeveloperName = 'SEC_TEST2',
					Type  = 'Regular'
				)
			};
			insert oGroupList;
		}
	}
	
	public testMethod static void testMethod1() {
		setupData1() ;
		Test.StartTest();
		CH_SecurityRule__c oSecurityRule = new CH_SecurityRule__c(
			CH_OrderofExecution__c = 5000,
			CH_3rdPartySecurityGroup__c = 'SEC||TEST1||',
			CH_ContractNumber__c = [SELECT Id, ContractNumber FROM ServiceContract WHERE Id = :oServiceContract.Id LIMIT 1].ContractNumber,
			CH_Active__c = true
		);
		insert oSecurityRule;
		oSecurityRule.CH_3rdPartySecurityGroup__c = 'SEC||TEST2||';
		update oSecurityRule;
		delete oSecurityRule;
		Test.StopTest();		 
	}
}