src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>L4Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>L4 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Scope__c</fullName>
        <description>Requirement 1115</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field needs to describe the approval scope of an upcoming gate approval (next G4 or G5): what is expected to be approved. It must include information on changes versus previous approval (no change or change + description of the delta)</inlineHelpText>
        <label>Approval Scope</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_and_Competitive_Situation__c</fullName>
        <description>Req #2286 : Create new field for Excel Add-In</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer and Competitive Situation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LOA_Bypass__c</fullName>
        <description>Sales Process : Sprint 5 hyper care fixes: 1114
D-8480: New Help text
00018285: Corrected Help Text
ticket 242449 replase Help Text</description>
        <inlineHelpText>&quot;Pre-approved&quot;
For AM: pricing and T&amp;Cs follow a blanket approval.
For PrM: pricing/margin and T&amp;Cs authorized by the BG.
&quot;G4 approved or contracted&quot;: pricing and T&amp;Cs are exactly the one of the signed contract Or Inline with previous approved G4.</inlineHelpText>
        <label>G4/G5 Bypass Offer Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No LoA</fullName>
                    <label>G4 Approved or Contracted</label>
                </value>
                <value>
                    <fullName>Authorized for Pricing Manager</fullName>
                </value>
                <value>
                    <fullName>Pre-approved Price List for Account Managers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req #2286 : Create new field for Excel Add-In</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <description>This field will be appended at the end of Offer Number (01, 02)</description>
        <formula>if(
	Opportunity__r.count_offer__c &lt; 9, &apos;0&apos; &amp; TEXT(Opportunity__r.count_offer__c +1 ), TEXT(Opportunity__r.count_offer__c+ 1)
)</formula>
        <label>#Offer</label>
        <type>Text</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Offer_Team__c.object
<CustomObject>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipName>Object_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member_Role__c</fullName>
        <label>Team Member Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Logistic Manager</fullName>
                    <isActive>false</isActive>
                    <label>Account Logistic Manager</label>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Account Manager (Supporting)</fullName>
                    <isActive>false</isActive>
                    <label>Account Manager (Supporting)</label>
                </value>
                <value>
                    <fullName>Account Manager (TRICORN Sales Case Owner (SCO))</fullName>
                </value>
                <value>
                    <fullName>BG Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>Bid Manager</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Commercial Contract Manager and Legal</fullName>
                </value>
                <value>
                    <fullName>Commercial Deal Manager(CWR)</fullName>
                    <isActive>false</isActive>
                    <label>Commercial Deal Manager(CWR)</label>
                </value>
                <value>
                    <fullName>Commercial Deal Manager Commercial War Room</fullName>
                </value>
                <value>
                    <fullName>CT Head</fullName>
                </value>
                <value>
                    <fullName>Customer Quality Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Supply Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Team Controller</fullName>
                </value>
                <value>
                    <fullName>E2E Solution Manager</fullName>
                </value>
                <value>
                    <fullName>G3 Facilitator</fullName>
                </value>
                <value>
                    <fullName>G4 G5 Facilitator</fullName>
                </value>
                <value>
                    <fullName>Global Sales Support SPOC</fullName>
                    <label>Global Sales Support MU Lead</label>
                </value>
                <value>
                    <fullName>Head of Sales</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Offer Controller</fullName>
                </value>
                <value>
                    <fullName>Offer Owner</fullName>
                </value>
                <value>
                    <fullName>One Customer Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Partner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager (Lead)</fullName>
                </value>
                <value>
                    <fullName>Project Contract Manager</fullName>
                </value>
                <value>
                    <fullName>Project Execution Owner</fullName>
                    <isActive>false</isActive>
                    <label>Project Execution Owner</label>
                </value>
                <value>
                    <fullName>Project Execution Owner (TRICORN Project Execution Owner (PEO))</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Offer Team</label>
    <nameField>
        <displayFormat>OT-{000}</displayFormat>
        <label>Object Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req 569: User will select Lead BG manually</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_BG_FN__c</fullName>
        <description>To be selected if Supporting BG is FN</description>
        <inlineHelpText>Please select if Supporting BG is FN.</inlineHelpText>
        <label>OLD Supporting BG FN</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_BG_GS__c</fullName>
        <description>Req #2286 : Create new field for Excel Add-In</description>
        <inlineHelpText>Please select if Supporting BG is GS.</inlineHelpText>
        <label>OLD Supporting BG GS</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_BG_ION__c</fullName>
        <description>To be selected for Supporting BG as ION</description>
        <inlineHelpText>Please select if Supporting BG is ION.</inlineHelpText>
        <label>OLD Supporting BG ION</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ION</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_BG_MN__c</fullName>
        <description>Checkbox to be selected if Supporting BG is MN.</description>
        <inlineHelpText>Please select if Supporting BG is MN.</inlineHelpText>
        <label>OLD Supporting BG MN</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_BG_NEN__c</fullName>
        <description>Sales Process &gt; Feb Release 18 &gt; Sprint 19 &gt; Req#5537</description>
        <inlineHelpText>Please select if Supporting BG is NEN.</inlineHelpText>
        <label>OLD Supporting BG NEN</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Role__c.object
<CustomObject>
    <description>Object that maintains the Nokia Sales Organization Hierarchy</description>
    <label>Sales Role</label>
    <nameField>
        <displayFormat>CMD-{0000}</displayFormat>
        <label>Sales Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/classes/OfferSnapshotCreationHelperTest.cls
@isTest
public class OfferSnapshotCreationHelperTest
{
	private static final Id OpptyDirect = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.PRESALESRISKOPPORTUNITY_READONLY).getRecordTypeId();

	private static User user = new User();
	private static Opportunity oppty = new Opportunity();
	private static List<Offer__c> offers = new List<Offer__c>();
	private static final String market = GlobalConstants.Const_Market + ' ' + GlobalConstants.Const_Ind;


	private static void setup(String userProfile) {
		user = TestDataFactory.userCreation(1,userProfile)[0];
		database.insert(user);
		Account account = new Account();
		account = TestDataFactory.createAccount(1)[0];
		account.L4name__c = market;
		database.insert(account);
		oppty = TestDataFactory.OpportunityCreation(1,account)[0];
		database.insert(oppty);
		offers = TestDataFactory.OfferCreation(2,oppty);
	}


	static testMethod void excelAddInUpdate() {
		setup('Excel Add-In Profile');
		offers[0].Lead_BG__c = 'NSW';
		offers[0].Supporting_BG_MN__c = 'MN';
		offers[0].Supporting_BG_ION__c = 'ION';
		offers[0].Supporting_BU_ION_Optics__c = 'ION Optics';
		offers[0].Supporting_BU_ION_IPR__c = 'ION IPR';
		offers[0].Supporting_BG_GS__c = 'GS';
		offers[0].Supporting_BG_FN__c = 'FN';
		offers[0].Supporting_BG_NEN__c = 'NEN';
		offers[0].Supporting_BU_NE_DAaaS__c = 'NE DAaaS';
		offers[0].Supporting_BU_NE_EOP__c = 'NE EOP';
		offers[0].Supporting_BU_NE_IoT__c = 'NE IoT';
		database.insert(offers);
		Map<Id,Offer__c> offersMap = new Map<Id,Offer__c>(offers);

		System.runAs(user) {
			Test.startTest();
			OfferSnapshotCreationHelper.excelAddInUpdate(offersMap,offersMap);
			OfferSnapshotCreationHelper.excelAddInUpdate(null,null);
			Test.stopTest();
		}
	}

	static testMethod void validateOfferFieldEditForPricingManager() {
		setup('System Administrator');
		Offer__c offer = offers[0];
		offer.Approval_Scope__c = 'Pending';
		database.insert(offer);
		List<Offer_Team__c> offerTeamMemberList = TestDataFactory.offerTeamCreation(1, offer,user);
		Map<Id, Offer__c> filteredOfferMap = new Map<Id, Offer__c>{offer.Id => offer};
		Map<Id, Id> offerIdOpptyIdMap = new Map<Id, Id>{offer.Id => oppty.Id};

		System.runAs(user) {
			Test.startTest();
			database.insert(offerTeamMemberList);
			OfferSnapshotCreationHelper.validateOfferFieldEditForPricingManager(filteredOfferMap,offerIdOpptyIdMap);
			OfferSnapshotCreationHelper.validateOfferFieldEditForPricingManager(null,null);
			Test.stopTest();
		}
	}

	static testMethod void validateApprovalScopeTest() {
		setup('Excel Add-In Profile');
		Map<ID,Offer__c> offerMap = new map<Id,Offer__c>();
		Offer__c offer = offers[0];
		offer.Approval_Scope__c = 'Pending';
		offer.Customer_and_Competitive_Situation__c = 'Pending';
		system.runAs(user){
			insert offer;
			offerMap.put(offer.id,offer);
			OfferSnapshotCreationHelper.validateOfferFieldsLoA(offerMap,offerMap);
		}
	}

	static testMethod void validateLoABypassOfferConditionFieldValueTest(){

		Map<Id, Offer__c> newMap = new Map<Id, Offer__c>();
		Map<Id, Offer__c> oldMap = new Map<Id, Offer__c>();
		setup('System Administrator');
		Offer__c offer = offers[0];
		database.insert(offer);
		oldMap.put(offer.Id, offer);

		Sales_Role__c salesRoleRec = NF_TestDataFactory.createSalesRole(user,'NSNC_PrMBG',market,'4 - BG Pricing Manager');
		insert salesRoleRec;

		Offer_Team__c offerTeamObj = TestDataFactory.offerTeamCreation(1,offer,user)[0];
		offerTeamObj.Team_Member_Role__c = GlobalConstants.OFFER_OPPTY_TEAM_ROLE_PRICING_MANAGER;

		Offer__c offerToUpdate = offer.clone(true,true,true,true);
		offerToUpdate.LOA_Bypass__c=GlobalConstants.PICKLIST_VALUE_AUTHORIZED_FOR_PRICING_MANAGER;

		System.runAs(user)
		{
			Test.startTest();
			insert offerTeamObj;
			database.update(offerToUpdate);
			newMap.put(offerToUpdate.Id, offerToUpdate);
			OfferSnapshotCreationHelper.validateLoABypassOfferConditionFieldValue(oldMap,newMap);
			Test.stopTest();
		}
	}


	static testMethod void CatchException_Test()
	{
		user userCreation = TestDataFactory.userCreation(1,'Global Process Admin Profile')[0];
		database.insert(userCreation);
		system.runAs(userCreation){
			test.starttest();
			OfferSnapshotCreationHelper.validateLoABypassOfferConditionFieldValue(null,null);
			test.stopTest();
		}
	}

	static testMethod void updateOpportunity_ExceptionTest()
	{
		List<Opportunity> opptiesToUpdate = new List<Opportunity>();
		opptiesToUpdate.add(new Opportunity(Id=null));
		user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		database.insert(userCreation);

		system.runAs(userCreation){
			test.starttest();
			OfferSnapshotCreationHelper.updateOpportunity(opptiesToUpdate);
			test.stopTest();
		}
	}
}