src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Ids__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Account Ids</label>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>NCP_Entitlement_Relationship__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Entitlement Relationship</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CH_ContactType__c</fullName>
        <description>Contact Type Ref: 4989</description>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                    <default>true</default>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
                <value>
                    <fullName>Nokia Employee</fullName>
                </value>
                <value>
                    <fullName>Sub-Contractor</fullName>
                </value>
                <value>
                    <fullName>No Relationship</fullName>
                </value>
                <value>
                    <fullName>Secondary Account</fullName>
                </value>
                <value>
                    <fullName>Communication Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_LegacyContactId__c</fullName>
        <description>This will be the CARES ID Number or the NCT ID Number, etc
REF - NOKIASC-4989</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Legacy Contact ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>Set the contact Active or Inactive</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>With Telemarketing</fullName>
                </value>
                <value>
                    <fullName>With Customer Marketing</fullName>
                </value>
                <value>
                    <fullName>Working - Contacted</fullName>
                </value>
                <value>
                    <fullName>Closed - Existing Opportunity</fullName>
                </value>
                <value>
                    <fullName>Closed - No Project Now</fullName>
                </value>
                <value>
                    <fullName>Closed - Converted (Qualified)</fullName>
                </value>
                <value>
                    <fullName>Redirected - Channel Sales</fullName>
                </value>
                <value>
                    <fullName>Closed - Competitor</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Invalid Contact</fullName>
                </value>
                <value>
                    <fullName>Redirected - LGS</fullName>
                </value>
                <value>
                    <fullName>Sent to Partner</fullName>
                </value>
                <value>
                    <fullName>Redirected - Partner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Assigned - Inside Sales</fullName>
                </value>
                <value>
                    <fullName>Working - Inside Sales</fullName>
                </value>
                <value>
                    <fullName>Contacted - Inside Sales</fullName>
                </value>
                <value>
                    <fullName>Handoff</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Converted to Opportunity</fullName>
                </value>
                <value>
                    <fullName>Marketing Engaged</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Converted from Lead</fullName>
                    <isActive>false</isActive>
                    <label>Converted from Lead</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Active_Nokia_Employee__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Req #428: Users not in corp directory</description>
        <label>Active Nokia Employee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CH_Case_Handling_Internal_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Handling Internal Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nokia_ID__c</fullName>
        <description>Added custom field &apos;Nokia ID&apos; of type text(12) added for Req #061
Bandhan (hyper care time) : Marked this field as External ID field so that we can use it to connect with external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Nokia ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UserConCreationHandler.cls
/**************************************************************************************************************************
NOKIASC-4622 :  Automatic creation of Contact for Nokia User
Author : Avanti Vaidya/TCS
**************************************************************************************************************************/
global class UserConCreationHandler {
	
	public static String userDataCombineStr;
	
	public static void CallFutureConCreation(List<User> userList){
		
		List<String> nokiaIdSet = new List<String>();
		List<String> emailSet = new List<String>();
		List<String> userDataList= new List<String>();
		Boolean isUserCreated = false;
	   
			for(User usr : userList){
				if(usr.CH_Case_Handling_Internal_Contact__c && usr.isActive && usr.Active_Nokia_Employee__c ){									  
					isUserCreated = true;
					if(usr.Nokia_ID__c != null){
						nokiaIdSet.add(usr.Nokia_ID__c);
					}
					emailSet.add(usr.email);
					userDataCombineStr = usr.firstname + ';'+ usr.LastName + ';'+ usr.email+ ';' +usr.MobilePhone+ ';'+ usr.Nokia_ID__c;						
					userDataList.add(userDataCombineStr);
				}
			}
			if(isUserCreated){
				UserConCreationHandler.contactCreationUpdationProcess(nokiaIdSet, emailSet, userDataList );
			}
	}
	
	public static void CallFutureUpdateConStatus(Map<Id, User> userOldMap ,  Map<Id, User> userNewMap){
		List<String> nokiaIdSet = new List<String>(); 
		List<String> emailSet = new List<String>();
		List<String> userDataList= new List<String>();
		List<String> nokiaIdDeactivatedSet = new List<String>();
		List<String> emailDeactivatedSet = new List<String>();
		Boolean isUserDeactivated = false;
		Boolean isUserActivated = false;
	  
				for(Id usrId : userNewMap.keySet()){
					User usrOld = userOldMap.get(usrId);
					User usrNew = userNewMap.get(usrId);
					if((usrNew.IsActive != usrOld.IsActive && usrNew.CH_Case_Handling_Internal_Contact__c != usrOld.CH_Case_Handling_Internal_Contact__c && usrNew.CH_Case_Handling_Internal_Contact__c == false && usrNew.IsActive == false) 
					   ||(usrNew.CH_Case_Handling_Internal_Contact__c != usrOld.CH_Case_Handling_Internal_Contact__c && usrNew.CH_Case_Handling_Internal_Contact__c == false)){	
						   isUserDeactivated = true;
						   if(usrNew.Nokia_ID__c != null)
							   nokiaIdDeactivatedSet.add(usrNew.Nokia_ID__c);
						   emailDeactivatedSet.add(usrNew.email);
					   //TCS - updated logic to fix problem of contact override of portal users - defect: https://yoursl.atlassian.net/browse/NOKIASC-21122
					   }else if(((usrNew.IsActive != usrOld.IsActive && usrNew.IsActive == true &&  usrNew.CH_Case_Handling_Internal_Contact__c == true && usrNew.Active_Nokia_Employee__c ) 
								 || (usrNew.IsActive == true &&  usrNew.CH_Case_Handling_Internal_Contact__c == true && usrNew.CH_Case_Handling_Internal_Contact__c != usrOld.CH_Case_Handling_Internal_Contact__c && usrNew.Active_Nokia_Employee__c) 
								 || (usrNew.CH_Case_Handling_Internal_Contact__c == true && usrNew.Active_Nokia_Employee__c && usrNew.IsActive == true
									 && (usrOld.firstname != usrNew.firstname || usrOld.LastName !=  usrNew.LastName || usrOld.email != usrNew.email ||  usrOld.MobilePhone != usrNew.MobilePhone)) )) 
					   {						 
						   isUserActivated = true;
						   if(usrNew.Nokia_ID__c != null)
							   nokiaIdSet.add(usrNew.Nokia_ID__c);
						   emailSet.add(usrNew.email);
						   userDataCombineStr = usrNew.firstname + ';'+ usrNew.LastName + ';'+ usrNew.email+ ';' +usrNew.MobilePhone+ ';'+ usrNew.Nokia_ID__c;
						   userDataList.add(userDataCombineStr);
					   }
				}
				if(isUserDeactivated){
					UserConCreationHandler.updateContactStatus(nokiaIdDeactivatedSet, emailDeactivatedSet);
				}
				if(isUserActivated){				   
					UserConCreationHandler.contactCreationUpdationProcess(nokiaIdSet, emailSet, userDataList);
				}
		
	}
	
	@future
	public static void contactCreationUpdationProcess(List<String> nokiaIdSet, List<String> emailSet, List<String> userDataList){		
		try{   
			system.debug('nokiaIdSet--'+nokiaIdSet + '---emailSet--'+ emailSet +  '--userDataList--'+ userDataList);
			String customer_AccountId;
			Account_Ids__c customerAccObj = Account_Ids__c.getValues('Customer Account');
			if(customerAccObj != null){
				customer_AccountId = customerAccObj.Account_Id__c != null ? customerAccObj.Account_Id__c : '';
			}
			
			String legal_AccountId;
			Account_Ids__c legalAccObj = Account_Ids__c.getValues('Legal Entity');
			if(legalAccObj != null){
				legal_AccountId = legalAccObj.Account_Id__c != null ? legalAccObj.Account_Id__c : '';
			}   
			List<Contact> conList = new List<Contact>();
			Map<String, Contact> conEmailUpdateMap = new Map<String,Contact>();
			if(nokiaIdSet != null){
				conList = [Select id, firstname, AccountId,Account.name, LastName, email, phone, Status__c, CH_LegacyContactId__c, CH_ContactType__c FROM contact where CH_LegacyContactId__c IN : nokiaIdSet OR email IN : emailSet ];	   
			}else{
				conList = [Select id, firstname, AccountId,Account.name, LastName, email, phone, Status__c, CH_LegacyContactId__c, CH_ContactType__c FROM contact where email IN : emailSet ];	   
			}
			system.debug('conList--'+conList);
			if(!conList.isEmpty()){
				for(Contact con : conList){
					conEmailUpdateMap.put(con.Email, Con);
				}
			 }
		
			if(conList.isEmpty()){
				List<Contact> conInsertList = new List<Contact>();
				
				for(String userDataStr : userDataList){
					List<String> splitUserDataList = userDataStr.split(';');
					if(!splitUserDataList.isEmpty()){
						
						Contact con = new Contact();
						con.firstname = splitUserDataList[0] == 'null' ?  '' :  splitUserDataList[0];
						
						if(String.isNotBlank(splitUserDataList[1])){
							con.LastName = splitUserDataList[1];
						}
						
						if(String.isNotBlank(splitUserDataList[2])){
							con.Email = splitUserDataList[2];
						}
						
						con.MobilePhone =  splitUserDataList[3] == 'null' ? '' : splitUserDataList[3];
						con.CH_LegacyContactId__c = splitUserDataList[4] == 'null'  ? '' : splitUserDataList[4] ;
						
						con.AccountId = customer_AccountId;
						con.Contact_Status__c = 'Active';
						con.CH_ContactType__c = 'Nokia Employee';
						conInsertList.add(con);
					}
				}
				
				
				if(!conInsertList.isEmpty()){
					insert conInsertList;
					system.debug('conInsertList---'+conInsertList);
					getAccContRelationList(conInsertList, legal_AccountId);
				}
			}else{
				List<Contact> conUpdateList = new List<Contact>();
			   String emailStr;
				for(String userDataStr : userDataList){
					List<String> splitUserDataList = userDataStr.split(';');
					   
					
					if(!splitUserDataList.isEmpty()){
						 if(String.isNotBlank(splitUserDataList[2])){
								emailStr = splitUserDataList[2];
						 }
						
						if(conEmailUpdateMap.containsKey(emailStr)){
							
							Contact con = conEmailUpdateMap.get(emailStr);
							if(con != null){
								con.firstname = splitUserDataList[0] == 'null' ?  '' :  splitUserDataList[0];
								
								if(String.isNotBlank(splitUserDataList[1])){
									con.LastName = splitUserDataList[1];
								}
								
								if(String.isNotBlank(splitUserDataList[2])){
									con.Email = splitUserDataList[2];
								}
								
								con.MobilePhone =  splitUserDataList[3] == 'null' ? '' : splitUserDataList[3];
								con.CH_LegacyContactId__c = splitUserDataList[4] == 'null'  ? '' : splitUserDataList[4] ;
								con.AccountId = customer_AccountId;								 
								con.Contact_Status__c = 'Active';
								con.CH_ContactType__c = 'Nokia Employee';
								conUpdateList.add(con);
							}
						}
						
					}
					
				}
				if(!conUpdateList.isEmpty()){
					system.debug('conUpdateList  debuggg--'+conUpdateList);
					update conUpdateList;
					getAccContRelationList(conUpdateList, legal_AccountId);
				}
			}
		}catch(Exception e){
			System.debug('Exception = '+e.getMessage() + 'Line number--'+ e.getLineNumber());
		}
	}
	
	@future
	public static void updateContactStatus(List<String> nokiaIdDeactivatedSet, List<String> emailDeactivatedSet){		
		try{
			system.debug('emailDeactivatedSet handler ---'+ emailDeactivatedSet + 'nokiaIdDeactivatedSet--'+nokiaIdDeactivatedSet);
			List<Contact> conInactiveList = new List<Contact>();
			Set<Id> contactIdSet = new Set<Id>();
			
			List<Contact> conDeclareList = new List<Contact>();
			if(nokiaIdDeactivatedSet != null){
				system.debug('nokiaIdDeactivatedSet--'+ nokiaIdDeactivatedSet);
				conDeclareList =  [Select id, firstname, AccountId,Account.name, LastName, email, phone, Status__c,CH_LegacyContactId__c,CH_ContactType__c FROM contact where CH_LegacyContactId__c IN : nokiaIdDeactivatedSet OR email IN : emailDeactivatedSet] ;
			}else{
				conDeclareList= [Select id, firstname, AccountId,Account.name, LastName, email, phone, Status__c, CH_LegacyContactId__c,CH_ContactType__c FROM contact where email IN : emailDeactivatedSet];
			}
			
			if(!conDeclareList.isEmpty()){
				for(Contact conObj : conDeclareList) {
					conObj.Contact_Status__c = 'Inactive';
					conInactiveList.add(conObj);
					contactIdSet.add(conObj.id);
				} 
				system.debug('contactIdSet--'+contactIdSet);
				if(!conInactiveList.isEmpty()){
					update conInactiveList;
					system.debug('conInactiveList if not empty---'+conInactiveList);
					Set<Id> UserOrGroupIdSet = new Set<Id>();
					Set<Id> caseIdSet = new Set<Id>();
					Id grpId = [select Id , DeveloperName from Group where DeveloperName = 'CH_DVT_Queue' Limit 1].id;
					for (GroupMember grpMem : [SELECT id, UserOrGroupId,GroupId  FROM GroupMember WHERE GroupId =: grpId ]  ){
						  UserOrGroupIdSet.add(grpMem.UserOrGroupId);
					} 
					for(Case caseObj : [Select id, Status, contactId FROM case where contactId IN : contactIdSet AND Status != 'Closed']){
						caseIdSet.add(caseObj.id);
						
					}
					sendMailTOQueueMembers(UserOrGroupIdSet, caseIdSet);
				} 
			}
		}catch(Exception e){
			System.debug('Error = '+e.getMessage() + 'Line number--'+ e.getLineNumber());
		}
		
	}
	
	private static void sendMailTOQueueMembers(Set<Id> queueMemIdSet, Set<Id> caseIdSet){
		try{
			Id emailTempId = [Select Id from EmailTemplate where DeveloperName = 'CH_Internal_Case_Contact_Deactivated' limit 1].id;
			if(emailTempId != null){
				List<Messaging.singleEmailMessage> mails = new List<Messaging.singleEmailMessage>();
				for(Id caseId : caseIdSet){
					if(caseId != null){
						for(Id queueMemId : queueMemIdSet){
							if(queueMemId != null){
								Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
								email.setTargetObjectId(queueMemId);
								email.setTemplateId(emailTempId);
								email.setSaveAsActivity(false); 
								email.setWhatId(caseId);
								mails.add(email);	
								system.debug('mails---'+mails); 
							}
						}
					}
				}
				
				if(!mails.isEmpty()){
					Messaging.sendEmail(mails);
				}
			}
			
		}catch(Exception e){
			System.debug('Error = '+e.getMessage() + 'Line number--'+ e.getLineNumber());
		}
	}
	
	public static void getAccContRelationList(List<Contact> contactList, String accountId){
		try{
			List<AccountContactRelation> accConRelationList = new List<AccountContactRelation>();
			List<AccountContactRelation> accConRelationInsUpList = new List<AccountContactRelation>();
			Set<Id> AccConRelContactIds = new Set<Id>();
			if(!contactList.isEmpty()){
				for(Contact con : contactList){
					AccConRelContactIds.add(con.id);
				}
				accConRelationList = [Select id , AccountId, contactId, Roles, NCP_Entitlement_Relationship__c FROM AccountContactRelation Where contactId IN : AccConRelContactIds AND  NCP_Entitlement_Relationship__c = true ];
				if(accConRelationList.isEmpty()){
					for(Id conIds :  AccConRelContactIds){
						AccountContactRelation accConRelationObj = new AccountContactRelation(AccountId = accountId, ContactId = conIds, NCP_Entitlement_Relationship__c = true, Roles = 'Business User');
						accConRelationInsUpList.add(accConRelationObj);
					}
					if(!accConRelationInsUpList.isEmpty())
						insert accConRelationInsUpList;
				}else{
					update accConRelationList ;
				}
			}
		}catch(Exception e){
			System.debug('Error = '+e.getMessage() + 'Line number--'+ e.getLineNumber());
		}
	}
}