src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Compliance__c</fullName>
        <label>Customer Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US_ALTICE</fullName>
                </value>
                <value>
                    <fullName>US_AT&amp;T</fullName>
                </value>
                <value>
                    <fullName>US_Company</fullName>
                </value>
                <value>
                    <fullName>US_Cox</fullName>
                </value>
                <value>
                    <fullName>US_Govern</fullName>
                </value>
                <value>
                    <fullName>US_SCEC</fullName>
                </value>
                <value>
                    <fullName>US_Sprint</fullName>
                </value>
                <value>
                    <fullName>US_T-Mobile</fullName>
                </value>
                <value>
                    <fullName>US_VWireless</fullName>
                </value>
                <value>
                    <fullName>US_VWireline</fullName>
                </value>
                <value>
                    <fullName>unassign</fullName>
                    <default>true</default>
                    <label>Unassign</label>
                </value>
                <value>
                    <fullName>WD_NATO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Offer__c</fullName>
        <description>This field will be appended at the end of Offer Number (01, 02)</description>
        <formula>if(
	Opportunity__r.count_offer__c &lt; 9, &apos;0&apos; &amp; TEXT(Opportunity__r.count_offer__c +1 ), TEXT(Opportunity__r.count_offer__c+ 1)
)</formula>
        <label>#Offer</label>
        <type>Text</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Offer_Team__c.object
<CustomObject>
    <fields>
        <fullName>BG__c</fullName>
        <description>Req#3650-Capture BG data on the Offer team level</description>
        <label>BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NSW</fullName>
                </value>
                <value>
                    <fullName>FN</fullName>
                </value>
                <value>
                    <fullName>ION</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>GS</fullName>
                </value>
                <value>
                    <fullName>NEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Offer Team Member</description>
        <inlineHelpText>Only active users, and users with Nokia Sales Profile, Non-Sales User Profile, Sales Ops Profile, Nokia Read Only, Marketing Profile or Admin profiles can be added as Offer Team Members</inlineHelpText>
        <label>Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This user can&apos;t be selected as Offer Team Member (User Profile is not consistent or User is inactive)</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00e41000000wIbSAAU,00e41000000wIbUAAU,00e41000000wIbVAAU,00e41000000wIbXAAU,00e41000000wIbYAAU,00e41000000wIbbAAE,00e58000000Rh5PAAS,00e41000000wIbWAAU</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Object_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer_Access__c</fullName>
        <description>This field will copy opportunity team access and display for offer team.</description>
        <label>Offer Access</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only</fullName>
                </value>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipName>Object_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member_Role__c</fullName>
        <label>Team Member Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Logistic Manager</fullName>
                    <isActive>false</isActive>
                    <label>Account Logistic Manager</label>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Account Manager (Supporting)</fullName>
                    <isActive>false</isActive>
                    <label>Account Manager (Supporting)</label>
                </value>
                <value>
                    <fullName>Account Manager (TRICORN Sales Case Owner (SCO))</fullName>
                </value>
                <value>
                    <fullName>BG Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>Bid Manager</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Commercial Contract Manager and Legal</fullName>
                </value>
                <value>
                    <fullName>Commercial Deal Manager(CWR)</fullName>
                    <isActive>false</isActive>
                    <label>Commercial Deal Manager(CWR)</label>
                </value>
                <value>
                    <fullName>Commercial Deal Manager Commercial War Room</fullName>
                </value>
                <value>
                    <fullName>CT Head</fullName>
                </value>
                <value>
                    <fullName>Customer Quality Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Supply Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Team Controller</fullName>
                </value>
                <value>
                    <fullName>E2E Solution Manager</fullName>
                </value>
                <value>
                    <fullName>G3 Facilitator</fullName>
                </value>
                <value>
                    <fullName>G4 G5 Facilitator</fullName>
                </value>
                <value>
                    <fullName>Global Sales Support SPOC</fullName>
                    <label>Global Sales Support MU Lead</label>
                </value>
                <value>
                    <fullName>Head of Sales</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Offer Controller</fullName>
                </value>
                <value>
                    <fullName>Offer Owner</fullName>
                </value>
                <value>
                    <fullName>One Customer Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Partner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager (Lead)</fullName>
                </value>
                <value>
                    <fullName>Project Contract Manager</fullName>
                </value>
                <value>
                    <fullName>Project Execution Owner</fullName>
                    <isActive>false</isActive>
                    <label>Project Execution Owner</label>
                </value>
                <value>
                    <fullName>Project Execution Owner (TRICORN Project Execution Owner (PEO))</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Offer Team</label>
    <nameField>
        <displayFormat>OT-{000}</displayFormat>
        <label>Object Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Compliance__c</fullName>
        <formula>text(Account.Customer_Compliance__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Compliance</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_LoA_Approval_Level__c</fullName>
        <description>Expected LoA Approval Level for Offer</description>
        <inlineHelpText>Expected LoA Approval Level for Offer. Currently inactive</inlineHelpText>
        <label>Old Expected LoA Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LoA_G4_Approval_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>G3_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G3 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G4_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G4 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G5_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Expected date for contract signing or other legally binding document (e.g. first PO)</inlineHelpText>
        <label>Win Declaration Planned Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Role__c.object
<CustomObject>
    <description>Object that maintains the Nokia Sales Organization Hierarchy</description>
    <fields>
        <fullName>BG__c</fullName>
        <description>For CMD BG Attribute coming from Pack4</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BG Attribute</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Sales Role</label>
    <nameField>
        <displayFormat>CMD-{0000}</displayFormat>
        <label>Sales Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/LoA_G4_Approval_Levels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A+</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>LoA Bypass</fullName>
        <label>G4/G5 Bypass</label>
    </customValue>
    <customValue>
        <fullName>A light</fullName>
        <isActive>false</isActive>
        <label>A light</label>
    </customValue>
    <description>Global picklist for LoA G4 Approval Levels</description>
    <masterLabel>LoA G4 Approval Levels</masterLabel>
</GlobalValueSet>

src/classes/CreateOfferApexCtlr.cls
/****************************************
* Class Name : CreateOfferApexCtlr
* Created Date: 27.9.2018
* Created By : Accenture
* Last Modified by: Accenture 
* Description : 
* Test Class: CreateOfferApexCtlr
*****************************************/
public without sharing class CreateOfferApexCtlr {
	/********************
*Method Name: getOppty
*Parameter: 
*Description:  Fetching all Opportunity Name,Id
*******************/
	@AuraEnabled
	public static Opportunity getOppty(String opptyId)
	{
		Opportunity opp;
		try{
			opp = [Select Id,Name,G4_Planned_Date__c,G3_Planned_Date__c,G5_Planned_Date__c,Account.Customer_Compliance__c, Expected_LoA_Approval_Level__c from Opportunity
	   where id=: opptyId limit 1];
		}catch(Exception ex)
		{
			ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR ,GlobalConstants.GETOPPTY); 
		}
		return opp;
	}
	
	 /********************
*Method Name: getAllLeadBG
*Parameter: 
*Description:  Fetching all Lead BG of OfferTeam
*******************/
	@AuraEnabled
	public static Map<string,string> getAllLeadBGOfOfferTeam(){
		Map<string,string> leadBGMap = new  Map<string,string>();
		// Get the list of picklist values for this field.
		map<String, Schema.SObjectField> fieldMap = CreateOfferApexCtlr.getFieldMapOfferTeam();
		system.debug('fieldMap'+fieldMap);
		list<Schema.PicklistEntry> values = fieldMap.get('BG__c').getDescribe().getPickListValues();
		system.debug('values'+values);
		// Add these values to the selectoption list.
		for (Schema.PicklistEntry val : values)
		{ 
			leadBGMap.put(val.getLabel(), val.getValue()); 
		}
		return leadBGMap;
	}
	/********************
*Method Name: saveOffer
*Parameter: 
*Description:  Save Offer Record
*******************/
	@AuraEnabled
	public static String saveOffer(Offer__c offerRec)
	{
		String offerId ;
		try{
			Database.SaveResult savedResults = Database.insert(offerRec, false);
			Boolean someFailure = false;
			if (!savedResults.isSuccess()) {
	someFailure = true;
	for (Database.Error err: savedResults.getErrors()) {
		offerId = err.getMessage();
		System.debug('Error occured : ' + err.getStatusCode() + ' : ' + err.getMessage());
		System.debug('Fields that affected this error : ' + err.getFields());
	}
			}
			if (!someFailure) {
	System.debug('Offer added successfully.');
	offerId = offerRec.id;
			} 
		}catch (Exception ex)
		{
			ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR,GlobalConstants.SAVEOFFER );  
		}
		return offerId;
	}
	
	/********************
*Method Name: saveOppty
*Parameter: 
*Description:  Save Opportunity Record
*******************/
	@AuraEnabled	
	public static string saveOppty(Opportunity opptyRec)
	{
		String opptyId ;
		try{
			Database.SaveResult updateResult = Database.update(opptyRec, false);
			Boolean someFailure = false;
			if (!updateResult.isSuccess()){
	someFailure = true;
	for (Database.Error err : updateResult.getErrors()){ 
		opptyId = err.getMessage();
		System.debug('Error occured : ' + err.getStatusCode() + ' : ' + err.getMessage());
		System.debug('Fields that affected this error : ' + err.getFields()); 
	}
			}
			if (!someFailure) {
	System.debug('Oppty updated successfully.');
	opptyId = 'Success';
			} 
			
		}catch (Exception ex){ ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR,GlobalConstants.SAVEOFFER );  }
		return opptyId;
	}
	
	
	/********************
*Method Name: saveOfferTeam
*Parameter: 
*Description:  Save Offer Team Record
*******************/
	/*Database.SaveResult[] savedResults = Database.insert(offerTeamList, true);

for(Integer i=0;i<savedResults.size();i++){
if(!savedResults[i].isSuccess()){//only look at failures, or NOT Successes
system.debug(savedResults[i]. getErrors());
system.debug(offerTeamList[i]);
msg += 'For User : '+wrapperFinalList[i].userName+' : '+savedResults[i]. getErrors();
}
}
throw new AuraHandledException(msg);
}*//*catch(DmlException e){
for (Integer i = 0; i < e.getNumDml(); i++) {
//Get Validation Rule & Trigger Error Messages
if(msg == '')
msg ='Row no : '+e.getDmlIndex(i)+ ' '+e.getLineNumber()+' '+e.getDmlFieldNames(0)+' '+e.getDmlFields(0)+' '+e.getDmlMessage(i) +  '\n' ;
else
msg = msg+'Row no : '+e.getDmlIndex(i)+ ' '+e.getDmlMessage(i) +  '\n' ;
}
//throw DML exception message
throw new AuraHandledException(msg);*/
	@AuraEnabled
	public static void saveOfferTeam(String wrapperList, Id newOfferId)
	{
		String msg = '';
		system.debug('wrapperList'+wrapperList);
		system.debug('newOfferId'+newOfferId);
		Type idArrType = Type.forName(GlobalConstants.LIST_WRAPPER);
		List<OfferTeamWrapper> wrapperFinalList = new List<OfferTeamWrapper>();		
		List <Offer_Team__c> offerTeamList ;
		Offer_Team__c offerTeamVar;
		try{
			wrapperFinalList = (List<OfferTeamWrapper>) JSON.deserialize(wrapperList, idArrType);
			system.debug('wrapperFinalList'+wrapperFinalList);
			if(wrapperFinalList != Null)
			{
	offerTeamList = new List<Offer_Team__c>();
	system.debug('In if statement');
	for(OfferTeamWrapper wrapperVar : wrapperFinalList)
	{
		if(wrapperVar.teamRole != Null || wrapperVar.teamRole != '')
		{
			system.debug('wrapperVar'+wrapperVar);
			offerTeamVar = new Offer_Team__c();
			offerTeamVar.Offer_Access__c = wrapperVar.offerAccess;
			offerTeamVar.Team_Member_Role__c = wrapperVar.teamRole;
			offerTeamVar.Name__c = wrapperVar.userId;
			offerTeamVar.Offer__c = newOfferId;
			offerTeamVar.Additional_Team_Role__c = wrapperVar.additionalTeamRole;
			offerTeamVar.BG__c = wrapperVar.leadBG; 
			system.debug('offerTeamVar'+offerTeamVar);
			offerTeamList.add(offerTeamVar);
		}
	}
	system.debug('offerTeamList'+offerTeamList);
	Database.SaveResult[] savedResults = Database.insert(offerTeamList, false);
	for(Database.SaveResult res : savedResults)
	{
		system.debug('res.getErrors()'+res.getErrors());
	}
	//system.debug('savedResults.getErrors()'+savedResults.getErrors());
	Boolean someFailure = false;
	for(Database.SaveResult result : savedResults){
		if (!result.isSuccess()) {
			someFailure = true;
			for (Database.Error err: result.getErrors()) {
				System.debug('Error occured : ' + err.getStatusCode() + ' : ' + err.getMessage());
				System.debug('Fields that affected this error : ' + err.getFields());
			}
		}
		if (!someFailure) {
			System.debug('New offer Team inserted successfully');
		} 
	}
			}			
		}catch (Exception ex)  {  ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR ,GlobalConstants.SAVEOFFERTEAM); }
	}
	
	
	/********************
*Method Name: getAllExpectedLoALevel
*Parameter: 
*Description:  Fetching all Expected Loa Level from picklist
*******************/
	@AuraEnabled
	public static Map<string,string> getAllExpectedLoALevel(){
		Map<string,string> expectedLoALevel= new  Map<string,string>();
		// Get the list of picklist values for this field.
		map<String, Schema.SObjectField> fieldMap = CreateOfferApexCtlr.getFieldMapOffer();
		system.debug('fieldMap'+fieldMap);
		try{
			list<Schema.PicklistEntry> values = fieldMap.get(GlobalConstants.Expected_LoA_Level).getDescribe().getPickListValues();
			system.debug('values'+values);
			// Add these values to the selectoption list.
			for (Schema.PicklistEntry val : values)
			{ 
	if(val.isActive())
		expectedLoALevel.put(val.getLabel(), val.getValue()); 
			}
		}catch (Exception ex){ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR ,GlobalConstants.SAVEOFFERTEAM); }
		return expectedLoALevel;
	}
	
	/********************
*Method Name: getFieldMap
*Parameter: 
*Description:  common exection in fetching picklist values of offer
*******************/
	private static map<String, Schema.SObjectField> getFieldMapOffer(){
		// Get the object type of the SObject.
		Schema.sObjectType objType = Offer__c.getSObjectType(); 
		system.debug('objType'+objType);
		// Describe the SObject using its object type.
		Schema.DescribeSObjectResult objDescribe = objType.getDescribe(); 
		system.debug('objDescribe'+objDescribe);
		// Get a map of fields for the SObject
		return objDescribe.fields.getMap(); 
	}
	
	/********************
*Method Name: getAllTeamMemberRole
*Parameter: 
*Description:  Fetching all Team Role from picklist
*******************/
	@AuraEnabled
	public static Map<string,string> getAllTeamMemberRole(){
		Map<string,string> teamMemberRole= new  Map<string,string>();
		// Get the list of picklist values for this field.
		map<String, Schema.SObjectField> fieldMap = CreateOfferApexCtlr.getFieldMapOfferTeam();
		system.debug('fieldMap'+fieldMap);
		try{
			list<Schema.PicklistEntry> values = fieldMap.get(GlobalConstants.TeamMember).getDescribe().getPickListValues();
			system.debug('values'+values);
			// Add these values to the selectoption list.
			for (Schema.PicklistEntry val : values)
			{ 
	if(val.isActive())
		teamMemberRole.put(val.getLabel(), val.getValue()); 
			}
		}catch (Exception ex){ ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR ,GlobalConstants.SAVEOFFERTEAM);	 }
		return teamMemberRole;
	}
	
	/********************
*Method Name: getAllTeamMemberRoleMap
*Parameter: 
*Description:  Fetching all Team Role from picklist
*******************/
	@AuraEnabled
	public static Map<string,string> getAllTeamMemberRoleMap(){
		Map<string,string> teamMemberRole= new  Map<string,string>();
		// Get the list of picklist values for this field.
		map<String, Schema.SObjectField> fieldMap = CreateOfferApexCtlr.getFieldMapOfferTeam();
		system.debug('fieldMap'+fieldMap);
		try{
			list<Schema.PicklistEntry> values = fieldMap.get(GlobalConstants.TeamMember).getDescribe().getPickListValues();
			system.debug('values'+values);
			// Add these values to the selectoption list.
			for (Schema.PicklistEntry val : values)
			{ 
	if(val.isActive())
		teamMemberRole.put(val.getValue(), val.getLabel()); 
			}
		}catch (Exception ex) {   ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR ,GlobalConstants.SAVEOFFERTEAM);   }
		return teamMemberRole; 
	}
	
	/********************
*Method Name: getAllAdditionalTeamMemberRole
*Parameter: 
*Description:  Fetching all Additional Team Role from picklist
*******************/
	@AuraEnabled
	public static Map<string,string> getAllAdditionalTeamMemberRole(){
		Map<string,string> additionalTeamMemberRole= new  Map<string,string>();
		// Get the list of picklist values for this field.
		map<String, Schema.SObjectField> fieldMap = CreateOfferApexCtlr.getFieldMapOfferTeam();
		system.debug('fieldMap'+fieldMap);
		try{
			list<Schema.PicklistEntry> values = fieldMap.get(GlobalConstants.AdditionalTeamMember).getDescribe().getPickListValues();
			system.debug('values'+values);
			// Add these values to the selectoption list.
			for (Schema.PicklistEntry val : values)
			{ 
	if(val.isActive())
		additionalTeamMemberRole.put(val.getLabel(), val.getValue()); 
			}
		}catch (Exception ex) { ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR ,GlobalConstants.SAVEOFFERTEAM);   }
		return additionalTeamMemberRole;
	}
	
	/********************
*Method Name: getAllAccessLevel
*Parameter: 
*Description:  Fetching all Access level from picklist
*******************/
	@AuraEnabled
	public static Map<string,string> getAllAccessLevel(){
		Map<string,string> accessLevel = new  Map<string,string>();
		// Get the list of picklist values for this field.
		map<String, Schema.SObjectField> fieldMap = CreateOfferApexCtlr.getFieldMapOfferTeam();
		system.debug('fieldMap'+fieldMap);
		try{
			list<Schema.PicklistEntry> values = fieldMap.get(GlobalConstants.Access_Level).getDescribe().getPickListValues();
			system.debug('values'+values);
			// Add these values to the selectoption list.
			for (Schema.PicklistEntry val : values)
			{ 
	if(val.isActive())
		accessLevel.put(val.getLabel(), val.getValue()); 
			}
		}catch (Exception ex){ ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR ,GlobalConstants.SAVEOFFERTEAM);  }
		return accessLevel;
	}
	
	/********************
*Method Name: getFieldMap
*Parameter: 
*Description:  common exection in fetching picklist values of Offer Team
*******************/
	private static map<String, Schema.SObjectField> getFieldMapOfferTeam(){
		// Get the object type of the SObject.
		Schema.sObjectType objType = Offer_Team__c.getSObjectType(); 
		system.debug('objType'+objType);
		// Describe the SObject using its object type.
		Schema.DescribeSObjectResult objDescribe = objType.getDescribe(); 
		system.debug('objDescribe'+objDescribe);
		// Get a map of fields for the SObject
		return objDescribe.fields.getMap(); 
	}
	
	/********************
*Method Name: fetOpptyTeam
*Parameter: 
*Description:  Fetching all Team Members of Opportunity
*******************/
	@AuraEnabled
	public static List<OfferTeamWrapper> getOpptyTeam(String opptyId)
	{
		List<OpportunityTeamMember> oppTeam;
		List<OfferTeamWrapper> wrapperList = new List<OfferTeamWrapper>();
		OfferTeamWrapper wrapper;
		// Get the object type of the SObject.
		Schema.sObjectType objType = OpportunityTeamMember.getSObjectType(); 
		system.debug('objType'+objType);
		// Describe the SObject using its object type.
		Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
		Map<string,string> teamMemberRole= new  Map<string,string>();
		// Get the list of picklist values for this field.
		map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
		system.debug('fieldMap'+fieldMap);
		list<Schema.PicklistEntry> values = fieldMap.get(gLOBALcONSTANTS.TEAMMEMBERROLE).getDescribe().getPickListValues();
		try{
			
			system.debug('values'+values);
			// Add these values to the select option list.
			for (Schema.PicklistEntry val : values)
			{ 
	teamMemberRole.put(val.getValue(), val.getLabel()); 
			}
			oppTeam = [Select Id,UserId,User.Name,User.NSA_Compliant__c,
		TeamMemberRole,Additional_Team_Role__c, OpportunityAccessLevel,
		opportunity.OwnerId, opportunity.Owner.NSA_Compliant__c, opportunity.Owner.Name
		from OpportunityTeamMember
		where OpportunityId=: opptyId 
		LIMIT :Limits.getLimitQueryRows() - Limits.getQueryRows()];
			system.debug('oppTeam'+oppTeam);
			if(oppTeam != Null)
			{
	for(OpportunityTeamMember opp : oppTeam)
	{
		wrapper = new OfferTeamWrapper();
		wrapper.teamRole = opp.TeamMemberRole;
		if(teamMemberRole.containsKey(opp.TeamMemberRole))
			wrapper.teamRoleLabel = teamMemberRole.get(opp.TeamMemberRole);
		else
			wrapper.teamRoleLabel = opp.TeamMemberRole;
		if(opp.OpportunityAccessLevel == GlobalConstants.ALL_ACCESS_OFFER || opp.OpportunityAccessLevel == GlobalConstants.EDIT_ACCESS )
			wrapper.offerAccess = GlobalConstants.READ_EDIT_ACCESS;
		else
			wrapper.offerAccess = GlobalConstants.READ_ONLY_ACCESS;
		wrapper.additionalTeamRole = opp.Additional_Team_Role__c;
		wrapper.userId = opp.UserId;
		wrapper.nsaCompliant = opp.User.NSA_Compliant__c ;
		wrapper.userName = opp.User.Name;
		wrapper.oppOwnerId = opp.opportunity.OwnerId;
		wrapper.oppOwnerNSA = opp.opportunity.Owner.NSA_Compliant__c;
		wrapper.oppOwnerName = opp.opportunity.Owner.Name;
		wrapperList.add(wrapper);
	}
	wrapperList = manageBidManager(wrapperList, teamMemberRole);
			}
		}catch(Exception ex) { ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR,GlobalConstants.GETOPPTYTEAM);		}
		System.debug(wrapperList);
		return wrapperList;
	}
	
	private static List<OfferTeamWrapper> manageBidManager(List<OfferTeamWrapper> offerTeamMembersList, Map<string,string> teamMemberRole)
	{
		Boolean hasPrimaryBM = false; //Bid manager has alternative role
		Boolean hasAlternateBM = false; //Bid manager has alternative role
		OfferTeamWrapper offerMemberWithAlt = new OfferTeamWrapper();
		
		for (OfferTeamWrapper offTeamMember : offerTeamMembersList)
		{
			if(offTeamMember != null && offTeamMember.teamRoleLabel != null && offTeamMember.teamRoleLabel.equals(GlobalConstants.BID_MANAGER_OFFER_TEAM_ROLE))//Check if we already have a Bid Manager assigned
			{ 
	hasPrimaryBM = true;
	break;
			}
			else if( offTeamMember != null && offTeamMember.additionalTeamRole != null && offTeamMember.additionalTeamRole.contains(GlobalConstants.BID_MANAGER_OFFER_TEAM_ROLE) && !hasAlternateBM)//Check if we already have a Bid Manager assigned
			{
	hasAlternateBM = true;
	offerMemberWithAlt = offTeamMember;
			}
		}
		
		//Assign new BM if needed 
		if (!hasPrimaryBM)//Need to create new offer team member
		{
			OfferTeamWrapper wrapper = new OfferTeamWrapper();
			wrapper.teamRole = GlobalConstants.BID_MANAGER_OFFER_TEAM_ROLE;
			if(teamMemberRole.containsKey(GlobalConstants.BID_MANAGER_OFFER_TEAM_ROLE))
	wrapper.teamRoleLabel = teamMemberRole.get(GlobalConstants.BID_MANAGER_OFFER_TEAM_ROLE);
			
			wrapper.offerAccess = GlobalConstants.READ_EDIT_ACCESS;
			if( hasAlternateBM)//Elect team member that is "Bid Manager" as an alternate role as "the Bid Manager"
			{
	wrapper.userId = offerMemberWithAlt.UserId;
	wrapper.nsaCompliant = offerMemberWithAlt.additionalTeamRole.contains(GlobalConstants.BID_MANAGER_OFFER_TEAM_ROLE);//offerMemberWithAlt.nsaCompliant;
	wrapper.userName = offerMemberWithAlt.additionalTeamRole;//offerMemberWithAlt.userName;
			}
			else//elect opportunity owner has the Bid Manager in team offer
			{
	wrapper.userId = offerTeamMembersList[0].oppOwnerId;
	wrapper.nsaCompliant = offerTeamMembersList[0].oppOwnerNSA;
	wrapper.userName = offerTeamMembersList[0].oppOwnerName;
			}
			offerTeamMembersList.add(wrapper);
		}
		return offerTeamMembersList;
	}
	/********************
*Method Name: getAllUserList
*Parameter: 
*Description:  Fetching all User
*******************/
	@AuraEnabled
	public static List<User> getAllUserList(String keyWord)
	{
		List<User> userList;
		//User userVar;
		String searchKey = GlobalConstants.WILDCARD_SEARCH + keyWord + GlobalConstants.WILDCARD_SEARCH;
		try{
			userList = [Select Id,Name,NSA_Compliant__c from User where Name like: searchKey and IsActive =: true LIMIT :GlobalConstants.QUERRY_LIMIT_MAX_USER_PER_OFFER];
			system.debug('userList'+userList);
		}catch(Exception ex){ ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR,GlobalConstants.GETALLUSERLIST); }
		return userList;
	}
	
	/********************
*Method Name: getUser
*Parameter: 
*Description:  Fetching selected User
*******************/
	@AuraEnabled
	public static User getUser(String userId)
	{
		User userList;
		try{
			userList = [Select Id,Name,NSA_Compliant__c from User where Id=: userId LIMIT 1];
			system.debug('userList'+userList);
		}catch(Exception ex)
		{
			ExceptionHandler.addException(ex,GlobalConstants.CREATEOFFERAEXCTLR ,GlobalConstants.GETUSER ); 
		}
		return userList;
	}
	
	
	/**********************************************************************************************************************
* author: Accenture
* Date: Feb-2019
* Param: String offTeamList, Id opptyId
* Return: List<OfferTeamWrapper>
* Description: Pricing Manager Validation in Offer Team
* High Level Process : 
**********************************************************************************************************************/   
	@AuraEnabled
	public static List<OfferTeamWrapper> offerTeamPrMValidation ( String offTeamList, Id opptyId)
	{
		system.debug('offTeamList'+offTeamList);
		set<String> orgLevel = new set<String>();
		Map<String,String> sRmap = new Map<String, String>();
		Type idArrType = Type.forName(GlobalConstants.LIST_WRAPPER);
		List<OfferTeamWrapper> wrapperFinalList = new List<OfferTeamWrapper>();	  
		List<OfferTeamWrapper> pricingManagerList = new List<OfferTeamWrapper>();
		try
		{ 
			wrapperFinalList = (List<OfferTeamWrapper>) JSON.deserialize(offTeamList, idArrType);
			system.debug('wrapperFinalList'+wrapperFinalList);
			Opportunity opp = [SELECT Org_L2__c,Org_L3__c,Org_L4__c,Org_L5__c,Org_L6__c,Org_L7__c 
		  FROM Opportunity 
		  WHERE Id =: opptyId AND SWx_Upsell_Proposal__c = null 
		  limit 1];
			{
	orgLevel.add(opp.Org_L2__c);
	orgLevel.add(opp.Org_L3__c);
	orgLevel.add(opp.Org_L4__c);
	orgLevel.add(opp.Org_L5__c);
	orgLevel.add(opp.Org_L7__c);
	orgLevel.add(opp.Org_L7__c);
			}
			if(orgLevel.size() > 0){
	for(Sales_Role__c sR : [SELECT User__c,Organisation__c FROM Sales_Role__c WHERE Role_Code__c LIKE :System.Label.NF_PrM_Role AND
				Organisation__c IN: orgLevel LIMIT: Limits.getLimitQueryRows() - Limits.getQueryRows()])
	{
		sRmap.put(sR.User__c, sR.Organisation__c);
	}
			}
			
			for(OfferTeamWrapper wrapper : wrapperFinalList )
			{  
	System.debug('wrapper::> '+wrapper);
	if((!sRmap.isEmpty() && !sRmap.containsKey(wrapper.userId) )|| sRmap.isEmpty())
	{
		pricingManagerList.add(wrapper);
	}
			}
			system.debug('pricingManagerList'+pricingManagerList);
		}
		Catch (Exception ex){ ExceptionHandler.addException(ex, GlobalConstants.OFFER_TEAM_HELPER_CLASS, GlobalConstants.OFFERTEAMPRMVALIDATION); }
		return pricingManagerList;
	}	  
}