src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Azores</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius And Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia And Herzegovina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Asia and Japan</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Middle East and Africa</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_CaseMilestoneTargetDate__c.field-meta.xml
<CustomField>
    <fullName>CH_CaseMilestoneTargetDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CaseMilestoneTargetDate</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/CH_Initial_Assignment__c.field-meta.xml
<CustomField>
    <fullName>CH_Initial_Assignment__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates that for a new ticket, no assignment has been made.
As soon as somebody is assigned the field is set to false</description>
    <label>CH Initial Assignment</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/CH_MilestoneSLA_Start__c.field-meta.xml
<CustomField>
    <fullName>CH_MilestoneSLA_Start__c</fullName>
    <description>Start Date/Time for the Case Entitlement Milestone Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Milestone Start Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/CH_Outage__c.field-meta.xml
<CustomField>
    <fullName>CH_Outage__c</fullName>
    <label>Outage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Severity__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/CH_ProductVariant__c.field-meta.xml
<CustomField>
    <fullName>CH_ProductVariant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product copied from the Covered Product if one exist on the case, else selected manually by the user</description>
    <label>Product Variant</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Product2.PMD_Additional_Classification__c</field>
            <operation>equals</operation>
            <value>Product Variant</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.CH_LegacyCaseStatus__c</field>
            <operation>equals</operation>
            <value>Closed</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Variant</relationshipLabel>
    <relationshipName>Support_Ticket2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CH_Reassignment__c.field-meta.xml
<CustomField>
    <fullName>CH_Reassignment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CH Reassignment</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/CH_Solution__c.field-meta.xml
<CustomField>
    <fullName>CH_Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Solution copied from the Covered Product if one exist on the case, else selected manually by the user</description>
    <label>Solution</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Product2.PMD_Portfolio_Classification__c</field>
            <operation>equals</operation>
            <value>Solution</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.CH_LegacyCaseStatus__c</field>
            <operation>equals</operation>
            <value>Closed</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CH_SystemRestored__c.field-meta.xml
<CustomField>
    <fullName>CH_SystemRestored__c</fullName>
    <description>System Restored</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Restored Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/CH_SystemRestoredTargetDate__c.field-meta.xml
<CustomField>
    <fullName>CH_SystemRestoredTargetDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Restore Target Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/CH_Workgroup__c.field-meta.xml
<CustomField>
    <fullName>CH_Workgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Workgroup</label>
    <referenceTo>CH_Workgroup__c</referenceTo>
    <relationshipLabel>Incidents and Problems</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/NCP_Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>NCP_Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <inlineHelpText>In case of system wide outage or major issue affecting all users, please create a P1/P2 incident ticket via our Global Support Desk.</inlineHelpText>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Information Request</fullName>
            </value>
            <value>
                <fullName>Critical- 2 Hours</fullName>
                <isActive>false</isActive>
                <label>Critical- 2 Hours</label>
            </value>
            <value>
                <fullName>High</fullName>
                <isActive>false</isActive>
                <label>High</label>
            </value>
            <value>
                <fullName>Moderate</fullName>
                <isActive>false</isActive>
                <label>Moderate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/CH_CA_OwnerAssignment_Controller.cls
public without sharing class CH_CA_OwnerAssignment_Controller {
	
	// Get Case Assign Type 
	@AuraEnabled 
	public static Boolean isActiveAssignment(Id caseId){
		Case supportCase = [SELECT Id, CreatedDate, CH_SystemRestoredTargetDate__c, CH_Initial_Assignment__c,
				RecordTypeId, Status, Severity__c, Account.Region__c, Account.Country__c,CH_Reassignment__c,
				AccountId, ProductId, CH_Outage__c, NCP_Service_Contract__r.Id, BusinessHoursId, CH_SystemRestored__c,
				CH_CaseMilestoneTargetDate__c, CH_MilestoneSLA_Start__c,AssetId,CH_ProductVariant__c,CH_Solution__c,
				CH_Workgroup__r.CH_Type__c,Country__c,EntitlementId,CH_GWC_SecurityGroup__c,CH_SecurityGroup__c, 
				CH_ServiceType__c, CH_Product_Module__c,CH_Rep_CDBContractType__c, CH_Originating_Incident_Number__c,
				CH_Originating_Incident_Number__r.AccountId,CH_Originating_Incident_Number__r.Country__c
				FROM Case 
				WHERE Id =:caseId];
		system.debug('Value of CH_CA_OwnerAssignment_Controller:'+supportCase.CH_Rep_CDBContractType__c);
		system.debug('supportCase 1 :'+supportCase);
		CH_CA_Assignment_Criteria_DTO caseAssignmentDetails;
		Id problemRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Problem').getRecordTypeId();
		if (supportCase.RecordTypeId == problemRecordTypeId){
			caseAssignmentDetails = new CH_CA_Assignment_Criteria_DTO().createProblemSearchCriteria(supportCase);
		}else {
			caseAssignmentDetails =  new CH_CA_Assignment_Criteria_DTO().createIncidentSearchCriteria(supportCase);
		}
		caseAssignmentDetails.validWorkgroupRules = CH_CA_Workgroup_Rule.GetWorkgroupRules(caseAssignmentDetails);

		Boolean assignmentType = new CH_CA_Assignment_Criteria_DTO().getAssignmentType(caseAssignmentDetails);
		System.debug('CH_CA: LIM CH_CA_OwnerAssignment_Controller.isActiveAssignment SOQL limit: ' + Limits.getQueries());
		return assignmentType; 
	}
		
	// // Get all the workgroup members 
	@AuraEnabled
	public static List<CH_CA_DTO.WorkgroupMemberDTO> getWorkgroupMembers(String caseId, Boolean noFilter){
		CH_CA_Service service = new CH_CA_Service(caseId); 
		List<CH_CA_DTO.WorkgroupMemberDTO> foundWorkgroupMembers = (noFilter==true ? service.getAllCaseAssignmentWorkgroupMembers() : service.getCaseAssignmentWorkgroupMembers());
		System.debug('CH_CA: LIM CH_CA_OwnerAssignment_Controller.getWorkgroupMembers SOQL limit: ' + Limits.getQueries());
		return foundWorkgroupMembers;  
	}
	
   // Get the workgroup instructions
	@AuraEnabled
	public static CH_WorkgroupInstructions__c getWorkgroupInstructions(Id caseId,Id workgroupId,String byPassCaseTeam){
		CH_CA_Service service = new CH_CA_Service(caseId); 
		CH_CA_DTO.SearchCriteriaDTO caseFields = service.getCaseDetails();
		CH_WorkgroupInstructions__c workgroupInstructions = service.getWorkgroupInstructions(caseFields,workgroupId,caseId,byPassCaseTeam);
		System.debug('CH_CA: LIM CH_CA_OwnerAssignment_Controller.getWorkgroupInstructions SOQL limit: ' + Limits.getQueries());
		return workgroupInstructions;
	}
	
	//Description - This method is used to update case owner 
	@AuraEnabled
	public static void updateSupportTicketOwner(String caseId, String memId){
		CH_Workgroup_Member__c validWorkgroupMember = 
		[SELECT Id, CH_Workgroup__c, CH_User__c, Name, 
		  CH_Workgroup_Member_Type__c, CH_Queue_Email__c,
		  CH_Workgroup__r.Name
		 FROM CH_Workgroup_Member__c	
		 WHERE Id = :memId LIMIT 1];
		
		Map<id,CH_Workgroup_Member__c> assignment = new Map<id,CH_Workgroup_Member__c>{caseId => validWorkgroupMember};
		CH_CA_Service service = new CH_CA_Service(); 
		if(!test.isRunningTest()){service.assignUser(assignment);}
		
		System.debug('CH_CA: LIM CH_CA_OwnerAssignment_Controller.updateSupportTicketOwner SOQL limit: ' + Limits.getQueries());
	}
	
	
	@AuraEnabled
	public static CH_Workgroup__c getWorkgroupName(String caseId){
		CH_CA_Service service = new CH_CA_Service(caseId); 
		CH_CA_DTO.SearchCriteriaDTO caseFields = service.getCaseDetails();
		CH_Workgroup__c workgroupInstructions = service.getWorkgroupName(caseFields);
		System.debug('CH_CA: LIM CH_CA_OwnerAssignment_Controller.getWorkgroupInstructions SOQL limit: ' + Limits.getQueries());
		return workgroupInstructions;
	}
}