src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>L7Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>L7 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__ApprovalProcessInstance__c.object
<CustomObject>
    <description>Represents an instance of a single, end-to-end approval process.</description>
    <fields>
        <fullName>Apttus_Approval__ApprovalProcessId__c</fullName>
        <description>ID of the approval process associated with the instance</description>
        <label>Approval Process</label>
        <referenceTo>Apttus_Approval__Approval_Process__c</referenceTo>
        <relationshipLabel>Process Instances</relationshipLabel>
        <relationshipName>ApprovalProcessInstances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approval Process Instance</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Process Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__Backup_Approver__c.object
<CustomObject>
    <description>Allows approvers and administrators to specify backup approvers.  There is an option to transfer all pending request from and to the approver and the backup approver upon activation or cancellation of backups.  The approvals engine automatically routes requests to backup approvers when this is in effect.</description>
    <fields>
        <fullName>Apttus_Approval__Backup_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backup/Delegate User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N700000028l1cEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Current_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N700000028l1fEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__DelegateUserIds__c</fullName>
        <description>IDs of approvers who were designated as Delegate of Backup</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>IDs of approvers who were designated as Delegate of Backup</inlineHelpText>
        <label>Delegate Users</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__InEffect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Effect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__IsDelegate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the this entry is for delegate user.</description>
        <inlineHelpText>- If box is checked: Approver/Validator and assigned Delegate(s) will get notified.
- If box is NOT checked: it is a complete delegation = ONLY the assigned Delegate will be notified, NOT the original Approver/Validator.</inlineHelpText>
        <label>Is Delegate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegate_Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegate Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Backup_Delegate_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegate_Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegate Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Backup_Delegate_Approvers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Backup/Delegate Approver</label>
    <nameField>
        <displayFormat>BU-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backup/Delegate Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account associated with the price list</description>
        <inlineHelpText>ID of the account associated with the price list</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CXM</fullName>
                </value>
                <value>
                    <fullName>CCRE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price List</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Analytics_Source__c</fullName>
        <label>Analytics Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CXM</fullName>
                </value>
                <value>
                    <fullName>CCRE</fullName>
                </value>
                <value>
                    <fullName>RMP</fullName>
                </value>
                <value>
                    <fullName>Siteforge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Recommendation_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SW Recommendation</fullName>
                </value>
                <value>
                    <fullName>HW Recommendation</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SWx_Upsell_Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Technical Recommendation</label>
        <referenceTo>SWx_Upsell_Proposal__c</referenceTo>
        <relationshipLabel>Quote/Proposal</relationshipLabel>
        <relationshipName>Quote_Proposal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote/Proposal (Account)</relationshipLabel>
        <relationshipName>Quote_Proposal</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatusTechField__c</fullName>
        <description>Technical Field : Used for ByPass Gates Validation Rules.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Approval Status Tech Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approvals_Current_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Approvals Current Status</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>G2_Approval_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G2 Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>G3_Approval_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G3 Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SWx_Upsell_Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLD Digital Proposal</label>
        <referenceTo>SWx_Upsell_Proposal__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Role__c.object
<CustomObject>
    <description>Object that maintains the Nokia Sales Organization Hierarchy</description>
    <fields>
        <fullName>Organisation__c</fullName>
        <description>Nokia Sales Organisation Identifier</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Organisation</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Code__c</fullName>
        <description>Nokia Role Code from CMD</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <description>Nokia Role Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Role</label>
    <nameField>
        <displayFormat>CMD-{0000}</displayFormat>
        <label>Sales Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SWx_Upsell_Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Digital Proposal</relationshipLabel>
        <relationshipName>SWx_Upsell_Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Analytics_Source__c</fullName>
        <label>Analytics Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCRE</fullName>
                </value>
                <value>
                    <fullName>CXM</fullName>
                </value>
                <value>
                    <fullName>RMP</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                    <isActive>false</isActive>
                    <label>DS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Recommendation_Type__c</fullName>
        <label>Proposal Recommendation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SW Recommendation</fullName>
                </value>
                <value>
                    <fullName>HW Recommendation</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Party__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Digital Proposal (Sold To Party)</relationshipLabel>
        <relationshipName>Digital_Proposal</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Digital Proposal</label>
    <nameField>
        <displayFormat>Digital.Proposal.{000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Proposal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>NSA_Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox to check whether the user is NSA Compliant or not.</description>
        <label>NSA Compliant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nokia_ID__c</fullName>
        <description>Added custom field &apos;Nokia ID&apos; of type text(12) added for Req #061
Bandhan (hyper care time) : Marked this field as External ID field so that we can use it to connect with external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Nokia ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DS_UpdateGate2HistoryDataTest.cls
/****************************************
* Name : DS_TabRenderingTest
* Author : Accenture

*****************************************/
@isTest(seeAllData=true)
Private class DS_UpdateGate2HistoryDataTest{
	
		private static Id oppDirectRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.CREATE_DIRECT_SALES_OPPORTUNITY).getRecordTypeId();

		  /******************************
	*Method Name: executeTest
	*Description: Test Method to cover DS_UpdateGate2HstoryData class
	********************************/
	static testMethod void executeTest(){
		Set<Id> accId = new Set<Id>();
			Map<Id,Opportunity> upsellProposalToOppty = new Map<Id,Opportunity>();
		User userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		userCreation.FirstName='Danabalan';
		userCreation.LastName='Amirthalingam';
		userCreation.Nokia_ID__c = '8896';
		userCreation.IsActive=true;
		insert userCreation;
		  
		 User userCreation1 = TestDataFactory.userCreation(1,'System Administrator')[0];
		userCreation1.FirstName='Danabalan1';
		userCreation1.LastName='Amirthalingam1';
		userCreation1.Nokia_ID__c = '8895566';
		userCreation1.IsActive=true;
		insert userCreation1;
		  
			system.runAs(userCreation){
			Test.startTest();
			
			List<Account> accountCreation = TestDataFactory.createAccount(2);
			accountCreation[0].AccountNumber = '3011234';
			accountCreation[0].L7Name__c = 'APJ ANO CT Ooredoo Myanmar';
			accountCreation[1].AccountNumber = '3011235';
			database.insert(accountCreation);
			accId.add(accountCreation[0].Id);
			accId.add(accountCreation[1].Id);
			
			Id swxRecordTypeId = Schema.SObjectType.SWx_Upsell_Proposal__c.getRecordTypeInfosByName().get('SWx Upsell Proposal').getRecordTypeId();
			Id ccreRecordTypeId = Schema.SObjectType.SWx_Upsell_Proposal__c.getRecordTypeInfosByName().get('CCRE Upsell Proposal').getRecordTypeId();
		   
			List <SWx_Upsell_Proposal__c> upsellProposalList = TestDataFactory.upsellList(3,accountCreation[0]);
			upsellProposalList[0].Analytics_Source__c = CSWXGlobalConstant.AnalyticsSource;
			upsellProposalList[0].RecordTypeId= swxRecordTypeId;
			upsellProposalList[0].Proposal_Recommendation_Type__c = CSWXGlobalConstant.SW_Recommendation;
			upsellProposalList[0].Account_ID__c = accountCreation[0].id;
			upsellProposalList[0].Sold_To_Party__c= accountCreation[0].id;
			upsellProposalList[1].Analytics_Source__c = CSWXGlobalConstant.AnalyticsSource;
			   
			upsellProposalList[1].RecordTypeId= swxRecordTypeId;
				
			upsellProposalList[1].Proposal_Recommendation_Type__c = CSWXGlobalConstant.HW_Recommendation;
			upsellProposalList[1].Account_ID__c = accountCreation[1].id;
			upsellProposalList[1].Sold_To_Party__c= accountCreation[1].id;
			upsellProposalList[2].Analytics_Source__c = CSWXGlobalConstant.AnalyticsSource_CCRE;
			upsellProposalList[2].RecordTypeId= ccreRecordTypeId;
			upsellProposalList[2].Account_ID__c = accountCreation[1].id;
			upsellProposalList[2].Sold_To_Party__c= accountCreation[1].id;
			
			database.insert(upsellProposalList);
			System.assertEquals(accountCreation[0].id, upsellProposalList[0].Account_ID__c);
			System.assertEquals(accountCreation[1].id, upsellProposalList[1].Account_ID__c);
			System.assertEquals( upsellProposalList[0].Analytics_Source__c, CSWXGlobalConstant.AnalyticsSource);
			System.assertEquals( upsellProposalList[1].Analytics_Source__c, CSWXGlobalConstant.AnalyticsSource);
		 
			List<Opportunity> optyCreation = TestDataFactory.OpportunityCreation(2,accountCreation[0]);
			optyCreation[0].SWx_Upsell_Proposal__c = upsellProposalList[0].Id;
			optyCreation[0].Apttus_Approval__Approval_Status__c = CSWXGlobalConstant.Approval_stage_approved;
			optyCreation[0].ApprovalStatusTechField__c = CSWXGlobalConstant.Approved_G2;
			optyCreation[0].Approvals_Current_Status__c = CSWXGlobalConstant.Approved_G2;
			optyCreation[0].G2_Approval_Date__c = System.now();
			optyCreation[0].G3_Approval_Date__c = System.now();
		   
			optyCreation[0].RecordTypeId=oppDirectRecordTypeId;
			
		   // optyCreation[1].SWx_Upsell_Proposal__c = upsellProposalList[2].Id;
			optyCreation[1].Apttus_Approval__Approval_Status__c = CSWXGlobalConstant.Approval_stage_approved;
			optyCreation[1].ApprovalStatusTechField__c = CSWXGlobalConstant.Approved_G2;
			optyCreation[1].Approvals_Current_Status__c = CSWXGlobalConstant.Approved_G2;
			optyCreation[1].G2_Approval_Date__c = System.now();
			optyCreation[1].G3_Approval_Date__c = System.now();
			
			optyCreation[1].RecordTypeId=oppDirectRecordTypeId;
			database.insert(optyCreation);
				
			Sales_Role__c sales=new Sales_Role__c(); 
		   sales.First_Name__c='Danabalan';
		   sales.Last_Name__c='Amirthalingam';
		   sales.Organisation__c='APJ ANO CT Ooredoo Myanmar';
		   sales.Role_Code__c=CSWXGlobalConstant.NSNG_COCT;
		   sales.Role_Name__c='Amirthalingam';
		   sales.User__c=userCreation.id;
		   insert sales;
				
				 
		  
			   Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
 Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));

		User u = new User(
		  Alias = 'testu',
		  Email = 'test@nokia.com',
		  EmailEncodingKey = 'UTF-8',
		  LastName = 'Test',
		  LanguageLocaleKey = 'en_US',
		  LocaleSidKey = 'en_US',
		  TimeZoneSidKey='America/Los_Angeles',
		  ProfileId = p.Id,
		  UserName='test@nokia.com',
		  Nokia_ID__c=randomInt +'0',
		  NSA_Compliant__c=True
		);
	
		INSERT u;
	
		User u1 = new User(
		  Alias = 'testu',
		  Email = 'test1@nokia.com',
		  EmailEncodingKey = 'UTF-8',
		  LastName = 'Test',
		  LanguageLocaleKey = 'en_US',
		  LocaleSidKey = 'en_US',
		  TimeZoneSidKey='America/Los_Angeles',
		  ProfileId = p.Id,
		  UserName='test1@nokia.com',
		   Nokia_ID__c=randomInt +'01',
		   NSA_Compliant__c=True
		);
	
		INSERT u1;
		System.debug(u1.id + '@@@@@@@' + u.id);
				
			   // Apttus_Approval__ApprovalProcessInstance__c appInstance=[SELECT Id, Name, Apttus_Approval__ApprovalProcessId__c FROM Apttus_Approval__ApprovalProcessInstance__c where Name=:CSWXGlobalConstant.G2_Approvals_New Limit 1 ];
	 
		
		Apttus_Approval__Backup_Approver__c objBA = new Apttus_Approval__Backup_Approver__c();

		objBA.Apttus_Approval__Current_User__c =UserInfo.getUserId();
		//objBA.Delegate_Approver1__c = u.Id;
		//objBA.Apttus_Approval__Backup_User__c = u1.Id;		
		//objBA.Delegate_Approver2__c = u1.Id;
		objBA.Apttus_Approval__IsActive__c = true;
		objBA.Apttus_Approval__InEffect__c = true;
		objBA.Apttus_Approval__IsDelegate__c = true;
		objBA.Apttus_Approval__DelegateUserIds__c = u.Id + ',' + u1.ID;
		
		
		insert objBA;

			system.debug('objBA-----@@@@@@'+objBA);
				  system.debug('sales-----@@@@@@'+sales);
			system.debug('optyCreation[0]--->'+optyCreation[0]);
			system.debug('optyCreation[0].SWx_Upsell_Proposal__c]--->'+optyCreation[0].SWx_Upsell_Proposal__c);
			system.debug('optyCreation[0].RecordType.DeveloperName--->'+optyCreation[0].RecordType.DeveloperName);
			system.debug('optyCreation[0].StageName--->'+optyCreation[0].StageName);
			/*optyCreation[0].SWx_Upsell_Proposal__c = upsellProposalList[0].Id;
			upsellProposalToOppty.put(upsellProposalList[0].Id, optyCreation[0]);
			upsellProposalToOppty.put(upsellProposalList[1].Id, optyCreation[0]);
			upsellProposalToOppty.put(upsellProposalList[2].Id, optyCreation[0]);
			Apttus_Proposal__Proposal__c quoteProposal = TestDataFactory.createProposal(1)[0];
			Apttus_Config2__PriceList__c priceList = TestDataFactory.priceList(1)[0];
			priceList.Type__c  = CSWXGlobalConstant.AnalyticsSource;
			priceList.Apttus_Config2__AccountId__c = accountCreation[0].id;
			database.insert(priceList);
			*/
				
				DS_UpdateGate2HistoryData job = new DS_UpdateGate2HistoryData(optyCreation,optyCreation[1].Id);
			ID jobID = System.enqueueJob(job);
		
			Test.stopTest();
		   
			}
		
	}  


	
}