src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NCP_P20_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>P20 ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_ServiceType__c.field-meta.xml
<CustomField>
    <fullName>CH_ServiceType__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
                <default>true</default>
                <label>Customer Support</label>
            </value>
            <value>
                <fullName>Internal Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/HWS_Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>HWS_Contract_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field is used to store the related Contract line item. It will not be shown on the UI</description>
    <label>Contract Line Item</label>
    <referenceTo>ContractLineItem</referenceTo>
    <relationshipLabel>Support Ticket</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_RMA_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_RMA_Number__c</fullName>
    <description>Created as the part of the US.SRM.1049</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RMA Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_SPS_Order_No__c.field-meta.xml
<CustomField>
    <fullName>HWS_SPS_Order_No__c</fullName>
    <description>HWST-1860</description>
    <encryptionScheme>None</encryptionScheme>
    <label>SPS Order No</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/NCP_Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>NCP_Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ContractLineItem.object
<CustomObject>
    <fields>
        <fullName>CH_ServiceType__c</fullName>
        <description>Service Type</description>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Internal Support</fullName>
                </value>
                <value>
                    <fullName>Advanced Exchange in Days</fullName>
                </value>
                <value>
                    <fullName>Advanced Exchange in Hours</fullName>
                </value>
                <value>
                    <fullName>Return for Repair or Replacement</fullName>
                </value>
                <value>
                    <fullName>Spare Part Sales</fullName>
                </value>
                <value>
                    <fullName>MVR Identical Repair</fullName>
                </value>
                <value>
                    <fullName>Return for Exchange</fullName>
                </value>
                <value>
                    <fullName>Identical Repair</fullName>
                </value>
                <value>
                    <fullName>Eco Repair</fullName>
                </value>
                <value>
                    <fullName>Return for Modification</fullName>
                </value>
                <value>
                    <fullName>Dead On Arrival, Advanced Exchange in Days</fullName>
                </value>
                <value>
                    <fullName>Dead on Arrival, Return for Repair or Replacement</fullName>
                </value>
                <value>
                    <fullName>Return for Upgrade</fullName>
                </value>
                <value>
                    <fullName>Return for Certification</fullName>
                </value>
                <value>
                    <fullName>MVR Return for Repair or Replacement</fullName>
                </value>
                <value>
                    <fullName>Commissioning Spares</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>CH_ERPSystem__c</fullName>
        <description>ERP System</description>
        <label>ERP System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>P20</fullName>
                </value>
                <value>
                    <fullName>SAP-Blue Planet</fullName>
                </value>
                <value>
                    <fullName>SAP E-Box (NAR)</fullName>
                </value>
                <value>
                    <fullName>NSB ERP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/HWS_CancelCaseSRRequest.cls
/*****************************************************************
Description:	This class returns json string of requested case
History																														
DATE			AUTHOR		  CHANGE
12/04/2019	  Vinod T		 Created
*****************************************************************/

Public without sharing Class HWS_CancelCaseSRRequest
{
	/*****************************************************************
Description:	Returns the string json of the requested case object 
Parameters: parentCaseId
Returns:  JSON String
Throws [Exceptions]: [optional]	
History															
DATE			AUTHOR		  CHANGE
12/04/2019	  Vinod T		 Created
*****************************************************************/
	Public SOORequestBody cancelSRRequest(Id parentCaseId,Id childId){
		try{
			Case caseRec = [SELECT id,CreatedBy.Name,Status,CreatedDate,CaseNumber,Account.NCP_P20_ID__c,
							(SELECT id,HWS_RMA_Number__c,HWS_Contract_Line_Item__r.CH_ServiceType__c,Status,NCP_Service_Contract__r.CH_ERPSystem__c,HWS_SPS_Order_No__c FROM Cases
							 WHERE Status ='Ordered')
							FROM Case
							WHERE id = :parentCaseId];
			
			system.debug('-----caserec---'+caseRec);
			system.debug('-----childId ---'+childId+'-----ParentId---'+parentCaseId);
			HWS_CancelParentCase_WRAPPER parentCase ;
			if(caseRec.Cases.size() > 0 && childId == null)
			{
				system.debug('=====Parent loop===');
				parentCase = new HWS_CancelParentCase_WRAPPER(caseRec);
				for(Case childCaseRec: caseRec.Cases){
					parentCase.Requestitems.add(new HWS_CancelChildCases_WRAPPER(childCaseRec));
				}
			} 
			else
			{
				parentCase = new HWS_CancelParentCase_WRAPPER(caseRec);
				for(Case c: caseRec.Cases){
					system.debug('===childCaseRec=='+c);
					
					system.debug('=Child before if======');
					if(c.id == childId){
						system.debug('=Child to send SOO======'+childId+'=====c.id--'+c.id);
						parentCase.Requestitems.add(new HWS_CancelChildCases_WRAPPER(c));
					}
					
				}
			} 
			String jsonString = JSON.serialize(parentCase,true);
			system.debug('---jsonString---'+jsonString);
			SOORequestBody obj=new SOORequestBody();
			obj.jsonPayload=jsonString;
			obj.caseNumber=caseRec.CaseNumber;
			system.debug('---SOORequestBody---'+obj);
			return obj;
		}
		Catch(Exception e){
			System.debug('Error in CancelCaseSRRequest***'+e.getMessage() +'on line number ' +e.getLineNumber() + ' '+ e.getCause());
			return null;
		}
	}
	public class SOORequestBody{
		public String jsonPayload;
		public String caseNumber;	 
	}
}