src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Cable Operator</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Large Enterprise</label>
                </value>
                <value>
                    <fullName>Small / Medium Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Small / Medium Enterprise</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Account_Number__c</fullName>
        <formula>If(BEGINS(AccountNumber,&apos;1&apos;  ), AccountNumber ,
If(BEGINS(Parent.AccountNumber,&apos;1&apos;  ), Parent.AccountNumber ,&apos;Unknown&apos;))</formula>
        <label>Legal Entity Account Number</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__Approval_Request__c.object
<CustomObject>
    <description>Designates an approval request created from an approval process</description>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                </value>
                <value>
                    <fullName>Notified</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reassigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The Deal Object would be the Parent of multiple Opportunities and would roll up information from those opportunities where relevant.</description>
    <label>Deal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/File_Sharing_Custom_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to save configuration settings related to File sharing after upload/ migration e.t.c.</description>
    <label>File Sharing Custom Setting</label>
</CustomObject>

src/objects/NCP_CustomerCommunitySetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>DO NOT UPDATE NAME FIELD</description>
    <fields>
        <fullName>Customer_Account_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Account Number</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Account</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_User_Profile__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer User Profile</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Customer Community Setting</label>
</CustomObject>

src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>ActiveOffer__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active Offer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Offer_Due_Date__c</fullName>
        <description>Requirement 580</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Offer Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <description>This field will be appended at the end of Offer Number (01, 02)</description>
        <formula>if(
	Opportunity__r.count_offer__c &lt; 9, &apos;0&apos; &amp; TEXT(Opportunity__r.count_offer__c +1 ), TEXT(Opportunity__r.count_offer__c+ 1)
)</formula>
        <label>#Offer</label>
        <type>Text</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Opportunity</fullName>
                </value>
                <value>
                    <fullName>Committed Upsell</fullName>
                </value>
                <value>
                    <fullName>Forecasting Only</fullName>
                    <isActive>false</isActive>
                    <label>Forecasting Only</label>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Large Enterprise</label>
                </value>
                <value>
                    <fullName>Opportunity with Pre-approved or contracted T&amp;Cs</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity with Pre-approved or contracted T&amp;Cs</label>
                </value>
                <value>
                    <fullName>Opportunity within a framework contract</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity within a framework contract</label>
                </value>
                <value>
                    <fullName>Opportunity within partner agreement w/o Offer Support</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity within partner agreement w/o Offer Support</label>
                </value>
                <value>
                    <fullName>Pre-approved Pice List for BG Presales</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Pice List for BG Presales</label>
                </value>
                <value>
                    <fullName>Pre-approved Pice List for Sales</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Pice List for Sales</label>
                </value>
                <value>
                    <fullName>Pre-approved Price List for Account Managers</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Price List for Account Managers</label>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                    <isActive>false</isActive>
                    <label>Service Provider</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NF_Facilitator_Notified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to fire WF Email Notification for sending notification to Facilitators. so they can approve and submit for G3</description>
        <label>G3 Facilitator Notified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phase_Status__c</fullName>
        <description>305:Set up the following phases for the sales process for standard opportunities: 
- for the single phases refer to the attached file &quot;Sales Process_&lt;latest file version&gt;&quot; / column &quot;Sales Phase&quot;</description>
        <label>Phase Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Submitted for G2 Approval</fullName>
                </value>
                <value>
                    <fullName>Opportunity in Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted for G3 Approval</fullName>
                </value>
                <value>
                    <fullName>Offer in Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted for G4 Approval</fullName>
                </value>
                <value>
                    <fullName>Offer Submitted to Customer (Manual)</fullName>
                </value>
                <value>
                    <fullName>Submitted for G5 Approval</fullName>
                    <label>Submitted for Gate 5 Contract Approval</label>
                </value>
                <value>
                    <fullName>PTA (PROJECT TARGET AGREEMENT) HANDOVER TO DELIVERY/OPERATIONS</fullName>
                </value>
                <value>
                    <fullName>Submitted for G6 Approval</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed(not won)</fullName>
                    <label>Closed (not won)</label>
                </value>
                <value>
                    <fullName>Won (Requested)</fullName>
                </value>
                <value>
                    <fullName>Pending Win/Loss Declaration</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                    <isActive>false</isActive>
                    <label>Closed Lost</label>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                    <isActive>false</isActive>
                    <label>Closed Won</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PSR_Approval_ApprovalNotificationTest.cls
/****************************************
 * Class Name : PSR_Approval_ApprovalNotificationTest
 * Created Date: 5th June 2017
 * Created By : Accenture
 * Last Modified by: Accenture
 * Last Modified Date: 
 * Description : Test class for PSR_Approval_ApprovalNotification_Comp Class
 *****************************************/

 @isTest
Private class PSR_Approval_ApprovalNotificationTest{
	 /******************************
	*Method Name:  Notification
	*Description: Test Method to cover Approval_ApprovalNotification_Comp
	
	********************************/
	
	
	 private static User testUser = NF_TestDataFactory.createAdminUser('System Administrator');
	private static User CurrentUser = NF_TestDataFactory.createAdminUser('System Administrator');
	Private static User sysAdminUser = NF_TestDataFactory.createAdminUser('System Administrator');
	Private Static List<User> Userlist =new List<User>();
	private static List<OpportunityTeamMember> opptyTeamMemberList = new List<OpportunityTeamMember>(); 
  
	private static Account currentAccount;
	private static Opportunity currentOpportunity;
	private static Id upsellDealId = Schema.SObjectType.Deal__c.getRecordTypeInfosByName().get('Upsell Deal').getRecordTypeId();
	private static Deal__c upsellDeal;
	private static Opportunity currentOpportunityC1;
	Private Static  List<Opportunity> Opplist=new List<Opportunity>();
	Private Static List<Apttus_Approval__Approval_Request__c> Approvalrequest;
	Private Static List<Offer__c> offerList = new List<Offer__c>();
	 Private Static List<Offer__c> offerListEmp = new List<Offer__c>();
	 Private Static  List<Opportunity> OpplistEmp=new List<Opportunity>();

	
	
	 static testMethod void Notification(){
		Userlist.add(testUser);
		 Userlist.add(sysAdminUser);
	 Database.insert(Userlist);	 
	 System.runAs(sysAdminUser){
	 NCP_CustomerCommunitySetting__c cs = new NCP_CustomerCommunitySetting__c();
		cs.Name = 'Default';
		cs.Customer_Account__c = 'Customer - test';
		cs.Customer_Account_Number__c = '12345';
		cs.Customer_User_Profile__c = 'Customers';
		insert cs;
	 
	 List<File_Sharing_Custom_Setting__c> fileSharingCustomSettingList = new List<File_Sharing_Custom_Setting__c>();
		fileSharingCustomSettingList = TestDataFactory.create_File_Sharing_Custom_Setting();
		database.insert(fileSharingCustomSettingList); 
	 DateTime dT = System.now();
   Date myDate = date.newinstance(dT.year(), dT.month(), dT.day());
	 
	 
	  currentAccount = NF_TestDataFactory.createAccount('132456783');
	currentAccount.BillingState='Ontario';
		 
		insert currentAccount;
		upsellDeal = TestDataFactory.createDeal(1)[0];
		upsellDeal.RecordTypeId = upsellDealId;
		insert upsellDeal;
		
		currentOpportunity = NF_TestDataFactory.createOpportunity(currentAccount.Id, 'Develop Opportunity', 'Opportunity in Progress', Date.today().addDays(10), 700);
			
		//currentOpportunity.Organisation_Level_5__c = 'LAT GCBT CARSO';
		//currentOpportunity.Organisation_Level_4__c = 'Market Latin America';
		currentOpportunity.NF_Facilitator_Notified__c=false;
	 currentOpportunity.Business_Type__c='Committed Upsell';
		currentOpportunity.Apttus_Approval__Approval_Status__c='Pending Approval'; 
		//currentOpportunity.Deal__c = upsellDeal.Id;
		//currentOpportunity.Phase_Status__c='Submitted for G3 Approval';   
		opplist.add(currentOpportunity);
		
		Insert  opplist;
		
		 opptyTeamMemberList = TestDataFactory.optyTeamMemberCreation(1,Userlist[0],opplist[0]);
			database.insert(opptyTeamMemberList);
		
		Approvalrequest=NF_TestDataFactory.getApprovalRequests(1,opplist,Userlist);
		Test.startTest();
		insert Approvalrequest;
			//Creating Offer
			Offer__c offerCreation = TestDataFactory.OfferCreation(1,currentOpportunity)[0];
			offerCreation.ActiveOffer__c = True;
			offerCreation.Expected_LoA_G4_Approval_Level__c='c';
			offerCreation.Customer_Offer_Due_Date__c =myDate ;					
			offerList.add(offerCreation);
			insert offerList;	 
		
	
		
		Approvalrequest=NF_TestDataFactory.getApprovalRequests(1,opplist,Userlist);
		
		database.insert(Approvalrequest);
		
		
		PSR_Approval_ApprovalNotification_Comp notification = new PSR_Approval_ApprovalNotification_Comp();
		
		notification.OppId=currentOpportunity.id;
		notification.Opp=currentOpportunity;
		notification.Off=offerCreation;
		notification.CTname='Test';
		notification.getOpp();
		 notification.getOff();
		 notification.getCTname();
		 Approvalrequest=notification.oppApprovalRequests;
		 
		 
		 //Empty Pass 
		 
	
		PSR_Approval_ApprovalNotification_Comp notification1 = new PSR_Approval_ApprovalNotification_Comp();
		
		notification1.OppId=Null;
		notification1.Opp=Null;
		notification1.Off=Null;
		notification1.CTname='Test';
		notification1.getOpp();
		 notification1.getOff();
		 notification1.getCTname();
		 notification1.oppApprovalRequests=Null;

		 Test.stopTest();
		 
	
		 
	
		 }
	
	
	
	}
	
 }