src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Azores</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius And Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia And Herzegovina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_ExternalBridge__c.field-meta.xml
<CustomField>
    <fullName>CH_ExternalBridge__c</fullName>
    <description>Details of the Bridge with the customer.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>External Bridge</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/CH_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>CH_Product_Name__c</fullName>
    <formula>Product.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/CH_ReportedDate__c.field-meta.xml
<CustomField>
    <fullName>CH_ReportedDate__c</fullName>
    <description>when was the issue reported</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Reported Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/CH_ServiceType__c.field-meta.xml
<CustomField>
    <fullName>CH_ServiceType__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
                <default>true</default>
                <label>Customer Support</label>
            </value>
            <value>
                <fullName>Internal Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/CH_Workgroup__c.field-meta.xml
<CustomField>
    <fullName>CH_Workgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Workgroup</label>
    <referenceTo>CH_Workgroup__c</referenceTo>
    <relationshipLabel>Incidents and Problems</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <inlineHelpText>In case of system wide outage or major issue affecting all users, please create a P1/P2 incident ticket via our Global Support Desk.</inlineHelpText>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Information Request</fullName>
            </value>
            <value>
                <fullName>Critical- 2 Hours</fullName>
                <isActive>false</isActive>
                <label>Critical- 2 Hours</label>
            </value>
            <value>
                <fullName>High</fullName>
                <isActive>false</isActive>
                <label>High</label>
            </value>
            <value>
                <fullName>Moderate</fullName>
                <isActive>false</isActive>
                <label>Moderate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/CH_Workgroup_Member__c.object
<CustomObject>
    <description>Workgroup members are assigned to a workgroup. A workgroup member has a user or queue assigned.</description>
    <fields>
        <fullName>CH_Queue_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Queue Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CH_Workgroup__c</fullName>
        <description>The workgroup that this member is assigned to</description>
        <inlineHelpText>The workgroup that this member is assigned to</inlineHelpText>
        <label>Workgroup</label>
        <referenceTo>CH_Workgroup__c</referenceTo>
        <relationshipLabel>Workgroup Members</relationshipLabel>
        <relationshipName>CH_Workgroup_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workgroup Member</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workgroup Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country field built for User. Requirement - 615. Also a parent field in dependency between Country and Market</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius And Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CH_CA_Notifications.cls
public without sharing class CH_CA_Notifications {
	// Create a chatter post for a workgroup
	public void NotifyViaChatter(Case supportCase, CH_Workgroup_Member__c newAssignedUser){
		if (String.isBlank(newAssignedUser.CH_Workgroup__c)){
			System.debug('CH_CA: CH_Workgroup__c is blank. No Chatter post.');
			return;
		}		

		System.debug('CH_CA: Chatter post to: ' + newAssignedUser.CH_Workgroup__c + '. By user: ' + newAssignedUser);
		
		// Create the chatter post for case assignment
		String body = 'The Case ' + supportCase.CaseNumber + ' has been assigned to ' + newAssignedUser.Name + ' #WorkgroupCase \n\n';
		body += 'Case Details:\n';
		body += 'Reported to Nokia	 : ' + string.valueOfGmt(supportCase.CH_ReportedDate__c) + '\n';
		body += 'Service Type	: ' + supportCase.CH_ServiceType__c + '\n';
		body += 'Case Type	: ' + supportCase.Type + '\n';
		body += 'Severity	 : ' + supportCase.Severity__c + '\n';
		body += 'Product	  : ' + supportCase.CH_Product_Name__c + '\n';
		body += 'External Bridge Number: ' + (supportCase.CH_ExternalBridge__c == null ? '' : supportCase.CH_ExternalBridge__c) + '\n';
		body += 'Customer	 : ' + supportCase.Account.Name + '\n';
		body += 'Country	  : ' + supportCase.Country__c + '\n';
		
		// Create the chatter post
		FeedItem post = new FeedItem();
		post.ParentId = newAssignedUser.CH_Workgroup__c;
		post.Body = body;
		insert post;


		System.debug('CH_CA: Posted to Chatter for workgroup ' + newAssignedUser.CH_Workgroup__c);		
	}
	
	// Send an email for case assignment
	public void NotifyViaEmail(Case supportCase, CH_Workgroup_Member__c newAssignedUser){
		string email = newAssignedUser.CH_Queue_Email__c;
		
		if (String.isBlank(email)){
			System.debug('CH_CA: Email is blank. No Email Send.'); 
			return;
		}
		//Changes added for 29521
		String getEmailAddress = System.Label.CH_NoReplyEmailAddress;
		//Get the Ordwide Email address
		OrgWideEmailAddress[] orgEmail = new OrgWideEmailAddress[]{};
		orgEmail = [select Id from OrgWideEmailAddress where Address =: getEmailAddress LIMIT 1];
		String subject = 'Case Assigned to ' + newAssignedUser.Name + ' for ' + 
			supportCase.Account.Name + ', ' + supportCase.CH_Product_Name__c;

		String body = 'Dear User,<br><br><br>';
		body += 'The Case ' + supportCase.CaseNumber + ' has been assigned to ' + 
			newAssignedUser.Name + '.<br><br>';
		body += 'The Case is within the ' + supportCase.CH_Stage__c + ' process stage.<br><br>';
		body += '<b>Case Details:</b><br>';
		body += 'Reported to Nokia	 : ' + string.valueOfGmt(supportCase.CH_ReportedDate__c) + '<br>';
		body += 'Service Type	: ' + supportCase.CH_ServiceType__c + '<br>';
		body += 'Case Type	: ' + supportCase.Type + '<br>';
		body += 'Severity	 : ' + supportCase.Severity__c + '<br>';
		body += 'Product	  : ' + supportCase.CH_Product_Name__c + '<br>';
		body += 'External Bridge Number: ' + (supportCase.CH_ExternalBridge__c == null ? '' : supportCase.CH_ExternalBridge__c) + '<br>';
		body += 'Customer	 : ' + supportCase.Account.Name + ' ' + (supportCase.Account.Region__c == null ? '' : supportCase.Account.Region__c) + '<br>';
		body += 'Country	  : ' + (supportCase.Country__c == null ? '' : supportCase.Country__c) + '<br>';
		body += 'Current Workgroup	 : ' + newAssignedUser.CH_Workgroup__r.Name + '<br>';
		body += 'View this <a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + supportCase.id + '">Case</a><br><br>';
		body += 'Regards,<br>';
		body += 'Nokia Support Services.';

		List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
		// Create the email
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		List<String> sendTo = new List<string>();
		sendTo.add(email);
		//mail.setSenderDisplayName('Nokia Support'); 
		If(orgEmail.get(0).Id!=null){
		mail.setOrgWideEmailAddressId(orgEmail.get(0).Id); 
		}
		mail.setReplyTo('no-reply@nokia.com');
		mail.setToAddresses(new String[] {email});
		mail.setBccSender(false);
		mail.setSubject(subject);
		mail.setHtmlBody(body);
		mail.setTreatTargetObjectAsRecipient(false);
		emailList.add(mail);
		// Send the email
		Messaging.sendEmail(emailList);		

		System.debug('CH_CA: Email send to ' + email);
	}
	
	//Post to chatter
	public static void postToChatter(Map<Id, String> chatterMap){
		List<FeedItem> postsToInsert = new List<FeedItem>();
		for(Id parentId : chatterMap.keySet()){
			// Create the chatter post
			FeedItem post = new FeedItem();
			post.ParentId = parentId;
			post.Body = chatterMap.get(parentId);
			postsToInsert.add(post);
		}
		insert postsToInsert;
	}
}