src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Cable Operator</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Large Enterprise</label>
                </value>
                <value>
                    <fullName>Small / Medium Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Small / Medium Enterprise</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>L4Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>L4 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L5Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>L5 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L7Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>L7 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__Backup_Approver__c.object
<CustomObject>
    <description>Allows approvers and administrators to specify backup approvers.  There is an option to transfer all pending request from and to the approver and the backup approver upon activation or cancellation of backups.  The approvals engine automatically routes requests to backup approvers when this is in effect.</description>
    <fields>
        <fullName>Apttus_Approval__Backup_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backup/Delegate User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N700000028l1cEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Cancellation_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cancellation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Current_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N700000028l1fEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Backup/Delegate Approver</label>
    <nameField>
        <displayFormat>BU-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backup/Delegate Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Nokia_Financial_Calendar__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date of Financial  Period (Req:406)</description>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Starting Date of  Financial Period (Req:406)</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Nokia Financial Calendar</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nokia Financial Calendar</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req #2286 : Create new field for Excel Add-In</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BU__c</fullName>
        <description>Req #2286 : Create new field for Excel Add-In</description>
        <label>Lead BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Offer_Lead_BU</valueSetName>
        </valueSet>
    </fields>
    <label>Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Opportunity</fullName>
                </value>
                <value>
                    <fullName>Committed Upsell</fullName>
                </value>
                <value>
                    <fullName>Forecasting Only</fullName>
                    <isActive>false</isActive>
                    <label>Forecasting Only</label>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Large Enterprise</label>
                </value>
                <value>
                    <fullName>Opportunity with Pre-approved or contracted T&amp;Cs</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity with Pre-approved or contracted T&amp;Cs</label>
                </value>
                <value>
                    <fullName>Opportunity within a framework contract</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity within a framework contract</label>
                </value>
                <value>
                    <fullName>Opportunity within partner agreement w/o Offer Support</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity within partner agreement w/o Offer Support</label>
                </value>
                <value>
                    <fullName>Pre-approved Pice List for BG Presales</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Pice List for BG Presales</label>
                </value>
                <value>
                    <fullName>Pre-approved Pice List for Sales</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Pice List for Sales</label>
                </value>
                <value>
                    <fullName>Pre-approved Price List for Account Managers</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Price List for Account Managers</label>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                    <isActive>false</isActive>
                    <label>Service Provider</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Signing_Entity__c</fullName>
        <description>Req::802 This flag / field shall identify the Legal Entity</description>
        <inlineHelpText>Based on the ERP system used to execute/deliver the orders. 
For example - If Order execution/Customer invoicing is done using fNOK SAP P20 system then select fNOK otherwise, if using fALU SAP BPP system then select fALU.</inlineHelpText>
        <label>Contract Signing Entity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>fALU</fullName>
                </value>
                <value>
                    <fullName>fNOK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_LoA_Approval_Level__c</fullName>
        <description>Expected LoA Approval Level for Offer</description>
        <inlineHelpText>Expected LoA Approval Level for Offer. Currently inactive</inlineHelpText>
        <label>Old Expected LoA Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LoA_G4_Approval_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>G4_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G4 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req 569: User will select Lead BG manually</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BU__c</fullName>
        <description>Selection of group within MN to lead on approvals. Mandatory selection from drop-down list if MN or ION are chosen as the Lead BG</description>
        <label>Lead BU</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_BG__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Business_Units</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SWx_Upsell_Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLD Digital Proposal</label>
        <referenceTo>SWx_Upsell_Proposal__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Request__c</fullName>
        <description>319: Standard Feild for Opportunity to know thw type of the request.</description>
        <label>Type of Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>RFP/RFI</fullName>
                </value>
                <value>
                    <fullName>Simple Offers</fullName>
                </value>
                <value>
                    <fullName>Proactive Bid</fullName>
                </value>
                <value>
                    <fullName>Budgetary Quote</fullName>
                    <isActive>false</isActive>
                    <label>Budgetary Quote</label>
                </value>
                <value>
                    <fullName>Proactive</fullName>
                    <isActive>false</isActive>
                    <label>Proactive</label>
                </value>
                <value>
                    <fullName>RFI</fullName>
                    <isActive>false</isActive>
                    <label>RFI</label>
                </value>
                <value>
                    <fullName>RFQ</fullName>
                    <isActive>false</isActive>
                    <label>RFQ</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unweighted_Amount_EUR__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Field will update as per the OIF Amount EUR value (Req:136)</description>
        <label>Unweighted Value EUR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Group__c</fullName>
        <description>Select the Business Group (Req:152)</description>
        <label>Business Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/globalValueSets/LoA_G4_Approval_Levels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A+</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>LoA Bypass</fullName>
        <label>G4/G5 Bypass</label>
    </customValue>
    <customValue>
        <fullName>A light</fullName>
        <isActive>false</isActive>
        <label>A light</label>
    </customValue>
    <description>Global picklist for LoA G4 Approval Levels</description>
    <masterLabel>LoA G4 Approval Levels</masterLabel>
</GlobalValueSet>

src/globalValueSets/Offer_Lead_BU.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>NI - FN</fullName>
    </customValue>
    <customValue>
        <fullName>NI - IPRTG</fullName>
    </customValue>
    <customValue>
        <fullName>NI - OPTICS</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NE EOP</fullName>
        <isActive>false</isActive>
        <label>NE EOP</label>
    </customValue>
    <customValue>
        <fullName>ION Video</fullName>
        <isActive>false</isActive>
        <label>ION Video</label>
    </customValue>
    <customValue>
        <fullName>ION IPR</fullName>
        <isActive>false</isActive>
        <label>ION IPR</label>
    </customValue>
    <customValue>
        <fullName>ION Optics</fullName>
        <isActive>false</isActive>
        <label>ION Optics</label>
    </customValue>
    <customValue>
        <fullName>SPS</fullName>
        <isActive>false</isActive>
        <label>SPS</label>
    </customValue>
    <customValue>
        <fullName>PPS</fullName>
        <isActive>false</isActive>
        <label>PPS</label>
    </customValue>
    <customValue>
        <fullName>NE SOL</fullName>
        <isActive>false</isActive>
        <label>NE SOL</label>
    </customValue>
    <customValue>
        <fullName>NE DAaaS</fullName>
        <isActive>false</isActive>
        <label>NE DAaaS</label>
    </customValue>
    <customValue>
        <fullName>NE IoT</fullName>
        <isActive>false</isActive>
        <label>NE IoT</label>
    </customValue>
    <customValue>
        <fullName>CNS - NEN</fullName>
        <isActive>false</isActive>
        <label>CNS - NEN</label>
    </customValue>
    <customValue>
        <fullName>CNS - CNSCORE</fullName>
        <isActive>false</isActive>
        <label>CNS - CNSCORE</label>
    </customValue>
    <customValue>
        <fullName>CNS - CNSBS</fullName>
        <isActive>false</isActive>
        <label>CNS - CNSBS</label>
    </customValue>
    <customValue>
        <fullName>CNS - CNSCMO</fullName>
        <isActive>false</isActive>
        <label>CNS - CNSCMO</label>
    </customValue>
    <description>Values for Lead BU from Offer</description>
    <masterLabel>Offer Lead BU</masterLabel>
</GlobalValueSet>

src/classes/NF_FacilitatorNotificationCtrl_CloneTest.cls
/**
* @name	NF_FacilitatorNotificationCtrl_CloneTest
* @author
* @since   July 08, 2017
* @desc	Class used to to cover the code for NF_FacilitatorNotificationCtrl_Clone 
* @history
*/

@isTest
private class NF_FacilitatorNotificationCtrl_CloneTest{
    private static User testUser = NF_TestDataFactory.createAdminUser('System Administrator');
    private static User dataloaderUser = NF_TestDataFactory.createAdminUser('Data Loader Profile');
    private static Id upsellDealId = Schema.SObjectType.Deal__c.getRecordTypeInfosByName().get('Upsell Deal').getRecordTypeId();
    private static Id swxRecordTypeId = Schema.SObjectType.SWx_Upsell_Proposal__c.getRecordTypeInfosByName().get('SWx Upsell Proposal').getRecordTypeId();
    
    private static Opportunity currentOpportunity;
    private static Account currentAccount;
    
    private static String stageName;
    private static String phaseStatus;
    private static String l4;
    private static String l5;
    private static String l7;
    private static String bg;
    private static String bu;
    private static Boolean noG4PlannedDate = false;
    private static String teamMemberRole;
    private static Boolean withOIF;
    private static String roleCode;
    private static Double totalValue = 1000.0;
    
    public static void setup(){
        
        //insert account
        currentAccount = NF_TestDataFactory.createAccount('132456783');
        currentAccount.L7Name__c = l7;
        currentAccount.L5Name__c = l5;
        currentAccount.L4Name__c = l4;
        insert currentAccount;
        //insert opp
        currentOpportunity = NF_TestDataFactory.createOpportunity(currentAccount.Id, stageName, phaseStatus, Date.today().addDays(10), 100);
        currentOpportunity.Business_Type__c=GlobalConstants.STANDARDOPPORTUNITY;
        currentOpportunity.Contract_Signing_Entity__c='fALU';
        currentOpportunity.Lead_BG__c = bg;
        currentOpportunity.Lead_BU__c = bu;
        currentOpportunity.Unweighted_Amount_EUR__c = totalValue;
        currentOpportunity.Type_of_Request__c = GlobalConstants.TYPE_REQUEST_RFP_RFI;
        currentOpportunity.Expected_LoA_Approval_Level__c = 'E';
        if(noG4PlannedDate) currentOpportunity.G4_Planned_Date__c = null;
        insert currentOpportunity;
        
    }
    
    public static void addTeamMember(){
        List<OpportunityTeamMember> opptyTeamMembers = TestDataFactory.optyTeamMemberCreation(1, testUser, currentOpportunity);
        opptyTeamMembers[0].TeamMemberRole = teamMemberRole;
        insert opptyTeamMembers;
    }
    
    public static void addOIF(){
        Product2 prod = TestDataFactory.productCreation(1)[0];
        prod.Business_Group__c='FN';
        prod.Family= 'FNCABLE';
        database.insert(prod);
        Nokia_Financial_Calendar__c nokiaFinCal = TestDataFactory.nokiaFinCalCreation(1)[0];
        database.insert(nokiaFinCal);
        nokiaFinCal.Start_Date__c=system.today()+1;
        nokiaFinCal.End_Date__c = system.today()+2;
        database.update(nokiaFinCal);
        List<Order_Intake_Forecast__c> oif1=new List<Order_Intake_Forecast__c>();
        oif1=TestDataFactory.orderIntakeCreation(1,currentOpportunity,prod,nokiaFinCal);
        insert oif1;
    }
    
    public static void addSalesRole(){
        User delegate1User = NF_TestDataFactory.createAdminUser('System Administrator');
        insert delegate1User;
        String orgLevel = l7 != null ? l7 : l5;
        Sales_Role__c currentSalesOrg = NF_TestDataFactory.createSalesRole(dataloaderUser, roleCode, orgLevel, '5 - G3 Facilitator');
        insert currentSalesOrg;
        Apttus_Approval__Backup_Approver__c backupApprover =new Apttus_Approval__Backup_Approver__c (
            Apttus_Approval__Backup_User__c= null,
            Apttus_Approval__Cancellation_Date__c= null,
            Apttus_Approval__Comment__c= null,
            Apttus_Approval__Current_User__c= dataloaderUser.Id,
            Apttus_Approval__DelegateUserIds__c= delegate1User.Id,
            Apttus_Approval__Effective_Date__c= null,
            Apttus_Approval__Expiration_Date__c= null,
            Apttus_Approval__InEffect__c= true,
            Apttus_Approval__IsActive__c= true,
            Apttus_Approval__IsDelegate__c= true,
            Apttus_Approval__SuppressDelegateNotification__c= false,
            Apttus_Approval__Transfer_in_flight__c= true,
            Delegate_Approver1__c= delegate1User.Id
        );
        insert backupApprover;
    }
    
    @isTest
    public static void testFacilitatorNotif_UpsellOpptyWithTeam(){
        insert testUser;
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'Market Europe';
        l5 = 'EUR GCBT Vodafone';
        bg = 'GS';
        teamMemberRole = CSWXGlobalConstant.AM;
        system.runAs(testUser){
            setup();
            addTeamMember();			
            Test.startTest();
            
            SWx_Upsell_Proposal__c upsellProposal_SWX=TestDataFactory.upsellList(1,currentAccount)[0];
            upsellProposal_SWX.Analytics_File_Refer_ID__c='GBR-61940-82356';
            upsellProposal_SWX.Analytics_Source__c='CXM';
            upsellProposal_SWX.Proposal_Recommendation_Type__c='renewal';
            upsellProposal_SWX.P20_Id__c=215616;
            upsellProposal_SWX.CurrencyIsoCode='EUR';
            upsellProposal_SWX.Unweighted_Value__c=429052;
            upsellProposal_SWX.Account_ID__c=currentAccount.Id;
            upsellProposal_SWX.Sold_To_Party__c = currentAccount.Id;
            upsellProposal_SWX.RecordTypeID=swxRecordTypeId;
            insert upsellProposal_SWX;
            
            currentOpportunity.SWx_Upsell_Proposal__c = upsellProposal_SWX.Id;
            update currentOpportunity;
            
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.init();
            currentOpportunity = facilitatorNotCtrl.currentOpp;
            facilitatorNotCtrl.ConfirmG3Facilitator();
            currentOpportunity = facilitatorNotCtrl.currentOpp;
            Test.stopTest();
            System.assert(facilitatorNotCtrl.FacilitatorName != null);
            System.assert(currentOpportunity.NF_Facilitator_Notified__c);
        }
        
    }
    
    @isTest
    public static void testFacilitatorNotif_UpsellOpptyWithoutTeam(){
        insert testUser;
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'Market Europe';
        l5 = 'EUR GCBT Vodafone';
        bg = 'GS';
        system.runAs(testUser){			
            setup();
            
            Test.startTest();
            
            SWx_Upsell_Proposal__c upsellProposal_SWX=TestDataFactory.upsellList(1,currentAccount)[0];
            upsellProposal_SWX.Analytics_File_Refer_ID__c='GBR-61940-82356';
            upsellProposal_SWX.Analytics_Source__c='CXM';
            upsellProposal_SWX.Proposal_Recommendation_Type__c='renewal';
            upsellProposal_SWX.P20_Id__c=215616;
            upsellProposal_SWX.CurrencyIsoCode='EUR';
            upsellProposal_SWX.Unweighted_Value__c=429052;
            upsellProposal_SWX.Account_ID__c=currentAccount.Id;
            upsellProposal_SWX.Sold_To_Party__c = currentAccount.Id;
            upsellProposal_SWX.RecordTypeID=swxRecordTypeId;
            insert upsellProposal_SWX;
            
            currentOpportunity.SWx_Upsell_Proposal__c = upsellProposal_SWX.Id;
            update currentOpportunity;
            
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.init();
            Test.stopTest();
            System.assert(facilitatorNotCtrl.FacilitatorName == null);
        }
        
    }
    
    @isTest
    public static void testFacilitatorNotif_IdentifyOppty(){
        insert testUser;
        stageName = 'Identify Opportunity';
        phaseStatus = 'Planned';
        l4 = 'Market Europe';
        l5 = 'EUR GCBT Vodafone';
        bg = 'GS';
        system.runAs(testUser){
            setup();
            Test.startTest();
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.showMandatoryInfo = false;
            facilitatorNotCtrl.init();
            Test.stopTest();
            System.assert(ApexPages.getMessages()[0].getDetail().contains( String.format(Label.NF_OnlyFacilitatorCanBeNotified,new String[] {GlobalConstants.DEVELOP_OPPORTUNITY})));
        }
        
    }
    
    @isTest
    public static void testFacilitatorNotif_G3Bypass(){
        insert testUser;
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'Market Europe';
        l5 = 'EUR GCBT Vodafone';
        bg = 'GS';
        system.runAs(testUser){
            
            setup();
            Test.startTest();
            
            Offer__c currentOffer = TestDataFactory.OfferCreation(1,currentOpportunity)[0];
            currentOffer.ActiveOffer__c = true;
            currentOffer.No_Support_Offer_Condition__c = GlobalConstants.PICKLIST_VALUE_YES;
            insert currentOffer;
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.showMandatoryInfo = false;
            facilitatorNotCtrl.init();
            Test.stopTest();
            System.assert(ApexPages.getMessages()[0].getDetail().contains(GlobalConstants.G3_FACILITATOR_BYPASS));
        }
    }
    
    @isTest
    public static void testFacilitatorNotif_G4PlannedDate(){
        insert testUser;
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'Market Europe';
        l5 = 'EUR GCBT Vodafone';
        bg = 'GS';
        noG4PlannedDate = true;
        system.runAs(testUser){
            setup();
            addOIF();
            Test.startTest();
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.showMandatoryInfo = false;
            facilitatorNotCtrl.init();
            currentOpportunity = facilitatorNotCtrl.currentOpp;
            Test.stopTest();
            List<ApexPages.Message> messages = ApexPages.getMessages();
            System.assert(messages[0].getDetail().contains(Label.NF_G4_PlannedDate_Error));
        }
        
    }
    
    @isTest
    public static void testFacilitatorNotif_WithoutOIF(){
        insert testUser;
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'Market Europe';
        l5 = 'EUR GCBT Vodafone';
        bg = 'GS';
        system.runAs(testUser){
            
            setup();
            Test.startTest();
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.showMandatoryInfo = false;
            facilitatorNotCtrl.init();
            Test.stopTest();
            System.assert(ApexPages.getMessages()[0].getDetail().contains(GlobalConstants.MANDATORY_OIF_FOR_APPROVAL));
        }
        
    }
    
    @isTest
    public static void testFacilitatorNotif_AlreadyNotified(){
        insert testUser;
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'Market Europe';
        l5 = 'EUR GCBT Vodafone';
        bg = 'GS';
        system.runAs(testUser){
            
            setup();
            addOIF();
            Test.startTest();
            currentOpportunity.NF_Facilitator_Notified__c = true;            
            update currentOpportunity;
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.showMandatoryInfo = false;
            facilitatorNotCtrl.init();
            Test.stopTest();
            System.assert(ApexPages.getMessages()[0].getDetail().contains(Label.NF_Facilitator_already_notified));
        }
        
    }
    
    @isTest
    public static void testFacilitatorNotif_MarketLATQueue(){		
        insert testUser;
        
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'Market Latin America';
        l5 = 'LAT GCBT CARSO';
        bg = 'ION';
        bu = 'ION IPR';
        roleCode = 'NSND_OQM';
        
        system.runAs(testUser){
            
            setup();
            addOIF();
            
            Test.startTest();
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.showMandatoryInfo = false;
            facilitatorNotCtrl.init();
            Test.stopTest();
            System.assert(ApexPages.getMessages()[0].getDetail().contains(GlobalConstants.G3_FACILITATOR_FOUND));
            System.assert(facilitatorNotCtrl.facilitatorQueue != null);
        }
        
    }
    
    @isTest
    public static void testFacilitatorNotif_MarketEuropeMandatoryFields(){		
        insert testUser;
        insert dataloaderUser;
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'Market Europe';
        l5 = 'EUR GCBT Vodafone';
        bg = 'FN';
        roleCode = 'NSND_OQM';
        system.runAs(dataloaderUser){
            setup();
            addOIF();
            Test.startTest();
            addSalesRole();
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.init();
            facilitatorNotCtrl.saveAndReturn();   
            facilitatorNotCtrl.init();
            facilitatorNotCtrl.proceed();
            facilitatorNotCtrl.currentOpp.Probability = 50;
            facilitatorNotCtrl.proceed();
            Test.stopTest();
            List<ApexPages.Message> messages = ApexPages.getMessages();
            System.assert(messages[0].getDetail().contains(GlobalConstants.G3_FACILITATOR_INFO_MSG));
            System.assert(facilitatorNotCtrl.FacilitatorName != null);
        }	
    }
    
    @isTest
    public static void testFacilitatorNotif_MarketEurope(){		
        insert testUser;
        insert dataloaderUser;
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'Market Europe';
        l5 = 'EUR GCBT Vodafone';
        bg = 'FN';
        roleCode = 'NSND_OQM';
        system.runAs(dataloaderUser){
            setup();
            addOIF();
            Test.startTest();
            addSalesRole();
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.showMandatoryInfo = false;
            facilitatorNotCtrl.init();
            currentOpportunity = facilitatorNotCtrl.currentOpp;
            facilitatorNotCtrl.ConfirmG3Facilitator();
            Test.stopTest();
            List<ApexPages.Message> messages = ApexPages.getMessages();
            Integer msgSize = messages.size();
            System.assert(messages[0].getDetail().contains(GlobalConstants.G3_FACILITATOR_FOUND));
            System.assert(facilitatorNotCtrl.FacilitatorName != null);
        }	
    }
    
    
    @isTest
    public static void testFacilitatorNotif_MarketNAM1(){		
        insert testUser;
        stageName = 'Develop Opportunity';
        phaseStatus = 'Opportunity in Progress';
        l4 = 'NE Americas';
        l5 = 'NE AME NAM';
        bg = 'NSW';
        system.runAs(testUser){
            
            
            setup();
            addOIF();
            Test.startTest();
            ApexPages.currentPage().getParameters().put('oppId', currentOpportunity.Id);
            NF_FacilitatorNotificationCtrl_Clone facilitatorNotCtrl = new NF_FacilitatorNotificationCtrl_Clone();
            facilitatorNotCtrl.showMandatoryInfo = false;
            facilitatorNotCtrl.init();
            currentOpportunity = facilitatorNotCtrl.currentOpp;
            facilitatorNotCtrl.ConfirmG3Facilitator();
            Test.stopTest();
            List<ApexPages.Message> messages = ApexPages.getMessages();
            Integer msgSize = messages.size();
            System.assert(messages[0].getDetail().contains(GlobalConstants.G3_FACILITATOR_FOUND));
            System.assert(currentOpportunity.NF_Facilitator_Notified__c);
        }
        
    }

}