src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Account_Number__c</fullName>
        <formula>If(BEGINS(AccountNumber,&apos;1&apos;  ), AccountNumber ,
If(BEGINS(Parent.AccountNumber,&apos;1&apos;  ), Parent.AccountNumber ,&apos;Unknown&apos;))</formula>
        <label>Legal Entity Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L4Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>L4 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__Approval_Request_History__c.object
<CustomObject>
    <description>Designates history for an approval request created from an approval process</description>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reassigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Notified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Approval__DelegateApproverIds__c</fullName>
        <description>IDs of approvers who were designated as Delegate for the Request Assignee</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>IDs of approvers who were designated as Delegate for the Request Assignee</inlineHelpText>
        <label>Delegate Approvers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NF_Assignee_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Assignee Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NF_Organization_Level__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Organisation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NF_Role_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NF_Role_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Request History</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Request History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__ApprovalRule__c.object
<CustomObject>
    <description>Represents a single rule in an approval ruleset</description>
    <label>Approval Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__ApprovalRuleAssignee__c.object
<CustomObject>
    <description>Represents a single assignee in an approval rule entry</description>
    <fields>
        <fullName>Apttus_Approval__AssigneeDescription__c</fullName>
        <description>The assignee description</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Assignee Description</label>
        <type>TextArea</type>
    </fields>
    <label>Approval Rule Assignee</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Assignee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Rule Assignees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__ApprovalRuleEntry__c.object
<CustomObject>
    <description>Represents a single entry in an approval rule</description>
    <fields>
        <fullName>Apttus_Approval__EntryLabel__c</fullName>
        <description>The entry label</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the name of a custom label containing text that will be used as the label for the entry</inlineHelpText>
        <label>Entry Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Rule Entry</label>
    <nameField>
        <displayFormat>RE-{0000000000}</displayFormat>
        <label>Rule Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NCP_CustomerCommunitySetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>DO NOT UPDATE NAME FIELD</description>
    <fields>
        <fullName>Customer_Account_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Account Number</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Account</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_User_Profile__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer User Profile</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Customer Community Setting</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req 569: User will select Lead BG manually</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BU__c</fullName>
        <description>Selection of group within MN to lead on approvals. Mandatory selection from drop-down list if MN or ION are chosen as the Lead BG</description>
        <label>Lead BU</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_BG__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Business_Units</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Org_L2__c</fullName>
        <formula>Account.L2Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation Level 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L3__c</fullName>
        <formula>Account.L3Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_3</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L4__c</fullName>
        <formula>Account.L4Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_4</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L5__c</fullName>
        <formula>Account.L5Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_5</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L6__c</fullName>
        <formula>Account.L6Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_6</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L7__c</fullName>
        <formula>Account.L7Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_7</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase_Status__c</fullName>
        <description>305:Set up the following phases for the sales process for standard opportunities: 
- for the single phases refer to the attached file &quot;Sales Process_&lt;latest file version&gt;&quot; / column &quot;Sales Phase&quot;</description>
        <label>Phase Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Submitted for G2 Approval</fullName>
                </value>
                <value>
                    <fullName>Opportunity in Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted for G3 Approval</fullName>
                </value>
                <value>
                    <fullName>Offer in Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted for G4 Approval</fullName>
                </value>
                <value>
                    <fullName>Offer Submitted to Customer (Manual)</fullName>
                </value>
                <value>
                    <fullName>Submitted for G5 Approval</fullName>
                    <label>Submitted for Gate 5 Contract Approval</label>
                </value>
                <value>
                    <fullName>PTA (PROJECT TARGET AGREEMENT) HANDOVER TO DELIVERY/OPERATIONS</fullName>
                </value>
                <value>
                    <fullName>Submitted for G6 Approval</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed(not won)</fullName>
                    <label>Closed (not won)</label>
                </value>
                <value>
                    <fullName>Won (Requested)</fullName>
                </value>
                <value>
                    <fullName>Pending Win/Loss Declaration</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                    <isActive>false</isActive>
                    <label>Closed Lost</label>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                    <isActive>false</isActive>
                    <label>Closed Won</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Role__c.object
<CustomObject>
    <description>Object that maintains the Nokia Sales Organization Hierarchy</description>
    <fields>
        <fullName>BG__c</fullName>
        <description>For CMD BG Attribute coming from Pack4</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BG Attribute</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <description>Nokia Sales Organisation Identifier</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Organisation</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Code__c</fullName>
        <description>Nokia Role Code from CMD</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Role</label>
    <nameField>
        <displayFormat>CMD-{0000}</displayFormat>
        <label>Sales Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/classes/NF_TL_UpdateHistoryRequestRCodeTest.cls
@isTest
private class NF_TL_UpdateHistoryRequestRCodeTest {
	
	private static User testUser = NF_TestDataFactory.createAdminUser('System Administrator');
	private static User testUser2 = NF_TestDataFactory.createAdminUser('System Administrator');
	private static Account currentAccount;
	private static Opportunity currentOpportunity;
	private static Opportunity currentOpportunity1;
	private static Opportunity currentOpportunity2;
	private static Opportunity currentOpportunity3;
	private static Sales_Role__c currentSalesOrg;
	private static Sales_Role__c currentSalesOrg1;
	private static Sales_Role__c currentSalesOrg2;
	private static Apttus_Approval__ApprovalRuleAssignee__c ruleAssignee;
	private static Apttus_Approval__ApprovalRuleAssignee__c ruleAssignee1;
	private static Apttus_Approval__ApprovalRuleAssignee__c ruleAssignee2;
	private static Apttus_Approval__ApprovalRuleAssignee__c ruleAssignee3;
	 
	Private Static List<Apttus_Approval__Approval_Request_History__c > CurrentRequest=new  List<Apttus_Approval__Approval_Request_History__c >();
	
	private static Apttus_Approval__Approval_Request_History__c currentApprovalRequest;
	private static Apttus_Approval__Approval_Request_History__c currentApprovalRequest1;
	private static Apttus_Approval__Approval_Request_History__c currentApprovalRequest2;
	private static Apttus_Approval__Approval_Request_History__c currentApprovalRequest3;
	 
	 

	public static void setup(){
	
	insert testUser2;
	
		 
		
		currentAccount = NF_TestDataFactory.createAccount('132456783');
		currentAccount.L4Name__c = 'LAT CARSO CT CO';
		insert currentAccount;

		List<Opportunity> oppList = new List<Opportunity>();
		currentOpportunity = NF_TestDataFactory.createOpportunity(currentAccount.Id, 'Develop Opportunity', 'Opportunity in Progress', Date.today().addDays(10), 700);
		//currentOpportunity.Organisation_Level_4__c = 'LAT CARSO CT CO';
		currentOpportunity.lead_bg__c = 'NSW';
		oppList.add(currentOpportunity);
		
		currentOpportunity1= NF_TestDataFactory.createOpportunity(currentAccount.Id, 'Develop Opportunity', 'Opportunity in Progress', Date.today().addDays(10), 700);
		//currentOpportunity1.Organisation_Level_4__c = 'LAT CARSO CT CO';
		currentOpportunity1.lead_bg__c = 'NSW';
		oppList.add(currentOpportunity1);
		
		currentOpportunity2 = NF_TestDataFactory.createOpportunity(currentAccount.Id, 'Develop Opportunity', 'Opportunity in Progress', Date.today().addDays(10), 700);
		//currentOpportunity2.Organisation_Level_4__c = 'LAT CARSO CT CO';
		currentOpportunity2.lead_bg__c = 'ION';
		currentOpportunity2.lead_bu__c = 'ION IPR';
		oppList.add(currentOpportunity2);
		
		currentOpportunity2.Phase_Status__c='Submitted for G3 Approval';
		currentOpportunity2.StageName='Develop Opportunity';
	 //Update currentOpportunity2 ;
		insert oppList;
		
		//List<Sales_Role__c> salesRoleList = new List<Sales_Role__c>();
		currentSalesOrg = NF_TestDataFactory.createSalesRole(testUser, 'NSNC_BM', 'LAT CARSO CT CO', '4 - RBC Presales Head AA G3 MU');
		insert currentSalesOrg;
		currentSalesOrg1 = NF_TestDataFactory.createSalesRole(testUser, 'NSNC_BM', 'LAT CARSO CT CO', '4 - RBC Presales Head AA G3 MU');
		CurrentSalesOrg1.BG__c='NSW';
		insert currentSalesOrg1;
		currentSalesOrg2 = NF_TestDataFactory.createSalesRole(testUser2, 'NSNC_BM', 'LAT CARSO CT CO', '4 - RBC Presales Head AA G3 MU');
		CurrentSalesOrg2.BG__c='ION';
		insert currentSalesOrg2;
		//salesRoleList.add(currentSalesOrg);
		//salesRoleList.add(currentSalesOrg1);
		//salesRoleList.add(currentSalesOrg2);
		//insert salesRoleList; 
		
		Apttus_Approval__ApprovalRule__c appRule = NF_TestDataFactory.createApprovalRule('rule class C1', true, 'Opportunity', 'Condition', 1);
		insert appRule;

		List<Apttus_Approval__ApprovalRuleEntry__c> ruleEntryList = new List<Apttus_Approval__ApprovalRuleEntry__c>();
		Apttus_Approval__ApprovalRuleEntry__c ruleEntry = NF_TestDataFactory.createRuleEntry(appRule.Id, 1);
		ruleEntry.Apttus_Approval__EntryLabel__c = 'Rule1';
		Apttus_Approval__ApprovalRuleEntry__c ruleEntry1 = NF_TestDataFactory.createRuleEntry(appRule.Id, 2);
		ruleEntry1.Apttus_Approval__EntryLabel__c = 'Rule2';
		Apttus_Approval__ApprovalRuleEntry__c ruleEntry2 = NF_TestDataFactory.createRuleEntry(appRule.Id, 3);
		ruleEntry2.Apttus_Approval__EntryLabel__c = 'Rule3';
		ruleEntryList.add(ruleEntry);
		ruleEntryList.add(ruleEntry1);
		ruleEntryList.add(ruleEntry2);
		insert ruleEntryList;
	 
		String assigneeValue2 = 'Sales_Role__c (Role_Code__c =\'%\\_BM\' AND Organisation__c =\':Org_L4__c\' AND Active=true AND (BG__c=\':Lead_BG__c\' OR BG__c=\':Lead_BU__c\'))).User__c';
		String assigneeValue1 = 'Sales_Role__c (Role_Code__c =\'%\\_BM\' AND Organisation__c =\':Org_L4__c\' AND Active=true).User__c';
		String assigneeValue ='Sales_Role__c(( Role_Code__c=\'%\\_BM\' AND ( Organisation__c =\':Org_L4__c\' OR Organisation__c =\':Org_L5__c\' OR Organisation__c =\':Org_L6__c\' OR Organisation__c =\':Org_L7__c\') AND Active=true AND BG__c=\'NSW\')).User__c';
		String assigneeValue3 = 'Sales_Role__c (Role_Code__c =\'%\\_BM\' AND (Organisation__c =\':Org_L2__c\' OR Organisation__c =\':Org_L3__c\') AND Active=true).User__c';
		
		List<Apttus_Approval__ApprovalRuleAssignee__c> ruleAssigneeList = new List<Apttus_Approval__ApprovalRuleAssignee__c>();
		ruleAssignee = NF_TestDataFactory.createArAssignee(ruleEntry.Id, 1, true, false, assigneeValue);
		ruleAssignee.Apttus_Approval__AssigneeDescription__c = 'NSNC_BM, Validator';
		ruleAssigneeList.add(ruleAssignee);
		
		
		ruleAssignee1 = NF_TestDataFactory.createArAssignee(ruleEntry.Id, 1, true, false, assigneeValue1);
		ruleAssignee1.Apttus_Approval__AssigneeDescription__c = 'NSNC_BM, Validator';
		ruleAssigneeList.add(ruleAssignee1);
		
		ruleAssignee2 = NF_TestDataFactory.createArAssignee(ruleEntry.Id, 1, true, false, assigneeValue2);
		ruleAssignee2.Apttus_Approval__AssigneeDescription__c = 'NMSD_BM, Validator';
		ruleAssigneeList.add(ruleAssignee2);
		
		ruleAssignee3 = NF_TestDataFactory.createArAssignee(ruleEntry1.Id, 1, true, false, assigneeValue3);
		ruleAssignee3.Apttus_Approval__AssigneeDescription__c = 'NSNG_BM, Validator';
		ruleAssigneeList.add(ruleAssignee3);
		insert ruleAssigneeList;
	
		ruleAssignee = [Select Id, Name, Apttus_Approval__AssigneeDescription__c from Apttus_Approval__ApprovalRuleAssignee__c where Id = :ruleAssignee.Id];
		ruleAssignee1 = [Select Id, Name, Apttus_Approval__AssigneeDescription__c from Apttus_Approval__ApprovalRuleAssignee__c where Id = :ruleAssignee1.Id];
		ruleAssignee2 = [Select Id, Name, Apttus_Approval__AssigneeDescription__c from Apttus_Approval__ApprovalRuleAssignee__c where Id = :ruleAssignee2.Id];
		ruleAssignee3 = [Select Id, Name, Apttus_Approval__AssigneeDescription__c from Apttus_Approval__ApprovalRuleAssignee__c where Id = :ruleAssignee3.Id];
		
		currentApprovalRequest = NF_TestDataFactory.createApprovalHistoryRequest('Notified', 'User', 'Opportunity', currentOpportunity.Id, true, false, testUser.FirstName+''+testUser.LastName, testUser.Id, ruleAssignee.Name);
		currentApprovalRequest.Apttus_Approval__DelegateApproverIds__c=testUser.Id+','+testUser.Id;
		currentApprovalRequest.NF_Assignee_Type__c='Validator';
		CurrentRequest.add(currentApprovalRequest);
		
		currentApprovalRequest1 = NF_TestDataFactory.createApprovalHistoryRequest('Notified', 'User', 'Opportunity', currentOpportunity.Id, true, false, testUser.FirstName+''+testUser.LastName, testUser.Id, ruleAssignee1.Name);
		currentApprovalRequest1.NF_Assignee_Type__c='Approver';
		currentApprovalRequest1.Apttus_Approval__Approval_Status__c='Submitted';
		currentApprovalRequest1.Apttus_Approval__DelegateApproverIds__c=testUser.Id+','+testUser.Id;
		CurrentRequest.add(currentApprovalRequest1);
	  
		currentApprovalRequest2 = NF_TestDataFactory.createApprovalHistoryRequest('Assigned', 'User', 'Opportunity', currentOpportunity2.Id, true, false, testUser.FirstName+''+testUser.LastName, testUser.Id, ruleAssignee2.Name);
		currentApprovalRequest2.NF_Assignee_Type__c='Approver';
		currentApprovalRequest2.Apttus_Approval__Approval_Status__c='Submitted';
		currentApprovalRequest2.Apttus_Approval__DelegateApproverIds__c=testUser.Id+','+testUser.Id;
		CurrentRequest.add(currentApprovalRequest2);
		
		currentApprovalRequest3 = NF_TestDataFactory.createApprovalHistoryRequest('Assigned', 'User', 'Opportunity', currentOpportunity2.Id, true, false, testUser.FirstName+''+testUser.LastName, testUser2.Id, ruleAssignee2.Name);
		currentApprovalRequest3.NF_Assignee_Type__c='Approver';
		currentApprovalRequest3.Apttus_Approval__Approval_Status__c='Submitted';
		currentApprovalRequest3.Apttus_Approval__DelegateApproverIds__c=testUser2.Id+','+testUser2.Id;
		CurrentRequest.add(currentApprovalRequest3);
	 
	 Database.insert(CurrentRequest);
	}
	
	@isTest static void test_updateRequestRcodeM() {
	NCP_CustomerCommunitySetting__c cs = new NCP_CustomerCommunitySetting__c();
		cs.Name = 'Default';
		cs.Customer_Account__c = 'Customer - test';
		cs.Customer_Account_Number__c = '12345';
		cs.Customer_User_Profile__c = 'Customers';
		insert cs;
		system.runAs(testUser){
		 Test.startTest();
			setup();
	 
			List<Apttus_Approval__Approval_Request_History__c> appRequests = new List<Apttus_Approval__Approval_Request_History__c>{currentApprovalRequest};
			NF_TL_UpdateHistoryRequestRCode.updateHistoryRequestRcodeM(CurrentRequest);
			Test.stopTest();

			Apttus_Approval__Approval_Request_History__c appRequestFetched = [Select NF_Organization_Level__c,NF_Role_Code__c,
				NF_Role_Name__c,NF_Assignee_Type__c from Apttus_Approval__Approval_Request_History__c where Id =:currentApprovalRequest.Id];
	
		}
	}
	
}