src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <label>Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AI</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AN</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AQ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AW</fullName>
                </value>
                <value>
                    <fullName>AX</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BF</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BJ</fullName>
                </value>
                <value>
                    <fullName>BL</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BN</fullName>
                </value>
                <value>
                    <fullName>BO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Compliance__c</fullName>
        <label>Customer Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US_ALTICE</fullName>
                </value>
                <value>
                    <fullName>US_AT&amp;T</fullName>
                </value>
                <value>
                    <fullName>US_Company</fullName>
                </value>
                <value>
                    <fullName>US_Cox</fullName>
                </value>
                <value>
                    <fullName>US_Govern</fullName>
                </value>
                <value>
                    <fullName>US_SCEC</fullName>
                </value>
                <value>
                    <fullName>US_Sprint</fullName>
                </value>
                <value>
                    <fullName>US_T-Mobile</fullName>
                </value>
                <value>
                    <fullName>US_VWireless</fullName>
                </value>
                <value>
                    <fullName>US_VWireline</fullName>
                </value>
                <value>
                    <fullName>unassign</fullName>
                    <default>true</default>
                    <label>Unassign</label>
                </value>
                <value>
                    <fullName>WD_NATO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CH_CountryISOName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Country Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_ProductRelease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CDB id_product_release, which is Enovia code of the product release.</description>
        <label>Product Release</label>
        <referenceTo>CH_ProductRelease__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_ProductVariant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Legacy code + revision, of the variant, is the same as the code in id_product in case of the variant is used as a standalone variant.</description>
        <label>Product Variant</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets (Product Variant)</relationshipLabel>
        <relationshipName>Assets3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CDB id_product_sol, which is Legacy code + revision of the solution, is the same as the code in id_product in case of  the solution is  used as a standalone solution</description>
        <label>Solution</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_Email3__c.field-meta.xml
<CustomField>
    <fullName>CH_Email3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email 3</label>
    <type>Email</type>
</CustomField>

src/objects/Case/fields/CH_ProductRelease__c.field-meta.xml
<CustomField>
    <fullName>CH_ProductRelease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product copied from the Covered Product if one exist on the case, else selected manually by the user</description>
    <label>DELETE Product Release</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Release</relationshipLabel>
    <relationshipName>Support_Ticket3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CH_ProductVariant__c.field-meta.xml
<CustomField>
    <fullName>CH_ProductVariant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product copied from the Covered Product if one exist on the case, else selected manually by the user</description>
    <label>Product Variant</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Product2.PMD_Additional_Classification__c</field>
            <operation>equals</operation>
            <value>Product Variant</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.CH_LegacyCaseStatus__c</field>
            <operation>equals</operation>
            <value>Closed</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Variant</relationshipLabel>
    <relationshipName>Support_Ticket2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CH_Solution__c.field-meta.xml
<CustomField>
    <fullName>CH_Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Solution copied from the Covered Product if one exist on the case, else selected manually by the user</description>
    <label>Solution</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Product2.PMD_Portfolio_Classification__c</field>
            <operation>equals</operation>
            <value>Solution</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.CH_LegacyCaseStatus__c</field>
            <operation>equals</operation>
            <value>Closed</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/CH_ProductRelease__c.object
<CustomObject>
    <description>This custom object holds all the releases for a product, being interfaced from Enovia/EDP.</description>
    <label>Product Release</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CH_ContactType__c</fullName>
        <description>Contact Type Ref: 4989</description>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                    <default>true</default>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
                <value>
                    <fullName>Nokia Employee</fullName>
                </value>
                <value>
                    <fullName>Sub-Contractor</fullName>
                </value>
                <value>
                    <fullName>No Relationship</fullName>
                </value>
                <value>
                    <fullName>Secondary Account</fullName>
                </value>
                <value>
                    <fullName>Communication Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Email3__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Email 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email1__c</fullName>
        <description>Req #1313. Required for Marketo Sync</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Email 2</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContractLineItem.object
<CustomObject>
    <fields>
        <fullName>CH_BusinessHour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CDB will send the Salesforce Business Hours name and we need to do a lookup against the Salesforce Business Hours based on the Business Hours name.</description>
        <label>Business Hour</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_CountryISOName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Country Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>NCP_Nokia_Product_Id__c</fullName>
        <description>Internal Nokia Product Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Nokia Product Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CH_LastCaseAssigned__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Case Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Nokia_ID__c</fullName>
        <description>Added custom field &apos;Nokia ID&apos; of type text(12) added for Req #061
Bandhan (hyper care time) : Marked this field as External ID field so that we can use it to connect with external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Nokia ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CH_Utils.cls
/****************************************
* Class Name : CH_Utils
* Created Date: 24 Mar 2020
* Created By : TCS
* Description : This class is to have all global queries executed from CH_CaseTriggerHandler class
* Test Class: CH_UtilsTest
*****************************************/
public class CH_Utils {
	public static Set<Id> globalAccountIdSet;	
	public static Set<Id> globalContactIdSet;
	public static Set<Id> globalEntitltmentIdSet;
	public static Set<Id> globalProductIdSet;
	public static Set<Id> globalAssetIdSet;
	public static Set<String> globalUserIdSet;
	public static Boolean doQueryAgain = false;
	public static Map<Id, Account> accountMap {
		get {
			if(accountMap == null || (accountMap != null && doQueryAgain)){
				//This query is useful when where clause is based on AccountIds from Case only
				accountMap = new Map<Id, Account>([SELECT Id, Name, CountryCode__c, AccountNumber, Customer_Compliance__c FROM Account WHERE Id IN :globalAccountIdSet]);				
			}
			doQueryAgain = false;
			return accountMap;
		}set;
	}
	public static Map<Id, Contact> contactMap {
		get {
			if(contactMap == null || (contactMap != null && doQueryAgain)){
				//This query is useful when where clause is based on ContactIds from Case only
				contactMap = new Map<Id, Contact>([SELECT Id, CH_ContactType__c, Email, Email1__c, CH_Email3__c FROM Contact WHERE Id IN :globalContactIdSet]);				
			}
			doQueryAgain = false;
			return contactMap;
		}set;
	}
	public static Map<Id, Entitlement> entitlementMap {
		get {
			if(entitlementMap == null || (entitlementMap != null && doQueryAgain)){
				//This query is useful when where clause is based on Entitlement from Case only
				entitlementMap = new Map<Id, Entitlement>([SELECT Id, AssetId, ContractLineItem.ServiceContractId, ServiceContractId, ContractLineItem.CH_BusinessHour__c FROM Entitlement WHERE Id IN :globalEntitltmentIdSet]);				
			}
			doQueryAgain = false;
			return entitlementMap;
		}set;
	}
	public static Map<Id, Product2> productMap {
		get {
			if(productMap == null|| (productMap != null && doQueryAgain)){
				//This query is useful when where clause is based on ProductIds from Case only
				productMap = new Map<Id, Product2>([SELECT Id, ProductCode, NCP_Nokia_Product_Id__c FROM Product2 WHERE Id IN :globalProductIdSet]);				
			}
			doQueryAgain = false;
			return productMap;
		}set;
	}
	public static Map<Id, Asset> assetMap {
		get {
			if(assetMap == null || (assetMap != null && doQueryAgain)){
				//This query is useful when where clause is based on AssetIds from Case only
				assetMap = new Map<Id, Asset>([SELECT Id, Product2Id , CH_ProductRelease__c, CH_ProductVariant__c, CH_Solution__c, CH_CountryISOName__c FROM Asset WHERE Id IN :globalAssetIdSet]);				
			}
			doQueryAgain = false;
			return assetMap;
		}set;
	}
	public static Map<String, User> userMap {
		get {
			if(userMap == null || (userMap != null && doQueryAgain)){
				//This query is useful when where clause is based on User(Owner) Id from Case only
				userMap = new Map<String, User>([SELECT Id, Name, UserRoleId, UserRole.Name, Nokia_ID__c, CH_LastCaseAssigned__c FROM User WHERE Id IN :globalUserIdSet]);				
			}
			doQueryAgain = false;
			return userMap;
		}set;
	}
	/********************
	*Method Name: getAccountMap
	*Parameter: Set of Account Ids 
	*Last updated by: TCS (24th Mar 2020)
	*Description: This is to return Account Map from global query. So that we can use one query.   
	*******************/
	public static Map<Id, Account> getAccountMap(Set<Id> accountIdSet) {
		if(globalAccountIdSet != null){
			for(Id objId: accountIdSet){
				if(!globalAccountIdSet.contains(objId)){
					doQueryAgain = true;
					globalAccountIdSet.add(objId);
				}
			}
		}
		else{
			globalAccountIdSet = accountIdSet;
		}
		return accountMap;
	}
	/********************
	*Method Name: getContactMap
	*Parameter: Set of Contact Ids 
	*Last updated by: TCS (24th Mar 2020)
	*Description: This is to return Contact Map from global query. So that we can use one query.   
	*******************/
	public static Map<Id, Contact> getContactMap(Set<Id> contactIdSet) {
		if(globalContactIdSet != null){
			for(Id objId: contactIdSet){
				if(!globalContactIdSet.contains(objId)){
					doQueryAgain = true;
					globalContactIdSet.add(objId);
				}
			}			
		}
		else{
			globalContactIdSet = contactIdSet;
		}	   
		return contactMap;
	}
	/********************
	*Method Name: getEntitlementMap
	*Parameter: Set of Entitlement Ids 
	*Last updated by: TCS (24th Mar 2020)
	*Description: This is to return Entitlement Map from global query. So that we can use one query.   
	*******************/
	public static Map<Id, Entitlement> getEntitlementMap(Set<Id> entitltmentIdSet) {
		if(globalEntitltmentIdSet != null){
			for(Id objId: entitltmentIdSet){
				if(!globalEntitltmentIdSet.contains(objId)){
					doQueryAgain = true;
					globalEntitltmentIdSet.add(objId);
				}
			}			
		}
		else{
			globalEntitltmentIdSet = entitltmentIdSet;
		}		   
		return entitlementMap;
	}
	/********************
	*Method Name: getProductMap
	*Parameter: Set of Product Ids 
	*Last updated by: TCS (24th Mar 2020)
	*Description: This is to return Product Map from global query. So that we can use one query.   
	*******************/
	public static Map<Id, Product2> getProductMap(Set<Id> productIdSet) {
		if(globalProductIdSet != null){
			for(Id objId: productIdSet){
				if(!globalProductIdSet.contains(objId)){
					doQueryAgain = true;
					globalProductIdSet.add(objId);
				}
			}
		}
		else{
			globalProductIdSet = productIdSet;
		}
		return productMap;
	}
	/********************
	*Method Name: getAssetMap
	*Parameter: Set of Asset Ids 
	*Last updated by: TCS (24th Mar 2020)
	*Description: This is to return Asset Map from global query. So that we can use one query.   
	*******************/
	public static Map<Id, Asset> getAssetMap(Set<Id> assetIdSet) {
		if(globalAssetIdSet != null){
			for(Id objId: assetIdSet){
				if(!globalAssetIdSet.contains(objId)){
					doQueryAgain = true;
					globalAssetIdSet.add(objId);
				}
			}
		}
		else{
			globalAssetIdSet = assetIdSet;
		}
		return assetMap;
	}
	/********************
	*Method Name: getUserMap
	*Parameter: Set of User Ids 
	*Last updated by: TCS (24th Mar 2020)
	*Description: This is to return User Map from global query. So that we can use one query.   
	*******************/
	public static Map<String, User> getUserMap(Set<String> userIdSet) {
		if(globalUserIdSet != null){
			for(Id objId: userIdSet){
				if(!globalUserIdSet.contains(objId)){
					doQueryAgain = true;
					globalUserIdSet.add(objId);
				}
			}
		}
		else{
			globalUserIdSet = userIdSet;
		}
		return userMap;
	}
	
}