src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Compliance__c</fullName>
        <label>Customer Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US_ALTICE</fullName>
                </value>
                <value>
                    <fullName>US_AT&amp;T</fullName>
                </value>
                <value>
                    <fullName>US_Company</fullName>
                </value>
                <value>
                    <fullName>US_Cox</fullName>
                </value>
                <value>
                    <fullName>US_Govern</fullName>
                </value>
                <value>
                    <fullName>US_SCEC</fullName>
                </value>
                <value>
                    <fullName>US_Sprint</fullName>
                </value>
                <value>
                    <fullName>US_T-Mobile</fullName>
                </value>
                <value>
                    <fullName>US_VWireless</fullName>
                </value>
                <value>
                    <fullName>US_VWireline</fullName>
                </value>
                <value>
                    <fullName>unassign</fullName>
                    <default>true</default>
                    <label>Unassign</label>
                </value>
                <value>
                    <fullName>WD_NATO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Logistic_Account_Type__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill-To</fullName>
                </value>
                <value>
                    <fullName>Ship-To</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Market North America</fullName>
                </value>
                <value>
                    <fullName>Market Latin America</fullName>
                </value>
                <value>
                    <fullName>Market Middle East and Africa</fullName>
                </value>
                <value>
                    <fullName>Market India</fullName>
                </value>
                <value>
                    <fullName>Market Greater China</fullName>
                </value>
                <value>
                    <fullName>Market Europe</fullName>
                </value>
                <value>
                    <fullName>Market Asia Pacific &amp; Japan</fullName>
                </value>
                <value>
                    <fullName>Market Other</fullName>
                </value>
                <value>
                    <fullName>Market NFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ngERP__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ngERP ID</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Legal_Entity</fullName>
        <active>true</active>
        <description>Legal Entity is for Nokia Internal Accounts</description>
        <label>Legal Entity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>HWS_Price__c</fullName>
        <description>HWST-1168 - Sprint-1908</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Price</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_SourceSystem__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HWS_Covered_Part</fullName>
        <active>true</active>
        <description>This will be used for SRM project. Created as part of US.SRM.1290</description>
        <label>Covered Part</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/Describe__c.field-meta.xml
<CustomField>
    <fullName>Describe__c</fullName>
    <description>If YES, please describe</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If YES, please describe</inlineHelpText>
    <label>If Yes, Please Describe</label>
    <type>TextArea</type>
</CustomField>

src/objects/Case/fields/HWS_Address_Name__c.field-meta.xml
<CustomField>
    <fullName>HWS_Address_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_AWBNumber__c.field-meta.xml
<CustomField>
    <fullName>HWS_AWBNumber__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Bar_Code__c.field-meta.xml
<CustomField>
    <fullName>HWS_Bar_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RMA Bar Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Case/fields/HWS_Bar_Code_Ref1__c.field-meta.xml
<CustomField>
    <fullName>HWS_Bar_Code_Ref1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Case Number Bar Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Case/fields/HWS_Faulty_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_Faulty_Serial_Number__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Serial Number of the faulty Unit</inlineHelpText>
    <label>Faulty Unit Serial Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_FaultyUnitMaterialCode__c.field-meta.xml
<CustomField>
    <fullName>HWS_FaultyUnitMaterialCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Faulty Unit Material Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_LSP_Courier_Name__c.field-meta.xml
<CustomField>
    <fullName>HWS_LSP_Courier_Name__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LSP (Courier Name)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Sellable_Product__c.field-meta.xml
<CustomField>
    <fullName>HWS_Sellable_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created with the reference to the US.</description>
    <inlineHelpText>Sellable Item Description</inlineHelpText>
    <label>Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sellable Product</relationshipLabel>
    <relationshipName>Sellable_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_ServiceType__c.field-meta.xml
<CustomField>
    <fullName>HWS_ServiceType__c</fullName>
    <description>Used to store the service type of the Support ticket.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Hws_Ship_to_Party_Address__c.field-meta.xml
<CustomField>
    <fullName>Hws_Ship_to_Party_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US.SRM.1363</description>
    <inlineHelpText>Select address for delivery of replacement Unit</inlineHelpText>
    <label>Ship to Party Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Logistic_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Support Tickets</relationshipLabel>
    <relationshipName>Hws_Ship_to_Part_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_Shippeddate__c.field-meta.xml
<CustomField>
    <fullName>HWS_Shippeddate__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Shipped Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/HWS_ShipTopartyId__c.field-meta.xml
<CustomField>
    <fullName>HWS_ShipTopartyId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ship To Party Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_TotalShippedQuantity__c.field-meta.xml
<CustomField>
    <fullName>HWS_TotalShippedQuantity__c</fullName>
    <description>Created to store total shipped quantity received.</description>
    <label>Total Shipped Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Case/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Issue_Reported_By__r.Market__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Agrihan Island</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alagoas</fullName>
            </value>
            <value>
                <fullName>Alamagan Island</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>Altai Krai</fullName>
            </value>
            <value>
                <fullName>Amapa</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Amurskaya Oblast</fullName>
            </value>
            <value>
                <fullName>Anatahan Island</fullName>
            </value>
            <value>
                <fullName>Andaman &amp; Nikobar</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Arkhangelsk Oblast</fullName>
            </value>
            <value>
                <fullName>Arno Island</fullName>
            </value>
            <value>
                <fullName>Asian RSFSR</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Asuncion Island</fullName>
            </value>
            <value>
                <fullName>Ata Island</fullName>
            </value>
            <value>
                <fullName>Australian Capital</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Norte</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Bali</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>CH_CDB_EntitlementId__c</fullName>
        <description>Change for the integration / migration to correctly link CDB Entitlement with the CDB Service offering ( entitlement_id) against the right Salesforce Entitlement Id.
This field is also used for linking the ContractLineItem-record belonging to the 1-on-1 relationship to the Entitlement-record.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CDB Entitlement ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_ServiceMappingId__c</fullName>
        <description>Name of Entitlement Process in SF which will enable mapping.</description>
        <label>Service Mapping Id</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_ServiceMappingType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HWS_CaseTriggerHelper_TEST.cls
/****************************************
* Class Name : HWS_CaseTriggerHelper_Test
* Created By : TCS
* Last Modified by: TCS
* Description : Test Class for Hws_CaseTriggerHelper and HWS_CasetriggerHandler
*****************************************/
@isTest
public class HWS_CaseTriggerHelper_TEST {
	private static Set<String> childCaseStatuses = new Set<String>{'Closed','Cancelled'};
		private static Id parentCaseId;
		@testSetup static void testDataSetup(){
			Id accountRecordType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LOGISTIC_ACCOUNT_EXISTING);
			Id childcase = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Child_Case_Read_Only);
			Id exchangeInDays = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Advance_Exchange_In_Days);
			Id exchangeInHours = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_ADVANCE_EXCHANGE_IN_HOURS);
			Id parentCaseRecordType = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Parent_Case);
			Id sparePartSales = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_SPS_PART_SALES);
			Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
			List<Case>listCase= new List<Case>();
			Account acc = HWS_DataFactory_TEST.insertAccount();
			acc.name='test1';
			acc.Customer_Compliance__c ='US_Govern';
			insert acc;
			
			Account acc2 = HWS_DataFactory_TEST.insertAccount(); 
			acc2.RecordTypeId =  legalEntityAccountType;
			acc2.ParentId = Acc.Id;
			insert acc2;
			
			Account acc1 = new Account();
			acc1.Name = 'Testing RMANUMBER FIELD';
			acc1.ParentId = Acc.Id;
			acc1.Logistic_Account_Type__c = 'Bill-To';
			acc1.ngERP__c = '1';
			acc1.BillingCountry = 'India';
			acc1.BillingStreet = 'Gachibowli, Gachibowli';
			acc1.BillingCity = 'Hyderabad';
			acc1.BillingPostalCode = '500071';
			acc1.BillingState = 'TELANGANA';
			acc1.Market__c = 'Market India';
			acc1.RecordTypeId = accountRecordType;
			//ACC1.RecordTypeId =  LegalEntityAccountType;
			insert acc1;
			Product2 prod = HWS_DataFactory_TEST.insertproduct2();
			prod.ProductCode = '1234';
			insert prod;
			hws_versionitem__c vItem = HWS_DataFactory_TEST.insertHwsversionitem();
			insert vItem;
			ServiceContract sc = HWS_DataFactory_TEST.insertServiceContract(Acc);
			insert sc;
			Asset ast = new Asset();
			Id assetRecordType = HWS_Utilty.getRecordTypeByName('Asset','HWS_Covered_Part');
			ast.RecordTypeId = assetRecordType;
			ast.Name = 'Test Asset';
			ast.AccountId = acc2.id;
	  ast.Product2Id = prod.Id;	
			ast.HWS_SourceSystem__c  = 'Puma1';
	  ast.HWS_Price__c = '20';
			insert ast;   
			/*Entitlement ent = new Entitlement();
			ent.Name = 'HWS Advance Exchange in Hours';
			ent.AccountId = ACC1.id;
			ent.AssetId = ast.Id;
			ent.CH_CDB_EntitlementId__c = '1234';
			ent.CH_ServiceMappingId__c = 'Advanced Exchange in Hours (AE-H)';
			insert ent;*/
			Case ca = new Case();
			ca.RecordTypeId = parentCaseRecordType;
			ca.AccountId = acc2.Id;
			ca.Hws_Ship_to_Party_Address__c= acc1.Id;
	  ca.AssetId=ast.Id;
			ca.Status='Closed';
			ca.Subject='Test Subject';
			ca.Description='test Description';
			//ca.HWS_Faulty_Serial_Number__c= 'test1234';
			ca.HWS_ShipTopartyId__c='1234566';
			ca.Describe__c = 'Test description3';
			insert ca;
			//parentCaseId = ca.Id;
			Case cas = new Case();
			cas.RecordTypeId = childcase;
			cas.ParentId = ca.Id;
			cas.AccountId = acc2.Id;
	  cas.AssetId=ast.Id;
			//cas.Status ='Cancelled';
			cas.Hws_Ship_to_Party_Address__c= acc1.Id;
			cas.HWS_Sellable_Product__c = prod.Id;
			cas.HWS_Faulty_Serial_Number__c = '1234'; 
			cas.HWS_FaultyUnitMaterialCode__c = '4567';
			cas.HWS_Shippeddate__c= system.today();
			//cas.HWS_AWBNumber__c = '122';
			cas.HWS_LSP_Courier_Name__c = 'Test123';
			cas.HWS_TotalShippedQuantity__c = 1234;
			cas.Describe__c = 'Test description';
			cas.HWS_Bar_Code__c = 'Test data111';
		  cas.HWS_Bar_Code_Ref1__c = 'Test data123';
			insert cas;
			
			Case cas1 = new Case();
			cas1.RecordTypeId = sparePartSales;
			cas1.ParentId = ca.Id;
			cas1.AccountId = acc2.Id;
			//cas.Status ='Cancelled';
			cas1.Hws_Ship_to_Party_Address__c= acc1.Id;
			cas1.HWS_Sellable_Product__c = prod.Id;
	  cas1.AssetId=ast.Id;
			cas1.HWS_Faulty_Serial_Number__c = '123434233'; 
			cas1.HWS_FaultyUnitMaterialCode__c = '456755667';
			cas1.HWS_ServiceType__c ='Spare Part Sales';
			cas1.HWS_TotalShippedQuantity__c = 12344455;
			cas1.HWS_Shippeddate__c= system.today();
			//cas1.HWS_AWBNumber__c = '12277';
			cas1.HWS_LSP_Courier_Name__c = 'Test1232334';
			cas1.Describe__c = 'Test description';
			cas1.HWS_Address_Name__c='test';
		  cas1.City__c = 'hyderabad';
		  cas1.State__c = 'Telangana';
		  cas1.Country__c = 'India';
		  cas1.POSTAL_CODE_CHQ__c = '500090';
			cas1.HWS_Bar_Code__c = 'Test data2222';
		  cas1.HWS_Bar_Code_Ref1__c = 'Test data123';
	  cas1.HWS_Quantity__c = 5;
			insert cas1;
			HWS_BypassStatusChangeValidation__c cussett = new HWS_BypassStatusChangeValidation__c();
			cussett.HWS_BypassCaseStatusValidation__c = true;
			insert cussett;
		}
	public static testmethod void parentCaseStatus(){		 
		List<Case> listCase= new List<Case>();
		List<Case> listChildCase= new List<Case>();
		Set<Id> caseIdSet = new Set<Id>();
		Id caseRectype = Schema.SObjectType.Case.getRecordTypeInfosByName().get('HWS Advance Exchange In Hours').getRecordTypeId();
		Account acc = [Select id from Account where name='test' limit 1];								
		Case caserec = [Select id,Status,HWS_SOO_CaseStatus__c from Case limit 1];  
		Product2 prod = [select id from Product2 where name='test'];
		Asset ast = [Select id from Asset limit 1];
		 //case cas1 = [select id,Status,HWS_SOO_CaseStatus__c,RecordTypeId,HWS_Faulty_Serial_Number__c,HWS_FaultyUnitMaterialCode__c from case where HWS_LSP_Courier_Name__c = 'Test123'];
		listCase.add(caserec);
		Case childCaseRec = HWS_DataFactory_TEST.insertChildCase();
		childCaseRec.ParentId = caserec.id; 
		childCaseRec.AccountId = acc.id;
	childCaseRec.AssetId = ast.Id;
		childCaseRec.HWS_Sellable_Product__c=prod.id;
		childCaseRec.Status ='Cancelled';		
		childCaseRec.AccountId = acc.Id;		
		childCaseRec.HWS_Faulty_Serial_Number__c= '12345'; 
		listChildCase.add(childCaseRec);
		test.startTest();
		insert listChildCase; 
		caseIdSet.add(childCaseRec.Id);
		for(Case cs:listCase){
			if(cs.cases.size() == 0){
				cs.Status ='Closed';
				system.assertEquals(cs.Status, 'Closed');
			}else{
				cs.Status ='Open';
				system.assertEquals(cs.Status, 'Open');
			}			
		}  
		HWS_CaseTriggerHelper.changeParentCaseStatus(caseIdSet);
		test.stopTest();				  
	}   
	public static testmethod void caseValidationmethod(){
		List<Case>listCase= new List<Case>();		
		hws_versionitem__c vItem = HWS_DataFactory_TEST.insertHwsversionitem();
		insert vItem;
		Case caseRec = HWS_DataFactory_TEST.insertChildCase();
		caseRec.HWS_Stockable_Product__c= vItem.id;
		caseRec.HWS_Faulty_Serial_Number__c= '';
		listCase.add(caserec);
		test.startTest();
		try{
			insert listCase;
			update listCase;
		}		
		Catch(Exception e){
			Boolean expectedExceptionThrown =  e.getMessage().contains('Please Enter Faulty Unit Serial Number');			
		}		
		test.stopTest();
	}
	public static testmethod void duplicateSernumMethod(){		
		List<Case>listCase = new List<Case>();		
		Case parentCase = [Select id from Case limit 1];
		Product2 prod = [select id from Product2 where name='test'];
	Asset ast = [Select id from Asset limit 1];
		Account acc2 = [Select id from account where name='test' LIMIT 1];
		Account acc1 = [Select id from account where name='Testing RMANUMBER FIELD' LIMIT 1];
		Case caseRec = HWS_DataFactory_TEST.insertChildCase();
		caseRec.Status ='Ordered';
		caseRec.AccountId = acc2.Id;
		caseRec.Hws_Ship_to_Party_Address__c= acc1.Id;
	caseRec.AssetId = ast.Id;
		caseRec.HWS_Faulty_Serial_Number__c = '123456';
		caseRec.ParentId = parentCase.Id;
		caseRec.HWS_Sellable_Product__c = prod.Id;
		listCase.add(caseRec);
		insert listCase;
		system.assertequals(listCase.size(),1);  
		listCase[0].HWS_Faulty_Serial_Number__c = '123456'; 
		test.startTest();
		try{
			update listCase ;
		}		
		Catch(Exception e){
			Boolean expectedExceptionThrown =  e.getMessage().contains('Duplicate faulty unit Serial number');
			//System.AssertEquals(expectedExceptionThrown, true);
		}
		test.stopTest();
	}
	
	public static testmethod void sendCaPMToAccOwnerTest(){		
		Id scRectype = Schema.SObjectType.ServiceContract.getRecordTypeInfosByName().get('Parent Service Contract').getRecordTypeId();		
		Id caseChildRectype = Schema.SObjectType.Case.getRecordTypeInfosByName().get('HWS Advance Exchange In Hours').getRecordTypeId();
		Account acc = [Select id from Account limit 1];		
		ServiceContract sc= [Select id from ServiceContract limit 1];
		sc.RecordTypeId=scRectype ;
		update sc;
		Case cs = [Select id from Case limit 1];		
		Case child = new case();
		child.status = 'On Hold';
		child.RecordTypeId=caseChildRectype; 
		child.ParentId = cs.Id;
		child.AccountId = acc.id;
		child.HWS_Failure_Description__c='1';
		child.HWS_Failure_Occurance__c = '1';
		//cs.HWS_Failure_Detection__c = '1';
		child.subject='test';
		child.description = 'test';
		child.NCP_Service_Contract__c = sc.id;
		child.HWS_Capm_Email__c = '';
		child.HWS_Bar_Code__c = 'Test data3333';
		child.HWS_Bar_Code_Ref1__c = 'Test data123';
		test.startTest();
		try{
		insert child;
		System.assertequals(child.HWS_Capm_Email__c,'');	 
		}
		catch(Exception e){
			String testException = e.getMessage();
		}  
		test.stopTest();
	}
	
	public static testmethod void rmaNumberPopulateTest(){
		Id parentCaseRecordType = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Parent_Case);		
		Id exchangeInHours = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_ADVANCE_EXCHANGE_IN_HOURS);
		Id exchangeInDays = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Advance_Exchange_In_Days);
		Id sparePartSales = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_SPS_PART_SALES);
		Case parentCase = [Select id,CaseNumber from Case where RecordTypeId = :parentCaseRecordType limit 1];
		Account acc2 = [Select id from account where name='test' LIMIT 1];
		Account acc1 = [Select id from account where name='Testing RMANUMBER FIELD' LIMIT 1];
		Product2 prod = [select id from Product2 where name='test'];
	Asset ast = [Select id from Asset limit 1];
		List<Case>listCase= new List<Case>();		
		for(integer i=0; i<5; i++){ 
			case childcase = new Case();
			childcase.RecordTypeId = exchangeInHours;
			if((childcase.RecordTypeId == exchangeInHours) || (childcase.RecordTypeId == exchangeInDays)){
				childcase.ParentId = parentCase.Id;
				childcase.AccountId = acc2.Id;
				childcase.Hws_Ship_to_Party_Address__c= acc1.Id;
				childcase.HWS_Sellable_Product__c = prod.Id;
		childcase.AssetId = ast.Id;
				childcase.HWS_Failure_Description__c = 'Fan defect';
				childcase.HWS_Failure_Detection__c = 'Start reset loop';
				childcase.HWS_Failure_Occurance__c = 'Permanent';
				childcase.HWS_Address_Name__c = 'Test Address';
				childcase.HWS_Bar_Code__c = 'Test data444';
			childcase.HWS_Bar_Code_Ref1__c = 'Test data123';
				childcase.HWS_RMA_Number__c = parentCase.CaseNumber+'-00'+(i+1);
				listCase.add(childcase);
			}
			else if(childcase.RecordTypeId == sparePartSales){
				childcase.ParentId = parentCase.Id;
				childcase.HWS_Sellable_Product__c = prod.Id;
		childcase.AssetId = ast.Id;
				childcase.Hws_Ship_to_Party_Address__c= acc1.Id;
				childcase.AccountId = acc2.Id;
				childcase.HWS_Quantity__c = Decimal.valueOf('1');
				childcase.HWS_Bar_Code__c = 'Test data555';
			childcase.HWS_Bar_Code_Ref1__c = 'Test data123';
				childcase.HWS_RMA_Number__c = parentCase.CaseNumber+'-00'+(i+1);
				//childcase.HWS_Requested_Delivery_Date_Time__c = date.valueOf('2019-03-15T12:00:00.000+0000');
				listCase.add(childcase);
			}
		}  
		test.startTest();
		insert listCase;
		System.assertequals(listCase[0].HWS_RMA_Number__c,parentCase.CaseNumber+'-001');
		test.stopTest();
	}  
	
	public static testmethod void handleCaseFieldChangesTest(){
		Id childcase = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Child_Case_Read_Only);
		List<Case> caseList = new List<Case>();		
		list<CH_Track_Field_Change__c> trackedFields = new list<CH_Track_Field_Change__c>();
		Case parentCase = [Select id from Case limit 1]; 
		Product2 prod = [select id from Product2 where name='test'];
		Account acc2 = [Select id from account where name='test' LIMIT 1];
		Account acc1 = [Select id from account where name='Testing RMANUMBER FIELD' LIMIT 1];
		map<id,case> casoldmap = new map<id,case>();
		map<id,case> casnewmap = new map<id,case>();
					  
		case cas1 = [select id,RecordTypeId,HWS_Faulty_Serial_Number__c,HWS_FaultyUnitMaterialCode__c, HWS_Bar_Code__c, HWS_Bar_Code_Ref1__c from case where HWS_LSP_Courier_Name__c = 'Test123'];
		cas1.HWS_Faulty_Serial_Number__c = '9877889';
		cas1.HWS_FaultyUnitMaterialCode__c = '1548121';
		cas1.HWS_TotalShippedQuantity__c = 45678;
		cas1.Describe__c = 'Test data123';
		cas1.HWS_Bar_Code__c = 'Test data6666';
		cas1.HWS_Bar_Code_Ref1__c = 'Test data123';
		test.startTest();
		update cas1;
		test.stopTest();		
	}
	
	/*public static testmethod void handleCaseFieldChangesTest2(){
		Id ParentCaseRecordType = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Parent_Case);
		Id childcase = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Child_Case_Read_Only);
		Account acc2 = [Select id from account where name='test' LIMIT 1];
		Account acc1 = [Select id from account where name='Testing RMANUMBER FIELD' LIMIT 1];
		Product2 prod = [select id from Product2 where name='test'];
		case cas1 = [select id,RecordTypeId,HWS_Faulty_Serial_Number__c,HWS_FaultyUnitMaterialCode__c from case where HWS_LSP_Courier_Name__c = 'Test123'];
		  cas1.AccountId = acc2.Id;
			cas1.Hws_Ship_to_Party_Address__c= acc1.Id;
		  cas1.HWS_Sellable_Product__c = prod.Id;
			cas1.Describe__c = 'Test description123';
			cas1.HWS_Faulty_Serial_Number__c = '9877889';
			cas1.HWS_FaultyUnitMaterialCode__c = '1548121';
		  cas1.HWS_Shippeddate__c= system.today()+1;
			//cas1.HWS_AWBNumber__c = '144';
			cas1.HWS_LSP_Courier_Name__c = 'Test1567';
			update cas1;
  } */
	public static testmethod void handleCaseFieldChangesTest3(){
		Id childcase = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Child_Case_Read_Only);
		List<Case> caseList = new List<Case>();		
		list<CH_Track_Field_Change__c> trackedFields = new list<CH_Track_Field_Change__c>();
		Case parentCase = [Select id from Case limit 1]; 
		Product2 prod = [select id from Product2 where name='test'];
		Account acc2 = [Select id from account where name='test' LIMIT 1];
		Account acc1 = [Select id from account where name='Testing RMANUMBER FIELD' LIMIT 1];
		map<id,case> casoldmap = new map<id,case>();
		map<id,case> casnewmap = new map<id,case>();
					  
		case cas1 = [select id,RecordTypeId,HWS_Faulty_Serial_Number__c,HWS_FaultyUnitMaterialCode__c from case where HWS_LSP_Courier_Name__c = 'Test1232334'];
		cas1.HWS_Faulty_Serial_Number__c = '9877889567';
		cas1.HWS_FaultyUnitMaterialCode__c = '15481213455';
		cas1.Describe__c = 'Test data123';
		cas1.HWS_TotalShippedQuantity__c=12345789;
		test.startTest();
		update cas1;
		test.stopTest();		
	}
	
	public static testmethod void validationsOnCaseForDate(){
		Case parentCase = [Select id from Case limit 1];
		Id sparePartSales = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_SPS_PART_SALES);
		List<Case>childCaseList = new List<Case>();
		Product2 prod = [select id from Product2 where name='test'];
		Account acc2 = [Select id from account where name='test' LIMIT 1];
		Account acc1 = [Select id from account where name='Testing RMANUMBER FIELD' LIMIT 1];
		Asset ast = [Select id from Asset limit 1];
	case childCase = new Case();
		childCase.RecordTypeId = sparePartSales;
		childCase.ParentId = parentCase.Id;
		childCase.AccountId = acc2.Id;
	childcase.AssetId = ast.Id;
		childCase.Hws_Ship_to_Party_Address__c= acc1.Id;
		childCase.HWS_Sellable_Product__c = prod.Id;
		childCase.HWS_Quantity__c = Decimal.valueOf('1');
		childCase.HWS_Planned_Delivery_Date__c = date.valueOf('2019-03-11T14:30:00.000+0000');
		childCase.HWS_Requested_Delivery_Date_Time__c = date.valueOf('2019-03-15T12:00:00.000+0000');
		childCase.HWS_Bar_Code__c = 'Test data777';
		childCase.HWS_Bar_Code_Ref1__c = 'Test data123';
		test.startTest();
		insert childCase;
		//  System.AssertEquals(expectedExceptionThrown, true);
		childCase.HWS_Requested_Delivery_Date_Time__c = date.valueOf('2019-03-17T12:00:00.000+0000');
		//childCaseList.add(childCase);
		update childCase;
		test.stopTest();
	}	
	public static testmethod void updateRetunDeliveryOnParentTest(){
		Case parentCase = [Select id from Case where HWS_ShipTopartyId__c='1234566' limit 1];
		Id exchangeInDays = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Advance_Exchange_In_Days);
		List<Case>childCaseList = new List<Case>(); 
		Product2 prod = [select id from Product2 where name='test'];
	Asset ast = [Select id from Asset limit 1];
		Account acc2 = [Select id from account where name='test' LIMIT 1];
		Account acc1 = [Select id from account where name='Testing RMANUMBER FIELD' LIMIT 1];
		list<case> childcasl = new List<case>();
		case childCase = new Case();
		childCase.RecordTypeId = exchangeInDays;
		childCase.ParentId = parentCase.Id;
		childCase.AccountId = acc2.Id;
	childCase.AssetId = ast.Id;
		childCase.HWS_Address_Name__c='test';
		childCase.City__c = 'hyderabad';
		childCase.State__c = 'Telangana';
		childCase.Country__c = 'India';
		childCase.POSTAL_CODE_CHQ__c = '500090';
		childCase.Hws_Ship_to_Party_Address__c= acc1.Id;
		childCase.HWS_Sellable_Product__c = prod.Id;		
		childCase.HWS_Bar_Code__c = 'Test data8888';
		childCase.HWS_Bar_Code_Ref1__c = 'Test data123';
		test.startTest();
		insert childCase;
		childcasl.add(childCase);
		//parentCase.HWS_ReturnAddressReceivedFromSOO__c = True;
		//update parentCase;
		HWS_CaseTriggerHelper.updateRetunDeliveryOnParent(childcasl);
		test.stopTest();
	}   
	public static testmethod void completeMilestoneTest(){
		Case parentCase = [Select id from Case limit 1];
		Id exchangeInDays = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Advance_Exchange_In_Days);
		List<Case>childCaseList = new List<Case>(); 
		Product2 prod = [select id from Product2 where name='test'];
	Asset ast = [Select id from Asset limit 1];
		Account acc2 = [Select id from account where name='test' LIMIT 1];
		Account acc1 = [Select id from account where name='Testing RMANUMBER FIELD' LIMIT 1];
		list<case> childCaseli = new list<case>();
		case childCase = new Case();
		DateTime createdOn = System.Now().addHours(-4);
		childCase.RecordTypeId = exchangeInDays;
		childCase.SlaStartDate = createdOn;
		childCase.ParentId = parentCase.Id;
		childCase.AccountId = acc2.Id;
	childcase.AssetId = ast.Id;
		childCase.HWS_ServiceType__c = 'Advanced Exchange in Days';
		childCase.Hws_Ship_to_Party_Address__c= acc1.Id;
		childCase.HWS_Sellable_Product__c = prod.Id;
		childCase.City__c = 'Hyderabad';
		childCase.HWS_Shippeddate__c = System.Now();
		childCase.HWS_Bar_Code__c = 'Test data9999';
		childCase.HWS_Bar_Code_Ref1__c = 'Test data123';
		childCaseli.add(childCase);
		test.startTest();
		insert childCaseli;
		parentCase.HWS_ReturnAddressReceivedFromSOO__c = True;
		HWS_CaseTriggerHelper.completeMilestone(childCaseli);
		update parentCase;
		test.stopTest();
	}
}