src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Compliance__c</fullName>
        <label>Customer Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US_ALTICE</fullName>
                </value>
                <value>
                    <fullName>US_AT&amp;T</fullName>
                </value>
                <value>
                    <fullName>US_Company</fullName>
                </value>
                <value>
                    <fullName>US_Cox</fullName>
                </value>
                <value>
                    <fullName>US_Govern</fullName>
                </value>
                <value>
                    <fullName>US_SCEC</fullName>
                </value>
                <value>
                    <fullName>US_Sprint</fullName>
                </value>
                <value>
                    <fullName>US_T-Mobile</fullName>
                </value>
                <value>
                    <fullName>US_VWireless</fullName>
                </value>
                <value>
                    <fullName>US_VWireline</fullName>
                </value>
                <value>
                    <fullName>unassign</fullName>
                    <default>true</default>
                    <label>Unassign</label>
                </value>
                <value>
                    <fullName>WD_NATO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Send_Check__c</fullName>
        <description>Created as per the requirement in the US (HWST-1340)</description>
        <label>Email Preferences</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Order Confirmation</fullName>
                </value>
                <value>
                    <fullName>Shipment confirmation</fullName>
                </value>
                <value>
                    <fullName>ETA update</fullName>
                </value>
                <value>
                    <fullName>Reminder to send faulty part</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Legal_Entity</fullName>
        <active>true</active>
        <description>Legal Entity is for Nokia Internal Accounts</description>
        <label>Legal Entity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>HWS_SourceSystem__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HWS_Covered_Part</fullName>
        <active>true</active>
        <description>This will be used for SRM project. Created as part of US.SRM.1290</description>
        <label>Covered Part</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_ServiceType__c.field-meta.xml
<CustomField>
    <fullName>CH_ServiceType__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
                <default>true</default>
                <label>Customer Support</label>
            </value>
            <value>
                <fullName>Internal Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/HWS_Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>HWS_Contract_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field is used to store the related Contract line item. It will not be shown on the UI</description>
    <label>Contract Line Item</label>
    <referenceTo>ContractLineItem</referenceTo>
    <relationshipLabel>Support Ticket</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_Faulty_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_Faulty_Serial_Number__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Serial Number of the faulty Unit</inlineHelpText>
    <label>Faulty Unit Serial Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Sellable_Product__c.field-meta.xml
<CustomField>
    <fullName>HWS_Sellable_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created with the reference to the US.</description>
    <inlineHelpText>Sellable Item Description</inlineHelpText>
    <label>Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sellable Product</relationshipLabel>
    <relationshipName>Sellable_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CH_ContactType__c</fullName>
        <description>Contact Type Ref: 4989</description>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                    <default>true</default>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
                <value>
                    <fullName>Nokia Employee</fullName>
                </value>
                <value>
                    <fullName>Sub-Contractor</fullName>
                </value>
                <value>
                    <fullName>No Relationship</fullName>
                </value>
                <value>
                    <fullName>Secondary Account</fullName>
                </value>
                <value>
                    <fullName>Communication Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>Set the contact Active or Inactive</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContractLineItem.object
<CustomObject>
    <fields>
        <fullName>CH_CDB_EntitlementId__c</fullName>
        <description>New custom field. Used along with CH_CDB_Contract_ID as a reference for checking service contracts in CDB</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CDB Entitlement Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_ServiceMappingId__c</fullName>
        <description>Name of Entitlement Process in SF which will enable mapping.</description>
        <label>Service Mapping Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_ServiceMappingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_ServiceType__c</fullName>
        <description>Service Type</description>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Internal Support</fullName>
                </value>
                <value>
                    <fullName>Advanced Exchange in Days</fullName>
                </value>
                <value>
                    <fullName>Advanced Exchange in Hours</fullName>
                </value>
                <value>
                    <fullName>Return for Repair or Replacement</fullName>
                </value>
                <value>
                    <fullName>Spare Part Sales</fullName>
                </value>
                <value>
                    <fullName>MVR Identical Repair</fullName>
                </value>
                <value>
                    <fullName>Return for Exchange</fullName>
                </value>
                <value>
                    <fullName>Identical Repair</fullName>
                </value>
                <value>
                    <fullName>Eco Repair</fullName>
                </value>
                <value>
                    <fullName>Return for Modification</fullName>
                </value>
                <value>
                    <fullName>Dead On Arrival, Advanced Exchange in Days</fullName>
                </value>
                <value>
                    <fullName>Dead on Arrival, Return for Repair or Replacement</fullName>
                </value>
                <value>
                    <fullName>Return for Upgrade</fullName>
                </value>
                <value>
                    <fullName>Return for Certification</fullName>
                </value>
                <value>
                    <fullName>MVR Return for Repair or Replacement</fullName>
                </value>
                <value>
                    <fullName>Commissioning Spares</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>CH_CDB_EntitlementId__c</fullName>
        <description>Change for the integration / migration to correctly link CDB Entitlement with the CDB Service offering ( entitlement_id) against the right Salesforce Entitlement Id.
This field is also used for linking the ContractLineItem-record belonging to the 1-on-1 relationship to the Entitlement-record.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CDB Entitlement ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_ServiceMappingId__c</fullName>
        <description>Name of Entitlement Process in SF which will enable mapping.</description>
        <label>Service Mapping Id</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_ServiceMappingType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/HWS_VersionItem__c.object
<CustomObject>
    <fields>
        <fullName>HWS_Serial_Number_Traceable__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Serial Number Traceable</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Version Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Version Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HWS_CancelServiceRequesttoSOO_SVC_TEST.cls
/*****************************************************************
Description: It is related to the HWS_CancelcaseSendSRtoSOO_SVC class

DATE			AUTHOR		  CHANGE
12/04/2019	  Vinod T		 Created
*****************************************************************/
@isTest
Public class HWS_CancelServiceRequesttoSOO_SVC_TEST{
	@testSetup static void testDataSetup(){
		Id logisticAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LOGISTIC_ACCOUNT_EXISTING);
		Id exchangeInDays = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Advance_Exchange_In_Days);
		Id exchangeInHours = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_ADVANCE_EXCHANGE_IN_HOURS);
		Id parentCaseRecordType = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_Parent_Case);
		Id spSales = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_SPS_PART_SALES);
		Id customerAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.CUSTOMER);
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		List<Case>listCase= new List<Case>();
		Account acc = HWS_DataFactory_TEST.insertAccount(); 
		acc.RecordTypeId =  customerAccountType; 
		acc.Customer_Compliance__c = 'US_AT&T';
		//acc.Email_Send_Check__c='Reminder to send faulty part';	 
		insert acc;
		System.assertEquals(acc.Customer_Compliance__c, 'US_AT&T');
		
		Account acc1 = HWS_DataFactory_TEST.insertAccount(); 
		acc1.RecordTypeId =  legalEntityAccountType;
		acc1.ParentId = acc.Id;
		//acc1.Customer_Compliance__c = 'US_AT&T';
		// acc.Email_Send_Check__c='ETA update'; 
		insert acc1;
		
		Contact con = HWS_DataFactory_TEST.insertContact();
		con.AccountId = acc.Id;
		con.Contact_Status__c = 'Active';
		con.CH_ContactType__c = 'Customer';
		con.email='xyz@example.com';
		insert con;
		
		Product2 prod = HWS_DataFactory_TEST.insertproduct2();
		prod.ProductCode = '1234';
		insert prod;
		
		Id pricebookId = Test.getStandardPricebookId();
		PriceBookEntry pbe = new PriceBookEntry();
		pbe.IsActive=true;
		pbe.Product2Id=prod.id;
		pbe.PriceBook2Id = pricebookId;
		pbe.UnitPrice = 100;	  
		insert pbe;
		
		PriceBook2 pb = HWS_DataFactory_TEST.createPriceBook();			 
		insert pb;   
		
		PricebookEntry pbety = new PricebookEntry();
		pbety.CurrencyIsoCode='EUR';
		pbety.IsActive=true;
		pbety.Product2Id=prod.id;
		pbety.PriceBook2Id = pb.Id;
		pbety.UnitPrice = 100;
		insert pbety;  
		
		ServiceContract sc = HWS_DataFactory_TEST.insertServiceContract(acc1);		
		sc.Pricebook2Id = pb.Id;
		insert sc;
		
		ContractLineItem cli=new ContractLineItem();
		cli.UnitPrice=1.00;
		cli.Quantity=1.00;
		cli.ServiceContractId= sc.id;
		cli.PricebookEntryId = pbety.id;
		cli.StartDate = date.valueOf('2019-04-09T12:00:00.000+0000');
		cli.EndDate = date.valueOf('2020-04-09T12:00:00.000+0000');
		cli.CH_ServiceType__c = 'Spare Part Sales';
		insert cli;
		
		Asset ast = new Asset();
		Id assetRecordType = HWS_Utilty.getRecordTypeByName('Asset','HWS_Covered_Part');
		ast.RecordTypeId = assetRecordType;
		ast.Name = 'Test Asset';
		ast.AccountId = acc1.id; 
		ast.Product2Id = prod.Id;
		ast.HWS_SourceSystem__c = 'Puma1';
		insert ast;   
		
		hws_versionitem__c hwsv = HWS_DataFactory_TEST.insertHwsversionitem();
		hwsv.HWS_Serial_Number_Traceable__c='';		
		insert hwsv;
		
		Entitlement ent = new Entitlement();
		ent.Name = 'Return for Repair';
		ent.AccountId = acc1.id;
		//ent.AssetId = ast.Id;
		ent.ContractLineItemId = cli.id;
		ent.CH_CDB_EntitlementId__c = '1234';
		ent.CH_ServiceMappingId__c = 'Advanced Exchange in Days';
		insert ent;
		
		Case parentCase = HWS_DataFactory_TEST.insertParentCase();
		parentCase.AccountId = acc1.id;
		parentCase.HWS_Sellable_Product__c = prod.Id;
		parentCase.status = 'Open'; 
		insert parentCase;																		   
				
	}
	Public Static testMethod void hwsCancelcaseSendSRtoSOOSVCTestMethod(){
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		List<Case> parntLst = new List<Case>();
		List<Case> chldLst = new List<Case>();
		Account acc1 = [Select id from Account where RecordTypeId = :legalEntityAccountType limit 1];
		Product2 prod = [Select id from Product2 limit 1];
		ContractLineItem cli = [Select id from ContractLineItem limit 1];
		Case parentCase = [Select id from Case where status = 'Open' limit 1];
		Asset ast = [Select id from Asset limit 1];
		parntLst.add(parentCase);
		Case caseRecOrdered = HWS_DataFactory_TEST.insertChildCase();
		caseRecOrdered.Status ='Ordered';
		caseRecOrdered.AccountId = acc1.id;
		caseRecOrdered.AssetId = ast.Id;
		caseRecOrdered.HWS_Faulty_Serial_Number__c = '12345';		
		caseRecOrdered.ParentId = parntLst[0].Id;
		caseRecOrdered.HWS_Sellable_Product__c = prod.Id;
		caseRecOrdered.HWS_Contract_Line_Item__c = cli.id;
		insert caseRecOrdered;
		chldLst.add(caseRecOrdered);
		Test.startTest(); 
		Test.setMock(HttpCalloutMock.class, new HWS_CancelSRHttpCalloutMock());
		HWS_CancelCase.cancelChildCases(parntLst[0].Id);
		HWS_CancelCase.cancelChildCases(chldLst[0].Id);
		HWS_CancelCase_Portal.cancelChildCases(parntLst[0].Id);
		HWS_CancelCase_Portal.cancelChildCases(chldLst[0].Id);		
		Test.stopTest();  
	}
	
	Public Static testMethod void hwsSendServiceRequesttoSOOSVCTestMethod1(){ 
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		List<Case> parntLst = new List<Case>();
		List<Case> chldLst = new List<Case>();
		Account acc1 = [Select id from Account where RecordTypeId = :legalEntityAccountType limit 1];
		Product2 prod = [Select id from Product2 limit 1];
		ContractLineItem cli = [Select id from ContractLineItem limit 1];
		Asset ast = [Select id from Asset limit 1];
		Case parentCase = [Select id from Case where status = 'Open' limit 1];
		parntLst.add(parentCase);
		Case caseRecOrdered = HWS_DataFactory_TEST.insertChildCase();
		caseRecOrdered.Status ='On Hold';
		caseRecOrdered.AccountId = acc1.id;
		caseRecOrdered.AssetId = ast.Id;
		caseRecOrdered.HWS_Faulty_Serial_Number__c = '12345';		
		caseRecOrdered.ParentId = parentCase.Id;
		caseRecOrdered.HWS_Sellable_Product__c = prod.Id;
		caseRecOrdered.HWS_Contract_Line_Item__c = cli.id;
		insert caseRecOrdered ;
		
		Test.startTest(); 
		Test.setMock(HttpCalloutMock.class, new HWS_CancelSRHttpCalloutMock());
		HWS_CancelCase.cancelChildCases(parentCase.id);
		HWS_CancelCase.cancelChildCases(caseRecOrdered.id);
		HWS_CancelCase_Portal.cancelChildCases(parentCase.id);
		HWS_CancelCase_Portal.cancelChildCases(caseRecOrdered.id);		
		Test.stopTest();  
	}
	
	Public Static testMethod void hwsSendServiceRequesttoSOOSVCTestMethod2(){
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		List<Case> parntLst = new List<Case>();
		List<Case> chldLst = new List<Case>();
		Account acc1 = [Select id from Account where RecordTypeId = :legalEntityAccountType limit 1];
		Product2 prod = [Select id from Product2 limit 1];
		ContractLineItem cli = [Select id from ContractLineItem limit 1];
		Asset ast = [Select id from Asset limit 1];
		Case parentCase = [Select id from Case where status = 'Open' limit 1];
		parntLst.add(parentCase);
		Case caseRecOrdered = HWS_DataFactory_TEST.insertChildCase();
		caseRecOrdered.Status ='On Hold';
		caseRecOrdered.AccountId = acc1.id;
		caseRecOrdered.AssetId = ast.Id;
		caseRecOrdered.HWS_Faulty_Serial_Number__c = '12345';		
		caseRecOrdered.ParentId = parentCase.Id;
		caseRecOrdered.HWS_Sellable_Product__c = prod.Id;
		caseRecOrdered.HWS_Contract_Line_Item__c = cli.id;		
		insert caseRecOrdered ;		
		Test.startTest(); 
		Test.setMock(HttpCalloutMock.class, new HWS_CancelSRHttpCalloutMock());
		HWS_CancelCase.cancelChildCases(caseRecOrdered.id);
		HWS_CancelCase_Portal.cancelChildCases(caseRecOrdered.id);		
		Test.stopTest();  
	} 
	
	Public Static testMethod void hwsSendServiceRequesttoSOOSVCTestMethod3(){
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		List<Case> parntLst = new List<Case>();
		List<Case> chldLst = new List<Case>();
		Account acc1 = [Select id from Account where RecordTypeId = :legalEntityAccountType limit 1];
		Product2 prod = [Select id from Product2 limit 1];
		ContractLineItem cli = [Select id from ContractLineItem limit 1];
		Asset ast = [Select id from Asset limit 1];
		Case parentCase = [Select id from Case where status = 'Open' limit 1];
		parntLst.add(parentCase);
		Case caseRecOrdered = HWS_DataFactory_TEST.insertChildCase();
		caseRecOrdered.Status ='On Hold';
		caseRecOrdered.AccountId = acc1.id;
		caseRecOrdered.AssetId = ast.Id;
		caseRecOrdered.HWS_Faulty_Serial_Number__c = '12345';		
		caseRecOrdered.ParentId = parentCase.Id;
		caseRecOrdered.HWS_Sellable_Product__c = prod.Id;
		caseRecOrdered.HWS_Contract_Line_Item__c = cli.id;
		insert caseRecOrdered ;		
		Test.startTest(); 
		Test.setMock(HttpCalloutMock.class, new HWS_CancelSRHttpCalloutMock());		
		HWS_CancelCase_Portal.cancelChildCases(caseRecOrdered.id);
		caseRecOrdered.Status ='Shipped';
		update caseRecOrdered;
		HWS_CancelCase.cancelChildCases(caseRecOrdered.id);
		HWS_CancelCase_Portal.cancelChildCases(caseRecOrdered.id);
		Test.stopTest();  
	} 
	
	Public Static testMethod void hwsSendServiceRequesttoSOOSVCTestMethod4(){
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		List<Case> parntLst = new List<Case>();
		List<Case> chldLst = new List<Case>();
		Account acc1 = [Select id from Account where RecordTypeId = :legalEntityAccountType limit 1];
		Product2 prod = [Select id from Product2 limit 1];
		ContractLineItem cli = [Select id from ContractLineItem limit 1];
		Asset ast = [Select id from Asset limit 1];		
		Case parentCase = [Select id from Case where status = 'Open' limit 1];
		parntLst.add(parentCase);	  
		Case caseRecOrdered = HWS_DataFactory_TEST.insertChildCase();
		caseRecOrdered.Status ='Request to Cancel';
		caseRecOrdered.AccountId = acc1.id;
		caseRecOrdered.AssetId = ast.Id;
		caseRecOrdered.HWS_Faulty_Serial_Number__c = '12345';		
		caseRecOrdered.ParentId = parentCase.Id;
		caseRecOrdered.HWS_Sellable_Product__c = prod.Id;
		caseRecOrdered.HWS_Contract_Line_Item__c = cli.id;
		insert caseRecOrdered ;
		Test.startTest(); 
		Test.setMock(HttpCalloutMock.class, new HWS_CancelSRHttpCalloutMock());
		HWS_CancelCase.cancelChildCases(caseRecOrdered.id);
		HWS_CancelCase_Portal.cancelChildCases(caseRecOrdered.id);
		HWS_CancelCase_Portal.getCancellationStatus(caseRecOrdered.id);
		Test.stopTest();  
	}
	
	Public Static testMethod void hwsCancelcaseSendSRtoSOOSVCTestMethod5(){
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		List<Case> parntLst = new List<Case>();
		List<Case> chldLst = new List<Case>();
		Account acc1 = [Select id from Account where RecordTypeId = :legalEntityAccountType limit 1];
		Product2 prod = [Select id from Product2 limit 1];
		ContractLineItem cli = [Select id from ContractLineItem limit 1];
		Asset ast = [Select id from Asset limit 1];
		Case parentCase = [Select id from Case where status = 'Open' limit 1];
		parntLst.add(parentCase);
		Case caseRecOrdered = HWS_DataFactory_TEST.insertChildCase();
		caseRecOrdered.Status ='Ordered';
		caseRecOrdered.AccountId = acc1.id;
		caseRecOrdered.AssetId = ast.Id;
		caseRecOrdered.HWS_Faulty_Serial_Number__c = '12345';		
		caseRecOrdered.ParentId = parntLst[0].Id;
		caseRecOrdered.HWS_Sellable_Product__c = prod.Id;
		caseRecOrdered.HWS_Contract_Line_Item__c = cli.id;
		chldLst.add(caseRecOrdered);	   
		insert chldLst;
		Test.startTest(); 
		Test.setMock(HttpCalloutMock.class, new HWS_CancelSRHttpCalloutMock());		
		HWS_CancelCase.cancelChildCases(chldLst[0].Id);		  
		Test.stopTest();  
	}
	
	Public Static testMethod void hwsCancelcaseSendSRtoSOOSVCTestMethod6(){		
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		List<Case> parntLst = new List<Case>();
		List<Case> chldLst = new List<Case>();
		Account acc1 = [Select id from Account where RecordTypeId = :legalEntityAccountType limit 1];
		Product2 prod = [Select id from Product2 limit 1];		
		ContractLineItem cli = [Select id from ContractLineItem limit 1];
		Asset ast = [Select id from Asset limit 1];
		Case parentCase = [Select id from Case where status = 'Open' limit 1];
		parntLst.add(parentCase);				  
		Case caseRecOrdered = HWS_DataFactory_TEST.insertChildCase();
		caseRecOrdered.Status ='Draft';
		caseRecOrdered.AccountId = acc1.id;
		caseRecOrdered.AssetId = ast.Id;
		caseRecOrdered.HWS_Faulty_Serial_Number__c = '12345';		
		caseRecOrdered.ParentId = parntLst[0].Id;
		caseRecOrdered.HWS_Sellable_Product__c = prod.Id;
		caseRecOrdered.HWS_Contract_Line_Item__c = cli.id;
		chldLst.add(caseRecOrdered);		
		insert chldLst;
		Test.startTest(); 
		Test.setMock(HttpCalloutMock.class, new HWS_CancelSRHttpCalloutMock());		
		HWS_CancelCase_Portal.cancelChildCases(parntLst[0].Id);
		HWS_CancelCase_Portal.cancelChildCases(chldLst[0].Id);
		chldLst[0].Status ='Ordered';
		update chldLst;
		HWS_CancelCase_Portal.cancelChildCases(parntLst[0].Id);
		HWS_CancelCase_Portal.cancelChildCases(chldLst[0].Id);
		HWS_CancelCase.cancelChildCases(parntLst[0].Id);
		HWS_CancelCase.cancelChildCases(chldLst[0].Id);
		Test.stopTest();  
	}
	
	Public Static testMethod void hwsCancelcaseSendSRtoSOOSVCTestMethod7(){
		Id legalEntityAccountType = HWS_Utilty.getRecordTypeByName('Account',HWS_Constants.LEGAL_ENTITY);
		List<Case> parntLst = new List<Case>();
		List<Case> chldLst = new List<Case>();
		Account acc1 = [Select id from Account where RecordTypeId = :legalEntityAccountType limit 1];
		Product2 prod = [Select id from Product2 limit 1];
		ContractLineItem cli = [Select id from ContractLineItem limit 1];
		Asset ast = [Select id from Asset limit 1];
		Case parentCase = [Select id from Case where status = 'Open' limit 1];
		parntLst.add(parentCase);
		Case caseRecOrdered = HWS_DataFactory_TEST.insertChildCase();
		caseRecOrdered.Status ='Ordered';
		caseRecOrdered.AccountId = acc1.id;
		caseRecOrdered.AssetId = ast.Id;
		caseRecOrdered.HWS_Faulty_Serial_Number__c = '12345';		
		caseRecOrdered.ParentId = parntLst[0].Id;
		caseRecOrdered.HWS_Sellable_Product__c = prod.Id;
		caseRecOrdered.HWS_Contract_Line_Item__c = cli.id;
		chldLst.add(caseRecOrdered);	   
		insert chldLst;
		Test.startTest(); 
		Test.setMock(HttpCalloutMock.class, new HWS_CancelSRHttpCalloutMock());		
		HWS_CancelCase_Portal.cancelChildCases(chldLst[0].Id);		  
		Test.stopTest();  
	}
}