src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Acc_No__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Account number-field as a copy of the AccountNumber-field to be used as external identifier in the integrations of related systems looking up account data in Salesforce. Projects involved: Case Handling and Support Portal.
Initially 2017 only used for data migration upsert capability.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Acc No</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Accreditation__c.object
<CustomObject>
    <description>To be able to maintain Partner&apos;s Accreditation Information</description>
    <fields>
        <fullName>Accreditation_Level__c</fullName>
        <description>To be able to maintain Partners Accreditation Level in the portal so that the accreditation status is accurately reflected in the system and partners are able to work on completing their training program.</description>
        <label>Accreditation Level</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Accreditation_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Authorized - Accreditation In Progress</fullName>
                </value>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Base - Certification In Progress</fullName>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Certified</fullName>
                </value>
                <value>
                    <fullName>Co-Branded</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interim</fullName>
                </value>
                <value>
                    <fullName>L2</fullName>
                    <isActive>false</isActive>
                    <label>L2</label>
                </value>
                <value>
                    <fullName>L3</fullName>
                    <isActive>false</isActive>
                    <label>L3</label>
                </value>
                <value>
                    <fullName>Master</fullName>
                </value>
                <value>
                    <fullName>NBOS</fullName>
                    <isActive>false</isActive>
                    <label>NBOS</label>
                </value>
                <value>
                    <fullName>No Accreditation</fullName>
                </value>
                <value>
                    <fullName>Nokia Brand of Service</fullName>
                </value>
                <value>
                    <fullName>Partner Branded</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
                <value>
                    <fullName>Super Advanced</fullName>
                    <isActive>false</isActive>
                    <label>Super Advanced</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Accreditation_Type__c</fullName>
        <description>To be able to maintain Partner&apos;s accreditation information in the portal so that the accreditation status is accurately reflected in the system and partners are able to work on completing their training program.</description>
        <label>Accreditation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                    <isActive>false</isActive>
                    <label>B</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <isActive>false</isActive>
                    <label>C</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accreditation and Pricing</relationshipLabel>
        <relationshipName>Accreditations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <description>To be able to maintain Partner&apos;s accreditation information in the portal so that the accreditation status is accurately reflected in the system and partners are able to work on completing their training program.</description>
        <label>Portfolio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Portfolio_New</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Level_Override__c</fullName>
        <description>To be able to maintain Partner&apos;s accreditation information in the portal so that the accreditation status is accurately reflected in the system and partners are able to work on completing their training program.
#field name changed in 2.1 sprint 2</description>
        <label>Pricing Level Override</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Accreditation_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Pricing_Level_Override</valueSetName>
        </valueSet>
    </fields>
    <label>Accreditation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Accreditation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accreditations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the price list  associated with the product or service</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Category__c</fullName>
        <formula>If(is_Custom_Product__c == true , &quot;Custom Product&quot;,IF(TEXT(Apttus_Config2__LineType__c) = &apos;Option&apos;,TEXT(Apttus_Config2__OptionId__r.NokiaCPQ_Category__c),TEXT(Apttus_Config2__ProductId__r.NokiaCPQ_Category__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account associated with the price list</description>
        <inlineHelpText>ID of the account associated with the price list</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the price list is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PriceList_Type__c</fullName>
        <label>PriceList Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPQ</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                    <label>Indirect Partner</label>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect Market</fullName>
                </value>
                <value>
                    <fullName>FN Direct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price List</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Configurations (Sold To)</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__EffectivePriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the price list effective for the configuration</description>
        <inlineHelpText>ID of the price list effective for the configuration</inlineHelpText>
        <label>Effective Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Configurations (Effective)</relationshipLabel>
        <relationshipName>Configurations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the price list associated with the configuration</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Apttus_Proposal__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prospect Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SFDC_520_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>R00N70000001yUfDEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Needs_Reprice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Pricing criteria has changed and thus quote needs to be repriced before validation.</inlineHelpText>
        <label>Needs Reprice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reprice_In_Progress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for requirement 3647 in Release 3</description>
        <label>Reprice In Progress</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__ConfigurationType__c</fullName>
        <description>The product configuration type</description>
        <label>Configuration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standalone</fullName>
                    <default>true</default>
                    <label>Standalone</label>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Portfolio_New.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Access - FBA</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Access - POL</fullName>
    </customValue>
    <customValue>
        <fullName>FastMile</fullName>
    </customValue>
    <customValue>
        <fullName>IP Routing</fullName>
    </customValue>
    <customValue>
        <fullName>Optics</fullName>
    </customValue>
    <customValue>
        <fullName>Modular Private Wireless Solution</fullName>
    </customValue>
    <customValue>
        <fullName>Airscale Wifi</fullName>
    </customValue>
    <customValue>
        <fullName>Airscale Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Small Cells</fullName>
    </customValue>
    <customValue>
        <fullName>Microwave</fullName>
    </customValue>
    <customValue>
        <fullName>Nuage</fullName>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
    </customValue>
    <customValue>
        <fullName>Vital QIP</fullName>
    </customValue>
    <customValue>
        <fullName>Vital Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Micro Core Networks</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Packet Core</fullName>
    </customValue>
    <customValue>
        <fullName>Optics - WaveLite</fullName>
        <isActive>false</isActive>
        <label>Optics - WaveLite</label>
    </customValue>
    <masterLabel>Portfolio</masterLabel>
</GlobalValueSet>

src/globalValueSets/Pricing_Level_Override.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Alliance Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Authorized</fullName>
    </customValue>
    <customValue>
        <fullName>Authorized - Accreditation In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Base</fullName>
    </customValue>
    <customValue>
        <fullName>Base - Certification In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Basic</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Branded</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Expert</fullName>
    </customValue>
    <customValue>
        <fullName>Master</fullName>
    </customValue>
    <customValue>
        <fullName>No Accreditation</fullName>
    </customValue>
    <customValue>
        <fullName>Nokia Brand of Service</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Branded</fullName>
    </customValue>
    <customValue>
        <fullName>Premier</fullName>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Professional</fullName>
    </customValue>
    <customValue>
        <fullName>Service Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Interim</fullName>
    </customValue>
    <customValue>
        <fullName>NBOS</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <customValue>
        <fullName>Nokia Brand of Service AED</fullName>
    </customValue>
    <customValue>
        <fullName>NOT APPLICABLE</fullName>
    </customValue>
    <customValue>
        <fullName>NBOS AED</fullName>
        <isActive>false</isActive>
        <label>NBOS AED</label>
    </customValue>
    <masterLabel>Pricing Level Override</masterLabel>
</GlobalValueSet>

src/classes/NokiaCPQ_Reprice_Quote_Controller_Test.cls
/****************************************
 * Name : NokiaCPQ_Reprice_Quote_Controller_Test
 * Author : Accenture
 * Description : Test class for NokiaCPQ_Reprice_Quote_controller, ProcessLineItemBatch, RepriceAllQuotesBatch & lightning component.
 *****************************************/

@istest(SeeAllData=true)
public class NokiaCPQ_Reprice_Quote_Controller_Test {

	/***********************
	* Method Name: submitForRepriceTest
	* Description: To cover the method submitForReprice from class NokiaCPQ_Reprice_Quote_controller.
	* Parameters: NA
	************************/
	static testmethod void submitForRepriceTest(){
		test.startTest();
		//create a Account
		List<Account> accounts = NOKIA_CPQ_TestDataFactory.getAccounts(1);
		accounts[0].Acc_No__c = 'Test10';
		insert accounts;
		
		//create opportunity
		GlobalConstants.SKIP_TRIGGER_OPPORTUNITY_ON_PRESALES = true;
		List<opportunity> opportunities = NOKIA_CPQ_TestDataFactory.getOpportunities(1,accounts);
		opportunities[0].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Create Indirect Sales Opportunity').getRecordTypeId();
		insert opportunities;  
		
		//create Accreditation
		List<Accreditation__c > accreditations = NOKIA_CPQ_TestDataFactory.createAccreditation(2);
		accreditations[0].partner__c = accounts[0].Id;
		accreditations[1].partner__c = accounts[0].Id;
		accreditations[1].Accreditation_Type__c = 'Maintenance';
		accreditations[1].Accreditation_Level__c = 'Premium';
		accreditations[1].Pricing_Level_Override__c = 'Premium';   
		insert accreditations;
		 
		//create a quote
		List<Apttus_Proposal__Proposal__c > proposals = NOKIA_CPQ_TestDataFactory.createProposal(1);
		proposals[0].Apttus_Proposal__Account__c = accounts[0].Id;
		proposals[0].Apttus_Proposal__Opportunity__c = opportunities[0].Id;
		proposals[0].NokiaCPQ_Needs_Reprice__c = true;
		proposals[0].Reprice_In_Progress__c = false;
		insert proposals;
		
		system.debug('proposals[0].Id;--->'+proposals[0].Id);
		
		//get a Price List
		/*Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c();
		priceList = [SELECT ID, Name, PriceList_Type__c, Apttus_Config2__Active__c FROM Apttus_Config2__PriceList__c WHERE Name='Global Price List (EUR)' Limit 1];
		*/
		Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c(
			Name = 'Global Price List (EUR)', 
			Apttus_Config2__Active__c = True
		);
		insert priceList;
		
		// create a product configuration
		List<Apttus_Config2__ProductConfiguration__c> prodConfigs = NOKIA_CPQ_TestDataFactory.createProdConfig(1);
		prodConfigs[0].Apttus_Config2__PriceListId__c = priceList.Id;
		prodConfigs[0].Apttus_Config2__EffectivePriceListId__c = priceList.Id;
		prodConfigs[0].Apttus_Config2__AccountId__c = accounts[0].Id;
		prodConfigs[0].Apttus_QPConfig__Proposald__c = proposals[0].Id;
		insert prodConfigs;
		
		//get a IP Routing Product
		Product2 productInst = new Product2();
		productInst = [SELECT Id, NAME, Portfolio__c, ProductCode, Apttus_Config2__ConfigurationType__c, NokiaCPQ_Category__c, NokiaCPQ_Product_Discount_Category__c, Pricing_Clusters_Search_Filter__c, Pricing_Clusters__c FROM Product2 WHERE Portfolio__c =: proposals[0].NokiaCPQ_Portfolio__c Limit 1];
			
		// create a Line Item
		List<Apttus_Config2__LineItem__c> lineItems = NOKIA_CPQ_TestDataFactory.createLineItem(1);
		lineItems[0].Apttus_Config2__ConfigurationId__c = prodConfigs[0].id;
		lineItems[0].Apttus_Config2__ProductId__c = productInst.Id;
		lineItems[0].Apttus_Config2__PriceListId__c = priceList.Id;
		insert lineItems;
		
		
		NokiaCPQ_Reprice_Quote_controller.submitForReprice(proposals[0].Apttus_Proposal__Opportunity__c);
		test.stopTest(); 
		
	}
	
	/***********************
	* Method Name: submitForRepriceTest2
	* Description: To cover the method submitForReprice from class NokiaCPQ_Reprice_Quote_controller such that validquoteList is empty.
	* Parameters: NA
	************************/
	static testmethod void submitForRepriceTest2(){
		test.startTest();
		//create a Account
		List<Account> accounts = NOKIA_CPQ_TestDataFactory.getAccounts(1);
		accounts[0].Acc_No__c = 'Test11';
		insert accounts;
		
		//create opportunity
		GlobalConstants.SKIP_TRIGGER_OPPORTUNITY_ON_PRESALES = true;
		List<opportunity> opportunities = NOKIA_CPQ_TestDataFactory.getOpportunities(1,accounts);
		opportunities[0].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Create Indirect Sales Opportunity').getRecordTypeId();
		insert opportunities;  
		
		//create Accreditation
		List<Accreditation__c > accreditations = NOKIA_CPQ_TestDataFactory.createAccreditation(2);
		accreditations[0].partner__c = accounts[0].Id;
		accreditations[1].partner__c = accounts[0].Id;
		accreditations[1].Accreditation_Type__c = 'Maintenance';
		accreditations[1].Accreditation_Level__c = 'Premium';
		accreditations[1].Pricing_Level_Override__c = 'Premium';   
		insert accreditations;
		 
		//create a quote
		List<Apttus_Proposal__Proposal__c > proposals = NOKIA_CPQ_TestDataFactory.createProposal(1);
		proposals[0].Apttus_Proposal__Account__c = accounts[0].Id;
		proposals[0].Apttus_Proposal__Opportunity__c = opportunities[0].Id;
		proposals[0].NokiaCPQ_Needs_Reprice__c = false;
		proposals[0].Reprice_In_Progress__c = false;
		insert proposals;
		
		system.debug('proposals[0].Id;--->'+proposals[0].Id);
		
		//get a Price List
		/*Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c();
		priceList = [SELECT ID, Name, PriceList_Type__c, Apttus_Config2__Active__c FROM Apttus_Config2__PriceList__c WHERE Name='Global Price List (EUR)' Limit 1];
		*/
		Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c(
			Name = 'Global Price List (EUR)', 
			Apttus_Config2__Active__c = True
		);
		insert priceList;
		
		// create a product configuration
		List<Apttus_Config2__ProductConfiguration__c> prodConfigs = NOKIA_CPQ_TestDataFactory.createProdConfig(1);
		prodConfigs[0].Apttus_Config2__PriceListId__c = priceList.Id;
		prodConfigs[0].Apttus_Config2__EffectivePriceListId__c = priceList.Id;
		prodConfigs[0].Apttus_Config2__AccountId__c = accounts[0].Id;
		prodConfigs[0].Apttus_QPConfig__Proposald__c = proposals[0].Id;
		insert prodConfigs;
		
		//get a IP Routing Product
		Product2 productInst = new Product2();
		productInst = [SELECT Id, NAME, Portfolio__c, ProductCode, Apttus_Config2__ConfigurationType__c, NokiaCPQ_Category__c, NokiaCPQ_Product_Discount_Category__c, Pricing_Clusters_Search_Filter__c, Pricing_Clusters__c FROM Product2 WHERE Portfolio__c =: proposals[0].NokiaCPQ_Portfolio__c Limit 1];
			
		// create a Line Item
		List<Apttus_Config2__LineItem__c> lineItems = NOKIA_CPQ_TestDataFactory.createLineItem(1);
		lineItems[0].Apttus_Config2__ConfigurationId__c = prodConfigs[0].id;
		lineItems[0].Apttus_Config2__ProductId__c = productInst.Id;
		lineItems[0].Apttus_Config2__PriceListId__c = priceList.Id;
		insert lineItems;
		
		NokiaCPQ_Reprice_Quote_controller newVar = new NokiaCPQ_Reprice_Quote_controller();
		NokiaCPQ_Reprice_Quote_controller.submitForReprice(proposals[0].Apttus_Proposal__Opportunity__c);
		test.stopTest(); 
		
	}
	
}