src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Cable Operator</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Large Enterprise</label>
                </value>
                <value>
                    <fullName>Small / Medium Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Small / Medium Enterprise</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DMP_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates if a Digital Marketplace is set up for the account.</inlineHelpText>
        <label>DMP Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Legal_Entity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checks whether the Legal Entity is the default one or not.
The &quot;Default&quot; field should only display on the Legal Entity page layout (only editable by global process and system admins) 
Requirement#: 654</description>
        <label>Default Legal Entity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Program__c</fullName>
        <label>Partner Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GPP 0.0</fullName>
                </value>
                <value>
                    <fullName>GPP 1.0</fullName>
                </value>
                <value>
                    <fullName>GPP 2.0</fullName>
                </value>
                <value>
                    <fullName>GPP 3.0</fullName>
                </value>
                <value>
                    <fullName>Global Alliance</fullName>
                </value>
                <value>
                    <fullName>SPAAP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Account.object
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account associated with the price list</description>
        <inlineHelpText>ID of the account associated with the price list</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CXM</fullName>
                </value>
                <value>
                    <fullName>CCRE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price List</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Agreement_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Quote/Proposal</relationshipLabel>
        <relationshipName>Quote_Proposal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Analytics_File_Refer_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Analytics File Refer ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Analytics_Source__c</fullName>
        <label>Analytics Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CXM</fullName>
                </value>
                <value>
                    <fullName>CCRE</fullName>
                </value>
                <value>
                    <fullName>RMP</fullName>
                </value>
                <value>
                    <fullName>Siteforge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prospect Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SFDC_520_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>R00N70000001yUfDEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field can represent either the quote end date or the contract end date.</inlineHelpText>
        <label>Quote End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field can represent either the quote start date or the contract start date.</inlineHelpText>
        <label>Quote Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_System__c</fullName>
        <formula>TEXT( Agreement_Lookup__r.Delivery_System__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delivery System</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP__c</fullName>
        <formula>TEXT(Agreement_Lookup__r.ERP__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ERP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote/Proposal (Account)</relationshipLabel>
        <relationshipName>Quote_Proposal</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Req #1313. Required for Marketo Sync</description>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Cable Operator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Opportunity</fullName>
                </value>
                <value>
                    <fullName>Committed Upsell</fullName>
                </value>
                <value>
                    <fullName>Forecasting Only</fullName>
                    <isActive>false</isActive>
                    <label>Forecasting Only</label>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                    <isActive>false</isActive>
                    <label>Large Enterprise</label>
                </value>
                <value>
                    <fullName>Opportunity with Pre-approved or contracted T&amp;Cs</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity with Pre-approved or contracted T&amp;Cs</label>
                </value>
                <value>
                    <fullName>Opportunity within a framework contract</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity within a framework contract</label>
                </value>
                <value>
                    <fullName>Opportunity within partner agreement w/o Offer Support</fullName>
                    <isActive>false</isActive>
                    <label>Opportunity within partner agreement w/o Offer Support</label>
                </value>
                <value>
                    <fullName>Pre-approved Pice List for BG Presales</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Pice List for BG Presales</label>
                </value>
                <value>
                    <fullName>Pre-approved Pice List for Sales</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Pice List for Sales</label>
                </value>
                <value>
                    <fullName>Pre-approved Price List for Account Managers</fullName>
                    <isActive>false</isActive>
                    <label>Pre-approved Price List for Account Managers</label>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                    <isActive>false</isActive>
                    <label>Service Provider</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req 569: User will select Lead BG manually</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field connects to the Legal Entity type Account associated with the Opportunity.
11th Jan: changing field label as per recent discussion.</description>
        <label>Account Legal Entity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Please check if attached account is Legal Entity for added account.</errorMessage>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Data Loader Profile</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Legal_Entity_on_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <description>This is an external ID field to be populated by an external system or auto-populated by SFDC</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/classes/DirectQuoteSharingWCustTriggerHelperTest.cls
@IsTest(SeeAllData=true) 
public class DirectQuoteSharingWCustTriggerHelperTest {
 private static  Id LERecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Legal Entity').getRecordTypeId();
	private static  Id custRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId(); 
	private static Id oppDirectRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.CREATE_DIRECT_SALES_OPPORTUNITY).getRecordTypeId();
	 private static  Id QuoteRecordTypeId = Schema.SObjectType.Apttus_Proposal__Proposal__c.getRecordTypeInfosByName().get(CSWXGlobalConstant.QuoteRecordType).getRecordTypeId();
/*
	 static testMethod void QuoteSharing(){
		  Test.startTest();
		List<Account> accounts=new List<Account>();
		Account Customeraccount = NF_TestDataFactory.createAccount('1TestNONV0000');
		Customeraccount.RecordTypeId=custRecordTypeId;
		 Customeraccount.DMP_Account__c=true;
		accounts.add(Customeraccount);
		Database.insert(accounts);
		
		Account LegalEntityaccount = NF_TestDataFactory.createAccount('10308719999AIA');
		LegalEntityaccount.Accountnumber='1323242223i';
		LegalEntityaccount.Recordtypeid=LERecordTypeId;
		LegalEntityaccount.ParentId=accounts[0].Id;
		LegalEntityaccount.Default_Legal_Entity__c = true;
		LegalEntityaccount.Partner_Program__c=null;
		accounts.add(LegalEntityaccount);
		Database.upsert(accounts); 
		
		Opportunity Opportunity_v1= NF_TestDataFactory.createOpportunity(accounts[0].Id, 'Execute (Start Delivery)', 'In Execution', Date.today().addDays(10), 7000000);
		Opportunity_v1.Lead_BG__c='NSW';
		Opportunity_v1.Opportunity_ID__c='19.IN.856951';
		Opportunity_v1.RecordTypeId = oppDirectRecordTypeId;
		Opportunity_v1.Business_Type__c = 'Standard Opportunity';
		
		Database.insert(Opportunity_v1);
		   
		List<Apttus_Config2__PriceList__c> priceListObj = TestDataFactory.priceList(1);
		priceListObj[0].Apttus_Config2__AccountId__c = LegalEntityaccount.id;
		priceListObj[0].Type__c  = 'CXM';
		database.insert(priceListObj[0]);
		
			   Apttus__APTS_Agreement__c agreementobj= new Apttus__APTS_Agreement__c();
		agreementobj.Apttus__Agreement_Number__c='00000024';
		agreementobj.Name= 'New demo';
		agreementobj.Apttus__Account__c = accounts[1].id;
		agreementobj.CurrencyIsoCode = 'EUR';
		agreementobj.Delivery_System__c = 'Scratch Order via P20';
		agreementobj.ERP__c = 'P20';
		agreementobj.Sales_Mode__c = 'Corporate Sales Mode';
		agreementobj.Confidence_Level__c = 'Low Level';
		agreementobj.Apttus__Contract_Start_Date__c=System.today();
		agreementobj.Apttus__Contract_End_Date__c=System.today()+30;
		agreementobj.Apttus_CMConfig__PriceListId__c = priceListObj[0].id;
		database.insert(agreementobj);
		 Set<String> customerUserTypes = new Set<String> {'CSPLiteUser', 'PowerPartner', 'PowerCustomerSuccess',   'CustomerSuccess'};

		 Contact ContactDS = new Contact(lastName=CSWXGlobalConstant.ContactNameDS,AccountId=accounts[0].id,Email=CSWXGlobalConstant.EmailContactNameDS );
		 database.insert(ContactDS);
				  User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
User newUser;
		 System.runAs ( thisUser ) {
UserRole ur = [Select PortalType, PortalAccountId From UserRole where PortalType =:'CustomerPortal' limit 1];
Profile p = [select Id,name from Profile where UserType in :customerUserTypes limit 1];
 
newUser = new User(
UserRoleId = ur.Id,
profileId = p.id,
username = 'newUser@yahoo.com',
email = 'pb@ff.com',
emailencodingkey = 'UTF-8',
localesidkey = 'en_US',
languagelocalekey = 'en_US',
timezonesidkey = 'America/Los_Angeles',
alias='nuser',
lastname='lastname',
contactId = ContactDS.id
);
database.insert(newUser,false);  
}
					
	   List <Apttus_Proposal__Proposal__c> QPList = new List<Apttus_Proposal__Proposal__c>();
		 Apttus_Proposal__Proposal__c Quote=new Apttus_Proposal__Proposal__c();
				  Quote.RecordTypeId=QuoteRecordTypeId;
				  Quote.Sold_To_Party__c=accounts[1].id;
		  Quote.Apttus_Proposal__Account__c =accounts[0].id;
				  Quote.Agreement_Lookup__c=agreementobj.id;
				  Quote.Apttus_Proposal__Opportunity__c=Opportunity_v1.id;
				  Quote.Analytics_Source__c='CXM';
				  Quote.Analytics_File_Refer_ID__c= 'LTE AIR Interface AR';
				  Quote.Apttus_Proposal__Approval_Stage__c='Approved';
				  Quote.Creation_Date__c=System.today();
				  Quote.Proposal_Recommendation_Type__c='SW Recommendation';
				  Quote.Contract_Start_Date__c=System.today();
				  Quote.Contract_End_Date__c=System.today()+30;
				  Quote.LOA_Status__c='Approved';
						   QPList.add(Quote);
		 Database.insert(QPList);
			 QPList[0].Revision_Status__c='Revision';
	  DirectQuoteSharingWCustTriggerHelper.shareDirectQuoteWithCustomer(QPList);
		Test.stopTest(); 

	 }
	*/
	static testMethod void QuoteSharing1(){
		Test.startTest();
		USer user1 = [Select Id,Profile.Name,Name,ContactID,AccountId from User where  isPortalEnabled = True and isActive = True and AccountId!=null and ContactID!=null  and contact.Account.DMP_Account__c =True and contact.Account.Active__c=true and (UserType = 'PowerCustomerSuccess' or UserType ='CustomerSuccess')   limit 1];
		 Account LegalEntityaccount = [Select id From Account Where RecordtypeId=:LERecordTypeId  AND Parentid=:user1.AccountId AND Active__c = true  limit 1 ];
			
		
		/* Account LegalEntityaccount = NF_TestDataFactory.createAccount('10308719999AIA');
		LegalEntityaccount.Accountnumber='1323242223i';
		LegalEntityaccount.Recordtypeid=LERecordTypeId;
		LegalEntityaccount.ParentId=user1.AccountId;
		LegalEntityaccount.Default_Legal_Entity__c = true;
		LegalEntityaccount.Partner_Program__c=null;
		LegalEntityaccount.Active__c = true;
		Database.insert(LegalEntityaccount); */
		
		
		  Opportunity Opportunity_v1= NF_TestDataFactory.createOpportunity(user1.AccountId, 'Execute (Start Delivery)', 'In Execution', Date.today().addDays(10), 7000000);
		Opportunity_v1.Lead_BG__c='NSW';
		Opportunity_v1.Opportunity_ID__c='19.IN.856951';
		Opportunity_v1.RecordTypeId = oppDirectRecordTypeId;
		Opportunity_v1.Business_Type__c = 'Standard Opportunity';
		Opportunity_v1.Legal_Entity__c=LegalEntityaccount.id;
		Opportunity_v1.End_Customer_LE__c=LegalEntityaccount.id;
		Database.insert(Opportunity_v1);
		
		 List <Apttus_Proposal__Proposal__c> QPList = new List<Apttus_Proposal__Proposal__c>();
		 Apttus_Proposal__Proposal__c Quote=new Apttus_Proposal__Proposal__c();
				  Quote.RecordTypeId=QuoteRecordTypeId;
				  Quote.Sold_To_Party__c=LegalEntityaccount.id;
		  Quote.Apttus_Proposal__Account__c =user1.AccountId;
				 // Quote.Agreement_Lookup__c=agreementobj.id;
				  Quote.Apttus_Proposal__Opportunity__c=Opportunity_v1.id;
				  Quote.Analytics_Source__c='CXM';
				  Quote.Analytics_File_Refer_ID__c= 'LTE AIR Interface AR';
				  Quote.Apttus_Proposal__Approval_Stage__c='Approved';
				  Quote.Creation_Date__c=System.today();
				  Quote.Proposal_Recommendation_Type__c='SW Recommendation';
				  Quote.Contract_Start_Date__c=System.today();
				  Quote.Contract_End_Date__c=System.today()+30;
				  Quote.LOA_Status__c='Approved';
						   QPList.add(Quote);
		 Database.insert(QPList);
			 QPList[0].Revision_Status__c='Revision';
	  DirectQuoteSharingWCustTriggerHelper.shareDirectQuoteWithCustomer(QPList);
		Test.stopTest();
	}
}