src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_Send_Check__c</fullName>
        <description>Created as per the requirement in the US (HWST-1340)</description>
        <label>Email Preferences</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Order Confirmation</fullName>
                </value>
                <value>
                    <fullName>Shipment confirmation</fullName>
                </value>
                <value>
                    <fullName>ETA update</fullName>
                </value>
                <value>
                    <fullName>Reminder to send faulty part</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>HWS_Part_Code__c</fullName>
        <formula>IF( HWS_SourceSystem__c =&apos;Puma1&apos;,  Product2.ProductCode ,  Product2.CARE_PartCode__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Part Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_Email3__c.field-meta.xml
<CustomField>
    <fullName>CH_Email3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email 3</label>
    <type>Email</type>
</CustomField>

src/objects/Case/fields/HWS_Address_Name__c.field-meta.xml
<CustomField>
    <fullName>HWS_Address_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Bar_Code__c.field-meta.xml
<CustomField>
    <fullName>HWS_Bar_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RMA Bar Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Case/fields/HWS_Bar_Code_Ref1__c.field-meta.xml
<CustomField>
    <fullName>HWS_Bar_Code_Ref1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Case Number Bar Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Case/fields/HWS_Communication_Contact__c.field-meta.xml
<CustomField>
    <fullName>HWS_Communication_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created with reference to the User Story.</description>
    <label>Communication Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Support Ticket</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_Customer_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_Customer_Reference_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer&apos;s Own Identifier for the Service Request.</inlineHelpText>
    <label>Customer Reference Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Failure_Description__c.field-meta.xml
<CustomField>
    <fullName>HWS_Failure_Description__c</fullName>
    <description>Created with reference to the User Story.</description>
    <inlineHelpText>Select appropriate option</inlineHelpText>
    <label>Failure Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unit/module not recognized</fullName>
            </value>
            <value>
                <fullName>No TX power</fullName>
            </value>
            <value>
                <fullName>Fan defect</fullName>
            </value>
            <value>
                <fullName>LED indicates alarm</fullName>
            </value>
            <value>
                <fullName>Unit alarm</fullName>
            </value>
            <value>
                <fullName>SW download failure</fullName>
            </value>
            <value>
                <fullName>Feature Activation effect</fullName>
            </value>
            <value>
                <fullName>Advise for exchange from others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/HWS_Failure_Description_Server_ID__c.field-meta.xml
<CustomField>
    <fullName>HWS_Failure_Description_Server_ID__c</fullName>
    <description>Created as the part of the US.SRM.1446</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Additional Information related to Fault</inlineHelpText>
    <label>Failure Description/ Server ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Failure_Detection__c.field-meta.xml
<CustomField>
    <fullName>HWS_Failure_Detection__c</fullName>
    <description>Created with reference to the User Story.</description>
    <inlineHelpText>Select appropriate option</inlineHelpText>
    <label>Failure Detection</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start reset loop</fullName>
            </value>
            <value>
                <fullName>Reboot module</fullName>
            </value>
            <value>
                <fullName>Fails on diagnostics</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Non-reproducible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/HWS_Failure_Detection_Date__c.field-meta.xml
<CustomField>
    <fullName>HWS_Failure_Detection_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date on which Failure was detected</inlineHelpText>
    <label>Failure Detection Date</label>
    <type>Date</type>
</CustomField>

src/objects/Case/fields/HWS_Failure_Occurance__c.field-meta.xml
<CustomField>
    <fullName>HWS_Failure_Occurance__c</fullName>
    <description>Created with reference to the User Story.</description>
    <inlineHelpText>Select appropriate option</inlineHelpText>
    <label>Failure Occurrence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In normal use</fullName>
            </value>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>During installation / commissioning / Dead On Arrival</fullName>
            </value>
            <value>
                <fullName>During or after lightning / severe weather conditions</fullName>
            </value>
            <value>
                <fullName>During or after SW or HW upgrade / modifications</fullName>
            </value>
            <value>
                <fullName>During preventive maintenance</fullName>
            </value>
            <value>
                <fullName>During high traffic load</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/HWS_Faulty_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_Faulty_Serial_Number__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Serial Number of the faulty Unit</inlineHelpText>
    <label>Faulty Unit Serial Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_OrderConfirmationSent__c.field-meta.xml
<CustomField>
    <fullName>HWS_OrderConfirmationSent__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Order Confirmation Sent</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/HWS_Part_Code__c.field-meta.xml
<CustomField>
    <fullName>HWS_Part_Code__c</fullName>
    <description>This is for ETA email template and Part code population.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Part Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Replacement_Unit_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_Replacement_Unit_Serial_Number__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Provide Replacement unit Serial Number</inlineHelpText>
    <label>Replacement Unit Serial Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_ReturnAddressReceivedFromSOO__c.field-meta.xml
<CustomField>
    <fullName>HWS_ReturnAddressReceivedFromSOO__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created with reference to the User Story.</description>
    <label>Return Address Received From SOO</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/HWS_RMA_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_RMA_Number__c</fullName>
    <description>Created as the part of the US.SRM.1049</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RMA Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Hws_Ship_to_Party_Address__c.field-meta.xml
<CustomField>
    <fullName>Hws_Ship_to_Party_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US.SRM.1363</description>
    <inlineHelpText>Select address for delivery of replacement Unit</inlineHelpText>
    <label>Ship to Party Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Logistic_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Support Tickets</relationshipLabel>
    <relationshipName>Hws_Ship_to_Part_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_Site_ID__c.field-meta.xml
<CustomField>
    <fullName>HWS_Site_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Identifier for faulty Unit Installation location</inlineHelpText>
    <label>Site ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Site_Information__c.field-meta.xml
<CustomField>
    <fullName>HWS_Site_Information__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Additional Information related to Faulty Unit Installation Location.</inlineHelpText>
    <label>Site Information</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Stockable_Product__c.field-meta.xml
<CustomField>
    <fullName>HWS_Stockable_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created with the reference to the US  1654.</description>
    <inlineHelpText>Version Item Code</inlineHelpText>
    <label>Part Revision</label>
    <referenceTo>HWS_VersionItem__c</referenceTo>
    <relationshipLabel>Support Ticket</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street Address 1</label>
    <type>TextArea</type>
</CustomField>

src/objects/Case/fields/Street_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street Address 2</label>
    <type>TextArea</type>
</CustomField>

src/objects/Case/fields/Street_Address_3__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street Address 3</label>
    <type>TextArea</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CH_Email3__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Email 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Req #1313. Required for Marketo Sync</description>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email1__c</fullName>
        <description>Req #1313. Required for Marketo Sync</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Email 2</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/HWS_VersionItem__c.object
<CustomObject>
    <fields>
        <fullName>HWS_Version_Code__c</fullName>
        <description>Created as the part of the US.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Version Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Version Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HWS_OrderConfirmationNotification.cls
/****************************************
* Class Name : HWS_OrderConfirmationNotification
* Created Date:  Mar 2019
* Created By : TCS
* Last Modified by: TCS
* Last Modified Date: 15 Mar 2019
* Description : Whenever SPM related Cases receives return delivery addresses an email will be trigger ed to the Contact and Communication Contact
with the order confirmation and failure report of the each individual case.
*****************************************/
public without sharing class HWS_OrderConfirmationNotification {
	public ApexPages.StandardSetController stdCntrlr {get; set;}
	public static Id currentParentCaseId {get;set;}
	public static Integer recordCount {get;set;}
	public HWS_OrderConfirmationNotification(ApexPages.StandardSetController controller){
		stdCntrlr = controller;
	}
	public static Id childCaseReadOnly {
		get {
			if(childCaseReadOnly == null){
				childCaseReadOnly = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_CHILD_CASE_READ_ONLY);
			}
			return childCaseReadOnly;
		}
		set;
	}
	public static Id parentCase {
		get {
			if(parentCase == null){
				parentCase = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_PARENT_CASE);
			}
			return parentCase;
		}
		set;
	}
	public static Id parentCaseReadOnly {
		get {
			if(parentCaseReadOnly == null){
				parentCaseReadOnly = HWS_Utilty.getRecordTypeByName('Case',HWS_Constants.HWS_PARENT_CASE_READ_ONLY);
			}
			return parentCaseReadOnly;
		}
		set;
	}	
	public static List<Case> childCaseList;
	public static boolean isMailSent=true;
	public static String emailCheck = 'Order Confirmation';
	
	/****************************************
* Method Name : sendEmailNotificationForPDF
* Created Date:  May 2019
* Created By : TCS
* Last Modified by: TCS
* Description : Whenever SPM related Cases receives return delivery addresses an email will be trigger ed to the Contact and Communication Contact with the order confirmation and failure report of the each individual case. The pdf will be generated using VF Page.
*****************************************/	
	@future (callout=true)
	public static void sendEmailNotificationForPDF(Set<Id> caseId){   
		//Calling the below method Asynchronusly to update parent case status based on multiple child cases updated at once.
		HWS_CaseTriggerHelper.changeParentCaseStatus(caseId);
		List<Case> childCases = new List<Case>();
		String emailBodyContent1 = System.Label.HWS_SREmailContent_1;
		String emailBodyContent2 = System.Label.HWS_SREmailContent_2;
		String fromAddress = System.Label.HWS_SupportEmailAddress;
		
		List<case> caseList = [select Id, RecordTypeId, ParentId from case where Id in :caseId];
		
		String[] ccAddress = new String[]{};//NOKIAsc-27247
			String contactName;
		List<Case> parentCasesToBeUpdated = new List<Case>();
		Set<Id> parentCaseIds = new Set<Id>();
		List<Case> parentCases = new List<Case>();
		
		for(Case cs:caseList){
			if(cs.RecordTypeId != parentCase && cs.RecordTypeId != parentCaseReadOnly){
				if(cs.ParentId != null){
					parentCaseIds.add(cs.ParentId);
				}
			}
		}
		
		OrgWideEmailAddress[] owea = new OrgWideEmailAddress[]{};
			EmailTemplate etemplate = new EmailTemplate();
		List<Messaging.EmailFileAttachment> attachmentList = new List<Messaging.EmailFileAttachment>();
		List <Attachment> attachlist = new List<Attachment>();
		List<FeedItem> postChatterList = new List<FeedItem>();
		String pdfBody='';
		system.debug('ParentCasesCheck'+parentCases);
		
		if(parentCaseIds.size()>0){	 
			parentCases = [SELECT Id, OwnerId, CaseNumber,Contact.Name,Contact.Email,Contact.Email1__c,Contact.CH_Email3__c, HWS_Communication_Contact__r.name, Account.Email_Send_Check__c, HWS_Communication_Contact__r.Email,HWS_ReturnAddressReceivedFromSOO__c,HWS_OrderConfirmationSent__c,HWS_Bar_Code__c,HWS_Bar_Code_Ref1__c,Origin,
						   (SELECT Id,HWS_RMA_Number__c,HWS_Customer_Reference_Number__c, Asset.ProductCode,Asset.HWS_Part_Code__c, Asset.Product2.Name, HWS_Faulty_Serial_Number__c,HWS_Bar_Code__c,HWS_Bar_Code_Ref1__c,HWS_Part_Code__c,
							Contact.Account.Name,Account.Name,Account.BillingCountry,Account.BillingState,Account.BillingCity,Account.BillingStreet,Account.BillingPostalCode,
							Parent.Hws_Ship_to_Party_Address__r.BillingCountry,Parent.Hws_Ship_to_Party_Address__r.BillingState,Parent.Hws_Ship_to_Party_Address__r.BillingCity,
							Parent.Hws_Ship_to_Party_Address__r.BillingStreet,Parent.Hws_Ship_to_Party_Address__r.BillingPostalCode,HWS_Failure_Description__c,Contact.Name, Contact.Email, Contact.Email1__c, Contact.CH_Email3__c, Contact.Phone,
							HWS_Stockable_Product__r.HWS_Version_Code__c,HWS_Site_ID__c,HWS_Failure_Detection__c,HWS_Replacement_Unit_Serial_Number__c,
							HWS_Failure_Detection_Date__c,HWS_Failure_Occurance__c,HWS_Failure_Description_Server_ID__c,HWS_Site_Information__c,HWS_Address_Name__c ,
							Street_Address_1__c,Street_Address_2__c,Street_Address_3__c,City__c,State__c,Country__c,POSTAL_CODE_CHQ__c
							FROM Cases
							WHERE Status='Ordered' AND RecordTypeId=:childCaseReadonly) 
						   FROM Case 
						   WHERE Id IN: parentCaseIds AND HWS_ReturnAddressReceivedFromSOO__c=:True];
			
		}
		if(parentCases.size()>0){
			owea = [select Id from OrgWideEmailAddress where Address =: fromAddress];		
			etemplate = [SELECT Id, Subject, HtmlValue, Body
						 FROM EmailTemplate
						 WHERE DeveloperName='HWS_OrderConfirmationEmailTemaplate'];  
			for(Case parent: parentCases){
				if(parent.Contact.Email1__c != Null){
	ccAddress.add(parent.Contact.Email1__c); //// NOKIASC 27247
	}
	if(parent.Contact.CH_Email3__c != Null){
	ccAddress.add(parent.Contact.CH_Email3__c);// NOKIASC 27247
			   }
				
				if(parent.Cases.Size()>0){ //null pointer check starts
					Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
					Messaging.EmailFileAttachment efa1 = new Messaging.EmailFileAttachment();
					List<Messaging.EmailFileAttachment> efaList = new List<Messaging.EmailFileAttachment>();
					//if(parent.Contact.Email!=Null){emailAddress.add(parent.Contact.Email);}
					//if(parent.HWS_Communication_Contact__r.Email!=Null){emailAddress.add(parent.HWS_Communication_Contact__r.Email);}
					contactName=((parent.Contact.Name!=null && parent.HWS_Communication_Contact__r.Name!=null)?parent.Contact.Name+'/'+parent.HWS_Communication_Contact__r.Name:(parent.Contact.Name!=null && parent.HWS_Communication_Contact__r.Name==null)?parent.Contact.Name:parent.HWS_Communication_Contact__r.Name);
					pdfBody += '<html><h4 style=\"text-align:left;\">Dear '+contactName+',</h4><br/></html>';
					pdfBody += '<html><h4 style=\"text-align:left;\">Thank you for contacting Nokia Care. This acknowledges your Hardware Services request '+ parent.CaseNumber + ' Your request has ' + parent.Cases.Size() + ' RMA(s) associated with it. Please find additional details below.</h4><br/></html>';
					pdfBody += '<html><h4 style=\"text-align:left;\">'+emailBodyContent1+'</h4><br/></html>';
					pdfBody += '<html><h4 style=\"text-align:left;\">'+emailBodyContent2+'</h4><br/></html>';
					pdfBody += '<br/><font size="2" ><table border="0.1" align="center" valign="middle" style="border-collapse: collapse"><tr><th bgcolor="#D6DBDF">RMA#</th><th bgcolor="#D6DBDF">Customer Ref#</th><th bgcolor="#D6DBDF">Part Code</th><th bgcolor="#D6DBDF">Part Description</th><th bgcolor="#D6DBDF">Faulty Serial Number</th></tr>';
					efa.setContentType('application/pdf');
					efa.setFileName('Order Confirmation_'+parent.CaseNumber+'.pdf');
					//calling the pdf with the parent case as arguement, the VF page will further iterate over this parent's child cases. -- Prateek -- NOKIASC-27243
					efa1=sendPdf(parent);
					attachmentList.add(efa1);
					Attachment a = new Attachment();
					a.ParentId = parent.Id;
					a.Body = efa1.body;
					a.Name = 'RMA\'s for Parent Case '+parent.CaseNumber+'.pdf';
					attachlist.add(a);
					for(Case child: parent.cases){
						pdfBody += '<tr><td>' +  (child.HWS_RMA_Number__c==null ? ' ' :child.HWS_RMA_Number__c) + '</td><td>' + (child.HWS_Customer_Reference_Number__c==null ? ' ' : child.HWS_Customer_Reference_Number__c) + '</td><td>' + (child.Asset.HWS_Part_Code__c==null ? ' ' : child.Asset.HWS_Part_Code__c)+ '</td><td>' + (child.Asset.Product2.Name==null ? ' ' : child.Asset.Product2.Name)+ '</td><td>' + (child.HWS_Faulty_Serial_Number__c==null ? ' ' : child.HWS_Faulty_Serial_Number__c) +'</td></tr><br/>';
						
						childCases.add(child);
					}  
					pdfBody += '</table><br/><br/>';
					pdfBody += '<html><h4 style=\"text-align:left;\">Regards,</h4></html>';
					pdfBody += '<html><h4 style=\"text-align:left;\">Nokia Care Services</h4><br/><br/></html>';
					efa.Body = Blob.toPDF(pdfBody);
					attachmentList.add(efa);
					if(parent.HWS_OrderConfirmationSent__c){
						if(parent.Account.Email_Send_Check__c != null && parent.Account.Email_Send_Check__c != '' && parent.Account.Email_Send_Check__c.contains(emailCheck)){
							if(parent.ContactId!=NULL){
								Messaging.SingleEmailMessage contactEmail = new Messaging.SingleEmailMessage();// for sending email to Contact
								contactEmail.setOrgWideEmailAddressId(owea.get(0).Id);
								
								contactEmail.setccAddresses(ccAddress); //// NOKIASC-27247
								contactEmail.setTemplateId(etemplate.Id);
								contactEmail.setTargetObjectId(parent.ContactId);
								contactEmail.setTreatTargetObjectAsRecipient(true);   
								contactEmail.setFileAttachments(attachmentList);
								try{
									Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {contactEmail});
								}
								catch(Exception e){
									System.debug('Exception Occured: '+e);
								}
							}
							if(parent.HWS_Communication_Contact__c!=NULL){
								Messaging.SingleEmailMessage comcontactEmail = new Messaging.SingleEmailMessage();// for sending email to Communication  Contact
								comcontactEmail.setOrgWideEmailAddressId(owea.get(0).Id);
								
								comcontactEmail.setccAddresses(ccAddress);// NOKIASC-27247
								comcontactEmail.setTemplateId(etemplate.Id);
								comcontactEmail.setTargetObjectId(parent.HWS_Communication_Contact__c);
								comcontactEmail.setTreatTargetObjectAsRecipient(true);   
								comcontactEmail.setFileAttachments(attachmentList);
								try{
									Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {comcontactEmail});
								}
								catch(Exception e){
									System.debug('Exception Occured: '+e);
								}
							}				
							
							if(parent.Origin=='web'){
								FeedItem postChatter = new FeedItem();
								postChatter.ParentId = parent.Id;
								postChatter.Body = 'Dear '+parent.Contact.Name+',\nYour Order with Case Number# '+(parent.caseNumber !=Null?parent.caseNumber :'')+' has been confirmed';
								postChatter.Title = 'Case';
								postChatter.LinkUrl = '/lightning/r/Case/'+parent.Id+'/view';
								postChatterList.add(postChatter);
							}
						}
						parent.HWS_OrderConfirmationSent__c=false;
						parentCasesToBeUpdated.add(parent);
					}
				} //null pointer check ends	
			}
			if(parentCasesToBeUpdated.Size()>0 && postChatterList.Size()>0){
				try{
					insert postChatterList;
				}
				catch(Exception e){
					System.debug('Exception while posting to chatter'+e);
				}
			}
			if(parentCasesToBeUpdated.Size()>0 && attachlist.Size()>0){
				try{
					insert attachlist;
				}
				catch(Exception e){
					System.debug('Exception while inserting attachments'+e);
				}
			}
			if(parentCasesToBeUpdated.Size()>0){	   
				
				try{
					update parentCasesToBeUpdated;
				}
				catch(Exception e){
					System.debug('Exception while updating parent case'+e);
				}
			}
		}
	}
	
	/****************************************
* Method Name : sendPdf
* Created Date:  May 2019
* Created By : TCS
* Last Modified by: TCS
* Description : The pdf will be generated usinf Vf page by using Pagereference.		
*****************************************/	 
	public static Messaging.EmailFileAttachment sendPdf(Case parentCase) {	
		//String logoUrl = System.Label.Nokia_Logo_URL; 
		String fileName='ParentCaseFile';
		Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
		efa.setContentType('application/pdf');
		//efa.setFileName('Failuredetails_'+fileName+'.pdf');
		efa.setFileName('RMA\'s for Parent Case '+parentCase.CaseNumber+'.pdf');
		efa.setInline(false);
		
		PageReference pdf = Page.HWS_OrderConfirmationNotificationVFPage;
		// add parent id to the parameters for standardcontroller
		pdf.getParameters().put('id',parentCase.Id);	 
		// the contents of the attachment from the pdf
		Blob body;
		
		try{	  
			// returns the output of the page as a PDF
			body = pdf.getContent();	  
			// need to pass unit test -- current bug  
		} catch (VisualforceException e) {
			body = Blob.valueOf('Some Text');
		}   
		
		efa.Body = body; 
		return efa;
	}
   
	//using this method as an extension to the VF page- HWS_OrderConfirmationNotificationVFPage, the VF page will iterate over the parent's child cases. 
	//The parent's id passed as param in the url of the VF page-- Prateek -- NOKIASC-27243
	public static List<Case> getCases(){
		currentParentCaseId  = ApexPages.CurrentPage().getparameters().get('id');
		List<Case> childCaseList = [select id, HWS_RMA_Number__c, Street_Address_1__c, Street_Address_2__c, Street_Address_3__c, City__c, State__c, Country__c, POSTAL_CODE_CHQ__c, HWS_Bar_Code__c, HWS_Shippeddate__c, 
									Account.Name, Account.BillingStreet, Account.BillingCity, Account.BillingState, Account.BillingCountry, Account.BillingPostalCode, HWS_Bar_Code_Ref1__c, 
									Parent.Hws_Ship_to_Party_Address__r.BillingStreet, Parent.Hws_Ship_to_Party_Address__r.BillingCity, Parent.Hws_Ship_to_Party_Address__r.BillingState, Parent.Hws_Ship_to_Party_Address__r.BillingCountry, Parent.Hws_Ship_to_Party_Address__r.BillingPostalCode, 
									HWS_Customer_Reference_Number__c, HWS_Faulty_Serial_Number__c, HWS_Failure_Detection_Date__c, HWS_Part_Code__c, HWS_Customer_Part_Revision__c, HWS_Stockable_Product__r.HWS_Version_Code__c, 
									Asset.Product2.Name, HWS_Site_ID__c, HWS_Site_Information__c, HWS_Failure_Occurance__c, HWS_Failure_Detection__c, HWS_Failure_Description__c, HWS_Failure_Description_Server_ID__c, HWS_Replacement_Unit_Serial_Number__c, 
									Contact.Name, Contact.Phone, Contact.Email, Contact.Email1__c, Contact.CH_Email3__c
									from Case where ParentId =: currentParentCaseId ];
		recordCount = childCaseList.size();
		return childCaseList;
	}
}