src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Hws_Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hws_Address_Line_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Address Line 2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hws_Address_Line_3__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Address Line 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LE_Customer_Compliance__c</fullName>
        <formula>IF(ISBLANK(TEXT(Parent.Customer_Compliance__c)), &apos;Unassigned&apos;, TEXT(Parent.Customer_Compliance__c))</formula>
        <inlineHelpText>Customer Compliance value from parent 301 account.</inlineHelpText>
        <label>LE Customer Compliance</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NCP_P20_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>P20 ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>P20_Logistic_ID__c</fullName>
        <description>P20 ID for Logistic accounts</description>
        <encryptionScheme>None</encryptionScheme>
        <label>P20 Logistic ID</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Asia and Japan</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Middle East and Africa</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>HWS_Currency__c</fullName>
        <description>HWST-1168 - Sprint - 1908</description>
        <formula>HWS_ContractLineItem__r.ServiceContract.HWS_Currency__c</formula>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_CARES_ServiceAgreement__c.field-meta.xml
<CustomField>
    <fullName>CH_CARES_ServiceAgreement__c</fullName>
    <formula>Entitlement.ServiceContract.CH_CARES_ServiceAgreement__c</formula>
    <label>CARES Service Agreement</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>HWS_Contract_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field is used to store the related Contract line item. It will not be shown on the UI</description>
    <label>Contract Line Item</label>
    <referenceTo>ContractLineItem</referenceTo>
    <relationshipLabel>Support Ticket</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_Currency__c.field-meta.xml
<CustomField>
    <fullName>HWS_Currency__c</fullName>
    <description>UAT Defect fix, will be used to get the currency value from related Service Contract</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Customer_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_Customer_Reference_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer&apos;s Own Identifier for the Service Request.</inlineHelpText>
    <label>Customer Reference Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Delivery_Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>HWS_Delivery_Additional_Information__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Additional instructions for the delivery Person.</inlineHelpText>
    <label>Delivery Additional Information</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Delivery_TimeZone__c.field-meta.xml
<CustomField>
    <fullName>HWS_Delivery_TimeZone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Delivery TimeZone</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Planned_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>HWS_Planned_Delivery_Date__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Planned Delivery Date(User timezone)</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/HWS_Requested_Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>HWS_Requested_Delivery_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Requested delivery date and time.</inlineHelpText>
    <label>Customer Requested Date(User Timezone)</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/HWS_RMA_Number__c.field-meta.xml
<CustomField>
    <fullName>HWS_RMA_Number__c</fullName>
    <description>Created as the part of the US.SRM.1049</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RMA Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Hws_Ship_to_Party_Address__c.field-meta.xml
<CustomField>
    <fullName>Hws_Ship_to_Party_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US.SRM.1363</description>
    <inlineHelpText>Select address for delivery of replacement Unit</inlineHelpText>
    <label>Ship to Party Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Logistic_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Support Tickets</relationshipLabel>
    <relationshipName>Hws_Ship_to_Part_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/HWS_Shipment_Recipient_Name__c.field-meta.xml
<CustomField>
    <fullName>HWS_Shipment_Recipient_Name__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the person who will receive parcel at delivery location</inlineHelpText>
    <label>Shipment Recipient Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/HWS_Shipment_Recipient_Phone__c.field-meta.xml
<CustomField>
    <fullName>HWS_Shipment_Recipient_Phone__c</fullName>
    <description>Created with reference to the User Story.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Phone Number of the Person who will receive parcel at delivery location</inlineHelpText>
    <label>Shipment Recipient Phone</label>
    <type>Phone</type>
</CustomField>

src/objects/Case/fields/HWS_ShipmentRecipientEmailId__c.field-meta.xml
<CustomField>
    <fullName>HWS_ShipmentRecipientEmailId__c</fullName>
    <description>US-HWST-2312 - 1908 sprint.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Email Id of the person who will receive the parcel at delivery location</inlineHelpText>
    <label>Shipment Recipient Email</label>
    <type>Email</type>
</CustomField>

src/objects/Case/fields/HWS_Stockable_Product__c.field-meta.xml
<CustomField>
    <fullName>HWS_Stockable_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created with the reference to the US  1654.</description>
    <inlineHelpText>Version Item Code</inlineHelpText>
    <label>Part Revision</label>
    <referenceTo>HWS_VersionItem__c</referenceTo>
    <relationshipLabel>Support Ticket</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/NCP_Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>NCP_Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ContractLineItem.object
<CustomObject>
    <fields>
        <fullName>CH_CDB_ContractId__c</fullName>
        <description>New custom field. Used as a reference for checking service contracts in CDB</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CDB Contract ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_CostObjectType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_CostObject__c</fullName>
        <description>to store the value coming from CDB as part of US.SRM.1031</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost Object</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_ServiceItemCode__c</fullName>
        <description>Code of the CDB service item.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Item Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_ServiceTypeCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Type Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_IncotermCity__c</fullName>
        <description>Created as part of US.SRM.1667A</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Incoterm City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_IncotermType__c</fullName>
        <description>Created As Part of US.SRM.1667A</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Incoterm Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_InvoicingTypeCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoicing Type Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_LeadTimeType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Lead Time Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_SAPP20LineItem__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP P20 Line item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_SeparateOrderPerPart__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Separate Order per Part</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/HWS_VersionItem__c.object
<CustomObject>
    <fields>
        <fullName>RES_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>RES ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Version Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Version Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>CH_CARES_ServiceAgreement__c</fullName>
        <description>CARES Service Agreement</description>
        <encryptionScheme>None</encryptionScheme>
        <label>CARES Service Agreement</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_CDB_ContractId__c</fullName>
        <description>Used as a reference for checking service contracts in CDB</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CDB Contract ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_ERPSystem__c</fullName>
        <description>ERP System</description>
        <label>ERP System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>P20</fullName>
                </value>
                <value>
                    <fullName>SAP-Blue Planet</fullName>
                </value>
                <value>
                    <fullName>SAP E-Box (NAR)</fullName>
                </value>
                <value>
                    <fullName>NSB ERP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_SAP_ContractNumber__c</fullName>
        <description>SAP P20 Contract Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP P20 Contract Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_CaresRepairServiceBillToCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cares Repair Service  Bill To Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_Currency__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Currency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_SalesOrganisation__c</fullName>
        <description>to store the sales organisation value coming from CDB as part of US ES-100</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Organisation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/HWS_CreateSRRequest.cls
/*****************************************************************
Description:	This class returns json string of requested case
History									
DATE			AUTHOR	CHANGE
11/11/2018	  Shiv Maila	  Created
20/12/2018	  Vinod Ch		Updated
*****************************************************************/
Public without sharing Class HWS_CreateSRRequest
{
	/*****************************************************************
Description:	Returns the string json of the requested case object 
Parameters: parentCaseId
Returns:  JSON String
Throws [Exceptions]: [optional]	
History						
DATE			AUTHOR	CHANGE
11/11/2018	  Shiv Maila	  Created
20/12/2018	  Vinod Ch		Updated
10/03/2019	  Harikishore	 Updated
*****************************************************************/
	Public SOORequestBody createSRRequest(Id parentCaseId){
		Case caserec = [SELECT id,Account.Name,Account.AccountNumber,Account.NCP_P20_ID__c, Account.LE_Customer_Compliance__c,CreatedBy.Name,Status,CreatedDate,HWS_Customer_Reference_Number__c,
			Hws_Ship_to_Party_Address__r.BillingCountryCode,Hws_Ship_to_Party_Address__r.BillingStateCode,CaseNumber,Origin,HWS_Shipment_Recipient_Name__c,Hws_Ship_to_Party_Address__r.ParentId,
			HWS_Shipment_Recipient_Phone__c,HWS_Delivery_Additional_Information__c,Hws_Ship_to_Party_Address__r.BillingPostalCode,HWS_ShipmentRecipientEmailId__c,
			Hws_Ship_to_Party_Address__r.Hws_Address_Line_1__c,Hws_Ship_to_Party_Address__r.Hws_Address_Line_2__c,Hws_Ship_to_Party_Address__r.Hws_Address_Line_3__c,
			Hws_Ship_to_Party_Address__r.BillingState,Hws_Ship_to_Party_Address__r.P20_Logistic_ID__c,Hws_Ship_to_Party_Address__r.BillingCity,Hws_Ship_to_Party_Address__r.Region__c,HWS_Delivery_TimeZone__c,
			(SELECT id,HWS_Stockable_Product__r.RES_ID__c,HWS_RMA_Number__c,Status,NCP_Service_Contract__r.CH_SAP_ContractNumber__c,NCP_Service_Contract__r.CH_CARES_ServiceAgreement__c,HWS_Customer_Reference_Number__c,
			 HWS_Planned_Delivery_Date__c,NCP_Service_Contract__r.HWS_SalesOrganisation__c,NCP_Service_Contract__r.HWS_CaresRepairServiceBillToCode__c,HWS_Requested_Delivery_Date_Time__c,
			 NCP_Service_Contract__r.HWS_Currency__c,NCP_Service_Contract__r.CH_ERPSystem__c,HWS_Contract_Line_Item__r.CH_ServiceItemCode__c,HWS_Contract_Line_Item__r.HWS_InvoicingTypeCode__c,
			 HWS_Contract_Line_Item__r.CH_CDB_ContractId__c,HWS_Contract_Line_Item__r.HWS_IncotermType__c,HWS_Contract_Line_Item__r.HWS_IncotermCity__c,HWS_Contract_Line_Item__r.CH_CostObject__c,
			 HWS_Contract_Line_Item__r.CH_CostObjectType__c,HWS_Contract_Line_Item__r.HWS_LeadTimeType__c,HWS_Contract_Line_Item__r.HWS_SeparateOrderPerPart__c,HWS_Contract_Line_Item__r.HWS_SAPP20LineItem__c,
			 HWS_Contract_Line_Item__r.Product2.Productcode,HWS_Contract_Line_Item__r.CH_ServiceTypeCode__c,Parent.HWS_Customer_PO__c,Asset.HWS_ContractLeadTimeDuration__c,Asset.HWS_ContractLeadTimeUnit__c,
			 HWS_Sellable_Product__r.ProductCode,HWS_Sellable_Product__r.HWS_Unit_of_Measure__c,HWS_Stockable_Product__r.Material_Code__c,HWS_Stockable_Product__r.HWS_Version_Code__c,HWS_Failure_Detection_Date__c,
			 HWS_Failure_Occurance__c,HWS_Failure_Detection__c,HWS_Failure_Description__c,HWS_Faulty_Serial_Number__c,HWS_Fault_Reported_By_Name__c,HWS_Fault_Reported_By_Phone__c,HWS_Fault_Reported_By_Email__c,
			 HWS_Replacement_Unit_Serial_Number__c,HWS_Customer_Part_Revision__c,HWS_Site_ID__c,HWS_Failure_Description_Server_ID__c,HWS_Site_Information__c,HWS_Stockable_Product__r.HWS_Serial_Number_Traceable__c,HWS_Quantity__c,RecordTypeId,
			 HWS_SPS_Order_No__c,HWS_Contract_Line_Item__r.CH_ServiceType__c,HWS_Delivery_TimeZone__c, HWS_ServiceType__c
			 FROM Cases
			 WHERE Status!='Cancelled')
			FROM Case
			WHERE id = :parentCaseId];
		HWS_ParentCase_WRAPPER parentCase ;
		if(caserec.Cases.size() > 0)
		{
			parentCase = new HWS_ParentCase_WRAPPER(caserec,caserec.Cases[0].NCP_Service_Contract__r.CH_ERPSystem__c,caserec.Cases[0].HWS_Contract_Line_Item__r.CH_ServiceType__c);
			for(Case childCaseRec: caserec.Cases){
	parentCase.Requestitems.add(new HWS_ChildCases_WRAPPER(childCaseRec));
			}
		}	
		String jsonString = JSON.serialize(parentCase,true);
		SOORequestBody obj=new SOORequestBody();
		obj.jsonPayload=jsonString;
		obj.caseNumber=caserec.CaseNumber;
		return obj;
	}
	public class SOORequestBody{
		public String jsonPayload;
		public String caseNumber;	 
	}
}