src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Azores</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius And Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia And Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Account_Number__c</fullName>
        <formula>If(BEGINS(AccountNumber,&apos;1&apos;  ), AccountNumber ,
If(BEGINS(Parent.AccountNumber,&apos;1&apos;  ), Parent.AccountNumber ,&apos;Unknown&apos;))</formula>
        <label>Legal Entity Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Market North America</fullName>
                </value>
                <value>
                    <fullName>Market Latin America</fullName>
                </value>
                <value>
                    <fullName>Market Middle East and Africa</fullName>
                </value>
                <value>
                    <fullName>Market India</fullName>
                </value>
                <value>
                    <fullName>Market Greater China</fullName>
                </value>
                <value>
                    <fullName>Market Europe</fullName>
                </value>
                <value>
                    <fullName>Market Asia Pacific &amp; Japan</fullName>
                </value>
                <value>
                    <fullName>Market Other</fullName>
                </value>
                <value>
                    <fullName>Market NFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Req #1313. Required for Marketo Sync</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Req #1313. Required for Marketo Sync</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MARKET NORTH AMERICA</fullName>
                </value>
                <value>
                    <fullName>MARKET EUROPE</fullName>
                </value>
                <value>
                    <fullName>MARKET GREATER CHINA</fullName>
                </value>
                <value>
                    <fullName>MARKET INDIA</fullName>
                </value>
                <value>
                    <fullName>MARKET LATIN AMERICA</fullName>
                </value>
                <value>
                    <fullName>MARKET MIDDLE EAST AND AFRICA</fullName>
                </value>
                <value>
                    <fullName>MARKET ASIA PACIFIC &amp; JAPAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ISO_Country_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Country_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Country Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ISO Country Codes</label>
</CustomObject>

src/objects/NCP_CustomerCommunitySetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>DO NOT UPDATE NAME FIELD</description>
    <fields>
        <fullName>Customer_Account_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Account Number</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Account</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_User_Profile__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer User Profile</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Customer Community Setting</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>Market field Built for requirement - 615. Dependent on Country field</description>
        <label>User Market</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Market North America</fullName>
                </value>
                <value>
                    <fullName>Market Latin America</fullName>
                </value>
                <value>
                    <fullName>Market Middle East and Africa</fullName>
                </value>
                <value>
                    <fullName>Market India</fullName>
                </value>
                <value>
                    <fullName>Market Greater China</fullName>
                </value>
                <value>
                    <fullName>Market Europe</fullName>
                </value>
                <value>
                    <fullName>Market Asia Pacific &amp; Japan</fullName>
                </value>
                <value>
                    <fullName>MARKET AMERICA</fullName>
                    <isActive>false</isActive>
                    <label>MARKET AMERICA</label>
                </value>
                <value>
                    <fullName>MARKET ASIA AND JAPAN</fullName>
                    <isActive>false</isActive>
                    <label>MARKET ASIA AND JAPAN</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NSA_Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox to check whether the user is NSA Compliant or not.</description>
        <label>NSA Compliant</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DynamicToolDisplayTest.cls
/* ----------------------------------------------------------------------------------------------------------------------------------------------------------
Name:			DynamicToolDisplay Test 
Description:	 DynamicToolDispla class to get tool assigned to current user
Date		Version	  Author		Summary of Changes 
-----------	  ----------	  -----------------	---------------------------------------------------------------------------------------------------
10/08/2017	  1.0		Supriyam			get tool assigned to current user
----------------------------------------------------------------------------------------------------------------------------------------------------------*/
@istest
public class DynamicToolDisplayTest {
	 @testSetup static void createTestData() {
			NCP_CustomerCommunitySetting__c cs = new NCP_CustomerCommunitySetting__c();
			cs.Name = 'Default';
			cs.Customer_Account__c = 'Customer - test';
			cs.Customer_Account_Number__c = '12345';
			cs.Customer_User_Profile__c = 'Customers';
			insert cs;
		}
	 public static testmethod void testTool(){
		List<user> runAsUSer = new List<user>();
		runAsUSer = TestDataFactory.userCreation(2,'System Administrator');
		runAsUSer[0].UserRoleId  = system.Label.Global_Role_ID;
		runAsUSer[0].NSA_Compliant__c = true;
		database.insert(runAsUSer);
		system.runAs(runAsUSer[0]){
		 List<Account> acc=TestDataFactory.createAccount(1);
		acc[0].AccountNumber = '00001234'; 
		acc[0].Market__c='Market North America'; 
		database.insert(acc);
		List<User> userList = new List<User>(); 
		
		String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
		Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
		String uniqueName =   dateString + randomInt; 
		 
		ISO_Country_Codes__c cc=new ISO_Country_Codes__c();
		 cc.Country_Name__c='United States Of America';
		 cc.Market__c='Market North America';
		 cc.Name='US';
	insert cc;
		contact con =new contact();
		con.LastName='test';
		con.AccountId=acc[0].id;
		con.MailingCountry = cc.Country_Name__c;
		con.MailingCountrycode= cc.Name;
		con.Market__c = cc.Market__c; 
		insert con;
		
		User userPRM = new User(alias = 'bpprm', email = uniqueName + '@nokia.com' /*+ orgId '.org' */, emailencodingkey = 'UTF-8', firstName = 'test', lastname = 'Testing', languagelocalekey = 'en_US', 
		localesidkey = 'en_US', profileid = system.Label.PRM_Profile_Id,  Country__c= 'Canada',Market__c='MARKET NORTH AMERICA', timezonesidkey = 'America/Los_Angeles', 
		Username = uniqueName + '@nokia.com' , Restriction_Level__c = 'Confidential', ContactId  = con.Id);
		userList.add(userPRM);
		Database.insert(userList[0]);
		 
		LIST<Additional_Resource_Request__c> dynamicTool=new LIST<Additional_Resource_Request__c>();
		Additional_Resource_Request__c addTool=new Additional_Resource_Request__c();
		addTool.Additional_Resource__c= 'SFDC PRM Access';
		addTool.Request_Status__c='Request';
		addTool.Partner_Contact__c=con.Id;
		addTool.Access_Level__c='Viewer';
		addTool.Partner_User__c=userinfo.getUserID();
		
		Additional_Resource_Request__c addTool2=new Additional_Resource_Request__c();
		addTool2.Additional_Resource__c= 'Co-op';
		addTool2.Request_Status__c='Request';
		addTool2.Partner_Contact__c=con.Id;
		addTool2.Access_Level__c='Viewer';
		addTool2.Partner_User__c=userinfo.getUserID();
		 
		Additional_Resource_Request__c addTool3=new Additional_Resource_Request__c();
		addTool3.Additional_Resource__c= 'Deal Registration';
		addTool3.Request_Status__c='Request';
		addTool3.Partner_Contact__c=con.Id;
		addTool3.Partner_User__c=userinfo.getUserID();
		addTool3.Access_Level__c='Viewer';
		
		 //insert addTool;
		 //insert addTool2;
		 //insert addTool3;
		 
		dynamicTool.add(addTool);
		dynamicTool.add(addTool2);
		dynamicTool.add(addTool3);
		insert dynamicTool;
		DynamicToolDisplay.getDynamicTool();
		}		
	 }
		@isTest static void leadTest2() {
	
		try {
			
		
			DynamicToolDisplay.getDynamicTool();
		} catch(DMLException e) {
			system.assertEquals(e.getMessage(), e.getMessage());
		}
		
		DynamicToolDisplay.getDynamicTool();
	}
	@isTest static void leadTest3() {
		LIST<Additional_Resource_Request__c> dynamicTool = new LIST<Additional_Resource_Request__c>();
		try {
			DynamicToolDisplay.getDynamicToolURL();
		} catch(DMLException e) {
			system.assertEquals(e.getMessage(), e.getMessage());
		}
		
		DynamicToolDisplay.getDynamicToolURL();
	}
}