src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Acc_No__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Account number-field as a copy of the AccountNumber-field to be used as external identifier in the integrations of related systems looking up account data in Salesforce. Projects involved: Case Handling and Support Portal.
Initially 2017 only used for data migration upsert capability.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Acc No</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContractLineItem.object
<CustomObject>
    <fields>
        <fullName>ExternalPricebookEntryId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>External Pricebook Entry Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NCP_External_Contract_Line_Item_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Nokia Support Portal specific field.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Nokia Support Portal specific field.</inlineHelpText>
        <label>External Contract Line Item Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NCP_External_Status__c</fullName>
        <description>Nokia Support Portal specific field</description>
        <inlineHelpText>Nokia Support Portal specific field</inlineHelpText>
        <label>External Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interface_Log__c.object
<CustomObject>
    <description>This object will be used for Interface/error handling</description>
    <label>Interface Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interface Log	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interface Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NCP_Authorised_Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>NCP_External_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NCP_External_Status__c</fullName>
        <label>External Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Authorized Entitlement</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Authorised Entitlement  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Entitlements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/NCP_Product_Content__c.object
<CustomObject>
    <fields>
        <fullName>NCP_External_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>NCP External Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Content</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Product Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Content</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>NCP_Entitlement_Access_Type__c</fullName>
        <label>Entitlement Access Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NCP_Access_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NCP_External_Service_Contract_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Service Contract Id</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NCP_External_Status__c</fullName>
        <label>External Status SP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/NCP_Access_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AcSys Portal</fullName>
    </customValue>
    <customValue>
        <fullName>ASLM</fullName>
    </customValue>
    <customValue>
        <fullName>Assignment Details</fullName>
    </customValue>
    <customValue>
        <fullName>CARES</fullName>
    </customValue>
    <customValue>
        <fullName>ClicS</fullName>
    </customValue>
    <customValue>
        <fullName>Configurators (US Only)</fullName>
    </customValue>
    <customValue>
        <fullName>Cover</fullName>
    </customValue>
    <customValue>
        <fullName>CRONOS</fullName>
    </customValue>
    <customValue>
        <fullName>Doc Center</fullName>
    </customValue>
    <customValue>
        <fullName>EEPT</fullName>
    </customValue>
    <customValue>
        <fullName>External Catalog Administration (US Only)</fullName>
    </customValue>
    <customValue>
        <fullName>Help Desk</fullName>
    </customValue>
    <customValue>
        <fullName>HWS (BO Reporting)</fullName>
    </customValue>
    <customValue>
        <fullName>HWS (Track and Trace)</fullName>
    </customValue>
    <customValue>
        <fullName>Invoice Services (US Only)</fullName>
    </customValue>
    <customValue>
        <fullName>IPM</fullName>
    </customValue>
    <customValue>
        <fullName>ITSM</fullName>
    </customValue>
    <customValue>
        <fullName>KB Knowledge Articles</fullName>
    </customValue>
    <customValue>
        <fullName>LKDI</fullName>
    </customValue>
    <customValue>
        <fullName>Network Performance Monitoring Tool AGN</fullName>
    </customValue>
    <customValue>
        <fullName>Network Performance Monitoring Tool BHA</fullName>
    </customValue>
    <customValue>
        <fullName>Non Technical Competency</fullName>
    </customValue>
    <customValue>
        <fullName>NOP</fullName>
    </customValue>
    <customValue>
        <fullName>Offline Timesheet Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Online Timesheet Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Order and Invoice Status (Global)</fullName>
    </customValue>
    <customValue>
        <fullName>Order Entry</fullName>
    </customValue>
    <customValue>
        <fullName>Order Entry Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Portal</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Data</fullName>
    </customValue>
    <masterLabel>Access Types</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/NCP_InterfaceLogFromIpaaS_WS_Test.cls
/**
 * Created by bkandov on 2019-07-01.
 */
@isTest
public class NCP_InterfaceLogFromIpaaS_WS_Test {

	@testSetup static void setup() {

		Account acc = NCP_TestFactory.createAccount();
		Account acc2 = NCP_TestFactory.createLegalAccount(acc.Id);
		Contact con = NCP_TestFactory.createContact(acc);
		ServiceContract scCDB = NCP_TestFactory.createServiceContract(acc2, NCP_Constants.TYPE_CARES);
		ServiceContract sccCDB = NCP_TestFactory.createChildServiceContract(acc2, scCDB, 'ClicS', NCP_Constants.RELATIONSHIP_P, true, false);
		List<ServiceContract> serviceContractsToInsert = new List<ServiceContract>();
		serviceContractsToInsert.add(sccCDB);

		insert serviceContractsToInsert;

		NCP_Authorised_Entitlement__c ae = NCP_TestFactory.createAuthorisedEntitlement(con, scCDB);

		Product2 pr = NCP_TestFactory.createProduct();
		NCP_Product_Content__c pc = NCP_TestFactory.createProductService(pr.Id, 'Discovery Center (Skylab)');
		contractLineItem cli = NCP_TestFactory.createContractLineItem(pr, scCDB);
	}

	@isTest
	static void testLogServiceContractFromIpaaS() {

		Id customerRecordTypeId = NCP_Utils.getObjectRecordTypeId('Account', NCP_Constants.ACCOUNT_RT_DEVNAME_CUSTOMER);
		Account acc = [SELECT Id FROM Account WHERE RecordTypeId = :customerRecordTypeId LIMIT 1];

		Id legalRecordTypeId = NCP_Utils.getObjectRecordTypeId('Account', NCP_Constants.ACCOUNT_RT_DEVNAME_LEGALENTITY);
		Account acc2 = [SELECT Id FROM Account WHERE RecordTypeId = :legalRecordTypeId LIMIT 1];

		Contact con = [SELECT Id FROM Contact WHERE AccountId = :acc.Id];

		User u = NCP_TestFactory.createUser(true, 'AES Admin', con, 'test@nokia.com.dev');
		insert u;

		ServiceContract sccCDB = [SELECT Id,AccountId,RecordType.Name,Pricebook2.Name,NCP_External_Status__c FROM ServiceContract WHERE AccountId = :acc2.Id LIMIT 1] ;

		Test.startTest();

		String jobId = '12345';

		Map<String, String> headers = new Map<String, String>();
		headers.put('Content-Type', 'text/csv');
		NCP_SingleRequestMock fakeApiJobDetails = new NCP_SingleRequestMock(200,
				'Complete',
				'{"id":"1","object": "ServiceContract","operation":"insert","numberRecordsProcessed":1,"numberRecordsFailed":1}',
				headers);

		NCP_SingleRequestMock fakeSuccessCall = new NCP_SingleRequestMock(200,
				'Complete',
				'sf__Id,sf__Created,Account.Acc_No__c,NCP_Entitlement_Access_Type__c,NCP_External_Service_Contract_Id__c,NCP_External_Status__c,Name,ParentServiceContract.NCP_External_Service_Contract_Id__c,PriceBook2.Name,recordType.Name\n' + sccCDB.Id + ',' + false + ',' + sccCDB.AccountId + ',' + '' + ',' + '' + ',' + sccCDB.NCP_External_Status__c + ',' + '' + ',' + 203818 + ',' + sccCDB.Pricebook2.Name + ',' + sccCDB.RecordType.Name + '\n',
				headers);

		NCP_SingleRequestMock fakeErrorCall = new NCP_SingleRequestMock(200,
				'Complete',
				'sf__Id,sf__Created,Account.Acc_No__c,NCP_Entitlement_Access_Type__c,NCP_External_Service_Contract_Id__c,NCP_External_Status__c,Name,ParentServiceContract.NCP_External_Service_Contract_Id__c,PriceBook2.Name,recordType.Name\n' + sccCDB.Id + ',' + false + ',' + sccCDB.AccountId + ',' + '' + ',' + '' + ',' + sccCDB.NCP_External_Status__c + ',' + '' + ',' + 203818 + ',' + sccCDB.Pricebook2.Name + ',' + sccCDB.RecordType.Name + '\n',
				headers);

		String host = System.Url.getSalesforceBaseURL().toExternalForm();
		Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String, HttpCalloutMock>();
		endpoint2TestResp.put(host + '/services/data/v43.0/jobs/ingest/' + jobid, fakeApiJobDetails);
		endpoint2TestResp.put(host + '/services/data/v43.0/jobs/ingest/' + jobid + '/successfulResults/', fakeSuccessCall);
		endpoint2TestResp.put(host + '/services/data/v43.0/jobs/ingest/' + jobid + '/failedResults/', fakeErrorCall);
		HttpCalloutMock multiCalloutMock = new NCP_InterfaceLogFromIpaaS_WS_Mock(endpoint2TestResp);

		Test.setMock(HttpCalloutMock.class, multiCalloutMock);

		NCP_InterfaceLogFromIpaaS_WS.CreateInterfaceLogFromIpaaS(jobId);

		List<Interface_Log__c> allRecords = [SELECT Id FROM Interface_Log__c];
		System.debug('allRecords >> ' + allRecords);

		Test.stopTest();
	}

	@isTest
	static void testLogContractLineItemFromIpaaS() {

		Id customerRecordTypeId = NCP_Utils.getObjectRecordTypeId('Account', NCP_Constants.ACCOUNT_RT_DEVNAME_CUSTOMER);
		Account acc = [SELECT Id FROM Account WHERE RecordTypeId = :customerRecordTypeId LIMIT 1];

		Contact con = [SELECT Id FROM Contact WHERE AccountId = :acc.Id];

		User u = NCP_TestFactory.createUser(true, 'AES Admin', con, 'test@nokia.com.dev');
		insert u;

		contractLineItem cli = [SELECT Id,ExternalPricebookEntryId__c,NCP_External_Contract_Line_Item_Id__c FROM contractLineItem LIMIT 1] ;

		Test.startTest();

		String jobId = '12345';
		Map<String, String> headers = new Map<String, String>();
		headers.put('Content-Type', 'text/csv');
		NCP_SingleRequestMock fakeApiJobDetails = new NCP_SingleRequestMock(200,
				'Complete',
				'{"id":"1","object": "contractLineItem","operation":"insert","numberRecordsProcessed":1,"numberRecordsFailed":1}',
				headers);

		NCP_SingleRequestMock fakeSuccessCall = new NCP_SingleRequestMock(200,
				'Complete',
				'ExternalPricebookEntryId__c,NCP_External_Contract_Line_Item_Id__c\n' + cli.ExternalPricebookEntryId__c + ',' + cli.NCP_External_Contract_Line_Item_Id__c + '\n',
				headers);

		NCP_SingleRequestMock fakeErrorCall = new NCP_SingleRequestMock(200,
				'Complete',
				'ExternalPricebookEntryId__c,NCP_External_Contract_Line_Item_Id__c\n' + cli.ExternalPricebookEntryId__c + ',' + cli.NCP_External_Contract_Line_Item_Id__c + '\n',
				headers);

		String host = System.Url.getSalesforceBaseURL().toExternalForm();
		Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String, HttpCalloutMock>();
		endpoint2TestResp.put(host + '/services/data/v43.0/jobs/ingest/' + jobid, fakeApiJobDetails);
		endpoint2TestResp.put(host + '/services/data/v43.0/jobs/ingest/' + jobid + '/successfulResults/', fakeSuccessCall);
		endpoint2TestResp.put(host + '/services/data/v43.0/jobs/ingest/' + jobid + '/failedResults/', fakeErrorCall);
		HttpCalloutMock multiCalloutMock = new NCP_InterfaceLogFromIpaaS_WS_Mock(endpoint2TestResp);

		Test.setMock(HttpCalloutMock.class, multiCalloutMock);

		NCP_InterfaceLogFromIpaaS_WS.CreateInterfaceLogFromIpaaS(jobId);

		List<Interface_Log__c> allRecords = [SELECT Id FROM Interface_Log__c];
		System.debug('allRecords >> ' + allRecords);

		Test.stopTest();
	}

	@isTest
	static void testAuthorisedEntitlementFromIpaaS() {

		Id customerRecordTypeId = NCP_Utils.getObjectRecordTypeId('Account', NCP_Constants.ACCOUNT_RT_DEVNAME_CUSTOMER);
		Account acc = [SELECT Id FROM Account WHERE RecordTypeId = :customerRecordTypeId LIMIT 1];

		Contact con = [SELECT Id FROM Contact WHERE AccountId = :acc.Id];

		User u = NCP_TestFactory.createUser(true, 'AES Admin', con, 'test@nokia.com.dev');
		insert u;

		NCP_Authorised_Entitlement__c ae = [SELECT Id,NCP_External_Id__c FROM NCP_Authorised_Entitlement__c LIMIT 1] ;

		Test.startTest();

		String jobId = '12345';
		Map<String, String> headers = new Map<String, String>();
		headers.put('Content-Type', 'text/csv');
		NCP_SingleRequestMock fakeApiJobDetails = new NCP_SingleRequestMock(200,
				'Complete',
				'{"id":"1","object": "NCP_Authorised_Entitlement__c","operation":"insert","numberRecordsProcessed":1,"numberRecordsFailed":1}',
				headers);

		NCP_SingleRequestMock fakeSuccessCall = new NCP_SingleRequestMock(200,
				'Complete',
				'NCP_External_Id__c\n' + ae.NCP_External_Id__c + '\n',
				headers);

		NCP_SingleRequestMock fakeErrorCall = new NCP_SingleRequestMock(200,
				'Complete',
				'NCP_External_Id__c\n' + ae.NCP_External_Id__c + '\n',
				headers);

		String host = System.Url.getSalesforceBaseURL().toExternalForm();
		Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String, HttpCalloutMock>();
		endpoint2TestResp.put(host + '/services/data/v43.0/jobs/ingest/' + jobid, fakeApiJobDetails);
		endpoint2TestResp.put(host + '/services/data/v43.0/jobs/ingest/' + jobid + '/successfulResults/', fakeSuccessCall);
		endpoint2TestResp.put(host + '/services/data/v43.0/jobs/ingest/' + jobid + '/failedResults/', fakeErrorCall);
		HttpCalloutMock multiCalloutMock = new NCP_InterfaceLogFromIpaaS_WS_Mock(endpoint2TestResp);

		Test.setMock(HttpCalloutMock.class, multiCalloutMock);

		NCP_InterfaceLogFromIpaaS_WS.CreateInterfaceLogFromIpaaS(jobId);

		List<Interface_Log__c> allRecords = [SELECT Id FROM Interface_Log__c];
		System.debug('allRecords >> ' + allRecords);

		Test.stopTest();
	}
	
	@isTest
	static void testInsertInterfaceLog() {

		Boolean abc = true;
		Test.startTest();
		
		try{
			NCP_InterfaceLog.insertInterfaceLog('CDB Parent Service Contract','Inbound', 'upsert', 'CDB Parent Service Contract', 'Success', 'Success', 'data');
			NCP_InterfaceLog.createInterfaceLog('CDB Parent Service Contract', 'Inbound', 'upsert', 'CDB Parent Service Contract', 'Success', 'Success', 'data');
		}catch(Exception e1){
		 	System.assertEquals(abc,true);   
		}
		System.assertEquals(abc,true);


		Test.stopTest();
	}


}