src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Legal_Entity</fullName>
        <active>true</active>
        <description>Legal Entity is for Nokia Internal Accounts</description>
        <label>Legal Entity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Record Type for all those Accounts which will get created in Salesforce. Not via Inegration</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CH_ContactType__c</fullName>
        <description>Contact Type Ref: 4989</description>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                    <default>true</default>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
                <value>
                    <fullName>Nokia Employee</fullName>
                </value>
                <value>
                    <fullName>Sub-Contractor</fullName>
                </value>
                <value>
                    <fullName>No Relationship</fullName>
                </value>
                <value>
                    <fullName>Secondary Account</fullName>
                </value>
                <value>
                    <fullName>Communication Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>NCP_Nokia_Product_Id__c</fullName>
        <description>Internal Nokia Product Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Nokia Product Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Relation__c.object
<CustomObject>
    <description>This object contains the relationship details of PI, SI and PCI</description>
    <label>Product Relation</label>
    <nameField>
        <displayFormat>PR-{000000000}</displayFormat>
        <label>Product Relations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CH_ProductUtils_Test.cls
/** 
* About 
* ----- 
* @Description	  : Case Handling Product Object Utility Test Class.
* @Project		  : Case Handling.
* @Modification Log : 
*  Created  : 2020 01 31 – tiago.almeida@nokia.com
* ----- 
**/
@isTest
private class CH_ProductUtils_Test {
	private static List<Product2> oProduct2List;
	
	@testSetup	
	static void setupTestData() {
		List<Account> oProspectList = TestDataFactory.createAccount('Prospect', 1, null);
		insert oProspectList;
		//
		Account oLegalEntity = TestDataFactory.createAccount('Legal_Entity', 1, oProspectList.get(0).Id).get(0);
		insert oLegalEntity;
		//
		Contact oContact = TestDataFactory.createContact(1, oProspectList.get(0)).get(0);
		oContact.LastName = 'Test LastName';
		oContact.CH_ContactType__c = 'customer';
		insert oContact;
		//
		oProduct2List = TestDataFactory.createProduct(2);
		insert oProduct2List;
		//
		List<Product_Relation__c> oProductRelation = TestDataFactory.createProductRelation(1, oProduct2List.get(0), oProduct2List.get(1));
		insert oProductRelation;
	}
	
	public static testMethod void test() {
		setupTestData();
		//
		test.startTest();
		try{
			CH_ProductUtils.searchProducts('Test');
			CH_ProductUtils.searchProductRelated('solution', 'product', oProduct2List.get(0).NCP_Nokia_Product_Id__c);
			CH_ProductUtils.searchProductRelated('productVariant', 'product', oProduct2List.get(0).NCP_Nokia_Product_Id__c);
			CH_ProductUtils.searchProductRelated('productModule', 'product', oProduct2List.get(0).NCP_Nokia_Product_Id__c);
			CH_ProductUtils.searchProductRelated('productRelease', 'product', oProduct2List.get(0).NCP_Nokia_Product_Id__c);
			CH_ProductUtils.searchProductRelated('swComponent', 'product', oProduct2List.get(0).NCP_Nokia_Product_Id__c);
			CH_ProductUtils.searchProductRelated('swModule', 'product', oProduct2List.get(0).NCP_Nokia_Product_Id__c);
			CH_ProductUtils.searchProductRelated('hwComponent', 'product', oProduct2List.get(0).NCP_Nokia_Product_Id__c);
			CH_ProductUtils.searchProductRelated('swRelease', 'product', oProduct2List.get(0).NCP_Nokia_Product_Id__c);
			CH_ProductUtils.searchProductRelated('swBuild', 'product', oProduct2List.get(0).NCP_Nokia_Product_Id__c);
		} catch(Exception e) {
			System.debug('The following exception has occurred: ' + e.getMessage());
		}
		test.stopTest();
	}
}