src/objects/Accreditation__c.object
<CustomObject>
    <description>To be able to maintain Partner&apos;s Accreditation Information</description>
    <fields>
        <fullName>Active_Contract_Types__c</fullName>
        <label>Active Contract Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NIRA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PPA-DIS</fullName>
                </value>
                <value>
                    <fullName>PPA-RES</fullName>
                </value>
                <value>
                    <fullName>Federal Government Agreement</fullName>
                </value>
                <value>
                    <fullName>Services Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>Reseller - (FALU)</fullName>
                </value>
                <value>
                    <fullName>Reseller - (FNOK)</fullName>
                </value>
                <value>
                    <fullName>PMA-NBOS</fullName>
                </value>
                <value>
                    <fullName>PMA-NBOS (Non-PPA Services Partner)</fullName>
                </value>
                <value>
                    <fullName>US Distributor - Legacy</fullName>
                </value>
                <value>
                    <fullName>PMA-Co-Branded</fullName>
                </value>
                <value>
                    <fullName>DMA-Co-Branded</fullName>
                </value>
                <value>
                    <fullName>DMA-Co-Branded (non PPA Distributor)</fullName>
                </value>
                <value>
                    <fullName>DMA-NBOS</fullName>
                </value>
                <value>
                    <fullName>DMA-NBOS (Non PPA Distributor)</fullName>
                </value>
                <value>
                    <fullName>Letter of Resale Authorization</fullName>
                </value>
                <value>
                    <fullName>Managed Services Amendment to SSA/MSA</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>PMA-Co-Branded (Non PPA Services Partner)</fullName>
                </value>
                <value>
                    <fullName>CPA-RES</fullName>
                </value>
                <value>
                    <fullName>CPA-DIS</fullName>
                </value>
                <value>
                    <fullName>CPA-DIS family</fullName>
                    <isActive>false</isActive>
                    <label>CPA-DIS family</label>
                </value>
                <value>
                    <fullName>CPA-RES family</fullName>
                    <isActive>false</isActive>
                    <label>CPA-RES family</label>
                </value>
                <value>
                    <fullName>PPA-DIS family</fullName>
                    <isActive>false</isActive>
                    <label>PPA-DIS family</label>
                </value>
                <value>
                    <fullName>PPA-RES family</fullName>
                    <isActive>false</isActive>
                    <label>PPA-RES family</label>
                </value>
                <value>
                    <fullName>Reseller Agreements</fullName>
                    <isActive>false</isActive>
                    <label>Reseller Agreements</label>
                </value>
                <value>
                    <fullName>SPaaP- Managed Services</fullName>
                    <isActive>false</isActive>
                    <label>SPaaP- Managed Services</label>
                </value>
                <value>
                    <fullName>SPaaP-Hybrid</fullName>
                    <isActive>false</isActive>
                    <label>SPaaP-Hybrid</label>
                </value>
                <value>
                    <fullName>SPaaP-Reseller</fullName>
                    <isActive>false</isActive>
                    <label>SPaaP-Reseller</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Evaluated_Accreditation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Evaluate Accreditation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accreditation and Pricing</relationshipLabel>
        <relationshipName>Accreditations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Accreditation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Accreditation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accreditations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Accreditation Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>DMA-Co-Branded</fullName>
                </value>
                <value>
                    <fullName>DMA-Co-Branded (non PPA Distributor)</fullName>
                </value>
                <value>
                    <fullName>DMA-NBOS</fullName>
                </value>
                <value>
                    <fullName>DMA-NBOS (Non PPA Distributor)</fullName>
                </value>
                <value>
                    <fullName>Federal Government Agreement</fullName>
                </value>
                <value>
                    <fullName>Letter of Resale Authorization</fullName>
                </value>
                <value>
                    <fullName>Managed Services Amendment to SSA/MSA</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>NDAC Standalone RES</fullName>
                </value>
                <value>
                    <fullName>NIRA</fullName>
                </value>
                <value>
                    <fullName>Partner Locator Consent</fullName>
                </value>
                <value>
                    <fullName>PMA-Co-Branded (Non PPA Services Partner)</fullName>
                </value>
                <value>
                    <fullName>PMA-NBOS</fullName>
                </value>
                <value>
                    <fullName>PMA-NBOS (Non-PPA Services Partner)</fullName>
                </value>
                <value>
                    <fullName>PMA-Co-Branded</fullName>
                </value>
                <value>
                    <fullName>PPA-DIS</fullName>
                </value>
                <value>
                    <fullName>PPA-RES</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>CPA-RES</fullName>
                </value>
                <value>
                    <fullName>CPA-DIS</fullName>
                </value>
                <value>
                    <fullName>US Distributor - Legacy</fullName>
                </value>
                <value>
                    <fullName>Reseller - (FNOK)</fullName>
                </value>
                <value>
                    <fullName>Reseller - (FALU)</fullName>
                </value>
                <value>
                    <fullName>Services Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>PFA</fullName>
                </value>
                <value>
                    <fullName>PFA-RES</fullName>
                </value>
                <value>
                    <fullName>PFA-DIS</fullName>
                </value>
                <value>
                    <fullName>CPA-DIS family</fullName>
                    <isActive>false</isActive>
                    <label>CPA-DIS family</label>
                </value>
                <value>
                    <fullName>CPA-RES family</fullName>
                    <isActive>false</isActive>
                    <label>CPA-RES family</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContractHelper.cls
/****************************************
 * Class Name : ContractHelper
 * Created Date: June 2018
 * Created By : Accenture
 * Last Modified by: Accenture
 * Last Modified Date: 
 * Description : Contract Helper
			  
 * Test Class: 
 *****************************************/
public without sharing class ContractHelper {

	/********************
	*Method Name: UpdatedAccountfforACcreditation level update
	*Parameter: 
	*Description: 
	*******************/
	public static void updateAccNAccreditation(list<Contract> newcontract){
		try{
			system.debug('newcontract  .....'+ newcontract);
			list<Account> accToUpdate = new list<Account>();
			list<string> accredContractType = new list<String>();
			map<id, String> accContract = new map<id, String>();
			map<id, list<String>> accActiveContract = new map<id, list<String>>();
			map<id, list<String>> accExpiredContract = new map<id, list<String>>();
			list<Accreditation__c> accredToUpdate = new list<Accreditation__c>();
			set<ID> accId = new set<ID>();
		   // set<ID> activeContract = new set<ID>();
		   // set<ID> ExpiredContract = new set<ID>();
			set<ID> activeContractAcc = new set<ID>();
			set<ID> expiredContractAcc = new set<ID>();
			
			for(Contract Contr : newcontract){
				system.debug('In contract loop : '+ Contr.name );
				accId.add(Contr.AccountID);
				accContract.put(Contr.AccountID, Contr.Contract_Type__c);
				if(Contr.Contract_Status__c == PRMGlobalConstants.EXPIRED){
				   
					list<String> expireCont = new list<String>();
					if(accExpiredContract.containsKey(Contr.AccountID)){
					expireCont = accExpiredContract.get(Contr.AccountID);
					}
					expireCont.add(Contr.Contract_Type__c);
					accExpiredContract.put(Contr.AccountID,expireCont);
					expiredContractAcc.add(Contr.accountid);
				}
				else if(Contr.Contract_Status__c == PRMGlobalConstants.ActiveSt){
				 
					list<String> activeCont = new list<String>();
					if(accActiveContract.containsKey(Contr.AccountID)){
					activeCont = accActiveContract.get(Contr.AccountID);
					}
					activeCont.add(Contr.Contract_Type__c);
					accActiveContract.put(Contr.AccountID,activeCont);
					activeContractAcc.add(Contr.accountid);
				}
				else{
					//
				}
				
			}
			
			system.debug('expiredContractAcc  .....'+ expiredContractAcc);
			system.debug('accExpiredContract  .....'+ accExpiredContract);
			
			for(Accreditation__c accred : [select id, name, Evaluated_Accreditation__c, Partner__c, Active_Contract_Types__c 
			from Accreditation__c where Partner__c in: accId Limit : (Limits.getLimitQueryRows()-Limits.getQueryRows())]){
			   system.debug(' in loop accred  .....'+ accred.name);
			  
				 if(accActiveContract.containsKey(accred.Partner__c)){
					String strAccredContractType = String.valueof(accred.get(PRMGlobalConstants.ContractActive));
					if(strAccredContractType != Null){
					   accredContractType = strAccredContractType.split(PRMGlobalConstants.SemiColon);
					   
					   accredContractType.addall(accActiveContract.get(accred.Partner__c));
					   string newContactType = string.join(accredContractType,PRMGlobalConstants.SemiColon);
					   accred.Active_Contract_Types__c = newContactType;
						}
					else{
					   if(accActiveContract.get(accred.Partner__c).size() > 1){
						   string newContactType = string.join(accActiveContract.get(accred.Partner__c),PRMGlobalConstants.SemiColon);
						   accred.Active_Contract_Types__c = newContactType;
					   }
					   else{
					   accred.Active_Contract_Types__c = accContract.get(accred.Partner__c);
					   }
				   }
				 
			   }
			  
			   if(accExpiredContract.containsKey(accred.Partner__c)){
					   system.debug(' Active contract type  .....'+ String.valueof(accred.get(PRMGlobalConstants.ContractActive)));
					   String strAccredContractType = String.valueof(accred.get(PRMGlobalConstants.ContractActive));
					   if(strAccredContractType != null){
						   accredContractType = strAccredContractType.split(PRMGlobalConstants.SemiColon);
						   list<string> expContactType = accExpiredContract.get(accred.Partner__c); 
						   
							if(!accredContractType.isempty() && accredContractType.size()>1){
								for(string expConttype : expContactType){
									 integer i=0;
									for(String ContType : accredContractType){
										
										if(ContType == expConttype){
											break;
										}
										i=i++;
									}
								accredContractType.remove(i);
								}
						  
							system.debug('accredContractType  .....'+ accredContractType);
							string newContactType = string.join(accredContractType,PRMGlobalConstants.SemiColon);
							accred.Active_Contract_Types__c = newContactType;
							
								}
						
					   /*
						if(!accredContractType.isempty() && accredContractType.size()>1){
							for(String ContType : accredContractType){
								
								if(ContType == accContract.get(accred.Partner__c)){
									break;
								}
								i=i++;
							}
							accredContractType.remove(i);
							string newContactType = string.join(accredContractType,';');
							accred.Active_Contract_Types__c = newContactType;
						
						
						}  */
						
						
							else {
								accred.Active_Contract_Types__c = null;
							} 
					   }
					
					}
					system.debug('Active_Contract_Types__c ...... '+ accred.Active_Contract_Types__c);
					accred.Evaluated_Accreditation__c = true;
					accredToUpdate.add(accred);
			   }   
			system.debug('accredToUpdate ...... '+ accredToUpdate);
			Database.update(accredToUpdate, false);
			
		
		}catch(Exception e){
			ExceptionHandler.addException(e,PRMGlobalConstants.ContractHelper ,PRMGlobalConstants.ContractHelper);
		}
	}
}