src/objects/Apttus_Config2__ConfigCustomDisplayActions__c.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__ActionLabelName__c</fullName>
        <description>The name of the custom label for the action.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The name of the custom label for the action.</inlineHelpText>
        <label>Action Label Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio__c</fullName>
        <description>Req 6624: Constraint Rule Optimization By Removing Formula Fields an covert them in text fields</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>NokiaCPQ_Is_Maintenance_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Maintenance Only Quotes all product prices are displayed as 0.00.</inlineHelpText>
        <label>Maintenance Only Quote?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio__c</fullName>
        <label>Portfolio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Airscale Wifi</fullName>
                </value>
                <value>
                    <fullName>Fixed Access - FBA</fullName>
                    <label>Broadband Access Networks</label>
                </value>
                <value>
                    <fullName>Fixed Network</fullName>
                </value>
                <value>
                    <fullName>Fixed Networks</fullName>
                </value>
                <value>
                    <fullName>FastMile</fullName>
                    <label>Fixed Wireless Access</label>
                </value>
                <value>
                    <fullName>Global Services</fullName>
                </value>
                <value>
                    <fullName>IP Routing</fullName>
                </value>
                <value>
                    <fullName>Microwave</fullName>
                </value>
                <value>
                    <fullName>Modular Private Wireless Solution</fullName>
                </value>
                <value>
                    <fullName>Nokia Software</fullName>
                </value>
                <value>
                    <fullName>Nuage</fullName>
                </value>
                <value>
                    <fullName>Fixed Access - POL</fullName>
                    <label>Optical LAN</label>
                </value>
                <value>
                    <fullName>Optics</fullName>
                </value>
                <value>
                    <fullName>Optics - WaveLite</fullName>
                </value>
                <value>
                    <fullName>QTC</fullName>
                </value>
                <value>
                    <fullName>Wireless PON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NokiaCPQ_DisplayActionCallback.cls
global with sharing class NokiaCPQ_DisplayActionCallback implements Apttus_Config2.CustomClass.IDisplayActionCallback{

	global static void start(Apttus_Config2.ProductConfiguration cart, List<Apttus_Config2.DisplayActionInfo> disActionInfoList){		 

		//system.debug('***DisplayActionCallback > start() > DisActList: '+disActionInfoList + ' <> cart:' + cart);
		
		Apttus_Config2__ProductConfiguration__c standardConfig = cart.getConfigSO();
		
		Apttus_Proposal__Proposal__c maintenanceQuote = [Select id,NokiaCPQ_Is_Maintenance_Quote__c,NokiaCPQ_Portfolio__c from Apttus_Proposal__Proposal__c where id =:standardConfig.Apttus_QPConfig__Proposald__c];
		//system.debug('maintenanceQuote -->'+maintenanceQuote);
		if(maintenanceQuote.NokiaCPQ_Is_Maintenance_Quote__c == True) {
		
			for(Apttus_Config2.DisplayActionInfo actionInfoInst : disActionInfoList){
			   
				Apttus_Config2__ConfigCustomDisplayActions__c ActionSOInst = actionInfoInst.ActionSO;
				
				String actionName = ActionSOInst.Apttus_Config2__ActionLabelName__c;
				//system.debug('***DisplayActionCallback > Action Name: ' + actionName);
	
				//system.debug('***DisplayActionCallback > Before: ' + ActionSOInst.Apttus_Config2__ActionLabelName__c + ' <> ' + actionInfoInst.IsEnabled + ' <> ' +  actionInfoInst.ActionSO.Apttus_Config2__IsEnabled__c);
	

				if(actionName.equals('AddMoreProducts')) {
					// MAKE ACTION INVISIBLE!!!
					actionInfoInst.IsEnabled = false;
					actionInfoInst.ActionSO.Apttus_Config2__IsEnabled__c= false;
				}
			   
				//system.debug('***DisplayActionCallback > After: ' + ActionSOInst.Apttus_Config2__ActionLabelName__c + ' <> ' + actionInfoInst.IsEnabled + ' <> ' +  actionInfoInst.ActionSO.Apttus_Config2__IsEnabled__c);
	
			 }
		 }
		 
		 if(maintenanceQuote.NokiaCPQ_Portfolio__c != Nokia_CPQ_Constants.IP_ROUTING_STRING) {
		
			for(Apttus_Config2.DisplayActionInfo actionInfoInst : disActionInfoList){
			   
				Apttus_Config2__ConfigCustomDisplayActions__c ActionSOInst = actionInfoInst.ActionSO;
				String gppActionName = ActionSOInst.Apttus_Config2__ActionLabelName__c;
				if(gppActionName.equals('GPPPricing')) {
					// MAKE ACTION INVISIBLE!!!
					actionInfoInst.IsEnabled = false;
					actionInfoInst.ActionSO.Apttus_Config2__IsEnabled__c= false;
				}
			 }
		 }
	}
	
	
	global static void setActionProperties(Apttus_Config2.CustomClass.ActionParams actionParam){
		//System.debug('***DisplayActionCallback > setActionProperties() > actionParam: '+actionParam);
		  
	}
}