src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__ConfigurationId__c</fullName>
        <description>ID of the associated configuration</description>
        <label>Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Is_Maintenance_Quote__c</fullName>
        <formula>Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.NokiaCPQ_Is_Maintenance_Quote__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Maintenance Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_LEO_Discount__c</fullName>
        <formula>Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.NokiaCPQ_LEO_Discount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LEO Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Opportunity_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to assign site to the line item.</description>
        <label>Site</label>
        <referenceTo>NokiaCPQ_Site__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio__c</fullName>
        <formula>IF( Apttus_Config2__ConfigurationId__r.Quote_Type__c == &apos;Direct CPQ&apos;, Apttus_Config2__ProductId__r.Direct_Portfolio__c ,Apttus_Config2__ProductId__r.Portfolio__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <formula>Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Quote_Type__c</formula>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_Config2__BusinessObjectType__c</fullName>
        <description>The type of the business object associated with the configuration</description>
        <label>Business Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                    <default>true</default>
                    <label>Agreement</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Collaboration Request</fullName>
                </value>
                <value>
                    <fullName>Favorite Configuration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_IsMainSSPAdded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMainSSPAdded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio_From_Quote__c</fullName>
        <formula>TEXT(Apttus_QPConfig__Proposald__r.NokiaCPQ_Portfolio__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio From Quote</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio__c</fullName>
        <description>Req 6624: Constraint Rule Optimization By Removing Formula Fields an covert them in text fields</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Pricing_Cluster__c</fullName>
        <description>Req 6624: Constraint Rule Optimization By Removing Formula Fields an covert them in text fields</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Pricing Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Quote_Type__c</fullName>
        <description>Req 6624: Constraint Rule Optimization By Removing Formula Fields an covert them in text fields</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Quote Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCcountry__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PCcountry</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <formula>Apttus_QPConfig__Proposald__r.Quote_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_Filter_Leo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Search Filter Leo</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>End_Customer_Country_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Customer Country Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQPricing_Cluster__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Pricing Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Existing_IONMaint_Contract__c</fullName>
        <label>Existing Maintenance Contract?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>NokiaCPQ_Portfolio__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Is_Maintenance_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Maintenance Only Quotes all product prices are displayed as 0.00.</inlineHelpText>
        <label>Maintenance Only Quote?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_LEO_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lab Equipment Quote?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Maintenance_Level__c</fullName>
        <label>Maintenance Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_No_of_Years__c</fullName>
        <label>No. of Years for Maintenance</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>NokiaCPQ_Portfolio__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio__c</fullName>
        <label>Portfolio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Airscale Wifi</fullName>
                </value>
                <value>
                    <fullName>Fixed Access - FBA</fullName>
                    <label>Broadband Access Networks</label>
                </value>
                <value>
                    <fullName>Fixed Network</fullName>
                </value>
                <value>
                    <fullName>Fixed Networks</fullName>
                </value>
                <value>
                    <fullName>FastMile</fullName>
                    <label>Fixed Wireless Access</label>
                </value>
                <value>
                    <fullName>Global Services</fullName>
                </value>
                <value>
                    <fullName>IP Routing</fullName>
                </value>
                <value>
                    <fullName>Microwave</fullName>
                </value>
                <value>
                    <fullName>Modular Private Wireless Solution</fullName>
                </value>
                <value>
                    <fullName>Nokia Software</fullName>
                </value>
                <value>
                    <fullName>Nuage</fullName>
                </value>
                <value>
                    <fullName>Fixed Access - POL</fullName>
                    <label>Optical LAN</label>
                </value>
                <value>
                    <fullName>Optics</fullName>
                </value>
                <value>
                    <fullName>Optics - WaveLite</fullName>
                </value>
                <value>
                    <fullName>QTC</fullName>
                </value>
                <value>
                    <fullName>Wireless PON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <description>To differentiate CPQ quotes from SWX Quotes</description>
        <formula>IF( 
	Apttus_Proposal__Opportunity__c != null, 
	IF( 
		AND(
			OR( 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Direct Sales Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Read Only Direct&apos; 
			), 
			isCQ__c = false
		   ), 
		IF(
			OR( 
				RecordTypeId = $Label.DS_QuoteEditRecordTypeId,
				RecordTypeId = $Label.DS_QuoteReadRecordTypeId 
			) , 
			&apos;Direct DS&apos;, 
			IF(OR( RecordTypeId = $Label.NokiaCPQ_DirectQuoteID,RecordTypeId = $Label.NokiaCPQ_DirectReadOnlyQuoteID) , &apos;Direct CPQ&apos;, &apos;NCQ&apos;)
			), 
		IF( 
			AND(
			  OR( 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Indirect Sales Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Indirect Workspace Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Read Only Indirect&apos; 
			     ),
				isCQ__c = false
			), 
			IF(
				OR(
					RecordTypeId = $Label.DS_QuoteEditRecordTypeId , 
					RecordTypeId = $Label.DS_QuoteReadRecordTypeId), 
				&apos;Indirect DS&apos;, 
				&apos;Indirect CPQ&apos;
			   ), 
			IF(isCQ__c,&apos;CQ&apos;,&apos;&apos;) 
		) 
	), 
	&apos;&apos; 
)</formula>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProductConfigTriggerHelper.cls
/*******************************
Class Name: ProductConfigTriggerHelper
Created By: 
Last Modified By: 
Last Modified Date: 
Description: 
*******************************/
public class ProductConfigTriggerHelper{
	/*****************************
*Method Name: calculatePrice
*Description: 
*Parameters: 
*Created By: 
*Last Modified By: 
*Last Modified Date: 
*******************************/ 
	public static String calculatePrice(Decimal currencyField){		 
		system.debug('currencyField' + currencyField);
		String adjustedField = '';
		//if(currencyField != null && currencyField.setscale(2) >= 1){
		system.debug('>=1 ' +  String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.Two)));
		if(String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.Two)) != null && String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.Two)).indexOf(Nokia_CPQ_Constants.DOT ) == Nokia_CPQ_Constants.minusOne){
			adjustedField = String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.Two)) +  Nokia_CPQ_Constants.dotZero;
		}
		else if(String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.Two)) != null && String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.Two)).right(Nokia_CPQ_Constants.Two).contains(Nokia_CPQ_Constants.DOT)){
			adjustedField = String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.Two)) + Nokia_CPQ_Constants.ZERO ;
		}
		else if(String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.Two)) != null && String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.two)).right(Nokia_CPQ_Constants.Three).contains(Nokia_CPQ_Constants.DOT)){
			adjustedField = String.valueOf(currencyField.setscale(Nokia_CPQ_Constants.Two));
		}
		//}
		/*else if(currencyField != null && currencyField.setscale(2) < 1){
system.debug('<1 ' + String.valueOf(currencyField.setscale(2)));
if(String.valueOf(currencyField.setscale(2)) != null && String.valueOf(currencyField.setscale(2)).indexOf('.') == -1){
adjustedField = String.valueOf(currencyField.setscale(2)) + '.00';
}
else if(String.valueOf(currencyField.setscale(2)) != null && String.valueOf(currencyField.setscale(2)).right(2).contains('.')){
adjustedField = String.valueOf(currencyField.setscale(2)) + '0';
}
else if(String.valueOf(currencyField.setscale(2)) != null && String.valueOf(currencyField.setscale(2)).right(3).contains('.')){
adjustedField = String.valueOf(currencyField.setscale(2));
}
}*/
		return adjustedField;
	}
	
	/************************************
* Method :  updateFieldsOnProdConfig
* Paramater: List<Apttus_Config2__ProductConfiguration__c>
* Comments: Used to assign values to fields before creation of Product Configuration
* Created By: Piyush Tawari 26-09-2019 
* Nokia CPQ REQ:6624  
* ************************************/
	public static void updateFieldsOnProdConfig(List<Apttus_Config2__ProductConfiguration__c> prodConfigList)
	{
		Map<Id,Apttus_Proposal__Proposal__c> quoteMap = new Map<Id,Apttus_Proposal__Proposal__c>();
		Set<Id> quoteIdSet = new Set<Id>();
		try{
			if(!prodConfigList.isEmpty())
			{
				for(Apttus_Config2__ProductConfiguration__c config : prodConfigList)
				{
					if(String.isNotBlank(config.Apttus_QPConfig__Proposald__c))
						quoteIdSet.add(config.Apttus_QPConfig__Proposald__c);
				}
				if(quoteIdSet.size() > 0)
				{
					for(Apttus_Proposal__Proposal__c quote : [Select Id,End_Customer_Country_Code__c,NokiaCPQ_Portfolio__c,NokiaCPQ_Existing_IONMaint_Contract__c,NokiaCPQ_LEO_Discount__c,NokiaCPQPricing_Cluster__c,
															  Quote_Type__c,NokiaCPQ_Is_Maintenance_Quote__c,NokiaCPQ_Maintenance_Level__c,
															  NokiaCPQ_No_of_Years__c from Apttus_Proposal__Proposal__c 
															  where id in:quoteIdSet
															  LIMIT: Limits.getLimitQueryRows() - Limits.getQueryRows()])
					{
						quoteMap.put(quote.Id,quote);
					}
					
					for(Apttus_Config2__ProductConfiguration__c config : prodConfigList)
					{
						if(quoteMap.containsKey(config.Apttus_QPConfig__Proposald__c)){
							if(quoteMap.get(config.Apttus_QPConfig__Proposald__c).Quote_Type__c!= Null)
								config.NokiaCPQ_Quote_Type__c = quoteMap.get(config.Apttus_QPConfig__Proposald__c).Quote_Type__c;
							if(quoteMap.get(config.Apttus_QPConfig__Proposald__c).NokiaCPQ_Portfolio__c != Null)
								config.NokiaCPQ_Portfolio__c = quoteMap.get(config.Apttus_QPConfig__Proposald__c).NokiaCPQ_Portfolio__c;
							if(quoteMap.get(config.Apttus_QPConfig__Proposald__c).NokiaCPQPricing_Cluster__c != Null)
								config.NokiaCPQ_Pricing_Cluster__c = quoteMap.get(config.Apttus_QPConfig__Proposald__c).NokiaCPQPricing_Cluster__c;
								if(quoteMap.get(config.Apttus_QPConfig__Proposald__c).  End_Customer_Country_Code__c != Null)
								config.PCcountry__c = quoteMap.get(config.Apttus_QPConfig__Proposald__c).End_Customer_Country_Code__c;
							
							
							//Heema : Re 6593
							if(/*quoteMap.get(config.Apttus_QPConfig__Proposald__c).NokiaCPQ_LEO_Discount__c ==  true && quoteMap.get(config.Apttus_QPConfig__Proposald__c).NokiaCPQ_Existing_IONMaint_Contract__c.equalsIgnoreCase('No') && */quoteMap.get(config.Apttus_QPConfig__Proposald__c).NokiaCPQ_No_of_Years__c=='1'){
								config.NokiaCPQ_IsMainSSPAdded__c = true;
							} 
							if(quoteMap!=null && quoteMap.get(config.Apttus_QPConfig__Proposald__c).Quote_Type__c!=Nokia_CPQ_Constants.directDS && config.Apttus_Config2__BusinessObjectType__c.equalsIgnoreCase(Nokia_CPQ_Constants.NOKIA_PROPOSAL) && config.NokiaCPQ_Portfolio_From_Quote__c!=Nokia_CPQ_Constants.QTC_PORTFOLIO){
								if(quoteMap.get(config.Apttus_QPConfig__Proposald__c).NokiaCPQ_LEO_Discount__c){
									config.Search_Filter_Leo__c = true;
								}
								else{
									config.Search_Filter_Leo__c = false;
								}
							}
						}
					}
				}
			}
		}catch(Exception ex)
		{
			System.debug('ProductConfigTriggerHelper class and updateFieldsOnProdConfig Method '+ex.getCause()+ex.getLineNumber()+ex.getMessage());
			ExceptionHandler.addException(ex,Nokia_CPQ_Constants.updateFieldsOnProdConfig, Nokia_CPQ_Constants.ProductConfigTriggerHelper);
		}
	}
	/************************************
* Method :  updateFieldsOnProdConfig
* Paramater: List<Apttus_Config2__ProductConfiguration__c>
* Comments: Clear Sites on Configuration Line Item
* Created By: priyanka Agrawal 23-01-2019 
* Nokia CPQ REQ:6624  
* ************************************/
	public static void clearSiteOnConfiguration(Set<id> prodConfigSet)
	{
		List<Apttus_Config2__LineItem__c> lineItemList = new List<Apttus_Config2__LineItem__c>();
		try{
			if(!prodConfigSet.isEmpty())
			{
				for(Apttus_Config2__LineItem__c lineItem : [select id,NokiaCPQ_Opportunity_Site__c from Apttus_Config2__LineItem__c 
															where Apttus_Config2__ConfigurationId__c in: prodConfigSet
															LIMIT: Limits.getLimitQueryRows() - Limits.getQueryRows()])
				{
					lineItem.NokiaCPQ_Opportunity_Site__c= null;
					lineItemList.add(lineItem);
				}
			}
				if(!lineItemList.isEmpty()){
								  database.update(lineItemList);  
				}
				
		  }catch(Exception ex)
		{
			ExceptionHandler.addException(ex,'clearSiteOnConfiguration', Nokia_CPQ_Constants.ProductConfigTriggerHelper+ex.getLineNumber());
		}
	}
}