src/objects/Apttus_Approval__Approval_Request__c.object
<CustomObject>
    <description>Designates an approval request created from an approval process</description>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                </value>
                <value>
                    <fullName>Notified</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reassigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>R00N70000001lyBlEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ApprovalStatusTechField__c</fullName>
        <description>Technical Field : Used for ByPass Gates Validation Rules.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Approval Status Tech Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approvals_Current_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Approvals Current Status</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>G2_Approval_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G2 Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>G3_Approval_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G3 Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req 569: User will select Lead BG manually</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phase_Status__c</fullName>
        <description>305:Set up the following phases for the sales process for standard opportunities: 
- for the single phases refer to the attached file &quot;Sales Process_&lt;latest file version&gt;&quot; / column &quot;Sales Phase&quot;</description>
        <label>Phase Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Submitted for G2 Approval</fullName>
                </value>
                <value>
                    <fullName>Opportunity in Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted for G3 Approval</fullName>
                </value>
                <value>
                    <fullName>Offer in Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted for G4 Approval</fullName>
                </value>
                <value>
                    <fullName>Offer Submitted to Customer (Manual)</fullName>
                </value>
                <value>
                    <fullName>Submitted for G5 Approval</fullName>
                    <label>Submitted for Gate 5 Contract Approval</label>
                </value>
                <value>
                    <fullName>PTA (PROJECT TARGET AGREEMENT) HANDOVER TO DELIVERY/OPERATIONS</fullName>
                </value>
                <value>
                    <fullName>Submitted for G6 Approval</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed(not won)</fullName>
                    <label>Closed (not won)</label>
                </value>
                <value>
                    <fullName>Won (Requested)</fullName>
                </value>
                <value>
                    <fullName>Pending Win/Loss Declaration</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                    <isActive>false</isActive>
                    <label>Closed Lost</label>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                    <isActive>false</isActive>
                    <label>Closed Won</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adding a Reference opportunity is mandatory to use following LOA bypasses:
-&gt; For &quot;No LOA&quot; = referring to the opportunity with the frame contract LOA approval,
-&gt; For &quot;Pre-approved Price List for Account Managers&quot; = referring to the related blanket approval.</description>
        <inlineHelpText>Adding a Reference opportunity is mandatory to use following G4/G5 Bypasses:
-&gt; For &quot;G4 Approved or Contracted&quot; = referring to the opportunity with the frame contract G4/G5 approval,
-&gt; For &quot;Pre-approved Price List for Acc Mgrs&quot; = referring to the related blanket approval.</inlineHelpText>
        <label>Reference Opportunity</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Create Direct Sales Opportunity, Create Indirect Sales Opportunity, Read Only Direct, Read Only Indirect</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Data Loader Profile</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SWx_Upsell_Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLD Digital Proposal</label>
        <referenceTo>SWx_Upsell_Proposal__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SWx_Upsell_Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Digital Proposal</relationshipLabel>
        <relationshipName>SWx_Upsell_Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Analytics_Source__c</fullName>
        <label>Analytics Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCRE</fullName>
                </value>
                <value>
                    <fullName>CXM</fullName>
                </value>
                <value>
                    <fullName>RMP</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                    <isActive>false</isActive>
                    <label>DS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Recommendation_Type__c</fullName>
        <label>Proposal Recommendation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SW Recommendation</fullName>
                </value>
                <value>
                    <fullName>HW Recommendation</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Party__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Digital Proposal (Sold To Party)</relationshipLabel>
        <relationshipName>Digital_Proposal</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Digital Proposal</label>
    <nameField>
        <displayFormat>Digital.Proposal.{000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Proposal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/classes/DS_CreateOIFAndOfferTest.cls
@isTest(seeAllData=true) 
public class DS_CreateOIFAndOfferTest {
	  
	private static Id oppDirectRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.CREATE_DIRECT_SALES_OPPORTUNITY).getRecordTypeId();
	
	 /******************************
	*Method Name: createOIFandOfferTest
	*Description: Test Method to cover OpportunityTriggerHelper class
	********************************/
	public testmethod static void createOIFandOfferTest(){
		Set<Id> accId = new Set<Id>();
			Map<Id,Opportunity> upsellProposalToOppty = new Map<Id,Opportunity>();
			user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
			insert userCreation;
		   
			system.runAs(userCreation){
			Test.startTest();
			
			List<Account> accountCreation = TestDataFactory.createAccount(2);
			accountCreation[0].AccountNumber = '3011234';
			accountCreation[1].AccountNumber = '3011235';
			database.insert(accountCreation);
			accId.add(accountCreation[0].Id);
			accId.add(accountCreation[1].Id);
			
			Id swxRecordTypeId = Schema.SObjectType.SWx_Upsell_Proposal__c.getRecordTypeInfosByName().get('SWx Upsell Proposal').getRecordTypeId();
			Id ccreRecordTypeId = Schema.SObjectType.SWx_Upsell_Proposal__c.getRecordTypeInfosByName().get('CCRE Upsell Proposal').getRecordTypeId();
		   
			List <SWx_Upsell_Proposal__c> upsellProposalList = TestDataFactory.upsellList(3,accountCreation[0]);
			upsellProposalList[0].Analytics_Source__c = CSWXGlobalConstant.AnalyticsSource;
			upsellProposalList[0].RecordTypeId= swxRecordTypeId;
			upsellProposalList[0].Proposal_Recommendation_Type__c = CSWXGlobalConstant.SW_Recommendation;
			upsellProposalList[0].Account_ID__c = accountCreation[0].id;
			upsellProposalList[0].Sold_To_Party__c = accountCreation[0].id;
			upsellProposalList[1].Analytics_Source__c = CSWXGlobalConstant.AnalyticsSource;
			upsellProposalList[1].RecordTypeId= swxRecordTypeId;
			upsellProposalList[1].Proposal_Recommendation_Type__c = CSWXGlobalConstant.HW_Recommendation;
			upsellProposalList[1].Account_ID__c = accountCreation[1].id;
			upsellProposalList[1].Sold_To_Party__c =accountCreation[1].id;
			upsellProposalList[2].Analytics_Source__c = 'CXM';//CSWXGlobalConstant.AnalyticsSource_CCRE;
			upsellProposalList[2].RecordTypeId= swxRecordTypeId; //ccreRecordTypeId;
			upsellProposalList[2].Account_ID__c = accountCreation[1].id;
			upsellProposalList[2].Proposal_Recommendation_Type__c = CSWXGlobalConstant.HW_Recommendation;
			upsellProposalList[2].Sold_To_Party__c =accountCreation[1].id;
				
			database.insert(upsellProposalList);
			System.assertEquals(accountCreation[0].id, upsellProposalList[0].Account_ID__c);
			System.assertEquals(accountCreation[1].id, upsellProposalList[1].Account_ID__c);
			System.assertEquals(accountCreation[1].id, upsellProposalList[2].Account_ID__c);	
			System.assertEquals( upsellProposalList[0].Analytics_Source__c, CSWXGlobalConstant.AnalyticsSource);
			System.assertEquals( upsellProposalList[1].Analytics_Source__c, CSWXGlobalConstant.AnalyticsSource);
		  //  System.assertEquals( upsellProposalList[2].Analytics_Source__c, CSWXGlobalConstant.AnalyticsSource_CCRE);
			
			Opportunity oppty ;
			oppty = TestDataFactory.OpportunityCreation(1,accountCreation[0])[0];
			oppty.StageName = CSWXGlobalConstant.DEVELOP_OPPTY;
			oppty.RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.CREATE_DIRECT_SALES_OPPORTUNITY).getRecordTypeId();
			oppty.SWx_Upsell_Proposal__c =upsellProposalList[0].Id;
			oppty.Lead_BG__c ='MN';
			oppty.Phase_Status__c = CSWXGlobalConstant.Opty_phase_Status;
			
			

			database.insert(oppty);
		 
			List<Opportunity> optyCreation = TestDataFactory.OpportunityCreation(2,accountCreation[0]);
			optyCreation[0].SWx_Upsell_Proposal__c = upsellProposalList[0].Id;
			//optyCreation[0].SWx_Upsell_Proposal__c = null;
			optyCreation[0].Apttus_Approval__Approval_Status__c = CSWXGlobalConstant.Approval_stage_approved;
			optyCreation[0].ApprovalStatusTechField__c = CSWXGlobalConstant.Approved_G2;
			optyCreation[0].Approvals_Current_Status__c = CSWXGlobalConstant.Approved_G2;
			optyCreation[0].G2_Approval_Date__c = System.now();
			optyCreation[0].G3_Approval_Date__c = System.now();
			optyCreation[0].RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.CREATE_DIRECT_SALES_OPPORTUNITY).getRecordTypeId();
			optyCreation[0].StageName = GlobalConstants.DEVELOP_OPPORTUNITY;
		   // optyCreation[0].Phase_Status__c ='Submitted for G3 Approval';
			  optyCreation[0].Phase_Status__c = CSWXGlobalConstant.Opty_phase_Status;
			  optyCreation[0].Reference_Opportunity__c= oppty.id;
			
			
			
			/*optyCreation[1].SWx_Upsell_Proposal__c = upsellProposalList[2].Id;
			optyCreation[1].Apttus_Approval__Approval_Status__c = CSWXGlobalConstant.Approval_stage_approved;
			optyCreation[1].ApprovalStatusTechField__c = CSWXGlobalConstant.Approved_G2;
			optyCreation[1].Approvals_Current_Status__c = CSWXGlobalConstant.Approved_G2;
			optyCreation[1].G2_Approval_Date__c = System.now();
			optyCreation[1].G3_Approval_Date__c = System.now();
			optyCreation[1].RecordTypeId=oppDirectRecordTypeId;
			optyCreation[1].StageName = GlobalConstants.DEVELOP_OPPORTUNITY;
			optyCreation[1].Phase_Status__c ='Submitted for G3 Approval';
			*/
			
			database.insert(optyCreation);
			Apttus_Approval__Approval_Request__c approvalData = new Apttus_Approval__Approval_Request__c();
			approvalData.Apttus_Approval__Related_Opportunity__c = optyCreation[0].id;   
			database.insert(approvalData);	
			
			system.debug('optyCreation[0]--->'+optyCreation[0]);
			system.debug('optyCreation[0].SWx_Upsell_Proposal__c]--->'+optyCreation[0].SWx_Upsell_Proposal__c);
			system.debug('optyCreation[0].RecordType.DeveloperName--->'+optyCreation[0].RecordType.DeveloperName);
			system.debug('optyCreation[0].StageName--->'+optyCreation[0].StageName);
			
			//DS_CreateOIFAndOffer.createOIFandOfferonDigiSalesOpportunity(optyCreation);
				
			optyCreation[0].SWx_Upsell_Proposal__c = upsellProposalList[2].Id;
			database.update(optyCreation);
			 System.enqueueJob( new DS_CreateOIFAndOffer(optyCreation) );
			//DS_CreateOIFAndOffer.createOIFandOfferonDigiSalesOpportunity(optyCreation);	
		   // DS_CreateOIFAndOffer.createOIFandOfferonDigiSalesOpportunity(NULL);
		   // DS_CreateOIFAndOffer.UpdateApprovalHistoryData(optyCreation[0].Id);  
			Test.stopTest();
			} 
	}  

}