src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Maintenance_Y1__c</fullName>
        <label>Maintenance Under Warranty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maintenance_Y2__c</fullName>
        <label>Maintenance Beyond Warranty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <description>To differentiate CPQ quotes from SWX Quotes</description>
        <formula>IF( 
	Apttus_Proposal__Opportunity__c != null, 
	IF( 
		AND(
			OR( 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Direct Sales Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Read Only Direct&apos; 
			), 
			isCQ__c = false
		   ), 
		IF(
			OR( 
				RecordTypeId = $Label.DS_QuoteEditRecordTypeId,
				RecordTypeId = $Label.DS_QuoteReadRecordTypeId 
			) , 
			&apos;Direct DS&apos;, 
			IF(OR( RecordTypeId = $Label.NokiaCPQ_DirectQuoteID,RecordTypeId = $Label.NokiaCPQ_DirectReadOnlyQuoteID) , &apos;Direct CPQ&apos;, &apos;NCQ&apos;)
			), 
		IF( 
			AND(
			  OR( 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Indirect Sales Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Indirect Workspace Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Read Only Indirect&apos; 
			     ),
				isCQ__c = false
			), 
			IF(
				OR(
					RecordTypeId = $Label.DS_QuoteEditRecordTypeId , 
					RecordTypeId = $Label.DS_QuoteReadRecordTypeId), 
				&apos;Indirect DS&apos;, 
				&apos;Indirect CPQ&apos;
			   ), 
			IF(isCQ__c,&apos;CQ&apos;,&apos;&apos;) 
		) 
	), 
	&apos;&apos; 
)</formula>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRS__c</fullName>
        <label>SRS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SSP__c</fullName>
        <label>SSP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IndirectCPQ_ProposalTriggerHandler.cls
/******************************************************************************************************
Name : IndirectCPQ_ProposalTriggerHandler
Created by: Accenture
Description : Handler class for Indirect CPQ to handle quote process.		
*********************************************************************************************************/
public class IndirectCPQ_ProposalTriggerHandler {
/******************************
*Method Name: afterUpdateMethod
*Description: This Method is used to handle after update logic of Proposal Trigger for Indirect
 ********************************/
	public static void afterUpdateMethod(List<Apttus_Proposal__Proposal__c> updatedQuoteList,Map<Id, Apttus_Proposal__Proposal__c> oldQuoteMap ){
		try{
			Set<Id> quoteIDSet = new Set<Id>();
			 for(Apttus_Proposal__Proposal__c quoteRecord : updatedQuoteList ){
				if( quoteRecord.Quote_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.QUOTE_TYPE_INDIRECTCPQ) && 
				  ( quoteRecord.Maintenance_Y1__c != oldQuoteMap.get(quoteRecord.Id).Maintenance_Y1__c ||
					quoteRecord.Maintenance_Y2__c != oldQuoteMap.get(quoteRecord.Id).Maintenance_Y2__c ||
					quoteRecord.SSP__c != oldQuoteMap.get(quoteRecord.Id).SSP__c ||
					quoteRecord.SRS__c != oldQuoteMap.get(quoteRecord.Id).SRS__c) )
				  {
				   
					quoteIDSet.add(quoteRecord.Id);
				  }
			}
		   if( quoteIDSet.size() > 0){
			 IndirectCPQ_ProposalTriggerHelper.UpdateStatusOnLI(quoteIDSet);
		   }
		  }catch(Exception ex){
			ExceptionHandler.addException(ex, IndirectCPQ_ProposalTriggerHandler.class.getName(), Nokia_CPQ_Constants.ERROR_MSD);
		}
	}
}