src/objects/Apttus_Approval__Approval_Request_History__c.object
<CustomObject>
    <description>Designates history for an approval request created from an approval process</description>
    <fields>
        <fullName>Apttus_Approval__Assigned_To_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Assigned To Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Approval History</relationshipLabel>
        <relationshipName>Related_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__SubstepName__c</fullName>
        <description>The name of the substep associated with the subprocess.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The name of the substep associated with the subprocess.</inlineHelpText>
        <label>Substep Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BG_Attribute__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BG Attribute</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NF_Assignee_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Assignee Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NF_Organization_Level__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Organisation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NF_Role_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NF_Role_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Request History</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Request History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__ApprovalRuleAssignee__c.object
<CustomObject>
    <description>Represents a single assignee in an approval rule entry</description>
    <fields>
        <fullName>Apttus_Approval__AssigneeDescription__c</fullName>
        <description>The assignee description</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Assignee Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__AssigneeValue__c</fullName>
        <description>The assignee value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Assignee Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Rule Assignee</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Assignee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Rule Assignees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req 569: User will select Lead BG manually</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BU__c</fullName>
        <description>Selection of group within MN to lead on approvals. Mandatory selection from drop-down list if MN or ION are chosen as the Lead BG</description>
        <label>Lead BU</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_BG__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Business_Units</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Org_L2__c</fullName>
        <formula>Account.L2Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation Level 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L3__c</fullName>
        <formula>Account.L3Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_3</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L4__c</fullName>
        <formula>Account.L4Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_4</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L5__c</fullName>
        <formula>Account.L5Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_5</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L6__c</fullName>
        <formula>Account.L6Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_6</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L7__c</fullName>
        <formula>Account.L7Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_7</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSR_Lead_Business_Group__c</fullName>
        <description>no longer used after March 2021 due to AP2021</description>
        <encryptionScheme>None</encryptionScheme>
        <label>OLD Lead BG Pre-Sales</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSR_Lead_Business_Unit__c</fullName>
        <description>no longer used after March 2021 due to AP2021</description>
        <formula>IF(AND(	PSR_Cost_BG_NEN__c &gt; PSR_Cost_Business_Group_FN__c, 
PSR_Cost_BG_NEN__c &gt; PSR_Cost_Business_Group_GS__c, 
PSR_Cost_BG_NEN__c &gt; PSR_Cost_Business_Group_MN__c , 
PSR_Cost_BG_NEN__c &gt; PSR_Cost_Business_Group_AA__c, 
PSR_Cost_BG_NEN__c &gt; PSR_Cost_Business_Group_ION__c), 
IF( AND(PSR_Cost_BU_NE_DAaaS__c &gt; PSR_Cost_BU_NE_EOP__c , 
PSR_Cost_BU_NE_DAaaS__c &gt; PSR_Cost_BU_NE_IoT__c ) , 
&quot;NE DAaaS&quot;, 
IF( PSR_Cost_BU_NE_EOP__c &gt; PSR_Cost_BU_NE_IoT__c , 
&quot;NE EOP&quot;, 
IF( PSR_Cost_BU_NE_IoT__c &gt; 0 , 
&quot;NE IoT&quot;, null))),

IF(AND(PSR_Cost_Business_Group_ION__c &gt; PSR_Cost_Business_Group_FN__c, 
PSR_Cost_Business_Group_ION__c &gt; PSR_Cost_Business_Group_GS__c, 
PSR_Cost_Business_Group_ION__c &gt; PSR_Cost_Business_Group_MN__c , 
PSR_Cost_Business_Group_ION__c &gt; PSR_Cost_Business_Group_AA__c, 
PSR_Cost_Business_Group_ION__c &gt; PSR_Cost_BG_NEN__c)
,IF( AND( PSR_Cost_BU_ION_IPR_DNI__c &gt; PSR_Cost_BU_ION_IPR_MPC__c,
PSR_Cost_BU_ION_IPR_DNI__c &gt; PSR_Cost_Business_Unit_ION_IPR__c,
PSR_Cost_BU_ION_IPR_DNI__c &gt; PSR_Cost_BU_ION_IPR_Services__c,
PSR_Cost_BU_ION_IPR_DNI__c &gt; PSR_Cost_BU_ION_IPR_Nuage__c,
PSR_Cost_BU_ION_IPR_DNI__c &gt; PSR_Cost_Business_Unit_ION_Optics__c,
PSR_Cost_BU_ION_IPR_DNI__c &gt; PSR_Cost_BU_ION_Optics_Services__c),
&quot;ION IPR&quot;,

IF( AND( PSR_Cost_BU_ION_IPR_MPC__c &gt; PSR_Cost_Business_Unit_ION_IPR__c,
PSR_Cost_BU_ION_IPR_MPC__c &gt; PSR_Cost_BU_ION_IPR_Services__c,
PSR_Cost_BU_ION_IPR_MPC__c &gt; PSR_Cost_BU_ION_IPR_Nuage__c,
PSR_Cost_BU_ION_IPR_MPC__c &gt; PSR_Cost_Business_Unit_ION_Optics__c,
PSR_Cost_BU_ION_IPR_MPC__c &gt; PSR_Cost_BU_ION_Optics_Services__c),
&quot;ION IPR&quot;,

IF( AND( PSR_Cost_Business_Unit_ION_IPR__c &gt; PSR_Cost_BU_ION_IPR_Services__c,
PSR_Cost_Business_Unit_ION_IPR__c &gt; PSR_Cost_BU_ION_IPR_Nuage__c,
PSR_Cost_Business_Unit_ION_IPR__c &gt; PSR_Cost_Business_Unit_ION_Optics__c,
PSR_Cost_Business_Unit_ION_IPR__c &gt; PSR_Cost_BU_ION_Optics_Services__c),
&quot;ION IPR&quot;,

IF( AND( PSR_Cost_BU_ION_IPR_Services__c &gt; PSR_Cost_BU_ION_IPR_Nuage__c,
PSR_Cost_BU_ION_IPR_Services__c &gt; PSR_Cost_Business_Unit_ION_Optics__c,
PSR_Cost_BU_ION_IPR_Services__c &gt; PSR_Cost_BU_ION_Optics_Services__c),
&quot;ION IPR&quot;, 

IF( AND( PSR_Cost_BU_ION_IPR_Nuage__c &gt; PSR_Cost_Business_Unit_ION_Optics__c,
PSR_Cost_BU_ION_IPR_Nuage__c &gt; PSR_Cost_BU_ION_Optics_Services__c),
&quot;ION IPR&quot;,

IF( AND( PSR_Cost_Business_Unit_ION_Optics__c &gt; PSR_Cost_BU_ION_Optics_Services__c),
&quot;ION Optics&quot;,

IF(PSR_Cost_BU_ION_Optics_Services__c &gt; 0, 
&quot;ION Optics&quot;, null
))))))),null)

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field only applies either ION or NEN is the Lead BG.</inlineHelpText>
        <label>OLD Lead BU Pre-Sales</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Role__c.object
<CustomObject>
    <description>Object that maintains the Nokia Sales Organization Hierarchy</description>
    <fields>
        <fullName>BG__c</fullName>
        <description>For CMD BG Attribute coming from Pack4</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BG Attribute</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <description>Nokia Sales Organisation Identifier</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Organisation</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Code__c</fullName>
        <description>Nokia Role Code from CMD</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <description>Nokia Role Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Role</label>
    <nameField>
        <displayFormat>CMD-{0000}</displayFormat>
        <label>Sales Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/classes/NF_TL_UpdateHistoryRequestRCode.cls
/**
*   This class is used as a helper to Update ApprovalRequest History 
*   "Role NAme", "Organization" and "AssigneeType" from the Rule Assignee Table
*/
public with sharing class NF_TL_UpdateHistoryRequestRCode {
	
	/**
	*   @desc   : Method used to update approvalRuleHistory Fields based on the appropriate AssigneeRule Table
	*   @param  : List<Apttus_Approval__Approval_Request_History__c>
	*/
	public static void updateHistoryRequestRcodeM(List<Apttus_Approval__Approval_Request_History__c> historyRequests){
		List<Apttus_Approval__Approval_Request_History__c> tmpRequests =[
					SELECT
						Id,
						Apttus_Approval__SubstepName__c,
						Apttus_Approval__Assigned_To_Id__c,
						Apttus_Approval__Related_Opportunity__c,
						Apttus_Approval__Related_Opportunity__r.PSR_Lead_Business_Unit__c,
						Apttus_Approval__Related_Opportunity__r.PSR_Lead_Business_Group__c,						
						Apttus_Approval__Related_Opportunity__r.Lead_BG__c,
						Apttus_Approval__Related_Opportunity__r.Lead_BU__c,
						Apttus_Approval__Related_Opportunity__r.Org_L2__c,
						Apttus_Approval__Related_Opportunity__r.Org_L3__c,
						Apttus_Approval__Related_Opportunity__r.Org_L4__c,
						Apttus_Approval__Related_Opportunity__r.Org_L5__c,
						Apttus_Approval__Related_Opportunity__r.Org_L6__c,
						Apttus_Approval__Related_Opportunity__r.Org_L7__c,
						BG_Attribute__c,
						NF_Organization_Level__c,
						NF_Role_Code__c,
						NF_Role_Name__c,
						NF_Assignee_Type__c
					FROM
						Apttus_Approval__Approval_Request_History__c
					WHERE
						Id in :historyRequests
					];

		set<String> assignedUsers = new set<String>();
		set<String> arulesSet = new set<String>();

		//Fetch  assignedTo Users + ApprovalRuleAssignees Name
		for(Apttus_Approval__Approval_Request_History__c request : historyRequests){
			arulesSet.add(request.Apttus_Approval__SubstepName__c);
			assignedUsers.add(request.Apttus_Approval__Assigned_To_Id__c);
			System.debug('-->User'+assignedUsers+arulesSet);
		}
		
		System.debug('historyRequests-->'+historyRequests);

		set<String> orgsSet = new set<String>();
		set<String> codesSet = new set<String>();
		set<String> BGSet = new set<String>();
		Map<String, String> arAssigneeToOrgndCodeMap = new Map<String, String>();
		Map<String, String> arAssigneeToType = new Map<String, String>();

		//Loop Through assignees and construct : Org, roles, Map for each assigneeName relatedOrg+Code
		for(Apttus_Approval__ApprovalRuleAssignee__c arAssignee :[SELECT Id,Apttus_Approval__AssigneeValue__c,
																	Apttus_Approval__AssigneeDescription__c,Name
																  FROM Apttus_Approval__ApprovalRuleAssignee__c
																  WHERE Name in :arulesSet
																]){
			String org='';
			String org1='';
			String code='';
			string lead_bg = '';
			string lead_bu = '';
			
			List<String> codList = new List<String>();
			List<String> org_codList = new List<String>();
			List<String> BG_List = new List<String>();
			
			String BG_Val = '';
			String BU_Val = '';
			 System.debug('Asignee Rule ID --->'+arAssignee.Id);
			
			//Map for unique AssigneeNAme to Description which can be : Approver, Validator, Stackholder to be used for ValidatorComments.
			if(!arAssigneeToType.containsKey(arAssignee.Name) && String.isNotBlank(arAssignee.Apttus_Approval__AssigneeDescription__c))
			arAssigneeToType.put(arAssignee.Name, arAssignee.Apttus_Approval__AssigneeDescription__c.subString(arAssignee.Apttus_Approval__AssigneeDescription__c.lastIndexOf(',')+1, arAssignee.Apttus_Approval__AssigneeDescription__c.length()));				   
	   
			
			//Check wether the Record has a valid value in  the field assigneeValue, if yes then split.
			if(arAssignee.Apttus_Approval__AssigneeValue__c != null && arAssignee.Apttus_Approval__AssigneeValue__c.contains('AND'))
			{
				codList = arAssignee.Apttus_Approval__AssigneeValue__c.split('AND');
				if(codList[1].contains('OR'))
				org_codList = codList[1].split('OR');
				If(codlist.size()== 4)
				{
				if(codList[3].contains('OR'))
				BG_List = codList[3].split('OR');						
				}
			}
			system.debug('org_codList:'+org_codList);
			system.debug('codList:'+codList);
			//Get the Organization Level from SalesRole, then get the value from the opportunity by Dynamic Apex.  
			 for(Apttus_Approval__Approval_Request_History__c request : tmpRequests)
			{
				 if(arAssignee.Name.equalsIgnoreCase(request.Apttus_Approval__SubstepName__c) && request.Apttus_Approval__Related_Opportunity__r != null && !codList.isEmpty())
				 {
													   
								 
					 if(!BG_List.isEmpty())
					 {		   
						Lead_bg = BG_List[0].subString(BG_List[0].lastIndexOf(':')+1,BG_List[0].length()-2).remove(' ');
						BG_Val = String.valueOf(request.Apttus_Approval__Related_Opportunity__r.get(Lead_bg));

						if(BG_Val == 'ION' || BG_Val == 'NEN')
						{
						BGSet.add(BG_Val);						
						Lead_bu = BG_List[1].subString(BG_List[1].lastIndexOf(':')+1,BG_List[1].IndexOf(')')-1).remove(' ');
						BG_Val = String.valueOf(request.Apttus_Approval__Related_Opportunity__r.get(Lead_bu));
						}
					 }
					 else if(codList.size() == 4)
					 {
					 BG_Val = codList[3].subString(codList[3].lastIndexOf('=')+2,codList[3].IndexOf(')')-1);
					 }
					 if(string.isNotBlank(BG_Val))
					 BGSet.add(BG_Val);
				
				if(!org_codList.isEmpty())
				{			 
					for(String org_all : Org_codList)
					{
						org_all.replace('(','').trim();													   
						If(org_all.contains(')'))
						org1 = org_all.subString(org_all.lastIndexOf(':')+1, org_all.IndexOf(')')-1).remove(' ');   
						else
						org1 = org_all.subString(org_all.lastIndexOf(':')+1, org_all.length()-2).remove(' ');	   
						org = String.valueOf(request.Apttus_Approval__Related_Opportunity__r.get(org1));														  
						code = codList[0].subString(codList[0].lastIndexOf('%')+2, codList[0].length()-2).remove(' '); 
					 //Map for Unique Assignee name to Code
					if(!arAssigneeToOrgndCodeMap.containsKey(arAssignee.Name) && String.isNotBlank(code) && String.isNotBlank(org))
					arAssigneeToOrgndCodeMap.put(arAssignee.Name,code+BG_Val);	 
					system.debug('arAssigneeToOrgndCodeMAp:'+arAssigneeToOrgndCodeMap);						
						if(org1.contains('2'))
						code = 'NSNA'+code;
						else if(org1.contains('3'))
						code = 'NSNB'+code;
						else if(org1.contains('4'))
						code = 'NSNC'+code;
						else if(org1.contains('5'))
						code = 'NSND'+code;
						else if(org1.contains('6'))
						code = 'NSNE'+code;
						else if(org1.contains('7'))
						code = 'NSNG'+code;		  
					//Sets used to get Sales Role records					   
					if(String.isNotBlank(code))
					codesSet.add(code);		 
						//Sets used to get Sales Role records.
						if(String.isNotBlank(org))
						orgsSet.add(org); 
									   
					}
				}		 
				else
				{
					org1 = codList[1].subString(codList[1].lastIndexOf(':')+1, codList[1].length()-2).remove(' ');
					  org = String.valueOf(request.Apttus_Approval__Related_Opportunity__r.get(org1));	
					code = codList[0].subString(codList[0].lastIndexOf('%')+2, codList[0].length()-2).remove(' ');
					//Map for Unique Assignee name to Code
					if(!arAssigneeToOrgndCodeMap.containsKey(arAssignee.Name) && String.isNotBlank(code) && String.isNotBlank(org))
					arAssigneeToOrgndCodeMap.put(arAssignee.Name,code+BG_Val);	 
					system.debug('arAssigneeToOrgndCodeMAp:'+arAssigneeToOrgndCodeMap); 
					if(org1.contains('2'))
						code = 'NSNA'+code;
						else if(org1.contains('3'))
						code = 'NSNB'+code;
						else if(org1.contains('4'))
						code = 'NSNC'+code;
						else if(org1.contains('5'))
						code = 'NSND'+code;
						else if(org1.contains('6'))
						code = 'NSNE'+code;
						else if(org1.contains('7'))
						code = 'NSNG'+code;		  
					//Sets used to get Sales Role records					   
					if(String.isNotBlank(code))
					codesSet.add(code);		 
					if(String.isNotBlank(org))			   
					orgsSet.add(org); 
																							 
				}									
			}											
		}
		}
		system.debug('code:'+codesSet);
		system.debug('OrsSet:'+orgsSet);
		system.debug('BGSet:'+BGSet);
		Map<String, Sales_Role__c> rolendOrgToSalesRoleMap = new Map<String, Sales_Role__c>();
		for(Sales_Role__c sRole :[
								SELECT
									Id,
									User__c,
									BG__c,
									Role_Name__c,
									Organisation__c,
									Role_Code__c
								FROM
									Sales_Role__c
								WHERE
									(BG__c = :BGSet or BG__c = '')
									AND
									Role_Code__c in :codesSet
									AND
									Organisation__c in :orgsSet
								 //   AND
								 //   User__c in :assignedUsers
								]
		){
			
			//Map for unique Code+Organization to the relevant record sRole.
			//String Role_Map_Key = sRole.Role_Code__c+''+sRole.Organisation__c;
			string Role = sRole.Role_Code__c;
			String Role_Map_Key ='';
			IF(sRole.BG__c!=null)
			Role_Map_Key = Role.subString(Role.lastIndexOf('_'))+sRole.BG__c;
			else
			Role_Map_Key = Role.subString(Role.lastIndexOf('_'));			
			if(!rolendOrgToSalesRoleMap.containsKey(Role_Map_Key.touppercase())){
				rolendOrgToSalesRoleMap.put(Role_Map_Key.touppercase(), sRole);
				system.debug('sRole:'+sRole);
			}
		}
		system.debug('########## rolendOrgToSalesRoleMap ' + rolendOrgToSalesRoleMap );
		//Loop throught historyRequest list and update the relevant data.
		Savepoint sp = null;
		for(Apttus_Approval__Approval_Request_History__c request : tmpRequests){
			 String RoleBGVal = '';
		if(arAssigneeToOrgndCodeMap.get(request.Apttus_Approval__SubstepName__c) != null )
		RoleBGVal = (arAssigneeToOrgndCodeMap.get(request.Apttus_Approval__SubstepName__c).touppercase());
		system.debug('RoleBGVal:'+RoleBGVal);
		  if((RoleBGVal.contains('ION')||RoleBGVal.contains('NEN')) && rolendOrgToSalesRoleMap.get(RoleBGVal) == null)
		  {
		  List<String> keyset = RoleBGVal.split(' ');
		  RoleBGVal = keyset[0];
		  system.debug('RoleBGVal:'+RoleBGVal);
		  }
			if(arAssigneeToOrgndCodeMap.get(request.Apttus_Approval__SubstepName__c) != null 
				&& rolendOrgToSalesRoleMap.get(RoleBGVal) != null
			  ){
				Sales_Role__c sRole = new Sales_Role__c();
				sRole = rolendOrgToSalesRoleMap.get(RoleBGVal);
				if(sRole != null){
					request.NF_Organization_Level__c = sRole.Organisation__c;
					system.debug('########## Role Code ' + sRole.Role_Code__c );
					system.debug('########## sRole.Role_Name__c ' + sRole.Role_Name__c );
					System.debug('########## sRole.BG__c'+sRole.BG__c);
					request.NF_Role_Code__c = sRole.Role_Code__c;
					request.NF_Role_Name__c = sRole.Role_Name__c; 
					if(sRole.BG__c<>NUll)  
					
					request.BG_Attribute__c=sRole.BG__c;
					
					
				}
			}
				if(arAssigneeToType.get(request.Apttus_Approval__SubstepName__c) != null){
				request.NF_Assignee_Type__c = arAssigneeToType.get(request.Apttus_Approval__SubstepName__c);
				}
		}
		try{
			sp = Database.setSavepoint();
			Database.update(tmpRequests,false);
		}catch(DmlException e){
			if (sp != null) Database.rollback(sp);
			system.debug('###Exception from NF_TL_UpdateHistoryRequestRCode : '+e.getMessage() + 'Stack Trace : '+e.getStackTraceString());
			throw e;
		}
		
	}
}