src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__AdjustmentAmount__c</fullName>
        <description>The manual price adjustment amount.</description>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ConfigurationId__c</fullName>
        <description>ID of the associated configuration</description>
        <label>Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ExtendedQuantity__c</fullName>
        <description>The extended quantity is Quantity X Parent Quantity)</description>
        <inlineHelpText>The extended quantity is Quantity X Parent Quantity)</inlineHelpText>
        <label>Extended Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineType__c</fullName>
        <description>The line type</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Service</fullName>
                    <default>true</default>
                    <label>Product/Service</label>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__OptionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected option</description>
        <label>Option</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Option Line Items</relationshipLabel>
        <relationshipName>OptionLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CPQ_Market_Model__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Flexible Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <formula>IF(TEXT(Apttus_Config2__LineType__c)==&quot;Product/Service&quot;,  TEXT(Apttus_Config2__ProductId__r.NokiaCPQ_Item_Type__c) ,  TEXT(Apttus_Config2__OptionId__r.NokiaCPQ_Item_Type__c ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Configuration_Type__c</fullName>
        <formula>IF(TEXT(Apttus_Config2__LineType__c) =&quot;Product/Service&quot;, TEXT(Apttus_Config2__ProductId__r.Apttus_Config2__ConfigurationType__c ), TEXT(Apttus_Config2__OptionId__r.Apttus_Config2__ConfigurationType__c) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Configuration Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Light_Color__c</fullName>
        <description>Field Created to set guidance color from PCB</description>
        <label>Deal Guidance Color</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RED</fullName>
                </value>
                <value>
                    <fullName>GREEN</fullName>
                </value>
                <value>
                    <fullName>YELLOW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Rationale_Of_Adjustment__c</fullName>
        <description>Req 6001: Rationale for adjustment given on cart</description>
        <label>Discount Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FoC Discount</fullName>
                </value>
                <value>
                    <fullName>One-time Lump Sum Discount</fullName>
                </value>
                <value>
                    <fullName>One-time Voucher</fullName>
                </value>
                <value>
                    <fullName>Retroactive Discount</fullName>
                </value>
                <value>
                    <fullName>Other One-time Discount</fullName>
                </value>
                <value>
                    <fullName>Lump Sum Discount</fullName>
                </value>
                <value>
                    <fullName>Run-Rate% Discount</fullName>
                </value>
                <value>
                    <fullName>Buy x Get y Free</fullName>
                </value>
                <value>
                    <fullName>Recurring Voucher</fullName>
                </value>
                <value>
                    <fullName>Tiered Volume-based Discount</fullName>
                </value>
                <value>
                    <fullName>Price Erosion</fullName>
                </value>
                <value>
                    <fullName>Currency Devaluation</fullName>
                </value>
                <value>
                    <fullName>Other Recurring Discount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Spare__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Req 6146: Checkbox field to identify spare parts in shopping cart</description>
        <label>Spare</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <formula>Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Quote_Type__c</formula>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio_From_Quote__c</fullName>
        <formula>TEXT(Apttus_QPConfig__Proposald__r.NokiaCPQ_Portfolio__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio From Quote</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <formula>Apttus_QPConfig__Proposald__r.Quote_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__SummaryGroup__c.object
<CustomObject>
    <description>Represents a summary of line items</description>
    <fields>
        <fullName>Apttus_Config2__AdjustmentAmount__c</fullName>
        <description>The price adjustment amount.</description>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ConfigurationId__c</fullName>
        <description>ID of the associated configuration</description>
        <label>Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Summary Groups</relationshipLabel>
        <relationshipName>SummaryGroups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineType__c</fullName>
        <description>The line type</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Category Total</fullName>
                </value>
                <value>
                    <fullName>Group Total</fullName>
                </value>
                <value>
                    <fullName>Grand Total</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Summary Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Totals</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Summary Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__TempRenew__c.object
<CustomObject>
    <description>Temporary object for capturing user input to create asset line items.during the amendment/renewal process.</description>
    <fields>
        <fullName>Apttus_Config2__AdjustmentAmount__c</fullName>
        <description>The manual price adjustment amount.</description>
        <inlineHelpText>The manual price adjustment amount.</inlineHelpText>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Temp Renew</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Temp Renew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temp Renews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>NokiaCPQ_Environment_Access_Type__c</fullName>
        <formula>IF(CONTAINS(NokiaCPQ_Environment_Access_URL__c,$Label.NokiaCPQ_Partner_Community_Name),&apos;PRM&apos;,&apos;sCRM&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Environment Access Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <description>To differentiate CPQ quotes from SWX Quotes</description>
        <formula>IF( 
	Apttus_Proposal__Opportunity__c != null, 
	IF( 
		AND(
			OR( 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Direct Sales Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Read Only Direct&apos; 
			), 
			isCQ__c = false
		   ), 
		IF(
			OR( 
				RecordTypeId = $Label.DS_QuoteEditRecordTypeId,
				RecordTypeId = $Label.DS_QuoteReadRecordTypeId 
			) , 
			&apos;Direct DS&apos;, 
			IF(OR( RecordTypeId = $Label.NokiaCPQ_DirectQuoteID,RecordTypeId = $Label.NokiaCPQ_DirectReadOnlyQuoteID) , &apos;Direct CPQ&apos;, &apos;NCQ&apos;)
			), 
		IF( 
			AND(
			  OR( 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Indirect Sales Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Indirect Workspace Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Read Only Indirect&apos; 
			     ),
				isCQ__c = false
			), 
			IF(
				OR(
					RecordTypeId = $Label.DS_QuoteEditRecordTypeId , 
					RecordTypeId = $Label.DS_QuoteReadRecordTypeId), 
				&apos;Indirect DS&apos;, 
				&apos;Indirect CPQ&apos;
			   ), 
			IF(isCQ__c,&apos;CQ&apos;,&apos;&apos;) 
		) 
	), 
	&apos;&apos; 
)</formula>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__ConfigurationType__c</fullName>
        <description>The product configuration type</description>
        <label>Configuration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standalone</fullName>
                    <default>true</default>
                    <label>Standalone</label>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Nokia_Validation_Callback.cls
/************************************************************************************************************
	* Apex Class Name   : Nokia_Validation_Callback.cls
	* Version		   : 1.0
	* Created Date	  : 28 Aug 2017
	* Function		  : validation call back on Cart
	* Modification Log  :
	* Developer				   Date					Description
	* -----------------------------------------------------------------------------------------------------------
	* Rupesh Sharma			   08/28/2017			  validation call back on Cart
	*
	************************************************************************************************************/
	global with sharing class Nokia_Validation_Callback implements Apttus_Config2.CustomClass.IValidationCallback2{
	 public Id ConfigId=null;
		Id Recordtype=null;
	 public Id proposalId;
	 private Apttus_Config2__ProductConfiguration__c configSO;  
	
 
	private Apttus_Config2__ProductConfiguration__c prdConfig;
	/* Method Name   : validateCart
	* Developer	  : Rupesh Sharma
	* Description	: validation messages on cart */
		global Apttus_Config2.CustomClass.ValidationResult validateCart(Apttus_Config2.ProductConfiguration cart) {
			Apttus_Config2.CustomClass.ValidationResult result= new Apttus_Config2.CustomClass.ValidationResult(true);
			Apttus_Proposal__Proposal__c quote = new Apttus_Proposal__Proposal__c();
			Apttus_Config2__ProductConfiguration__c Prodid = new Apttus_Config2__ProductConfiguration__c();
			try{					
				ConfigId = cart.getConfigSO().Id;
				 
				configSO = cart.getConfigSO();			 
				Prodid=[select id,Quote_Type__c,NokiaCPQ_Portfolio_From_Quote__c from Apttus_Config2__ProductConfiguration__c  where id=:ConfigId];
				if(!String.isblank(Prodid.Quote_Type__c) && Prodid.Quote_Type__c.contains('CPQ')) {
				List<Apttus_Config2__LineItem__c> Lineitemlist1=[select id,Apttus_Config2__LineType__c,
																 Apttus_Config2__ProductId__r.Apttus_Config2__ConfigurationType__c,
																 Apttus_Config2__ProductId__r.IsActive,
																 Apttus_Config2__ProductId__r.name,
								 Apttus_Config2__ProductId__r.ProductCode,
																 Apttus_Config2__ProductId__r.Portfolio__c,
																 Apttus_Config2__OptionId__r.name,Apttus_Config2__OptionId__r.IsActive,
																 Apttus_Config2__ProductId__c,Apttus_Config2__OptionId__c,
																 NokiaCPQ_Rationale_Of_Adjustment__c,Apttus_Config2__AdjustmentAmount__c,NokiaCPQ_Configuration_Type__c,NokiaCPQ_Spare__c,Item_Type__c,NokiaCPQ_Light_Color__c,
																 CPQ_Market_Model__c,Apttus_Config2__ExtendedQuantity__c,Apttus_Config2__Quantity__c
																 from Apttus_Config2__LineItem__c
																 where Apttus_Config2__ConfigurationId__c =:ConfigId];
				//Recordtype=Prodid.Apttus_QPConfig__Proposald__r.RecordTypeid;
				//currentquoteId = ApexPages.currentPage().getParameters().get('id');
			   
				
				quote =  [Select id,NokiaCPQ_Environment_Access_Type__c,Quote_Type__c,NokiaCPQ_LEO_Discount__c,NokiaCPQ_Is_Maintenance_Quote__c,NokiaCPQ_Portfolio__c from Apttus_Proposal__Proposal__c where id = :configSO.Apttus_QPConfig__Proposald__c];
				set<Id> Pricelistid= new set<Id>();
				Map<ID,Boolean> ProductMap= new Map<ID,Boolean>();
				Boolean isOnlyMaintenance=true;
	   
				//if(quote.Quote_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.QUOTE_TYPE_INDIRECTCPQ))
				//{	  
					If(Lineitemlist1.size() > 0)
					{				
						
						for(Apttus_Config2__LineItem__c lin:Lineitemlist1) {	

							if(!Prodid.NokiaCPQ_Portfolio_From_Quote__c.equalsignorecase('QTC'))
						{
							
							if (lin.Apttus_Config2__LineType__c== 'Product/Service')
							{
			 
				if(lin.Apttus_Config2__ProductId__r.ProductCode!='MT001' &&	
				  lin.Apttus_Config2__ProductId__r.ProductCode!='MT002'
								   && lin.Apttus_Config2__ProductId__r.ProductCode!='SSP002' && lin.Apttus_Config2__ProductId__r.ProductCode!='SRS')
				   {
									   isOnlyMaintenance=false;
								   }
							  
								if (lin.Apttus_Config2__ProductId__r.IsActive == false ) {
									result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR,'The Quote cannot be validated as it contains products that are no longer available for purchase. Please remove the following items:' + lin.Apttus_Config2__ProductId__r.name));   
									result.isSuccess = false;
								}					  
							}
			  if (lin.NokiaCPQ_Spare__c==True && ((Nokia_CPQ_Constants.lin_Apttus_QPConfig.equals(lin.Apttus_Config2__LineType__c) && Nokia_CPQ_Constants.BUNDLE.equals(lin.NokiaCPQ_Configuration_Type__c)) ||
															   Nokia_CPQ_Constants.NOKIA_OPTION.equals(lin.Apttus_Config2__LineType__c) || !Nokia_CPQ_Constants.HARDWARE_STRING.equals(lin.Item_Type__c))) {
									result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR,System.Label.RestrictSpare));   
									result.isSuccess = false;
								}
							else if(lin.Apttus_Config2__LineType__c == 'Option'){
								if (lin.Apttus_Config2__OptionId__r.IsActive == false ) {
									result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR,'The Quote cannot be validated as it contains products that are no longer available for purchase. Please remove the following items:' + lin.Apttus_Config2__OptionId__r.name ));   
									result.isSuccess = false;
								}					  
							}
							system.debug('quote.NokiaCPQ_Portfolio__c'+quote.NokiaCPQ_Portfolio__c);
							system.debug('lin.Apttus_Config2__ProductId__r.Portfolio__c'+lin.Apttus_Config2__ProductId__r.Portfolio__c);
							if(!quote.NokiaCPQ_Portfolio__c.equalsignorecase(lin.Apttus_Config2__ProductId__r.Portfolio__c) && !String.isEmpty(lin.Apttus_Config2__ProductId__r.Portfolio__c ) && !String.isBlank(lin.Apttus_Config2__ProductId__r.Portfolio__c) ){
					  
					   
									result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR,'The Quote cannot be finalized as it contains products that do not belong to the portfolio you selected on the quote. Please remove the following items:' +lin.Apttus_Config2__ProductId__r.name  ));   
									result.isSuccess = false;
								 
				   
							}
						}
						if(Prodid.NokiaCPQ_Portfolio_From_Quote__c.equalsignorecase('QTC')){
							if(lin.CPQ_Market_Model__c<>NULL){
								System.debug('FG::> '+lin.CPQ_Market_Model__c);
								String modelname = lin.CPQ_Market_Model__c;
								String [] modelArray = modelname.split('\\s');			  
								String qty = modelArray[modelArray.size()-1];
								string Quantity = qty.substringBetween('(',')');
								Integer FGqty = Integer.valueOf(Quantity);
								Integer Extqty = Integer.valueOf(lin.Apttus_Config2__Quantity__c);
								System.debug('FGqty::> '+FGqty +' '+ 'Extqty::> '+Extqty);
								if(Math.mod(Extqty, FGqty)<>0){
									result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR,'Item ' +lin.Apttus_Config2__ProductId__r.name +' is part of a Flexible Group. The quantity you entered is invalid. The quantity entered must be a multiple of the Flexible Group Quantity.'  ));
									result.isSuccess = false;
								}
							}
						}
					}   
//Heema :Req 6383
			 if(isOnlyMaintenance==true && quote.NokiaCPQ_Is_Maintenance_Quote__c==false && !quote.NokiaCPQ_Portfolio__c.equalsIgnoreCase('QTC')){
						result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR,'You must select at least one catalog or custom product in the cart before you can finalize.'));   
									result.isSuccess = false;	
						}
					}
					
				
				//}
		/* Requirement   : Req:6001
				* Developer	  : Piyush Tawari 
				* Description	: warning messages on cart for product
				1.if adjustment given but rationale not provided*/
				if(quote.Quote_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.QUOTE_TYPE_DIRECTCPQ) && !quote.NokiaCPQ_Portfolio__c.equalsIgnoreCase('QTC') ){	  
					system.debug('In directquote code');
					if(Lineitemlist1.size() > 0){										 
						for(Apttus_Config2__LineItem__c lin:Lineitemlist1) {
							if(quote.NokiaCPQ_Portfolio__c == Nokia_CPQ_Constants.AIRSCALE_WIFI_STRING){
								system.debug('In Product/Service and options');
								system.debug('LineItemInDirect'+lin);
								if (lin.Apttus_Config2__AdjustmentAmount__c != null && 
									lin.Apttus_Config2__AdjustmentAmount__c != 0.00 && 
									String.isBlank(lin.NokiaCPQ_Rationale_Of_Adjustment__c )) {
										if(lin.Apttus_Config2__LineType__c== Nokia_CPQ_Constants.lin_Apttus_QPConfig){
											system.debug('In Product/Service error');
											result.Messages.add(new ApexPages.Message(ApexPages.Severity.WARNING,System.label.Rationale_Needed_Product + lin.Apttus_Config2__ProductId__r.name));	
											result.isSuccess = true;
										}else if(lin.Apttus_Config2__LineType__c == Nokia_CPQ_Constants.NOKIA_OPTION &&
												 Nokia_CPQ_Constants.BUNDLE.equals(lin.NokiaCPQ_Configuration_Type__c)){
													 system.debug('In options error');
													 result.Messages.add(new ApexPages.Message(ApexPages.Severity.WARNING,System.label.Rationale_Needed_Product + lin.Apttus_Config2__OptionId__r.name));	
													 result.isSuccess = true;													
												 }
									}
							}
							/* Requirement   : Req:6671,6670,6500
							* Developer	  : Piyush Tawari, Kamlesh Jandu 
							* Description	: Error message on cart if Guidance is RED */
							String DealGuidancePortfolios = System.label.Deal_Guidance_Applicable_Portfolios;
							if(DealGuidancePortfolios.contains(quote.NokiaCPQ_Portfolio__c)){
								   Boolean isPricingManager = FeatureManagement.checkPermission(Nokia_CPQ_Constants.PRICING_MANAGER);
									//system.debug(isPricingManager );
								   Boolean isSalesUser = FeatureManagement.checkPermission(Nokia_CPQ_Constants.CPQ_SALES_USER);
									//system.debug(isSalesUser );
								   Map<String, String> mapValues = Apttus_Config2.RuntimeContext.getParameters();
								   String PageAction = mapValues.get('pageAction');
								   //system.debug('PageAction'+PageAction);
								   if(PageAction == 'Finalize'){
									   if(isSalesUser && !isPricingManager &&
										  !Nokia_CPQ_Constants.BUNDLE.equals(lin.NokiaCPQ_Configuration_Type__c) && 
										  lin.NokiaCPQ_Light_Color__c == Nokia_CPQ_Constants.RED ){
											  result.isSuccess = false;
											  result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR, System.label.Deal_Guidance_Error));													
											  return result;
										  }
								   }	 
							   }
						}
					}					
				}
			 }
		   
			
			}
			catch(exception ex){
				System.debug('EXception --- ' +ex);
			}
		   
			result.isSuccess = true;
			 if(!String.isblank(Prodid.Quote_Type__c) && Prodid.Quote_Type__c.contains('CPQ') && !Prodid.NokiaCPQ_Portfolio_From_Quote__c.equalsignorecase('QTC')) {
				if(quote.Quote_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.QUOTE_TYPE_INDIRECTCPQ)){
				prdConfig =  cart.getConfigSO();
				
				List<Apttus_Config2__SummaryGroup__c> summaryLines = [Select Id,NokiaCPQ_Net_Price__c,Apttus_Config2__Description__c,Apttus_Config2__ExtendedPrice__c,Apttus_Config2__AdjustmentAmount__c from Apttus_Config2__SummaryGroup__c Where  Apttus_Config2__ConfigurationId__c = :prdConfig.Id];
				
				if(Nokia_CPQ_Constants.NOKIA_PROPOSAL.equalsIgnoreCase(prdConfig.Apttus_Config2__BusinessObjectType__c)){
												  
					if(isChargeTypeMaintenance(summaryLines)) {
					   
						result.isSuccess = false;
						result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR, Nokia_CPQ_Constants.NOKIA_CHARGE_TYPE_ERROR_MSG));					
						
						return result;
					}  
					
					if(isCADCorrect(summaryLines)) {
					   
						result.isSuccess = false;
						result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR, Nokia_CPQ_Constants.NOKIA_CAD_ERROR_MSG));				   
						
						return result;
					} 
					if(quote.NokiaCPQ_LEO_Discount__c== true && isValidLEOAmount(summaryLines)){
					system.debug('i am LEO');
					 result.isSuccess = false;
						result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR, Nokia_CPQ_Constants.NOKIA_LEO_WARNING_MSG));					
						system.debug('result'+result);
						return result;
					}
				}
			}
		   
		  }
	   /* Requirement   : Req:6337
				* Developer	  : Priyanka Agrawal
				* Description	: warning messages on cart for NP
				1.if NP not equal to CNP - Reserves*/
			if(!String.isblank(Prodid.Quote_Type__c) && Prodid.Quote_Type__c.contains('CPQ') && !Prodid.NokiaCPQ_Portfolio_From_Quote__c.equalsignorecase('QTC')) {
				if(quote.Quote_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.QUOTE_TYPE_DIRECTCPQ) && quote.NokiaCPQ_Portfolio__c != 'QTC' ){
					List<CPQ_Advance_Pricing__mdt> tempData = new List<CPQ_Advance_Pricing__mdt>();
					tempData = [Select MasterLabel,Action_Name__c from CPQ_Advance_Pricing__mdt where MasterLabel = :quote.NokiaCPQ_Portfolio__c];
					if(!tempData.isEmpty()){
						Map<String, String> mapValues = Apttus_Config2.RuntimeContext.getParameters();
						String PageAction = mapValues.get('pageAction');
						List<Apttus_Config2__SummaryGroup__c> summaryLines = [Select Id,Nokia_CPQ_Reserves__c,NokiaCPQ_Extended_CNP_2__c,NokiaCPQ_Extended_NP__c from Apttus_Config2__SummaryGroup__c Where  Name = 'Total (One Time)' AND Apttus_Config2__ConfigurationId__c = :ConfigId LIMIT 1];
 
						 if(PageAction == tempData[0].Action_Name__c){
							Decimal differnceCNP = (summaryLines[0].NokiaCPQ_Extended_CNP_2__c - (summaryLines[0].Nokia_CPQ_Reserves__c*summaryLines[0].NokiaCPQ_Extended_CNP_2__c)/100).setScale(2, RoundingMode.HALF_UP);
							 system.debug('differnceCNP---in loop'+differnceCNP + ' NP**' + summaryLines[0].NokiaCPQ_Extended_NP__c);
							if(differnceCNP != summaryLines[0].NokiaCPQ_Extended_NP__c ){	   
								system.debug('PageAction'+PageAction);
								result.isSuccess = false;
								result.Messages.add(new ApexPages.Message(ApexPages.Severity.ERROR, Nokia_CPQ_Constants.AdvacncePricing_error));				   
								
								return result;
							}
						}
					}
				}
			}
 
			return result;
		}
	   
		
 
	/* Method Name   : validateCart
	* Developer	  : Rupesh Sharma
	* Description	: This method returns true when the CAD is applied on any Sub Total Lines */	   
		@TestVisible private Boolean isChargeTypeMaintenance(List<Apttus_Config2__SummaryGroup__c> summaryLines) {
			/*maintenance Fee Flag*/
			@TestVisible Boolean isMaintenanceFee = FALSE;
	
			for(Apttus_Config2__SummaryGroup__c osl:summaryLines)
			{
				if(osl.Apttus_Config2__Description__c!=null && osl.Apttus_Config2__AdjustmentAmount__c!=null&&!osl.Apttus_Config2__Description__c.equalsIgnoreCase('Total (One Time) (One Time)')&&Double.valueOf(osl.Apttus_Config2__AdjustmentAmount__c)>0.00)
				{
					isMaintenanceFee = TRUE;
				}
			}
			return isMaintenanceFee;
		}
 
	/* Method Name   : validateCart
	* Developer	  : Rupesh Sharma
	* Description	: This method returns true when the CAD is applied wrong */	   
		@TestVisible private Boolean isCADCorrect(List<Apttus_Config2__SummaryGroup__c> summaryLines) {
		   /*CAD discount Flag*/
			@TestVisible Boolean isCADcorrect = FALSE;
			for(Apttus_Config2__SummaryGroup__c osl:summaryLines)
			{
				if(osl.Apttus_Config2__Description__c!=null && osl.Apttus_Config2__AdjustmentAmount__c!=null&&osl.Apttus_Config2__Description__c.equalsIgnoreCase('Total (One Time) (One Time)')&& osl.Apttus_Config2__AdjustmentAmount__c>osl.Apttus_Config2__ExtendedPrice__c)
				{
					isCADcorrect = TRUE;
				}
			}
			return isCADcorrect;
		}
   /*Method name validate cart
	*developer : heema solanki
	*Description : this method will return true if quote amunt is less than 500 for LEO */
	  @TestVisible private Boolean isValidLEOAmount(List<Apttus_Config2__SummaryGroup__c> summaryLines) { 
		/*valid LEO amount check*/
		@TestVisible Boolean isValidLEOAmount = FALSE;
		for(Apttus_Config2__SummaryGroup__c osl:summaryLines)
		{
			if(osl.Apttus_Config2__Description__c!=null && osl.Apttus_Config2__Description__c.equalsIgnoreCase('Total (One Time) (One Time)') && osl.NokiaCPQ_Net_Price__c < 500)
			{
				isValidLEOAmount = TRUE;
			}
		}
	  
		return isValidLEOAmount;
	}
	   
	/* Method Name   : validateCart
	* Developer	  : Apttus
	* Description	: OOTB */		   
		global Apttus_Config2.CustomClass.ValidationResult validateRampLineItems(Apttus_Config2.ProductConfiguration cart, List<Apttus_Config2.LineItem> rampLineItems) {
			Apttus_Config2.CustomClass.ValidationResult result= new Apttus_Config2.CustomClass.ValidationResult(true);
			return result;
		}
 
	/* Method Name   : validateCart
	* Developer	  : Apttus
	* Description	: OOTB */		   
		global Apttus_Config2.CustomClass.ValidationResult validateAssetItems(Apttus_Config2.ProductConfiguration cart, List<Apttus_Config2__TempRenew__c> assetItems) {
		   
			Apttus_Config2.CustomClass.ValidationResult result= new Apttus_Config2.CustomClass.ValidationResult(true);
			return result;
		}
 
	   
	}