src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__ContractNumbers__c</fullName>
        <description>A comma separated list of contract numbers associated with the line item</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Numbers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PricingStatus__c</fullName>
        <description>The pricing status</description>
        <label>Pricing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Is_Maintenance_Quote__c</fullName>
        <formula>Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.NokiaCPQ_Is_Maintenance_Quote__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Maintenance Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_LEO_Discount__c</fullName>
        <formula>Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.NokiaCPQ_LEO_Discount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LEO Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio__c</fullName>
        <formula>IF( Apttus_Config2__ConfigurationId__r.Quote_Type__c == &apos;Direct CPQ&apos;, Apttus_Config2__ProductId__r.Direct_Portfolio__c ,Apttus_Config2__ProductId__r.Portfolio__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <formula>Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Quote_Type__c</formula>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_Config2__BusinessObjectType__c</fullName>
        <description>The type of the business object associated with the configuration</description>
        <label>Business Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                    <default>true</default>
                    <label>Agreement</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Collaboration Request</fullName>
                </value>
                <value>
                    <fullName>Favorite Configuration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ContractNumbers__c</fullName>
        <description>A comma separated list of contract numbers associated wth the cart</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Numbers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The current status of the configuration</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Ready For Approvals</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>In Collaboration</fullName>
                </value>
                <value>
                    <fullName>Ready For Finalization</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_IsMainSSPAdded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMainSSPAdded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio__c</fullName>
        <description>Req 6624: Constraint Rule Optimization By Removing Formula Fields an covert them in text fields</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <formula>Apttus_QPConfig__Proposald__r.Quote_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Direct_Price_List_Number__c</fullName>
        <description>Comma separated Price List Numbers for all applicable CLPs</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Direct Price List Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsCollaborationProgress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCollaborationInProgress</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Existing_IONMaint_Contract__c</fullName>
        <label>Existing Maintenance Contract?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>NokiaCPQ_Portfolio__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Is_Maintenance_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Maintenance Only Quotes all product prices are displayed as 0.00.</inlineHelpText>
        <label>Maintenance Only Quote?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_LEO_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lab Equipment Quote?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Last_Reprice__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Reprice</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Needs_Reprice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Pricing criteria has changed and thus quote needs to be repriced before validation.</inlineHelpText>
        <label>Needs Reprice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_No_of_Years__c</fullName>
        <label>No. of Years for Maintenance</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>NokiaCPQ_Portfolio__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio__c</fullName>
        <label>Portfolio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Airscale Wifi</fullName>
                </value>
                <value>
                    <fullName>Fixed Access - FBA</fullName>
                    <label>Broadband Access Networks</label>
                </value>
                <value>
                    <fullName>Fixed Network</fullName>
                </value>
                <value>
                    <fullName>Fixed Networks</fullName>
                </value>
                <value>
                    <fullName>FastMile</fullName>
                    <label>Fixed Wireless Access</label>
                </value>
                <value>
                    <fullName>Global Services</fullName>
                </value>
                <value>
                    <fullName>IP Routing</fullName>
                </value>
                <value>
                    <fullName>Microwave</fullName>
                </value>
                <value>
                    <fullName>Modular Private Wireless Solution</fullName>
                </value>
                <value>
                    <fullName>Nokia Software</fullName>
                </value>
                <value>
                    <fullName>Nuage</fullName>
                </value>
                <value>
                    <fullName>Fixed Access - POL</fullName>
                    <label>Optical LAN</label>
                </value>
                <value>
                    <fullName>Optics</fullName>
                </value>
                <value>
                    <fullName>Optics - WaveLite</fullName>
                </value>
                <value>
                    <fullName>QTC</fullName>
                </value>
                <value>
                    <fullName>Wireless PON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Prior_Leo_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prior Leo Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Prior_Number_of_years__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Prior Number of years</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <description>To differentiate CPQ quotes from SWX Quotes</description>
        <formula>IF( 
	Apttus_Proposal__Opportunity__c != null, 
	IF( 
		AND(
			OR( 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Direct Sales Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Read Only Direct&apos; 
			), 
			isCQ__c = false
		   ), 
		IF(
			OR( 
				RecordTypeId = $Label.DS_QuoteEditRecordTypeId,
				RecordTypeId = $Label.DS_QuoteReadRecordTypeId 
			) , 
			&apos;Direct DS&apos;, 
			IF(OR( RecordTypeId = $Label.NokiaCPQ_DirectQuoteID,RecordTypeId = $Label.NokiaCPQ_DirectReadOnlyQuoteID) , &apos;Direct CPQ&apos;, &apos;NCQ&apos;)
			), 
		IF( 
			AND(
			  OR( 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Indirect Sales Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Create Indirect Workspace Opportunity&apos;, 
				Apttus_Proposal__Opportunity__r.RecordType.Name = &apos;Read Only Indirect&apos; 
			     ),
				isCQ__c = false
			), 
			IF(
				OR(
					RecordTypeId = $Label.DS_QuoteEditRecordTypeId , 
					RecordTypeId = $Label.DS_QuoteReadRecordTypeId), 
				&apos;Indirect DS&apos;, 
				&apos;Indirect CPQ&apos;
			   ), 
			IF(isCQ__c,&apos;CQ&apos;,&apos;&apos;) 
		) 
	), 
	&apos;&apos; 
)</formula>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reprice_In_Progress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for requirement 3647 in Release 3</description>
        <label>Reprice In Progress</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NokiaCPQ_Reprice_Quote_Ctrlr.cls
/*************************************************************
@Name: NokiaCPQ_Reprice_Quote_Ctrlr
@Author: Accenture
@Description: This class contains Logic for quote level reprice
******************************************************************/ 

public with sharing class NokiaCPQ_Reprice_Quote_Ctrlr 
{
	public Apttus_Proposal__Proposal__c quote;
	public String currentquoteId {get;set;}
	public List<Apttus_Config2__ProductConfiguration__c> productConfigs = new List<Apttus_Config2__ProductConfiguration__c>();
	public List<Apttus_Config2__LineItem__c> configLineItems = new List<Apttus_Config2__LineItem__c>();
	public List<Apttus_Config2__LineItem__c> configLineItemsUpdate = new List<Apttus_Config2__LineItem__c>();
	public List<Apttus_Config2__LineItem__c> configLineItemsOptions = new List<Apttus_Config2__LineItem__c>();
	public List<Apttus_Config2__LineItem__c> configLineItemsBundles = new List<Apttus_Config2__LineItem__c>();
	public List<Apttus_Config2__LineItem__c> configLineItemsArcadiaBundles = new List<Apttus_Config2__LineItem__c>();
	public List<Apttus_Config2__LineItem__c> configLineItemsBundleAndSRSMaint = new List<Apttus_Config2__LineItem__c>();
	public List<Apttus_Config2__LineItem__c> configLineItemsBundlesAgain = new List<Apttus_Config2__LineItem__c>();
	public List<Apttus_Config2__LineItem__c> productPriceconfigLineItems = new List<Apttus_Config2__LineItem__c>();
	public List<Apttus_Config2__LineItem__c> productPriceconfigLineItemFinal = new List<Apttus_Config2__LineItem__c>();
	public Apttus_Config2__ProductConfiguration__c productConfig; 
	public Id configId;
	public Boolean actionPollerActive{get; set;}
	public Boolean hasPendingItems{get; set;} 
	public Boolean flagUpdatePrice; 
	public Apttus_CpqApi.CPQ.UpdatePriceRequestDO objUpdatePriceRequestDO ;
	public Boolean pricingNotRequired;
	public Boolean isError{get; set;}
	public Boolean isChangedLEO{get; set;}
	public Integer totalLineItems {get; set;}
	public transient Integer completedLineItems {get; set;} 
	public Boolean isFinalized {get; set;}
	public Boolean isDirect {get; set;}
	public Integer countOptions {get; set;}
	public Integer countBundles {get; set;}
	public Integer countSRSMaintenance {get; set;}
	public Integer countArcadiaItems {get; set;}
	public Integer countFlag {get; set;}
	public List<Apttus_Config2__LineItem__c> configLineItemsSRSMaintenance = new List<Apttus_Config2__LineItem__c>();
	Set<String> srsMaintenanceSet = new Set<String>{Nokia_CPQ_Constants.NOKIA_PRODUCT_NAME_SRS,Nokia_CPQ_Constants.NOKIA_YEAR2_BEYOND,Nokia_CPQ_Constants.NOKIA_YEAR1_MAINTENANCE,Nokia_CPQ_Constants.NOKIA_PRODUCT_NAME_SSP};
	
	//constructor defined

	public NokiaCPQ_Reprice_Quote_Ctrlr(){
	isChangedLEO=false;
		currentquoteId = ApexPages.currentPage().getParameters().get(Nokia_CPQ_Constants.QUOTEIDPARAMETER);
		quote = [Select id,NokiaCPQ_Last_Reprice__c,NokiaCPQ_Needs_Reprice__c, Reprice_In_Progress__c, IsCollaborationProgress__c,Quote_Type__c,Direct_Price_List_Number__c,NokiaCPQ_Is_Maintenance_Quote__c,NokiaCPQ_Portfolio__c,NokiaCPQ_Prior_Leo_Value__c,NokiaCPQ_LEO_Discount__c,NokiaCPQ_No_of_Years__c,NokiaCPQ_Existing_IONMaint_Contract__c,NokiaCPQ_Prior_Number_of_years__c from Apttus_Proposal__Proposal__c where id = :currentquoteId]; 
		
		//Heema: Req 6383
		if(quote.NokiaCPQ_Is_Maintenance_Quote__c){
		productConfigs = [Select id,Apttus_Config2__Status__c,Apttus_Config2__ContractNumbers__c,NokiaCPQ_IsMainSSPAdded__c from Apttus_Config2__ProductConfiguration__c where Apttus_QPConfig__Proposald__c = :currentquoteId AND Apttus_Config2__BusinessObjectType__c =: Nokia_CPQ_Constants.NOKIA_PROPOSAL AND ((Apttus_Config2__Status__c = 'Saved' OR Apttus_Config2__Status__c='Finalized')) Order by CreatedDate DESC];
		}
		else{
		productConfigs = [Select id,Apttus_Config2__Status__c,Apttus_Config2__ContractNumbers__c,NokiaCPQ_IsMainSSPAdded__c from Apttus_Config2__ProductConfiguration__c where Apttus_QPConfig__Proposald__c = :currentquoteId AND Apttus_Config2__BusinessObjectType__c =: Nokia_CPQ_Constants.NOKIA_PROPOSAL Order by CreatedDate DESC]; 
		}
		
		if(quote.Quote_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.QUOTE_TYPE_DIRECTCPQ)){
			isDirect = true;
		}
		else if(quote.Quote_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.QUOTE_TYPE_INDIRECTCPQ)){
			isDirect = false;
		}
		//heema D-13889
		if(quote.NokiaCPQ_No_of_Years__c!=quote.NokiaCPQ_Prior_Number_of_years__c){
		
		isChangedLEO = true;
		}

		//Varsha: Fixed for Defect D-7623
		if(!productConfigs.isEmpty()){
			configId = productConfigs.get(0).Id;
		}   
	}
	
	public void callConstraintRule(){
		if(isChangedLEO){
				List<Integer> primaryLines = new List<Integer>();
				Apttus_CPQApi.CPQWebService.associateConstraintRules(configId,primaryLines);
				Apttus_CPQApi.CPQWebService.applyConstraintRules(configId, false);
		}
	}
	//This method uses logic for reprice
	public PageReference init(){
		try{
			if(quote.NokiaCPQ_Needs_Reprice__c == false){
				pricingNotRequired = true;
				hasPendingItems = false;
				actionPollerActive = false;
				isError = true;
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,Nokia_CPQ_Constants.SINGLEREPRICENOTREQ));
			}
			else if(quote.NokiaCPQ_Needs_Reprice__c == true && quote.IsCollaborationProgress__c == true){
				pricingNotRequired = true;
				hasPendingItems = false;
				actionPollerActive = false;
				isError = true;
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,Nokia_CPQ_Constants.SINGLEREPRICEINCOLLAB));
			}
			else if(configId == null){
				quote.NokiaCPQ_Needs_Reprice__c = false;
				Database.update(quote, false);
				pricingNotRequired = true;
				hasPendingItems = false;
				actionPollerActive = false;
				isError = true;
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,Nokia_CPQ_Constants.CONFIGUREFIRST));
			}
			else{
				//update Product Config with Contract Number for Direct
				if(isDirect && quote.Direct_Price_List_Number__c != productConfigs.get(0).Apttus_Config2__ContractNumbers__c){
					productConfigs.get(0).Apttus_Config2__ContractNumbers__c = quote.Direct_Price_List_Number__c;
					Database.update(productConfigs.get(0), false);
				}
				If(isChangedLEO){
					if(quote.NokiaCPQ_No_of_Years__c.equalsIgnoreCase(Nokia_CPQ_Constants.NOKIA_1YEAR)){
						productConfigs.get(0).NokiaCPQ_IsMainSSPAdded__c = true;
					}
					else{
						productConfigs.get(0).NokiaCPQ_IsMainSSPAdded__c = false;
					}
					Database.update(productConfigs.get(0), false);
				}
				configLineItems = [Select Id,Apttus_Config2__PricingStatus__c, NokiaCPQ_Configuration_Type__c,Apttus_Config2__IsPrimaryLine__c, Apttus_Config2__ChargeType__c,Apttus_Config2__LineType__c,Apttus_Config2__IsHidden__c from Apttus_Config2__LineItem__c where Apttus_Config2__ConfigurationId__c = :configId];
				//Heema : 6383 Req Start
				if(quote.NokiaCPQ_Is_Maintenance_Quote__c){
					For(Apttus_Config2__LineItem__c productPriceconfigLineItem : configLineItems){
						if(productPriceconfigLineItem.Apttus_Config2__ChargeType__c.equalsIgnoreCase('Standard Price')){
						productPriceconfigLineItem.Apttus_Config2__IsHidden__c = false;
						productPriceconfigLineItems.add(productPriceconfigLineItem);
						}
					}
				
					if(!productPriceconfigLineItems.isEmpty()){
						Database.update(productPriceconfigLineItems, false);
					}
				}
				//Heema : 6383 Req End
				if(!configLineItems.isEmpty()){ 
					quote.Reprice_In_Progress__c = true;				  
					Database.update(quote, false);
					totalLineItems  = configLineItems.size();
					system.debug('configLineItems before status update>>'+configLineItems);

					for(Apttus_Config2__LineItem__c configLineItem : configLineItems){
						if(isDirect == true){
							//top level bundles
							if(configLineItem.Apttus_Config2__LineType__c.equalsIgnoreCase(Nokia_CPQ_Constants.NOKIA_PRODUCT_SERVICES) && configLineItem.NokiaCPQ_Configuration_Type__c != null && configLineItem.NokiaCPQ_Configuration_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.BUNDLE) && configLineItem.Apttus_Config2__ChargeType__c.equalsIgnoreCase(Nokia_CPQ_Constants.STANDARD_PRICE)){
								configLineItem.Apttus_Config2__PricingStatus__c = Nokia_CPQ_Constants.PENDING_STRING;
								configLineItemsBundles.add(configLineItem);
							}
							//Arcadia items
							else if(configLineItem.Apttus_Config2__LineType__c.equalsIgnoreCase(Nokia_CPQ_Constants.NOKIA_OPTION) && configLineItem.NokiaCPQ_Configuration_Type__c != null && configLineItem.NokiaCPQ_Configuration_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.BUNDLE)){
								configLineItem.Apttus_Config2__PricingStatus__c= Nokia_CPQ_Constants.PENDING_STRING;
								configLineItemsArcadiaBundles.add(configLineItem);
							}
							//options with standard price charge type
							else if(configLineItem.NokiaCPQ_Configuration_Type__c.equalsIgnoreCase(Nokia_CPQ_Constants.NOKIA_STANDALONE) && configLineItem.Apttus_Config2__ChargeType__c.equalsIgnoreCase(Nokia_CPQ_Constants.STANDARD_PRICE)){
								configLineItem.Apttus_Config2__PricingStatus__c= Nokia_CPQ_Constants.PENDING_STRING;
								configLineItemsOptions.add(configLineItem);
							}
							//options with charge type other than standard price
							else if(srsMaintenanceSet.contains(configLineItem.Apttus_Config2__ChargeType__c)){
								configLineItem.Apttus_Config2__PricingStatus__c= Nokia_CPQ_Constants.PENDING_STRING;
								configLineItemsSRSMaintenance.add(configLineItem);
							}
							if(quote.NokiaCPQ_Portfolio__c == 'Nokia Software'){
								if(configLineItem.Apttus_Config2__LineType__c.equalsIgnoreCase(Nokia_CPQ_Constants.NOKIA_PRODUCT_SERVICES)){
									configLineItem.Apttus_Config2__PricingStatus__c= Nokia_CPQ_Constants.PENDING_STRING;
									configLineItemsBundlesAgain.add(configLineItem);
								}
							}
						}
						else if(isDirect == false){
							// For Indirect, both Bundles and Options are processed together
							configLineItem.Apttus_Config2__PricingStatus__c= 'Pending';
							configLineItemsOptions.add(configLineItem);							 
						}  
					}
					system.debug('configLineItemsBundles-->'+configLineItemsBundles);
					system.debug('configLineItemsArcadiaBundles-->'+configLineItemsArcadiaBundles);
					system.debug('configLineItemsOptions-->'+configLineItemsOptions);
					system.debug('configLineItemsSRSMaintenance-->'+configLineItemsSRSMaintenance);
					
					Database.update(configLineItemsOptions,false); 
					countOptions = configLineItemsOptions.size();
					if(isDirect == true){
						countBundles = configLineItemsBundles.size();
						countSRSMaintenance = configLineItemsSRSMaintenance.size();
						countArcadiaItems = configLineItemsArcadiaBundles.size();
					}
				}
				
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,Nokia_CPQ_Constants.REPRICING_WAIT_MSG));
				pricingNotRequired  = false;
				hasPendingItems = false; 
				actionPollerActive = true;
				objUpdatePriceRequestDO = new Apttus_CpqApi.CPQ.UpdatePriceRequestDO();
				objUpdatePriceRequestDO.CartId = configId;
				isError = false;
				
				if(!Test.isRunningTest()){
				Apttus_CpqApi.CPQ.UpdatePriceResponseDO result = Apttus_CpqApi.CPQWebService.updatePriceForCart(objUpdatePriceRequestDO);
					hasPendingItems = result.IsPricePending;
					system.debug('hasPendingItems in runningtest--> '+hasPendingItems);
				}
				else{
				   hasPendingItems = true; 
				}
				
				if(hasPendingItems){
					actionPollerActive = true;
					flagUpdatePrice = true;
					system.debug('flagUpdatePrice-->'+flagUpdatePrice);
				}
			  
				if(isDirect == true){
					completedLineItems = countOptions;
					countFlag=1;
				}
				else if(isDirect == false){
					completedLineItems = [Select Count() from Apttus_Config2__LineItem__c where Apttus_Config2__ConfigurationId__c = :configId AND Apttus_Config2__PricingStatus__c =: Nokia_CPQ_Constants.COMPLETE_MSG]; 
				}
			}
		}
		catch(Exception e){
			System.debug('Excpetion'+e);
			ExceptionHandler.addException(e,NokiaCPQ_Reprice_Quote_Ctrlr.class.getName(),Nokia_CPQ_Constants.ERROR_MSD);
		}

		return null;
	}

	//This method contains logic to update the price
	public void doUpdatePrice(){
		try{
			if(flagUpdatePrice == true){  
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,Nokia_CPQ_Constants.REPRICING_WAIT_MSG));	  
				objUpdatePriceRequestDO = new Apttus_CpqApi.CPQ.UpdatePriceRequestDO();
				objUpdatePriceRequestDO.CartId = configId;
				if(!Test.isRunningTest()){
					Apttus_CpqApi.CPQ.UpdatePriceResponseDO result = Apttus_CpqApi.CPQWebService.updatePriceForCart (objUpdatePriceRequestDO);
					hasPendingItems = result.IsPricePending; 
				
					system.debug('doUpdatePrice hasPendingItems-->'+hasPendingItems);
					List<Integer> pendingLineNumbers = result.PendingLineNumbers;  
					List<Integer> completedLineNumbers = result.CompletedLineNumbers;
				}
				else{
				   hasPendingItems = false; 
				}
				//Update arcadia items in 2nd call
				if(configLineItemsArcadiaBundles.size() > 0 && hasPendingItems == False && isDirect == true){   
					Database.update(configLineItemsArcadiaBundles,false);
					hasPendingItems = true; 
					completedLineItems = countOptions+countArcadiaItems;
					countFlag = 2;
					configLineItemsArcadiaBundles.clear();
					system.debug('in 2nd call configLineItemsArcadiaBundles' + completedLineItems);
				}
				
				//Update Main Bundle in 3rd call
				if(configLineItemsArcadiaBundles.size()==0 && configLineItemsBundles.size() > 0 && isDirect == true && hasPendingItems == False){   
					Database.update(configLineItemsBundles,false);
					hasPendingItems = true; 
					completedLineItems = countOptions+countArcadiaItems+countBundles;
					countFlag = 3;
					configLineItemsBundles.clear();
					system.debug('in 3rd call configLineItemsBundles' + completedLineItems);
				}
				
				//Update Maintenance Lines in 4th call
				if(configLineItemsArcadiaBundles.size()==0 && configLineItemsBundles.size()==0 && configLineItemsSRSMaintenance.size()>0 && isDirect == true && hasPendingItems == False){	   
					Database.update(configLineItemsSRSMaintenance,false);
					hasPendingItems = true;
					completedLineItems = countOptions+countBundles+countArcadiaItems+countSRSMaintenance;
					countFlag=4;
					configLineItemsSRSMaintenance.clear();
					system.debug('in 4th call configLineItemsSRSMaintenance' + completedLineItems);
					  
				}
				
				//Update Main Bundle again in 5th call
				if(configLineItemsSRSMaintenance.size()==0 && countFlag == 4 && isDirect == true && hasPendingItems == False){
					
					countFlag=5;
					completedLineItems = countOptions+countBundles+countArcadiaItems+countSRSMaintenance;
					system.debug('in 5th call configLineItemsBundlesAgain' + completedLineItems);  
					 if(!configLineItemsBundlesAgain.isEmpty()){
						Database.update(configLineItemsBundlesAgain,false);
						hasPendingItems = true; 
						configLineItemsBundlesAgain.clear();
					}
				}

				//Set completedlineItems for Direct
				if(isDirect && countFlag == 1){
					completedLineItems = countOptions;
				}
				else if(isDirect && countFlag == 2){
					completedLineItems = countOptions+countArcadiaItems;
				}
				else if(isDirect && countFlag == 3){
					completedLineItems = countOptions+countArcadiaItems+countBundles;
				}
				else if(isDirect){
					completedLineItems = countOptions+countBundles+countArcadiaItems+countSRSMaintenance;
				}

				if(hasPendingItems == false){	
					
					ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,Nokia_CPQ_Constants.REPRICING_COMPLETE_MSG));				  
					Apttus_CpqApi.CPQ.FinalizeCartRequestDO requestFinalizeCart = new Apttus_CpqApi.CPQ.FinalizeCartRequestDO(); 
					requestFinalizeCart.CartId = configId; 
					if(!Test.isRunningTest()){				   
						Apttus_CpqApi.CPQ.FinalizeCartResponseDO responseFinalizeCart = Apttus_CpqApi.CPQWebService.finalizeCart(requestFinalizeCart);
				
						if(responseFinalizeCart.IsSuccess){
							ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,Nokia_CPQ_Constants.FINALIZE_MSG));
							isFinalized = true;
							actionPollerActive = false; 
							quote.NokiaCPQ_Last_Reprice__c = System.Now();
							quote.NokiaCPQ_Needs_Reprice__c = false;
							quote.Reprice_In_Progress__c = false;
						
							update quote;
						}
					}
				}
				else if(hasPendingItems == true ){ 
					actionPollerActive = true;  
				}

				if(countFlag == 5 && isDirect == true){
					completedLineItems = countOptions+countBundles+countSRSMaintenance+countArcadiaItems;
				}
				else if(isDirect == false){
					if(quote.NokiaCPQ_Is_Maintenance_Quote__c){
						For(Apttus_Config2__LineItem__c productPriceconfigLineItem : productPriceconfigLineItems){
						productPriceconfigLineItem.Apttus_Config2__IsHidden__c = true;
						productPriceconfigLineItemFinal.add(productPriceconfigLineItem);
					}
				
					if(!productPriceconfigLineItemFinal.isEmpty()){
						Database.update(productPriceconfigLineItemFinal, false);
					}
					}
					else{
					completedLineItems = [Select Count() from Apttus_Config2__LineItem__c where Apttus_Config2__ConfigurationId__c = :configId AND Apttus_Config2__PricingStatus__c =: Nokia_CPQ_Constants.COMPLETE_MSG]; 
					}
				}
			}
		}
		catch(Exception e){
			ExceptionHandler.addException(e,NokiaCPQ_Reprice_Quote_Ctrlr.class.getName(),Nokia_CPQ_Constants.ERROR_MSD);
		}
	}

	//This method contains the logic to cancel button action.
	public PageReference cancel(){
		return new PageReference(Nokia_CPQ_Constants.SLASH+currentquoteId);
	}
}