src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/HWS_Sent_To_SOO__c.field-meta.xml
<CustomField>
    <fullName>HWS_Sent_To_SOO__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created with reference to the User Story.</description>
    <label>Sent To SOO</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Interface_Log__c.object
<CustomObject>
    <description>This object will be used for Interface/error handling</description>
    <fields>
        <fullName>Comment__c</fullName>
        <description>Comment section for Error Log</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comment</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Interface_Type__c</fullName>
        <description>What are the type of Interface</description>
        <label>Interface Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ALCR ACC SYNC</fullName>
                </value>
                <value>
                    <fullName>Business Hours</fullName>
                </value>
                <value>
                    <fullName>CAPSV to SF</fullName>
                </value>
                <value>
                    <fullName>CARES Authorised Entitlement</fullName>
                </value>
                <value>
                    <fullName>CARES Child Service Contract</fullName>
                </value>
                <value>
                    <fullName>CARES Contract Line Item</fullName>
                </value>
                <value>
                    <fullName>CARES Parent Service Contract</fullName>
                </value>
                <value>
                    <fullName>CART Interface</fullName>
                </value>
                <value>
                    <fullName>CDB/CARES Interface Generic Error</fullName>
                </value>
                <value>
                    <fullName>CDB CARE Contract Type</fullName>
                </value>
                <value>
                    <fullName>CDB CARE Service Contract</fullName>
                </value>
                <value>
                    <fullName>CDB ServiceContract</fullName>
                </value>
                <value>
                    <fullName>CDB Supplier</fullName>
                </value>
                <value>
                    <fullName>CMD Pack1 Account Sync</fullName>
                </value>
                <value>
                    <fullName>CMD Pack3 P20ID Sync</fullName>
                </value>
                <value>
                    <fullName>CMD Pack4 Sales Role Sync</fullName>
                </value>
                <value>
                    <fullName>CMD Pack4 User Sync</fullName>
                </value>
                <value>
                    <fullName>CMD Pack 5 Account Sync</fullName>
                </value>
                <value>
                    <fullName>Contract Line Item</fullName>
                </value>
                <value>
                    <fullName>CQ Process Quote</fullName>
                </value>
                <value>
                    <fullName>CQ Sync Offer</fullName>
                </value>
                <value>
                    <fullName>CQ Sync Quote</fullName>
                </value>
                <value>
                    <fullName>CQ UpdateQuote/Pricing</fullName>
                </value>
                <value>
                    <fullName>CQ UpdateQuote/Status</fullName>
                </value>
                <value>
                    <fullName>CSOD Certification Sync</fullName>
                </value>
                <value>
                    <fullName>CSOD Course Sync</fullName>
                </value>
                <value>
                    <fullName>CSOD Curriculum Mapping Table Sync</fullName>
                </value>
                <value>
                    <fullName>Customer S2S</fullName>
                </value>
                <value>
                    <fullName>Customers SSO JIT</fullName>
                </value>
                <value>
                    <fullName>DataHub</fullName>
                </value>
                <value>
                    <fullName>SOO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>What is the type of the message</description>
        <label>Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>What is the status of the error/interface log</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Batch Update Opportunity Managers - Apex Batch Logs</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>Partial Success (Race Conditions Occurred)</fullName>
                </value>
                <value>
                    <fullName>Request queued for future callout</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Post Processing Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interface Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interface Log	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interface Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HWS_CancelcaseSendSRtoSOO_SVC.cls
/*****************************************************************
Description:	Service request to Submit the Json created by HWS_CancelSRRequest class to SOO 
History																														
DATE		AUTHOR		  CHANGE
12/04/2019	  Vinod T		 Created
*****************************************************************/
Public without sharing class HWS_CancelcaseSendSRtoSOO_SVC{
	//Public  HWS_SendServiceRequesttoSOO_SVC(){}
	//@AuraEnabled
	//Public Boolean isSenttoSOO; 
	/*****************************************************************
Description: Future method callout to submit parent case to SOO
Parameters: ParentCaseId
Returns: NA
Throws [Exceptions]: [optional]														  
History															
DATE			AUTHOR		  CHANGE
12/04/2019	  Vinod T		 Created
*****************************************************************/
	@AuraEnabled
	Public Static processResponse sendToSOO(Id parentCaseId,Id childId)
	{ 
		ProcessResponse pr=new ProcessResponse();
		HWS_CancelCaseSRRequest objSR = new HWS_CancelCaseSRRequest();
		HWS_CancelCaseSRRequest.SOORequestBody createSRJSON =objSR.cancelSRRequest(parentCaseId,childId);	
		HTTP http; 
		HTTPResponse response; 
		HTTPRequest request ;
		String stCaseNumber=createSRJSON.caseNumber;
		try{ 
			String caseNumber;
			request = new HTTPRequest();
			request.setEndpoint('callout:IPAAS_CANCEL_SR');
			System.debug('Json created ===='+createSRJSON);
			request.setHeader('Content-Type','application/json');
			request.setbody(createSRJSON.jsonPayload);
			System.debug('====Request Body to send SOO===='+createSRJSON.jsonPayload);
		  //  request.setbody(null);
			request.setMethod('POST');
			request.setTimeout(12000);
			http = new HTTP();
			 response =http.send(request);
			 System.debug('Code**'+response.getStatus());
			Case parentCase = new Case(id=parentCaseId);
			//parentCase.HWS_Sent_To_SOO__c =true;
			if(response.getStatusCode()==200){
				 System.debug('**Response Body**'+response.getBody());
				pr = (ProcessResponse)JSon.deserialize(response.getBody(),ProcessResponse.class);
				pr.isError=false;
				pr.statusCode=response.getStatusCode();
				pr.message=response.getStatus();
				System.debug('response status'+pr.Status);
			}else{
		   
				pr.isError=true;
				pr.SOORequestID=null;
				pr.statusCode=response.getStatusCode();
				pr.message=response.getStatus();  
				createOutboundErrorLog(pr,parentCaseId,null,stCaseNumber);
			}
		
			
		}catch(exception ex){
			pr.isError=true;
			pr.SOORequestID=null;
			pr.statusCode=null;
			pr.message=ex.getMessage();
			System.debug('Exception ===== '+ex.getMessage());
			createOutboundErrorLog(pr,parentCaseId,null,stCaseNumber); 
		   
		}
		return pr;
	}
	//Method used to log the inbound response errors
	Public Static void createOutboundErrorLog(ProcessResponse response,Id caseId,Integer resStatusCode,String caseNumber){
		
		try{
			Interface_log__c ilogCallout = new Interface_log__c();
			ilogCallout.Name='CaseNumber ' + caseNumber;
			ilogCallout.Interface_Type__c = 'SOO';
			ilogCallout.Message_Type__c = 'Outbound';
			ilogCallout.Status__c ='Failure';
			ilogCallout.Comment__c=response.message;	
			Database.insert(ilogCallout);
			
		}
		catch(exception ex){
			 System.debug('Exception***'+ex.getMessage());
		   
		}
	}
	
	Public class ProcessResponse{
		@AuraEnabled Public String message;
		@AuraEnabled Public Integer statusCode;
		@AuraEnabled Public String SOORequestID;
		@AuraEnabled Public Boolean isError;
		@AuraEnabled Public String Status;
		public ProcessResponse(){
			message='';
			isError=false;
			
		}
	}
}