src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>CH_Account_Name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/CH_BlockCases__c.field-meta.xml
<CustomField>
    <fullName>CH_BlockCases__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox become true based on trigger CH_BlacklistCaseReportTrigger</description>
    <label>Block Cases</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/CH_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>CH_BusinessUnit__c</fullName>
    <description>Reporting field: Get Product Business Unit into standard report types</description>
    <formula>Product.CH_Business_Unit__c</formula>
    <inlineHelpText>Reporting field: Get Product Business Unit into standard report types</inlineHelpText>
    <label>Rep: Product Business Unit</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/CH_CaseOriginSystem__c.field-meta.xml
<CustomField>
    <fullName>CH_CaseOriginSystem__c</fullName>
    <label>Case Origin System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ptf_fi</fullName>
            </value>
            <value>
                <fullName>ptf_in</fullName>
            </value>
            <value>
                <fullName>ptf_us</fullName>
            </value>
            <value>
                <fullName>ptf_cn</fullName>
            </value>
            <value>
                <fullName>tmobile-tim</fullName>
            </value>
            <value>
                <fullName>tcom-dtag</fullName>
            </value>
            <value>
                <fullName>orange-irma</fullName>
            </value>
            <value>
                <fullName>vodafone</fullName>
            </value>
            <value>
                <fullName>Schweizer-Armee</fullName>
            </value>
            <value>
                <fullName>megafon</fullName>
            </value>
            <value>
                <fullName>telefonica</fullName>
            </value>
            <value>
                <fullName>pnms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/CH_EntitlementException__c.field-meta.xml
<CustomField>
    <fullName>CH_EntitlementException__c</fullName>
    <label>Entitlement Exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Not Listed</fullName>
            </value>
            <value>
                <fullName>Covered Network Element Asset Not Listed</fullName>
            </value>
            <value>
                <fullName>Covered Product Asset Not Listed</fullName>
            </value>
            <value>
                <fullName>Entitlement Not Listed</fullName>
            </value>
            <value>
                <fullName>Entitlement Script Verification Required</fullName>
            </value>
            <value>
                <fullName>Entitlement Script Verified Manually</fullName>
            </value>
            <value>
                <fullName>Network Element Asset Not Listed</fullName>
            </value>
            <value>
                <fullName>No Exception</fullName>
                <default>true</default>
                <label>No Exception</label>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/CH_EntitlementReport__c.field-meta.xml
<CustomField>
    <fullName>CH_EntitlementReport__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entitlement Report</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/CH_ExternalBridge__c.field-meta.xml
<CustomField>
    <fullName>CH_ExternalBridge__c</fullName>
    <description>Details of the Bridge with the customer.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>External Bridge</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/CH_Outage__c.field-meta.xml
<CustomField>
    <fullName>CH_Outage__c</fullName>
    <label>Outage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Severity__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/CH_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>CH_Product_Name__c</fullName>
    <formula>Product.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/CH_ServiceType__c.field-meta.xml
<CustomField>
    <fullName>CH_ServiceType__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
                <default>true</default>
                <label>Customer Support</label>
            </value>
            <value>
                <fullName>Internal Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <inlineHelpText>In case of system wide outage or major issue affecting all users, please create a P1/P2 incident ticket via our Global Support Desk.</inlineHelpText>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Information Request</fullName>
            </value>
            <value>
                <fullName>Critical- 2 Hours</fullName>
                <isActive>false</isActive>
                <label>Critical- 2 Hours</label>
            </value>
            <value>
                <fullName>High</fullName>
                <isActive>false</isActive>
                <label>High</label>
            </value>
            <value>
                <fullName>Moderate</fullName>
                <isActive>false</isActive>
                <label>Moderate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/CH_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store Case Handling specific settings</description>
    <fields>
        <fullName>SettingValue__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SettingValue</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CH_Settings</label>
</CustomObject>

src/objects/ErrorLog__c.object
<CustomObject>
    <description>Created As part of US NOKIASC-27623. This object will be used to capture the exception in Async methods.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Error ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CH_CaseProcessQueueable.cls
/****************************************
* Class Name : CH_CaseProcessQueueable
* Created Date: 01 April 2020
* Created By : TCS
* Last Modified by: TCS
* Description : To perform asynchronous calls from CH_CaseTriggerHandler 
* US : Code Opt - NOKIASC-27610 & 27611
*****************************************/
public class CH_CaseProcessQueueable implements Queueable{
	Public static List<ErrorLog__c> errorList = new List<ErrorLog__c>();
	Public Static List<FeedItem> chatterPostList = new List<FeedItem>();
	FeedItem newChatterPost = new FeedItem();
	List<Case> newCaseList = new List<Case>();
	Set<Id> caseIdSet = new Set<Id>();
	Map<Id,Case> oldCaseMap = new Map<Id,Case>();
	boolean afterInsertCheck;
	boolean afterUpdateCheck;
	String asyncType = 'QUEUEABLE';
	String className = 'CH_CaseTriggerHelper';
	String methodEntCheck='checkEntitlementExceptionCases';
	String methodBlockList='CH_BlacklistCaseReportTrigger';
	CH_Settings__c entExpAsyncCheck;
	CH_Settings__c blackListAsyncCheck;
	Boolean asyncBLCheck = false;
	Boolean asyncEECheck = false;
	public CH_CaseProcessQueueable(Set<Id> caseIdSet, Map<Id,Case> oldCaseMap, boolean afterInsertCheck, boolean afterUpdateCheck){
		this.caseIdSet = caseIdSet;
		this.oldCaseMap = oldCaseMap;
		this.afterInsertCheck = afterInsertCheck;
		this.afterUpdateCheck = afterUpdateCheck; 
		entExpAsyncCheck = CH_Settings__c.getValues('checkEntitlementExceptionCases');
		blackListAsyncCheck = CH_Settings__c.getValues('CH_BlacklistCaseReportTrigger');
		//Add Query on Case for new case list.
		newCaseList = [SELECT Id,CH_EntitlementReport__c,CH_BlockCases__c,CH_EntitlementException__c,AccountId,ProductId,CH_ServiceType__c,Country__c,ContactId,
					   CH_Product_Name__c,CH_Account_Name__c,RecordType.DeveloperName,RecordType.Name,Status,CH_BusinessUnit__c,Severity__c,CH_Outage__c,CaseNumber, 
					   Origin,Subject,CreatedDate,CH_ExternalBridge__c FROM Case WHERE Id in :caseIdSet];
		if(entExpAsyncCheck != null && entExpAsyncCheck.SettingValue__c == 'true'){
			asyncEECheck = true;
		}
		if(blackListAsyncCheck != null && blackListAsyncCheck.SettingValue__c == 'true'){
			asyncBLCheck = true;
		}
	}
	public void execute(QueueableContext context){
		if(afterInsertCheck){
			String triggerEvent='INSERT';
			try{
				//Added this for setEntitlementReport
				System.debug('CASE LIST IN QUEUEABLE BEFORE:'+newCaseList);
				if(!asyncEECheck)
					CH_CaseTriggerHelper.checkEntitlementExceptionCases(newCaseList);
				if(!asyncBLCheck)
					CH_CaseTriggerHelper.CH_BlacklistCaseReportTrigger(newCaseList);
				List<Case> updateCaseList = new List<Case>();
				System.debug('CASE LIST IN QUEUEABLE AFTER:'+newCaseList);
				for(case c:newCaseList){
					//check for null for both fields
					// CH_EntitlementReport__c,CH_BlockCases__c
					if(Test.isRunningTest())
					{
						System.debug('SUBJECT:'+c.Subject);
						if(c.Subject=='TEST2'){
							Integer a=10/0;
						}
					}
					if((c.CH_EntitlementReport__c != '' && c.CH_EntitlementReport__c != null) || c.CH_BlockCases__c != null)
						updateCaseList.add(c);
				}
				if(!updateCaseList.isEmpty()){
					//**changes related NOKIASC-27623 Code Opt start
					Database.SaveResult[] srList = Database.update(updateCaseList,false);
					for(Integer index = 0, size = srList.size(); index < size; index++){
						if(!srList[index].isSuccess()){
							System.debug('Failed records');
							for(Database.Error err: srList.get(index).getErrors()){
								List<CollaborationGroup> cgList = CH_ErrorLogUtils.getErrorLogChatterGroup();
								Id errorchatterGroupId;
								if(!cgList.isEmpty()){
									errorchatterGroupId = cgList[0].Id;
								}
								String recId;
								if(updateCaseList[index].id!=Null &&updateCaseList[index].id!=''){
									recId =  updateCaseList[index].id; 
								}else{
									recId = ''; 
								}
								System.debug('recId ===== '+recId);
								ErrorLog__c newErrorLog = New ErrorLog__c();
								if(String.isBlank(updateCaseList[index].CH_EntitlementReport__c)){
									newErrorLog = CH_ErrorLogUtils.createErrorLog(err.getMessage(),className,methodEntCheck, triggerEvent,asyncType,recId);
									String chatterPostBody = CH_ErrorLogUtils.createChatterbody(className, methodEntCheck,err);
									newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorchatterGroupId,chatterPostBody);
								}else{
									newErrorLog = CH_ErrorLogUtils.createErrorLog(err.getMessage(),className, 'CH_BlacklistCaseReportTrigger', triggerEvent,asyncType,recId);
									String chatterPostBody = CH_ErrorLogUtils.createChatterbody(className, methodEntCheck,err);
									System.debug('updateCaseList[index].Origin ====  '+updateCaseList[index].Origin);
									if(updateCaseList[index].Origin == 'S2S'){
										Map<String, Id> interfaceKeyUserGroups = CH_UserNotificationUTIL.getCollaborationGroupsForExternalSystems(new Set<String>{updateCaseList[index].CH_CaseOriginSystem__c});
										Id errorChatterGroupS2S = interfaceKeyUserGroups.get(updateCaseList[index].CH_CaseOriginSystem__c); 
										newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorChatterGroupS2S,chatterPostBody);  
									}else{
										newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorchatterGroupId,chatterPostBody);
									}
								}
								errorList.add(newErrorLog);
								chatterPostList.add(newChatterPost);
							}
						}
					}
					//**changes related NOKIASC-27623 Code Opt end.
				} 
			}catch(exception e){
				//**changes related NOKIASC-27623 Code Opt start
				List<CollaborationGroup> cgList = CH_ErrorLogUtils.getErrorLogChatterGroup();
				List<String> exStringList = New List<String>();
				Id errorchatterGroupId;
				String className;
				String methname;
				String methodName;
				List<String> methStringList = new List<String>();
				if(!cgList.isEmpty()){
					errorchatterGroupId = cgList[0].Id;
				}
				String exceptionString = e.getStackTraceString();
				if(String.isNotBlank(exceptionString)){
					exStringList = exceptionString.split('\\.');
				}
				if(!exStringList.isEmpty()){
					className = exStringList[1];
					methname = exStringList[2];	
				}
				if(String.isNotBlank(exceptionString)){
					methStringList = methName.split(':');
				}
				if(!methStringList.isEmpty()){
				   methodName = methStringList[0]; 
				}
				ErrorLog__c newErrorLog = New ErrorLog__c();
				newErrorLog = CH_ErrorLogUtils.createErrorLog(e.getMessage(), className, methodName,triggerEvent,asyncType,'');
				newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorchatterGroupId, e.getStackTraceString());
				errorList.add(newErrorLog);
				chatterPostList.add(newChatterPost);
				//**changes related NOKIASC-27623 Code Opt end.
			}
			try{
				CH_CaseTriggerUtilityHelper.createProductChatterGroup(newCaseList,new Map <Id,Case>(),triggerEvent);
				if(Test.isRunningTest())
				{
					//System.debug('SUBJECT:'+c.Subject);
					//if(c.Subject=='TEST2'){
					Integer a=10/0;
					//}
				}
			}
			catch(exception e){
				//**changes related NOKIASC-27623 Code Opt start
				List<CollaborationGroup> cgList = CH_ErrorLogUtils.getErrorLogChatterGroup();
				List<String> exStringList = New List<String>();
				Id errorchatterGroupId;
				String className;
				String methname;
				String methodName;
				List<String> methStringList = new List<String>();
				if(!cgList.isEmpty()){
					errorchatterGroupId = cgList[0].Id;
				}
				String exceptionString = e.getStackTraceString();
				if(String.isNotBlank(exceptionString)){
					exStringList = exceptionString.split('\\.');
				}
				if(!exStringList.isEmpty()){
					className = exStringList[1];
					methname = exStringList[2];	
				}
				if(String.isNotBlank(exceptionString)){
					methStringList = methName.split(':');
				}
				if(!methStringList.isEmpty()){
				   methodName = methStringList[0]; 
				}
				ErrorLog__c newErrorLog = New ErrorLog__c();
				newErrorLog = CH_ErrorLogUtils.createErrorLog(e.getMessage(), className, methodName,triggerEvent,asyncType,'');
				newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorchatterGroupId, e.getStackTraceString());
				errorList.add(newErrorLog);
				chatterPostList.add(newChatterPost);
				//**changes related NOKIASC-27623 Code Opt end.
			}
		}
		if(afterUpdateCheck){
			String triggerEvent='UPDATE';
			try{
				
				//Added this for setEntitlementReport
				System.debug('CASE LIST IN QUEUEABLE BEFORE#####:'+newCaseList);
				if(!asyncEECheck)
					CH_CaseTriggerHelper.checkEntitlementExceptionCases(oldCaseMap, newCaseList);	
				if(!asyncBLCheck)
					CH_CaseTriggerHelper.CH_BlacklistCaseReportTrigger(newCaseList);   
				List<Case> updateCaseList = new List<Case>();
				for(case c:newCaseList){
					//check for oldmap and new case list values for both fields
					//if(c.CH_EntitlementReport__c!=null || c.CH_BlockCases__c!=null)
					if(Test.isRunningTest())
					{
						if(c.Subject=='TEST2'){
							Integer a=10/0;
						}
					}
					if(!oldCaseMap.isempty() && (c.CH_EntitlementReport__c != oldCaseMap.get(c.Id).CH_EntitlementReport__c || c.CH_BlockCases__c != oldCaseMap.get(c.Id).CH_BlockCases__c)) {
						updateCaseList.add(c);
					}
				}
				if(!updateCaseList.isEmpty()){
					//**changes related NOKIASC-27623 Code Opt start
					Database.SaveResult[] srList = Database.update(updateCaseList,false);
					System.debug('srList.size() ===  '+srList.size());
					for(Integer index = 0, size = srList.size(); index < size; index++){
						if(!srList[index].isSuccess()){
							System.debug('inside failure update');
							for(Database.Error err: srList.get(index).getErrors()){
								List<CollaborationGroup> cgList = CH_ErrorLogUtils.getErrorLogChatterGroup();
								Id errorchatterGroupId;
								if(!cgList.isEmpty()){
									errorchatterGroupId = cgList[0].Id;
								}
								String recId;
								if(updateCaseList[index].id!=Null &&updateCaseList[index].id!=''){
									recId =  updateCaseList[index].id; 
								}else{
									recId = ''; 
								}
								ErrorLog__c newErrorLog = New ErrorLog__c();
								if(String.isBlank(updateCaseList[index].CH_EntitlementReport__c)){
									String chatterBody = CH_ErrorLogUtils.createChatterbody(className,methodEntCheck,err);
									newErrorLog = CH_ErrorLogUtils.createErrorLog(err.getMessage(),className,methodEntCheck,triggerEvent,asyncType,recId);
									newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorchatterGroupId,chatterBody);
								}else{
									String chatterBody = CH_ErrorLogUtils.createChatterbody(className,methodBlockList,err);
									newErrorLog = CH_ErrorLogUtils.createErrorLog(err.getMessage(),className,methodBlockList,triggerEvent,asyncType,recId);
									System.debug('updateCaseList[index].Origin ====  '+updateCaseList[index].Origin);
									if(updateCaseList[index].Origin == 'S2S'){
										Map<String, Id> interfaceKeyUserGroups = CH_UserNotificationUTIL.getCollaborationGroupsForExternalSystems(new Set<String>{updateCaseList[index].CH_CaseOriginSystem__c});
										Id errorChatterGroupS2S = interfaceKeyUserGroups.get(updateCaseList[index].CH_CaseOriginSystem__c); 
										newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorChatterGroupS2S,chatterBody);  
									}else{
										newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorchatterGroupId,chatterBody);
									}
								}
								errorList.add(newErrorLog);
								chatterPostList.add(newChatterPost);
							}
						}
						
					}
					//**changes related NOKIASC-27623 Code Opt end.
				} 
				System.debug('CASE LIST IN QUEUEABLE AFTER#####:'+newCaseList);
			}catch(exception e){
				//**changes related NOKIASC-27623 Code Opt start
				List<CollaborationGroup> cgList = CH_ErrorLogUtils.getErrorLogChatterGroup();
				List<String> exStringList = New List<String>();
				Id errorchatterGroupId;
				String className;
				String methname;
				String methodName;
				List<String> methStringList = new List<String>();
				if(!cgList.isEmpty()){
					errorchatterGroupId = cgList[0].Id;
				}
				String exceptionString = e.getStackTraceString();
				if(String.isNotBlank(exceptionString)){
					exStringList = exceptionString.split('\\.');
				}
				if(!exStringList.isEmpty()){
					className = exStringList[1];
					methname = exStringList[2];	
				}
				if(String.isNotBlank(exceptionString)){
					methStringList = methName.split(':');
				}
				if(!methStringList.isEmpty()){
				   methodName = methStringList[0]; 
				}
				ErrorLog__c newErrorLog = New ErrorLog__c();
				newErrorLog = CH_ErrorLogUtils.createErrorLog(e.getMessage(), className, methodName,triggerEvent,asyncType,'');
				newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorchatterGroupId, e.getStackTraceString());
				errorList.add(newErrorLog);
				chatterPostList.add(newChatterPost);
				//**changes related NOKIASC-27623 Code Opt end.
			}
			try{
				CH_CaseTriggerUtilityHelper.createProductChatterGroup(newCaseList,oldCaseMap,triggerEvent);
				if(Test.isRunningTest())
				{
					if(newCaseList[1].Subject=='TEST2'){
						Integer a=10/0;
					}
				}
			}catch(exception e){
				//**changes related NOKIASC-27623 Code Opt start
				List<CollaborationGroup> cgList = CH_ErrorLogUtils.getErrorLogChatterGroup();
				List<String> exStringList = New List<String>();
				Id errorchatterGroupId;
				String className;
				String methname;
				String methodName;
				List<String> methStringList = new List<String>();
				if(!cgList.isEmpty()){
					errorchatterGroupId = cgList[0].Id;
				}
				String exceptionString = e.getStackTraceString();
				if(String.isNotBlank(exceptionString)){
					exStringList = exceptionString.split('\\.');
				}
				if(!exStringList.isEmpty()){
					className = exStringList[1];
					methname = exStringList[2];	
				}
				if(String.isNotBlank(exceptionString)){
					methStringList = methName.split(':');
				}
				if(!methStringList.isEmpty()){
				   methodName = methStringList[0]; 
				}
				ErrorLog__c newErrorLog = New ErrorLog__c();
				newErrorLog = CH_ErrorLogUtils.createErrorLog(e.getMessage(), className, methodName,triggerEvent,asyncType,'');
				newChatterPost = CH_ErrorLogUtils.postToErrorLogChatGroup(errorchatterGroupId, e.getStackTraceString());
				errorList.add(newErrorLog);
				chatterPostList.add(newChatterPost);
				//**changes related NOKIASC-27623 Code Opt end.
			}
		}
		//**changes related NOKIASC-27623 Code Opt start
		if(errorList.size()>0){
			CH_ErrorLogUtils.insertErrorLog(errorList);
		}
		if(chatterPostList.size()>0){
			CH_ErrorLogUtils.insertchatterPost(chatterPostList);
		}
		//**changes related NOKIASC-27623 Code Opt end.
	}
}