src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>CH_Product_Name__c</fullName>
    <formula>Product.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/CH_Reported_Date__c.field-meta.xml
<CustomField>
    <fullName>CH_Reported_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reported Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <inlineHelpText>In case of system wide outage or major issue affecting all users, please create a P1/P2 incident ticket via our Global Support Desk.</inlineHelpText>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Information Request</fullName>
            </value>
            <value>
                <fullName>Critical- 2 Hours</fullName>
                <isActive>false</isActive>
                <label>Critical- 2 Hours</label>
            </value>
            <value>
                <fullName>High</fullName>
                <isActive>false</isActive>
                <label>High</label>
            </value>
            <value>
                <fullName>Moderate</fullName>
                <isActive>false</isActive>
                <label>Moderate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/CH_csvDownloadCtrl.cls
public class CH_csvDownloadCtrl {
 @AuraEnabled
   public static list <case> fetchCase(){
	  
	  List <Case> returnCaseList = new List < Case > ();
	  string uid = userinfo.getUserId();
	   list<user> cid=[Select contactId from user where id=: userinfo.getUserId()];
	   string cid1 = cid[0].contactId;
	   for(case cas: [SELECT CaseNumber,Subject, Status,Severity__c,CreatedDate,CH_Product_Name__c,CH_Reported_Date__c,ContactId  From Case where contactId=:cid1 LIMIT 1000 ]) {
			 returnCaseList.add(cas);
		  }
		 return returnCaseList;
   }
}