src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_ProductVariant__c.field-meta.xml
<CustomField>
    <fullName>CH_ProductVariant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product copied from the Covered Product if one exist on the case, else selected manually by the user</description>
    <label>Product Variant</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Product2.PMD_Additional_Classification__c</field>
            <operation>equals</operation>
            <value>Product Variant</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.CH_LegacyCaseStatus__c</field>
            <operation>equals</operation>
            <value>Closed</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Variant</relationshipLabel>
    <relationshipName>Support_Ticket2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CH_ServiceType__c.field-meta.xml
<CustomField>
    <fullName>CH_ServiceType__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
                <default>true</default>
                <label>Customer Support</label>
            </value>
            <value>
                <fullName>Internal Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/CH_Solution__c.field-meta.xml
<CustomField>
    <fullName>CH_Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Solution copied from the Covered Product if one exist on the case, else selected manually by the user</description>
    <label>Solution</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Product2.PMD_Portfolio_Classification__c</field>
            <operation>equals</operation>
            <value>Solution</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.CH_LegacyCaseStatus__c</field>
            <operation>equals</operation>
            <value>Closed</value>
        </filterItems>
        <filterItems>
            <field>Product2.CH_Valid__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CH_Workgroup__c.field-meta.xml
<CustomField>
    <fullName>CH_Workgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Workgroup</label>
    <referenceTo>CH_Workgroup__c</referenceTo>
    <relationshipLabel>Incidents and Problems</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/CH_Workgroup_Rule__c.object
<CustomObject>
    <fields>
        <fullName>CH_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that the rule applies to</description>
        <inlineHelpText>The customer that the rule applies to. Only one customer can be selected. If you need multiple customers, you need to create a customer group</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Legal_Entity</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Workgroup Rules</relationshipLabel>
        <relationshipName>CH_Workgroup_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_Contract_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CH_Country1__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CH_Region1__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CH_Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Customer_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account group that the rule applies to</description>
        <inlineHelpText>The customer group that the rule applies to</inlineHelpText>
        <label>Customer Group</label>
        <referenceTo>CH_CustomerGrouping__c</referenceTo>
        <relationshipLabel>Workgroup Rules</relationshipLabel>
        <relationshipName>CH_Workgroup_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_LevelOfSupport__c</fullName>
        <label>Level Of Support</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_Level_Of_Support</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_OrderNumber__c</fullName>
        <description>This field will give order of workgroup.</description>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CH_ProductVariant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Variant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.CH_Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Portfolio_Classification__c</field>
                <operation>equals</operation>
                <value>Complementary Product</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Additional_Classification__c</field>
                <operation>equals</operation>
                <value>Product Variant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Workgroup Rules (Product Variant)</relationshipLabel>
        <relationshipName>Workgroup_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR (3 AND 7) OR 4 OR 5 OR 6 OR 8)</booleanFilter>
            <filterItems>
                <field>Product2.CH_Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Portfolio_Classification__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Portfolio_Classification__c</field>
                <operation>equals</operation>
                <value>Complementary Product</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Portfolio_Classification__c</field>
                <operation>equals</operation>
                <value>Parallel Product</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Portfolio_Classification__c</field>
                <operation>equals</operation>
                <value>Service Product</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Portfolio_Classification__c</field>
                <operation>equals</operation>
                <value>Service Module</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Additional_Classification__c</field>
                <operation>notEqual</operation>
                <value>Product Variant</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Portfolio_Classification__c</field>
                <operation>equals</operation>
                <value>Solution</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Workgroup Rules</relationshipLabel>
        <relationshipName>CH_Workgroup_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_Region1__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_ServiceContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contract number that the rule applies to</description>
        <inlineHelpText>The contract number that the rule applies to</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Workgroup Rules</relationshipLabel>
        <relationshipName>Workgroup_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_ServiceType__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Internal Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Severity__c</fullName>
        <description>This field will give severity of incident</description>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                </value>
                <value>
                    <fullName>Information Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.CH_Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product2.PMD_Portfolio_Classification__c</field>
                <operation>equals</operation>
                <value>Solution</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Workgroup Rules (Solution)</relationshipLabel>
        <relationshipName>Workgroup_Rules2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_Workgroup__c</fullName>
        <description>Each rule has one workgroup assigned. But a workgroup can be assigned to many rules</description>
        <inlineHelpText>When this rule is selected, the assigned workgroup is used for handling the case</inlineHelpText>
        <label>Workgroup</label>
        <referenceTo>CH_Workgroup__c</referenceTo>
        <relationshipLabel>Workgroup Rules</relationshipLabel>
        <relationshipName>CH_Workgroup_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workgroup Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workgroup Rules</pluralLabel>
    <recordTypes>
        <fullName>CH_KB_WorkgroupRule</fullName>
        <active>true</active>
        <label>CH_KB_WorkgroupRule</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CH_Workgroup_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CH_Workgroup Rule</label>
        <referenceTo>CH_Workgroup_Rule__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/CH_Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua And Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Azores</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius And Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia And Herzegovina</fullName>
    </customValue>
    <masterLabel>CH Countries</masterLabel>
</GlobalValueSet>

src/globalValueSets/CH_Level_Of_Support.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Initial Support</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Support</fullName>
    </customValue>
    <customValue>
        <fullName>Smart Tier 1</fullName>
        <isActive>false</isActive>
        <label>Smart Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Expert</fullName>
        <isActive>false</isActive>
        <label>Expert</label>
    </customValue>
    <customValue>
        <fullName>Expert Support</fullName>
        <isActive>false</isActive>
        <label>Expert Support</label>
    </customValue>
    <description>The level of support that is applied</description>
    <masterLabel>CH Level Of Support</masterLabel>
</GlobalValueSet>

src/globalValueSets/CH_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Market Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Market Greater China</fullName>
    </customValue>
    <customValue>
        <fullName>Market India</fullName>
    </customValue>
    <customValue>
        <fullName>Market Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Market Middle East &amp; Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Market North America</fullName>
    </customValue>
    <customValue>
        <fullName>NNO Others</fullName>
    </customValue>
    <customValue>
        <fullName>Market Asia and Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Market Asian and Japan</fullName>
        <isActive>false</isActive>
        <label>Market Asian and Japan</label>
    </customValue>
    <customValue>
        <fullName>Region OTHER</fullName>
        <isActive>false</isActive>
        <label>Region OTHER</label>
    </customValue>
    <customValue>
        <fullName>Region Latin America</fullName>
        <isActive>false</isActive>
        <label>Region Latin America</label>
    </customValue>
    <customValue>
        <fullName>Region North America</fullName>
        <isActive>false</isActive>
        <label>Region North America</label>
    </customValue>
    <customValue>
        <fullName>Region Greater China</fullName>
        <isActive>false</isActive>
        <label>Region Greater China</label>
    </customValue>
    <customValue>
        <fullName>Region Asia-Pacific</fullName>
        <isActive>false</isActive>
        <label>Region Asia-Pacific</label>
    </customValue>
    <customValue>
        <fullName>Region Middle East &amp; Africa</fullName>
        <isActive>false</isActive>
        <label>Region Middle East &amp; Africa</label>
    </customValue>
    <customValue>
        <fullName>Market Asia-Pacific</fullName>
        <isActive>false</isActive>
        <label>Market Asia-Pacific</label>
    </customValue>
    <customValue>
        <fullName>Region Europe</fullName>
        <isActive>false</isActive>
        <label>Region Europe</label>
    </customValue>
    <masterLabel>CH Region</masterLabel>
</GlobalValueSet>

src/classes/CH_CA_Workgroup_Rule.cls
public class CH_CA_Workgroup_Rule {
	// Get the workgroup rules for the rule based on the search criteria - Used by lightning component CH_Test_Workgroup_Rules
	public static List<CH_Workgroup_Rule__c> GetWorkgroupRules(CH_CA_Assignment_Criteria_DTO caseAssignmentDetails){
		return getAllWorkgroupRules(caseAssignmentDetails);
	} 
	
	// Get the workgroup rules that apply to the search criteria
	// Points to the old GetWorkgroupRules2 that still uses the old
	// CH_CA_Assignment_Criteria_DTO. This needs to be refactored.
	public CH_CA_Assignment_Criteria_DTO getWorkgroupRules(CH_CA_DTO.SearchCriteriaDTO searchCriteriaDTO, boolean onlyFirstRule){
		// Temp reformat from new DTO to old DTO. Needs refactoring
		CH_CA_Assignment_Criteria_DTO caseAssignmentDetails = TempSearchCriteriaToCaseAssignmentDTO(searchCriteriaDTO);
		return GetWorkgroupRules2(caseAssignmentDetails,onlyFirstRule);
	}
	
	// Get the workgroup members for the add members to case team component
	public CH_CA_Assignment_Criteria_DTO GetWorkgroupRules2(CH_CA_Assignment_Criteria_DTO caseAssignmentDetails, boolean onlyFirstRule){
		// Get the worgroup rules that apply
		List<CH_Workgroup_Rule__c> allWorkgroupRules = getAllWorkgroupRules(caseAssignmentDetails);
		// If only the first rule needs to be used for getting the workgroup members
		If (onlyFirstRule){
			List<CH_Workgroup_Rule__c> tempValidWorkgroupRules = new List<CH_Workgroup_Rule__c>();
			tempValidWorkgroupRules.add(allWorkgroupRules[0]);
			caseAssignmentDetails.validWorkgroupRules = tempValidWorkgroupRules;
		} else {
			caseAssignmentDetails.validWorkgroupRules = allWorkgroupRules;
		}
		return caseAssignmentDetails;
	}
	
	// Get all workgroup rules that are according to the rule criteria
	@TestVisible
	private static List<CH_Workgroup_Rule__c> getAllWorkgroupRules(CH_CA_Assignment_Criteria_DTO caseAssignmentDetails) {
		// Dynamic SOQL doesn't allow complex binding so this is a workaround
		string contractType=caseAssignmentDetails.contractType;
		string contract = caseAssignmentDetails.contract;
		string severity = caseAssignmentDetails.severity;
		string region = caseAssignmentDetails.region;
		string serviceType = caseAssignmentDetails.serviceType;
		string country = caseAssignmentDetails.country;
		List<string> levelOfSupport = caseAssignmentDetails.levelOfSupport;
		string customerId = caseAssignmentDetails.customerId;
		List<Id> customerGroupIds = caseAssignmentDetails.customerGroupIds;
		Id customerGroupId = caseAssignmentDetails.customerGroupId;
		string productId = caseAssignmentDetails.productId;
		string productModule = caseAssignmentDetails.productModule;
		string productVariant = caseAssignmentDetails.productVariant;
		string solution = caseAssignmentDetails.solution;
		List<Id> productGroupIds = caseAssignmentDetails.productGroupIds;
		Id productGroupId = caseAssignmentDetails.productGroupId;
		string outage = caseAssignmentDetails.outage;
		boolean activeValue; 
		String active = caseAssignmentDetails.active; 
		Boolean workgroupTypeSize = false;
		// Changes added as a part of 28331
		Boolean isLevelOfSuppport = false;
		if (!String.isBlank(active) && active!= 'Any'){
			if(active=='Yes'||active=='true'){
				activeValue=true;
			} else{
				activeValue=false;
			}
		}
		List<string> workgroupType =caseAssignmentDetails.workgroupType; 
		//Changes added from 20.1.2
		if(workgroupType.size() == 1 && workgroupType[0] == ''){
			workgroupTypeSize = true;
		}
		//Changes added as a part of 28331
		if(levelOfSupport.size() == 1 && levelOfSupport[0] == ''){
			isLevelOfSuppport = true;
		}
		string kbWorkgroupRecordTypeId = Schema.SObjectType.CH_Workgroup_Rule__c.getRecordTypeInfosByName().get('CH_KB_WorkgroupRule').getRecordTypeId();		
		System.debug('CH_CA: SOQL kbWorkgroupRecordTypeId: ' + kbWorkgroupRecordTypeId);
		String sQuery = 'SELECT Id, Name, CH_Workgroup__r.Name, CH_OrderNumber__c, CH_ServiceType__c,CH_Contract_Type__c,CH_Workgroup__r.recordtypeid, ' + 
			'  CH_ServiceContract__r.Name, CH_Severity__c, CH_Region1__c, CH_Workgroup__c, CH_Solution__r.Name, ' +
			'  CH_Country1__c, CH_LevelOfSupport__c, CH_Account__r.Name, CH_ProductVariant__r.Name, ' +
			'  CH_Customer_Group__r.Name, CH_Product__r.Name, CH_Product_Module__r.Name, ' +
			'  CH_Product_Group__r.Name, CH_Outage__c, CH_BusinessHours__c, CH_Workgroup__r.CH_BusinessHours__c,CH_Workgroup_Type__c,CH_Active__c' +
			'  FROM CH_Workgroup_Rule__c WHERE recordtypeid != :kbWorkgroupRecordTypeId AND ';
		System.debug('CH_CA: SOQL SELECT: ' + sQuery);
		if(activeValue!=null){
			String whereClause = ' (CH_Active__c= :activeValue)AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + activeValue);
			sQuery += whereClause;
		}
		if (workgroupType.size() > 0 && !workgroupTypeSize){
			String whereClause = ' (CH_Workgroup_Type__c IN :workgroupType OR CH_Workgroup_Type__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + workgroupType);
			sQuery += whereClause;
		}
		system.debug('Value of contractType:'+contractType);
		if(!String.isBlank(contractType) ){
			String whereClause = ' (CH_Contract_Type__c= :contractType OR CH_Contract_Type__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + contractType);
			sQuery += whereClause;
		}
		if(!String.isBlank(contract)){
			String whereClause = ' (CH_ServiceContract__c= :contract OR CH_ServiceContract__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + contract);
			sQuery += whereClause;
		}
		else{
			String whereClause = ' (CH_ServiceContract__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + contract);		   
			System.debug('CH_CA: contract: ' + contract );
			sQuery += whereClause;
		}
		
		if (!String.isBlank(serviceType)){
			String whereClause = ' (CH_ServiceType__c = :serviceType OR CH_ServiceType__c = NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + serviceType);
			sQuery += whereClause;
		}
		if (!String.isBlank(severity)){
			String whereClause = ' (CH_Severity__c= :severity OR CH_Severity__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + severity);
			sQuery += whereClause;
		}
		if (!String.isBlank(country) && !country.equals('--None--')){   //country case is always not blank
			String whereClause = ' ( (CH_Country1__c= :country AND CH_Region1__c= :region) OR '+
				'(CH_Country1__c= :country AND CH_Region1__c= NULL) OR '+
				'(CH_Country1__c= NULL AND CH_Region1__c= NULL) OR '+
				'(CH_Country1__c= NULL AND CH_Region1__c= :region) ) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: country ' + country + ' region ' + region );
			sQuery += whereClause;
		}
		/*Commented as a part of 27982
		else { //14488
			String whereClause = ' (CH_Country1__c= NULL AND CH_Region1__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: for country blank ' + whereClause + ' value: ' + country);
			sQuery += whereClause;			
		}
		*/
		if (!String.isBlank(region)){   
			String whereClause = ' (CH_Region1__c= :region OR CH_Region1__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: region ' + region );
			sQuery += whereClause;
		}
		/*Commented as a part of 27982
		else { //14488
			String whereClause = ' (CH_Region1__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: for region blank ' + whereClause + ' value: ' + region);
			sQuery += whereClause;			
		}
		*/
		//Changes added as a part of 28331
		if (levelOfSupport.size()>0 && !isLevelOfSuppport){
			String whereClause = ' (CH_LevelOfSupport__c IN :levelOfSupport OR CH_LevelOfSupport__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + levelOfSupport);
			sQuery += whereClause;
		}
		if (!String.isBlank(customerId) && customerGroupIds.size() == 0){
			String whereClause = ' ((CH_Account__c= :customerId OR CH_Account__c= NULL) AND CH_Customer_Group__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + customerId);
			sQuery += whereClause;
		}
		if (!String.isBlank(customerId) && customerGroupIds.size() > 0){
			String whereClause = ' ((CH_Account__c= :customerId OR CH_Account__c= NULL) AND (CH_Customer_Group__c IN :customerGroupids OR CH_Customer_Group__c = null)) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value custGroupId: ' + customerGroupids + ' value custId: ' + customerId);
			sQuery += whereClause;
		}
		if (String.isBlank(customerId) && !String.isBlank(customerGroupId)){
			String whereClause = ' (CH_Customer_Group__c = :customerGroupId OR CH_Customer_Group__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + customerGroupId);
			sQuery += whereClause;
		}
		/*Commented as a part of 27982
		if (String.isBlank(customerId) && String.isBlank(customerGroupId)){		   
			String whereClause = ' (CH_Account__c= NULL AND CH_Customer_Group__c= NULL) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + customerGroupId);
			sQuery += whereClause;
		}
		*/
		if (!String.isBlank(productId) && productGroupIds.size() == 0){
			String whereClause = ' ((CH_Product__c= :productId OR CH_Product__c= NULL) AND CH_Product_Group__c= Null) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + productId);
			sQuery += whereClause;
		}
		if (!String.isBlank(productId) && productGroupIds.size() > 0){
			String whereClause = ' ((CH_Product__c= :productId OR CH_Product__c= NULL) AND (CH_Product_Group__c IN :productGroupids OR CH_Product_Group__c = null)) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value prodId: ' + productId + ' value prodGroupId: ' + productGroupIds);
			sQuery += whereClause;
		}
		if (String.isBlank(productId) && !String.isBlank(productGroupId)){
			String whereClause = ' (CH_Product_Group__c = :productGroupid OR CH_Product_Group__c= Null) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + productGroupId);
			sQuery += whereClause;
		}
		if (!String.isBlank(productModule)){
			String whereClause = ' (CH_Product_Module__c = :productModule OR CH_Product_Module__c= Null) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + productModule);
			sQuery += whereClause;
		}
		else {
			String whereClause = ' (CH_Product_Module__c = :productModule) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + productModule);
			sQuery += whereClause;			
		}		
		if (!String.isBlank(productVariant)){
			String whereClause = ' (CH_ProductVariant__c = :productVariant OR CH_ProductVariant__c= Null) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + productVariant);
			sQuery += whereClause;
		}
		else {
			String whereClause = ' (CH_ProductVariant__c = :productVariant) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + productVariant);
			sQuery += whereClause;			
		}
		if (!String.isBlank(solution)){
			String whereClause = ' (CH_Solution__c = :solution OR CH_Solution__c= Null) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + solution);
			sQuery += whereClause;
		} 
		else {
			String whereClause = ' (CH_Solution__c = :solution) AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + solution);
			sQuery += whereClause;			
		}		system.debug('Value of outage:'+outage);
		if (outage != 'Any'){
			String whereClause = ' (CH_Outage__c = :outage OR CH_Outage__c = \'Any\') AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: ' + outage);
			sQuery += whereClause;
		}
		else {
			String whereClause = ' (CH_Outage__c = \'Any\' OR CH_Outage__c = \'Yes\' OR CH_Outage__c = \'No\') AND';
			System.debug('CH_CA: SOQL WHERE: ' + whereClause + ' value: Any');
			sQuery += whereClause;
		}
		integer len1 = sQuery.length();
		if(sQuery.endsWithIgnoreCase('AND')){
			sQuery = sQuery.substring(0, len1 - 3);
		}
		if(sQuery.endsWithIgnoreCase('WHERE')){
			sQuery = sQuery.substring(0, len1 - 5);
		}
		sQuery = ''+sQuery+' ORDER BY CH_OrderNumber__c ASC NULLS LAST';
		system.debug('CH_CA: sQuery ' + sQuery);
		List<CH_Workgroup_Rule__c> lstOfWorkgroupRules = Database.query(sQuery);
		system.debug('CH_CA: found rules: ' + lstOfWorkgroupRules.size());
		
		// Only for debug purposes
		for(CH_Workgroup_Rule__c rule:lstOfWorkgroupRules){
			system.debug('CH_CA: Found rule with ordernumber: ' + rule.CH_OrderNumber__c );
		}		
		
		return lstOfWorkgroupRules;
	}
	
	// Temp class that needs to be refactored.
	// The code for CH_CA_Assignment_Criteria_DTO in this class needs to be replaced by 
	// CH_CA_DTO.SearchCriteriaDTO
	private CH_CA_Assignment_Criteria_DTO TempSearchCriteriaToCaseAssignmentDTO(CH_CA_DTO.SearchCriteriaDTO searchCriteriaDTO){
		CH_CA_Assignment_Criteria_DTO caseAssignmentDTO = new CH_CA_Assignment_Criteria_DTO();
		caseAssignmentDTO.contract = searchCriteriaDTO.contract;
		caseAssignmentDTO.severity = searchCriteriaDTO.severity;
		caseAssignmentDTO.region = searchCriteriaDTO.region;
		caseAssignmentDTO.country = searchCriteriaDTO.country;
		caseAssignmentDTO.levelOfSupport = searchCriteriaDTO.levelOfSupports;
		if (!String.isBlank(searchCriteriaDTO.customerId)){
			caseAssignmentDTO.customerId = searchCriteriaDTO.customerId;
		}
		caseAssignmentDTO.GetCustomerGroupsForCustomer();
		//caseAssignmentDTO.customerGroupId = searchCriteriaDTO.customerGroupId;
		if (!String.isBlank(searchCriteriaDTO.customerGroupId)){
			caseAssignmentDTO.customerGroupId = searchCriteriaDTO.customerGroupId;
		}
		if (!String.isBlank(searchCriteriaDTO.productId)){
			caseAssignmentDTO.productId = searchCriteriaDTO.productId;
		}
		caseAssignmentDTO.GetProductGroupsForProduct();
		//caseAssignmentDTO.productGroupId = searchCriteriaDTO.productGroupId;
		if (!String.isBlank(searchCriteriaDTO.productGroupId)){
			caseAssignmentDTO.productGroupId = searchCriteriaDTO.productGroupId;
		}
		caseAssignmentDTO.workgroupType = searchCriteriaDTO.workgroupTypes;
		caseAssignmentDTO.outage = searchCriteriaDTO.outage;
		caseAssignmentDTO.active = String.valueOf(searchCriteriaDTO.activeRules);
		caseAssignmentDTO.serviceType = searchCriteriaDTO.serviceType;
		if (!String.isBlank(searchCriteriaDTO.solution)){
			caseAssignmentDTO.solution = searchCriteriaDTO.solution;
		}
		if (!String.isBlank(searchCriteriaDTO.productModule)){
			caseAssignmentDTO.productModule = searchCriteriaDTO.productModule;
		}
		if (!String.isBlank(searchCriteriaDTO.productVariant)){
			caseAssignmentDTO.productVariant = searchCriteriaDTO.productVariant;
		}
		caseAssignmentDTO.contractType =searchCriteriaDTO.contractType;
		return caseAssignmentDTO;
	}
}