src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_Problem__c.field-meta.xml
<CustomField>
    <fullName>CH_Problem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to relate a Problem Case to an Incident Case</description>
    <label>Problem</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CH_Problem</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Problem</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CH_Workgroup__c.field-meta.xml
<CustomField>
    <fullName>CH_Workgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Workgroup</label>
    <referenceTo>CH_Workgroup__c</referenceTo>
    <relationshipLabel>Incidents and Problems</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/CH_Workgroup__c.object
<CustomObject>
</CustomObject>

src/objects/CH_Workgroup_Member__c.object
<CustomObject>
    <description>Workgroup members are assigned to a workgroup. A workgroup member has a user or queue assigned.</description>
    <fields>
        <fullName>CH_Role__c</fullName>
        <description>This will shows the role of a workgroup member.</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CH_Workgroup_Member_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Manager 1</fullName>
                    <label>Manager 1st Contact</label>
                </value>
                <value>
                    <fullName>Manager 2</fullName>
                    <label>Manager 2nd Contact</label>
                </value>
                <value>
                    <fullName>Manager 3</fullName>
                    <label>Manager 3rd Contact</label>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
                <value>
                    <fullName>Incident Manager</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Problem Manager</fullName>
                </value>
                <value>
                    <fullName>Author</fullName>
                </value>
                <value>
                    <fullName>Internal Approver (Approver)</fullName>
                </value>
                <value>
                    <fullName>Public Approver (Publisher)</fullName>
                </value>
                <value>
                    <fullName>Read-only user (Non author)</fullName>
                </value>
                <value>
                    <fullName>Workgroup Administrator</fullName>
                </value>
                <value>
                    <fullName>No Role</fullName>
                </value>
                <value>
                    <fullName>Hotline</fullName>
                </value>
                <value>
                    <fullName>Technical Escalation Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Care Manager</fullName>
                </value>
                <value>
                    <fullName>Field Agent</fullName>
                </value>
                <value>
                    <fullName>Quotation Manager</fullName>
                </value>
                <value>
                    <fullName>Quotation Manager - NokiaA</fullName>
                </value>
                <value>
                    <fullName>Quotation Manager - NokiaN</fullName>
                </value>
                <value>
                    <fullName>Warranty Manager - NokiaA</fullName>
                </value>
                <value>
                    <fullName>Warranty Manager - NokiaN</fullName>
                </value>
                <value>
                    <fullName>Warranty Manager</fullName>
                </value>
                <value>
                    <fullName>Price Manager - NokiaA</fullName>
                </value>
                <value>
                    <fullName>Price Manager - NokiaN</fullName>
                </value>
                <value>
                    <fullName>Price Manager</fullName>
                </value>
                <value>
                    <fullName>Order Coordinator</fullName>
                </value>
                <value>
                    <fullName>Customer Delivery Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user that is assigned to the workgroup member</description>
        <inlineHelpText>The user that is assigned to the workgroup member</inlineHelpText>
        <label>User</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Is not possible to add Customer Contacts/Users with Profile = &quot;Customer Login&quot; to Workgroups as members.</errorMessage>
            <filterItems>
                <field>User.Profile.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>CH_Workgroup_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_Workgroup__c</fullName>
        <description>The workgroup that this member is assigned to</description>
        <inlineHelpText>The workgroup that this member is assigned to</inlineHelpText>
        <label>Workgroup</label>
        <referenceTo>CH_Workgroup__c</referenceTo>
        <relationshipLabel>Workgroup Members</relationshipLabel>
        <relationshipName>CH_Workgroup_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workgroup Member</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workgroup Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CH_CA_CaseTeam_Test.cls
@isTest
public class CH_CA_CaseTeam_Test {
	@testSetup
	static void setuptestdata(){ 
		CH_UTIL_TEST.setupCase(false);
	}
	
	// Case has status=created, no onwer and no workgroup assigned
	@istest 
	static void addMembersToCaseTeamAtCreationUpdate1(){
		Test.startTest(); 
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		insert newCase;
		List<CaseTeamMember> caseTeamMembers = CH_CA_CaseTeam_Controller.getCaseTeamMembers(newCase.id);
		System.debug('1.Number of Queries: ' +  Limits.getQueries());
		Test.stopTest();
		
		//System.assert(caseTeamMembers.size() == 1,'Expected 1. Actual ' + caseTeamMembers.size());
	}
	
	// Add an incident and case manager
	@istest
	static void addMembersToCaseTeamAtCreationUpdate2(){
		Test.startTest(); 
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Incident with Restoration', false);
		CH_Workgroup_Member__c workgroupMember = [SELECT CH_User__c, CH_Workgroup__c	
												  FROM CH_Workgroup_Member__c 
												  WHERE CH_Role__c = 'Engineer' LIMIT 1];
		newCase.OwnerId = workgroupMember.CH_User__c;
		newCase.CH_Workgroup__c = workgroupMember.CH_Workgroup__c;
		newCase.Status = 'Assigned';
		insert newCase;
		List<CaseTeamMember> caseTeamMembers = CH_CA_CaseTeam_Controller.getCaseTeamMembers(newCase.id);
		System.debug('1.Number of Queries: ' +  Limits.getQueries());
		Test.stopTest();
		
		//System.assert(caseTeamMembers.size() == 3,'Expected 3. Actual ' + caseTeamMembers.size());
	}
	
	// Add a case manager
	@istest
	static void addMembersToCaseTeamAtAssignment(){
		Test.startTest(); 
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		insert newCase;
		newCase.OwnerId = [SELECT Id FROM User WHERE alias = 'TSTNP1' LIMIT 1].Id;
		newCase.CH_Workgroup__c = [SELECT Id FROM CH_Workgroup__c LIMIT 1].Id;
		update newCase;
		
		CH_CA_CaseTeam caseTeam = new CH_CA_CaseTeam();
		caseTeam.addTeamMembers(new List<Case>{newCase});
		
		//The code below was causing Too many SOQL queries error and doesn't deliver any additional coverage
		/*CH_CA_CaseTeam caseTeam = new CH_CA_CaseTeam();
System.debug('1.Number of Queries: ' +  Limits.getQueries());
caseTeam.addTeamMembers(newCase);
List<CaseTeamMember> caseTeamMembers = CH_CA_CaseTeam_Controller.getCaseTeamMembers(newCase.id);*/
		Test.stopTest();
		
		//System.assert(caseTeamMembers.size() == 2,'Expected 2. Actual ' + caseTeamMembers.size());
	}	 
	
	@istest
	static void performTeamMembersInsert(){
		Test.startTest();
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		insert newCase;
		
		User newUser = [SELECT Id FROM User WHERE alias = 'TSTNP1' LIMIT 1];
		Id roleId = [SELECT Id FROM CaseTeamRole LIMIT 1].Id;
		CaseTeamMember caseTeamMember = new CaseTeamMember();
		caseTeamMember.ParentId = newCase.Id;
		caseTeamMember.MemberId = newUser.Id;
		caseTeamMember.TeamRoleId = roleId;
		List<caseTeamMember> members = new List<caseTeamMember>{caseTeamMember};
			
			CH_CA_CaseTeam.performTeamMembersInsert(members);
		List<CaseTeamMember> caseTeamMembers = CH_CA_CaseTeam_Controller.getCaseTeamMembers(newCase.id);
		Test.stopTest();
		
		// 1 added automaticly when case is created
		//System.assert(caseTeamMembers.size() == 2,'Expected 2. Actual ' + caseTeamMembers.size());
		
		// Try to add the same on again
		CH_CA_CaseTeam.performTeamMembersInsert(members);
		caseTeamMembers = CH_CA_CaseTeam_Controller.getCaseTeamMembers(newCase.id);
		//System.assert(caseTeamMembers.size() == 2,'Expected 2. Actual ' + caseTeamMembers.size());			
	}
	
	@istest
	static void performTeamMembersDelete(){
		// No managers added automaticly since there is no workgroup assigned to the case
		Test.startTest();
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		insert newCase;
		
		User newUser = [SELECT Id FROM User WHERE alias = 'TSTNP1' LIMIT 1];
		Id roleId = [SELECT Id FROM CaseTeamRole LIMIT 1].Id;
		CaseTeamMember caseTeamMember = new CaseTeamMember();
		caseTeamMember.ParentId = newCase.Id;
		caseTeamMember.MemberId = newUser.Id;
		caseTeamMember.TeamRoleId = roleId;
		insert caseTeamMember;
		List<caseTeamMember> members = new List<caseTeamMember>{caseTeamMember};
			
			CH_CA_CaseTeam.performTeamMembersDelete(members);
		List<CaseTeamMember> caseTeamMembers = CH_CA_CaseTeam_Controller.getCaseTeamMembers(newCase.id);
		Test.stopTest();  
		
		// 1 added automaticly when case is created
		//System.assert(caseTeamMembers.size() == 1,'Expected 1. Actual ' + caseTeamMembers.size());		
	}
	
	// Test needs to be fixed
	@istest
	static void handleProblemOwnerOnIncidents(){
		Test.startTest();
		Case problemCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Problem', false);
		problemCase.Status='Assigned';
		problemCase.CH_Problem__c = null;
		insert problemCase;
		
		Case restaurationCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Incident with Restoration', false);
		restaurationCase.ParentId = problemCase.Id;
		restaurationCase.CH_Problem__c = problemCase.Id;
		restaurationCase.Status='Assigned';
		insert restaurationCase;
		
		restaurationCase.OwnerId = [Select id from User where id != :restaurationCase.OwnerId limit 1].id;
		
		map<Id, Case> oldCases = new map<Id, Case>();
		oldCases.put(restaurationCase.Id, problemCase);
		map<id, Case> newCases = new map<id, Case>();
		newCases.put(problemCase.Id, restaurationCase);
		CH_CA_CaseTeam.handleProblemOwnerOnIncidents(newCases,oldCases);
		Test.stopTest();
	}
	
	@istest
	static void getAllProblemIncidents(){
		Test.startTest(); 
		Case problemCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Problem', false);
		problemCase.Status='Assigned';
		insert problemCase;
		
		Case restaurationCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Incident with Restoration', false);
		restaurationCase.ParentId = problemCase.Id;
		restaurationCase.CH_Problem__c = problemCase.Id;
		restaurationCase.Status='Assigned';
		insert restaurationCase;
		
		set<Id> problemIds = new set<Id>();
		problemIds.add(problemCase.Id);
		map<Id, list<Id>> problemIncidents = CH_CA_CaseTeam.getAllProblemIncidents(problemIds);
		Test.stopTest();
		
		//system.assert(problemIncidents.size() == 1, 'Expected 1 Incendent for the problem. Actual ' + problemIncidents.size());
	}
}