src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/CH_Workgroup__c.field-meta.xml
<CustomField>
    <fullName>CH_Workgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Workgroup</label>
    <referenceTo>CH_Workgroup__c</referenceTo>
    <relationshipLabel>Incidents and Problems</relationshipLabel>
    <relationshipName>Support_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/CH_Workgroup__c.object
<CustomObject>
</CustomObject>

src/objects/CH_Workgroup_Rule__c.object
<CustomObject>
    <fields>
        <fullName>CH_OrderNumber__c</fullName>
        <description>This field will give order of workgroup.</description>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CH_Workgroup__c</fullName>
        <description>Each rule has one workgroup assigned. But a workgroup can be assigned to many rules</description>
        <inlineHelpText>When this rule is selected, the assigned workgroup is used for handling the case</inlineHelpText>
        <label>Workgroup</label>
        <referenceTo>CH_Workgroup__c</referenceTo>
        <relationshipLabel>Workgroup Rules</relationshipLabel>
        <relationshipName>CH_Workgroup_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workgroup Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workgroup Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CH_Workgroup_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>CH_Workgroup__c</fullName>
        <label>Workgroup</label>
        <referenceTo>CH_Workgroup__c</referenceTo>
        <relationshipLabel>Workgroup Schedules</relationshipLabel>
        <relationshipName>Workgroup_Schedules1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workgroup Schedule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workgroup Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workgroup Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CH_CA_WorkgroupMemberSchedule_Test.cls
@istest
public class CH_CA_WorkgroupMemberSchedule_Test {

	@testSetup   
	static void setuptestdata(){  
		CH_UTIL_TEST.setupCase(false);
		CH_UTIL_TEST.createWorkgroupSchedules(); 
	}	
	
	@istest
	static void getWorkgroupMembersCaseTeam(){
		test.starttest();
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		Insert newCase;

		List<CH_Workgroup_Rule__c> foundWorkgroupRules = [SELECT Id, CH_Workgroup__c, CH_OrderNumber__c 
														  FROM CH_Workgroup_Rule__c];		

		CH_CA_WorkgroupMemberSchedule schedule = new CH_CA_WorkgroupMemberSchedule();
		List<CH_CA_DTO.WorkgroupMemberDTO> workgroupMemberDTOs = schedule.getWorkgroupMembersCaseTeam(foundWorkgroupRules, newCase);
		test.stoptest();
	}

	@istest
	static void getWorkgroupMembersCaseTeamAvailability(){
		test.starttest();
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		Insert newCase;
	  
		List<CH_Workgroup_Rule__c> foundWorkgroupRules = [SELECT Id, CH_Workgroup__c, CH_OrderNumber__c 
														  FROM CH_Workgroup_Rule__c];		
		CH_CA_Service service = new CH_CA_Service(newCase.Id); 
		CH_CA_DTO.SearchCriteriaDTO searchCriteriaDTO = service.getCaseDetails();
		CH_CA_WorkgroupMemberSchedule schedule = new CH_CA_WorkgroupMemberSchedule();
		List<CH_CA_DTO.WorkgroupMemberDTO> workgroupMemberDTOs = schedule.getWorkgroupMembersCaseTeamAvailability(foundWorkgroupRules, searchCriteriaDTO);
		test.stoptest();	   
	}
	
	@istest
	static void getWorkgroupMembersActiveCaseInitialAssignment(){
		test.starttest();
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		Insert newCase;
		CH_CA_Service service = new CH_CA_Service(newCase.id);
		CH_CA_DTO.SearchCriteriaDTO searchCriteriaDTO = new CH_CA_DTO.SearchCriteriaDTO();
		searchCriteriaDTO.severity = 'Critical';
		searchCriteriaDTO.outage = 'Yes';
		searchCriteriaDTO.levelOfSupports.add('Initial Support');
		searchCriteriaDTO.workgroupTypes.add('Engineer');
		List<CH_Workgroup_Rule__c> foundWorkgroupRules = [SELECT Id, CH_Workgroup__c, CH_OrderNumber__c 
														  FROM CH_Workgroup_Rule__c];		
 		
		CH_CA_WorkgroupMemberSchedule schedule = new CH_CA_WorkgroupMemberSchedule();
		List<CH_CA_DTO.WorkgroupMemberDTO> workgroupMemberDTOs = schedule.getWorkgroupMembersActiveCaseInitialAssignment(foundWorkgroupRules, searchCriteriaDTO);
		test.stoptest();	   
	}
	
	@istest
	static void getWorkgroupMembersActiveCaseReAssignment(){
		test.starttest();		
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		Insert newCase;

		List<CH_Workgroup_Rule__c> foundWorkgroupRules = [SELECT Id, CH_Workgroup__c, CH_OrderNumber__c 
														  FROM CH_Workgroup_Rule__c];		
		CH_CA_Service service = new CH_CA_Service(newCase.Id); 
		CH_CA_DTO.SearchCriteriaDTO searchCriteriaDTO = service.getCaseDetails();
		CH_CA_WorkgroupMemberSchedule schedule = new CH_CA_WorkgroupMemberSchedule();
		List<CH_CA_DTO.WorkgroupMemberDTO> workgroupMemberDTOs = schedule.getWorkgroupMembersActiveCaseReAssignment(foundWorkgroupRules, searchCriteriaDTO);
		test.stoptest();	   
	}
	
	@istest
	static void getWorkgroupMembersPassiveCaseAssignment(){
		test.starttest();
		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		Insert newCase;

		List<CH_Workgroup_Rule__c> foundWorkgroupRules = [SELECT Id, CH_Workgroup__c, CH_OrderNumber__c 
														  FROM CH_Workgroup_Rule__c];		 

		CH_CA_WorkgroupMemberSchedule schedule = new CH_CA_WorkgroupMemberSchedule();
		List<CH_CA_DTO.WorkgroupMemberDTO> workgroupMemberDTOs = schedule.getAllWorkgroupMembersPassiveCaseAssignment(foundWorkgroupRules, newCase);
		test.stoptest();	   
	}
	
	@istest
	static void getWorkgroupMembersPassiveCaseAssignmentNoSchedule(){
		test.starttest();
		// Delete the schedule
		CH_Workgroup_Schedule__c foundSchedule = [SELECT Id FROM CH_Workgroup_Schedule__c LIMIT 1];
		Delete foundSchedule;

		Case newCase = CH_UTIL_TEST.createCaseNotSaved('TEST1', 'Minor', 'No', 'Nokia Standard Case', false);
		Insert newCase;

		List<CH_Workgroup_Rule__c> foundWorkgroupRules = [SELECT Id, CH_Workgroup__c, CH_OrderNumber__c 
														  FROM CH_Workgroup_Rule__c];		

		CH_CA_WorkgroupMemberSchedule schedule = new CH_CA_WorkgroupMemberSchedule();
		List<CH_CA_DTO.WorkgroupMemberDTO> workgroupMemberDTOs = schedule.getAllWorkgroupMembersPassiveCaseAssignment(foundWorkgroupRules, newCase);
		test.stoptest();	 
	}
}