src/objects/Case.object
<CustomObject>
</CustomObject>

src/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>This field is intended to be used by Case Handling and CRM  team ONLY.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Issue</fullName>
            </value>
            <value>
                <fullName>General Issues</fullName>
            </value>
            <value>
                <fullName>Access/Visibility</fullName>
            </value>
            <value>
                <fullName>Mass Update Request</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>ERM</fullName>
            </value>
            <value>
                <fullName>Security Group</fullName>
            </value>
            <value>
                <fullName>User Access</fullName>
            </value>
            <value>
                <fullName>CH - General Issues</fullName>
                <label>CH SWS - General Issue</label>
            </value>
            <value>
                <fullName>CH - User Access</fullName>
                <label>CH SWS - User Access</label>
            </value>
            <value>
                <fullName>CH - Security Group</fullName>
                <label>CH SWS - Security Group</label>
            </value>
            <value>
                <fullName>CH- Work Group Management and Authorized Contact</fullName>
                <label>CH SWS - Workgroup Management and Authorized Contact</label>
            </value>
            <value>
                <fullName>CH - Key User Management</fullName>
                <label>CH SWS - Key User Management</label>
            </value>
            <value>
                <fullName>HWS - Authorized Contact</fullName>
                <label>CH HWS - Authorized Contact</label>
            </value>
            <value>
                <fullName>HWS - General Issues</fullName>
                <label>CH HWS - General Issue</label>
            </value>
            <value>
                <fullName>HWS - User Access</fullName>
                <label>CH HWS - User Access</label>
            </value>
            <value>
                <fullName>HWS - Security Group</fullName>
                <label>CH HWS - Security Group</label>
            </value>
            <value>
                <fullName>Enterprise (including Partners)</fullName>
            </value>
            <value>
                <fullName>NAM Contracted Quote</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>Order-to-Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Issue_Reported_By__c.field-meta.xml
<CustomField>
    <fullName>Issue_Reported_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Actual user raising the case.</inlineHelpText>
    <label>Issue Reported By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Default_Case_Owner__c</label>
</CustomObject>

src/objects/CH_Attachment__c.object
<CustomObject>
    <description>This object is used for getting details of attachments through respective fields.</description>
    <fields>
        <fullName>AttachmentID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>AttachmentID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To display the files that have been uploaded.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CH_Attachment</relationshipLabel>
        <relationshipName>CH_Attachment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CH_Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CH_Attachment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CH_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store Case Handling specific settings</description>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SettingValue__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SettingValue</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CH_Settings</label>
</CustomObject>

src/classes/CAPS_AttachmentDelOnCloseCancelQueueTest.cls
/***************************************************************
* Class Name : CAPS_AttachmentDelOnCloseCancelQueueTest	test
* Created Date: 24 July 2019
* Description : Test class for CAPS_AttachmentDelOnCloseCancelQueue
***************************************************************/
@IsTest

private class CAPS_AttachmentDelOnCloseCancelQueueTest {
  
  //Stup Data
	@testSetup
	public static void setup()
	{
		
		CH_Settings__c cstObj = new CH_Settings__c();
		cstObj.Description__c = 'test custom settings';
		cstObj.SettingValue__c = '3';
		cstObj.Name = 'SpecificTimeForOnhold';
		insert cstObj;

		CH_ManageCreateQueueAsynchQueue.doChainJob = false;
		Case cs = new Case();
		cs.Subject = 'Creating Non Ch test data CAPS123';
		cs.Category__c = 'General Issues';
		cs.Type = 'Services_Project_Team';
		cs.Issue_Reported_By__c = userinfo.getuserid();
		cs.RecordTypeId =  Schema.SObjectType.Case.getRecordTypeInfosByName().get('SF Support').getRecordTypeId();
		cs.Status = 'New';
		cs.Description = 'test';
		insert cs;

		List<CH_Attachment__c> chAttchList = new List<CH_Attachment__c>();//Service Provider End User Information
		chAttchList.add(CAPS_TestDataUtil.createCHAttachmentRecord(1,'Service Provider End User Information',cs.Id)[0]);
		chAttchList.add(CAPS_TestDataUtil.createCHAttachmentRecord(1,'Other Information',cs.Id)[0]);
		chAttchList.add(CAPS_TestDataUtil.createCHAttachmentRecord(1,'Service Provider End User Information',cs.Id)[0]);
		chAttchList.add(CAPS_TestDataUtil.createCHAttachmentRecord(1,'Service Provider End User Information',cs.Id)[0]);		 
		insert chAttchList;
		
	}
	@isTest
	public static void updateRetentionDaysforLightningTest() {
		CAPS_TestDataUtil.createCustomSettingsData();
		CH_ManageCreateQueueAsynchQueue.doChainJob = false;
		Map<String,Boolean> attahmentIdVsToBeDeletedMap = new Map<String,Boolean>();
		Map<String, Map<String,String>> attachIDVsMapOfUpdateFieldsMap = new Map<String, Map<String,String>>();
		Map<String,String> valueVsFieldMap = new Map<String,String>();
		Map<String,String> attachmentIdVsDateMap = new Map<String,String>();
		Case cs = [SELECT Id, Status FROM Case WHERE subject = 'Creating Non Ch test data CAPS123' LIMIT 1];
		List<CH_Attachment__c> chAttchList = [SELECT Id, AttachmentID__c FROM CH_Attachment__c WHERE Case__c =: cs.Id LIMIT 2];
		attachmentIdVsDateMap.put(chAttchList[0].AttachmentID__c,CAPS_ConstantHandler.RETENTION_DAYS1_STR);
		attahmentIdVsToBeDeletedMap.put(chAttchList[0].AttachmentID__c, true);
		
		valueVsFieldMap.put(CAPS_ConstantHandler.CASESTATUS, 'Cancelled');
		attachIDVsMapOfUpdateFieldsMap.put(chAttchList[0].AttachmentID__c, valueVsFieldMap);
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CAPS_DeleteMockHttpResponse());
		CAPS_AttachmentDelOnCloseCancelQueue job = new CAPS_AttachmentDelOnCloseCancelQueue(attahmentIdVsToBeDeletedMap, attachIDVsMapOfUpdateFieldsMap, attachmentIdVsDateMap);
		job.maximum = 1;
		System.enqueueJob(job);
		Test.stopTest();
	}
}