src/objects/CH_Workgroup__c.object
<CustomObject>
</CustomObject>

src/objects/CH_Workgroup_Member__c.object
<CustomObject>
    <description>Workgroup members are assigned to a workgroup. A workgroup member has a user or queue assigned.</description>
    <fields>
        <fullName>CH_Role__c</fullName>
        <description>This will shows the role of a workgroup member.</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CH_Workgroup_Member_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Manager 1</fullName>
                    <label>Manager 1st Contact</label>
                </value>
                <value>
                    <fullName>Manager 2</fullName>
                    <label>Manager 2nd Contact</label>
                </value>
                <value>
                    <fullName>Manager 3</fullName>
                    <label>Manager 3rd Contact</label>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
                <value>
                    <fullName>Incident Manager</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Problem Manager</fullName>
                </value>
                <value>
                    <fullName>Author</fullName>
                </value>
                <value>
                    <fullName>Internal Approver (Approver)</fullName>
                </value>
                <value>
                    <fullName>Public Approver (Publisher)</fullName>
                </value>
                <value>
                    <fullName>Read-only user (Non author)</fullName>
                </value>
                <value>
                    <fullName>Workgroup Administrator</fullName>
                </value>
                <value>
                    <fullName>No Role</fullName>
                </value>
                <value>
                    <fullName>Hotline</fullName>
                </value>
                <value>
                    <fullName>Technical Escalation Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Care Manager</fullName>
                </value>
                <value>
                    <fullName>Field Agent</fullName>
                </value>
                <value>
                    <fullName>Quotation Manager</fullName>
                </value>
                <value>
                    <fullName>Quotation Manager - NokiaA</fullName>
                </value>
                <value>
                    <fullName>Quotation Manager - NokiaN</fullName>
                </value>
                <value>
                    <fullName>Warranty Manager - NokiaA</fullName>
                </value>
                <value>
                    <fullName>Warranty Manager - NokiaN</fullName>
                </value>
                <value>
                    <fullName>Warranty Manager</fullName>
                </value>
                <value>
                    <fullName>Price Manager - NokiaA</fullName>
                </value>
                <value>
                    <fullName>Price Manager - NokiaN</fullName>
                </value>
                <value>
                    <fullName>Price Manager</fullName>
                </value>
                <value>
                    <fullName>Order Coordinator</fullName>
                </value>
                <value>
                    <fullName>Customer Delivery Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user that is assigned to the workgroup member</description>
        <inlineHelpText>The user that is assigned to the workgroup member</inlineHelpText>
        <label>User</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Is not possible to add Customer Contacts/Users with Profile = &quot;Customer Login&quot; to Workgroups as members.</errorMessage>
            <filterItems>
                <field>User.Profile.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>CH_Workgroup_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CH_Workgroup_Member_Type__c</fullName>
        <label>Workgroup Member Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hotline</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Workgroup__c</fullName>
        <description>The workgroup that this member is assigned to</description>
        <inlineHelpText>The workgroup that this member is assigned to</inlineHelpText>
        <label>Workgroup</label>
        <referenceTo>CH_Workgroup__c</referenceTo>
        <relationshipLabel>Workgroup Members</relationshipLabel>
        <relationshipName>CH_Workgroup_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workgroup Member</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workgroup Members</pluralLabel>
    <recordTypes>
        <fullName>CH_CA_WorkgroupMember</fullName>
        <active>true</active>
        <description>Case Assignment Workgroup Members</description>
        <label>CH_CA_WorkgroupMember</label>
    </recordTypes>
    <recordTypes>
        <fullName>CH_KB_Workgroup_Members</fullName>
        <active>true</active>
        <description>Workgroup Members Record Type for Knowlegde Management</description>
        <label>CH_KB_WorkgroupMember</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CH_Workgroup_Rule__c.object
<CustomObject>
    <fields>
        <fullName>CH_OrderNumber__c</fullName>
        <description>This field will give order of workgroup.</description>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CH_Outage__c</fullName>
        <label>Outage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Any</fullName>
                    <default>true</default>
                    <label>Any</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Severity__c</fullName>
        <description>This field will give severity of incident</description>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                </value>
                <value>
                    <fullName>Information Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Workgroup__c</fullName>
        <description>Each rule has one workgroup assigned. But a workgroup can be assigned to many rules</description>
        <inlineHelpText>When this rule is selected, the assigned workgroup is used for handling the case</inlineHelpText>
        <label>Workgroup</label>
        <referenceTo>CH_Workgroup__c</referenceTo>
        <relationshipLabel>Workgroup Rules</relationshipLabel>
        <relationshipName>CH_Workgroup_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workgroup Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workgroup Rules</pluralLabel>
    <recordTypes>
        <fullName>CH_CA_WorkgroupRule</fullName>
        <active>true</active>
        <label>CH_CA_WorkgroupRule</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CH_Workgroup_Controller_Test.cls
@istest
public class CH_Workgroup_Controller_Test {
	
	@testSetup
	public static void setup(){
		Test.startTest();	
		CH_UTIL_TEST.setupCase(false);	
		Test.stopTest();
	}
	
	@istest
	static void getRecordTypeName(){
		string recordTypeNameToSearch = 'CH_CA_WorkgroupMember';
		string objectType = 'CH_Workgroup_Member__c';
		id recordTypeIdToSearch = Schema.SObjectType.CH_Workgroup_Member__c.getRecordTypeInfosByName().get(recordTypeNameToSearch).getRecordTypeId();
		string recordTypeNameRetrieved = CH_Workgroup_Controller.getRecordTypeName(recordTypeIdToSearch, objectType);
		System.assert(recordTypeNameRetrieved == recordTypeNameToSearch, 'Expected ' + recordTypeNameToSearch + '. Actual ' + recordTypeNameRetrieved);

		recordTypeNameToSearch = 'CH_KB_WorkgroupMember';
		recordTypeIdToSearch = Schema.SObjectType.CH_Workgroup_Member__c.getRecordTypeInfosByName().get(recordTypeNameToSearch).getRecordTypeId();
		recordTypeNameRetrieved = CH_Workgroup_Controller.getRecordTypeName(recordTypeIdToSearch, objectType);
		// Warning: there's a difference between the KB recordtype name and api name. CH_KB_WorkgroupMember and CH_KB_Workgroup_Members
		System.assert(recordTypeNameRetrieved == 'CH_KB_Workgroup_Members', 'Expected ' + recordTypeNameToSearch + '. Actual ' + recordTypeNameRetrieved);
	}

	@istest
	static void getDefaultRecordTypeName(){
		string recordTypeNameToSearch = 'CH_CA_WorkgroupMember';
		string objectType = 'CH_Workgroup_Member__c';
		id recordTypeIdToSearch = Schema.SObjectType.CH_Workgroup_Member__c.getRecordTypeInfosByName().get(recordTypeNameToSearch).getRecordTypeId();
		string recordTypeNameRetrieved = CH_Workgroup_Controller.getDefaultRecordTypeName(objectType);
		System.assert(recordTypeNameRetrieved == recordTypeNameToSearch, 'Expected ' + recordTypeNameToSearch + '. Actual ' + recordTypeNameRetrieved);
	}
	
	@istest
	static void getaccessCheck(){
		Test.startTest();	
		CH_ManageCreateQueueAsynchQueue.doChainJob = false;
		CH_ManagePSAndQueueToWGMemberAsynchQueue.doChainJob = false;
		Id getworkgroupRecordId = Schema.SObjectType.CH_Workgroup__c.getRecordTypeInfosByName().get('CH_CA_Workgroup').getRecordTypeId();
		CH_Workgroup__c workgroup = new CH_Workgroup__c();
		workgroup.name = 'TestWorkgroup';
		workgroup.CH_Workgroup_Instructions__c = 'This is a workgroup instruction';
		workgroup.CH_Type__c = 'Engineer;Smart Tier 1';
		workgroup.RecordTypeId = getworkgroupRecordId;
		insert workgroup;
		
		id getworkgroupRuleRecordId = Schema.SObjectType.CH_Workgroup_Rule__c.getRecordTypeInfosByName().get('CH_CA_WorkgroupRule').getRecordTypeId();
		List<CH_Workgroup_Rule__c> newWorkgroupRules = new List<CH_Workgroup_Rule__c>();
		// Create an active rule
		CH_Workgroup_Rule__c rule = new CH_Workgroup_Rule__c ();
		rule.name = 'ACTIVE';
		rule.CH_Workgroup__c = workgroup.Id;
		rule.CH_Severity__c = 'Major';
		rule.CH_Outage__c = 'Yes';
		rule.CH_OrderNumber__c = 10;
		rule.RecordTypeId = getworkgroupRuleRecordId;
		insert rule;
		
		Boolean getAcess=CH_Workgroup_Controller.accessCheck(rule.Id);
		System.assert(getAcess== True,'Expect True. Actual: ' + getAcess);
		CH_Workgroup_Rule__c getRecrdTypeName=CH_Workgroup_Controller.getRecrdTypeName(rule.Id);
		Boolean getProfileCheck=CH_Workgroup_Controller.getValidUser();
		Test.StopTest(); 
	}
	
	@istest
	static void accessCheckMember(){
	 Test.startTest(); 
		CH_ManageCreateQueueAsynchQueue.doChainJob = false;
		CH_ManagePSAndQueueToWGMemberAsynchQueue.doChainJob = false;
		Id getworkgroupRecordId = Schema.SObjectType.CH_Workgroup__c.getRecordTypeInfosByName().get('CH_CA_Workgroup').getRecordTypeId();
		CH_Workgroup__c workgroup = new CH_Workgroup__c();
		workgroup.name = 'TestWorkgroup';
		workgroup.CH_Workgroup_Instructions__c = 'This is a workgroup instruction';
		workgroup.CH_Type__c = 'Engineer;Smart Tier 1';
		workgroup.RecordTypeId = getworkgroupRecordId;
		insert workgroup;

		
		id getworkgroupMemberRecordId = Schema.SObjectType.CH_Workgroup_Member__c.getRecordTypeInfosByName().get('CH_CA_WorkgroupMember').getRecordTypeId();
		List<CH_Workgroup_Member__c> newWorkgroupMember = new List<CH_Workgroup_Member__c>();
		// Create an active rule
		
		CH_Workgroup_Member__c member = new CH_Workgroup_Member__c ();
		 /*CH_Workgroup_Member__c workgroupMember = [SELECT Id,CH_User__c,	
												  FROM CH_Workgroup_Member__c 
												  WHERE CH_Role__c = 'Engineer' LIMIT 1];*/
		CH_Workgroup_Member__c workgroupMember = [SELECT Id,CH_User__c FROM CH_Workgroup_Member__c WHERE Name =:CH_UTIL_TEST.TEST_QUEUE_LABEL LIMIT 1];
		System.debug('---->'+workgroupMember);
		member.CH_Workgroup_Member_Type__c = 'Queue';
		member.CH_Workgroup__c = workgroup.Id;
		member.CH_Role__c = 'Queue';
		member.CH_User__c = workgroupMember.CH_User__c;
		member.RecordTypeId = getworkgroupMemberRecordId;
		insert member;
	   
		
		Boolean getAcess=CH_Workgroup_Controller.accessCheckMember(member.Id);
		//System.assert(getAcess== True,'Expect True. Actual: ' + getAcess);
		CH_Workgroup_Member__c getRecrdTypeNameMember=CH_Workgroup_Controller.getRecrdTypeNameMember(member.Id);
		 Test.stopTest();
	} 
}