src/objects/CH_Workgroup__c.object
<CustomObject>
</CustomObject>

src/objects/CH_Workgroup_Filter__c.object
<CustomObject>
    <fields>
        <fullName>CH_Country__c</fullName>
        <label>Country</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_LevelOfSupport__c</fullName>
        <label>Level Of Support</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_Level_Of_Support</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Outage__c</fullName>
        <label>Outage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                    <isActive>false</isActive>
                    <label>All</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Region__c</fullName>
        <label>Region</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Severity__c</fullName>
        <label>Severity</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_Severity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CH_Workgroup_Schedule__c</fullName>
        <label>Workgroup Schedule</label>
        <referenceTo>CH_Workgroup_Schedule__c</referenceTo>
        <relationshipLabel>Workgroup Filters</relationshipLabel>
        <relationshipName>CH_Workgroup_Filters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CH_Workgroup_Type__c</fullName>
        <label>Workgroup Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CH_Workgroup_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Workgroup Filter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workgroup Filters Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workgroup Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CH_Workgroup_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>CH_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To determine whether schedule is active or not US# 16339</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CH_End_DateTime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End DateTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CH_Start_DateTime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start DateTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CH_Workgroup__c</fullName>
        <label>Workgroup</label>
        <referenceTo>CH_Workgroup__c</referenceTo>
        <relationshipLabel>Workgroup Schedules</relationshipLabel>
        <relationshipName>Workgroup_Schedules1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workgroup Schedule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workgroup Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workgroup Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/CH_Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua And Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Azores</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius And Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia And Herzegovina</fullName>
    </customValue>
    <masterLabel>CH Countries</masterLabel>
</GlobalValueSet>

src/globalValueSets/CH_Level_Of_Support.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Initial Support</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Support</fullName>
    </customValue>
    <customValue>
        <fullName>Smart Tier 1</fullName>
        <isActive>false</isActive>
        <label>Smart Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Expert</fullName>
        <isActive>false</isActive>
        <label>Expert</label>
    </customValue>
    <customValue>
        <fullName>Expert Support</fullName>
        <isActive>false</isActive>
        <label>Expert Support</label>
    </customValue>
    <description>The level of support that is applied</description>
    <masterLabel>CH Level Of Support</masterLabel>
</GlobalValueSet>

src/globalValueSets/CH_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Market Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Market Greater China</fullName>
    </customValue>
    <customValue>
        <fullName>Market India</fullName>
    </customValue>
    <customValue>
        <fullName>Market Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Market Middle East &amp; Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Market North America</fullName>
    </customValue>
    <customValue>
        <fullName>NNO Others</fullName>
    </customValue>
    <customValue>
        <fullName>Market Asia and Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Market Asian and Japan</fullName>
        <isActive>false</isActive>
        <label>Market Asian and Japan</label>
    </customValue>
    <customValue>
        <fullName>Region OTHER</fullName>
        <isActive>false</isActive>
        <label>Region OTHER</label>
    </customValue>
    <customValue>
        <fullName>Region Latin America</fullName>
        <isActive>false</isActive>
        <label>Region Latin America</label>
    </customValue>
    <customValue>
        <fullName>Region North America</fullName>
        <isActive>false</isActive>
        <label>Region North America</label>
    </customValue>
    <customValue>
        <fullName>Region Greater China</fullName>
        <isActive>false</isActive>
        <label>Region Greater China</label>
    </customValue>
    <customValue>
        <fullName>Region Asia-Pacific</fullName>
        <isActive>false</isActive>
        <label>Region Asia-Pacific</label>
    </customValue>
    <customValue>
        <fullName>Region Middle East &amp; Africa</fullName>
        <isActive>false</isActive>
        <label>Region Middle East &amp; Africa</label>
    </customValue>
    <customValue>
        <fullName>Market Asia-Pacific</fullName>
        <isActive>false</isActive>
        <label>Market Asia-Pacific</label>
    </customValue>
    <customValue>
        <fullName>Region Europe</fullName>
        <isActive>false</isActive>
        <label>Region Europe</label>
    </customValue>
    <masterLabel>CH Region</masterLabel>
</GlobalValueSet>

src/globalValueSets/CH_Severity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Critical</fullName>
    </customValue>
    <customValue>
        <fullName>Major</fullName>
    </customValue>
    <customValue>
        <fullName>Minor</fullName>
    </customValue>
    <customValue>
        <fullName>Information Request</fullName>
    </customValue>
    <masterLabel>CH Severity</masterLabel>
</GlobalValueSet>

src/globalValueSets/CH_Workgroup_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Smart Tier 1</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Expert</fullName>
    </customValue>
    <customValue>
        <fullName>Incident Managers</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Escalation Managers</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Care Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Field Support</fullName>
    </customValue>
    <masterLabel>CH Workgroup Type</masterLabel>
</GlobalValueSet>

src/classes/CH_CA_MS_List_Schedules_Controller.cls
public class CH_CA_MS_List_Schedules_Controller {
	
	// Get the schedules for a workgroup
	@AuraEnabled
	public static List<CH_Workgroup_Schedule__c> getSchedules(Id workgroupId){
		List<CH_Workgroup_Schedule__c> workgroupSchedules;
		workgroupSchedules = [SELECT Id, CH_Active__c, Name, CH_Start_DateTime__c, CH_End_DateTime__c,
					 (SELECT CH_Region__c, CH_Country__c, CH_Outage__c, CH_Severity__c, CH_Workgroup_Type__c,CH_LevelOfSupport__c	
					   FROM CH_Workgroup_Filters__r)
					 FROM CH_Workgroup_Schedule__c 
							  WHERE CH_Workgroup__c =:workgroupId
							  ORDER BY CH_Start_DateTime__c, Name];

		return workgroupSchedules;
	}

	// Get the locale of the logged i user
	// getLocale() returns en_US this is converted to international standard of en-US
	@AuraEnabled
	public static string getLocale(){
		String userLocale = UserInfo.getLocale();
		return userLocale.replace('_','-');
	}
	
	// Delete the selected rows and return the status of the deletion
	@AuraEnabled
	public static string deleteSelectedSchedules(List<id> selectedScheduleIds){
		//Delete the schedules
		List<CH_Workgroup_Schedule__c> selectedSchedules;
		selectedSchedules = [SELECT Id FROM CH_Workgroup_Schedule__c WHERE Id in :selectedScheduleIds];
		
		return CH_CA_MS_Util.deleteSelectedObjects(selectedSchedules, 'schedule');
	}
}