src/objects/CloneObject__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Req #1237,1239,1240</description>
    <fields>
        <fullName>Field_API__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Field API</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Object</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CloneRecord</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>G3_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G3 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G4_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G4 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G5_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Expected date for contract signing or other legally binding document (e.g. first PO)</inlineHelpText>
        <label>Win Declaration Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G6_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities
4372: Help text for G6 Planned Date</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>G6 Planned Date cannot be edited prior to G5 Approval.</inlineHelpText>
        <label>G6 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IfOpportunityIsCloned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Requirement 1507: If Lead BG is MN, ca chatter post should be there</description>
        <label>IfOpportunityIsCloned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req 569: User will select Lead BG manually</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BU__c</fullName>
        <description>Selection of group within MN to lead on approvals. Mandatory selection from drop-down list if MN or ION are chosen as the Lead BG</description>
        <label>Lead BU</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_BG__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Business_Units</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityTeamMember.object
<CustomObject>
    <fields>
        <fullName>Additional_Team_Role__c</fullName>
        <description>Req 665: This will help to add user with different role</description>
        <label>Additional Team Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Account Manager (TRICORN Sales Case Owner (SCO))</fullName>
                </value>
                <value>
                    <fullName>BG Business Controller RBC</fullName>
                </value>
                <value>
                    <fullName>BG Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>BG Sales &amp; Business Development</fullName>
                </value>
                <value>
                    <fullName>Bid Manager</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                    <isActive>false</isActive>
                    <label>Business Development</label>
                </value>
                <value>
                    <fullName>Commercial Contract Manager (L&amp;C)</fullName>
                </value>
                <value>
                    <fullName>Commercial Contract Manager and Legal</fullName>
                    <isActive>false</isActive>
                    <label>Commercial Contract Manager and Legal</label>
                </value>
                <value>
                    <fullName>Commercial Deal Manager Commercial War Room</fullName>
                    <isActive>false</isActive>
                    <label>Commercial Deal Manager Commercial War Room</label>
                </value>
                <value>
                    <fullName>CT Head</fullName>
                </value>
                <value>
                    <fullName>Customer CTO</fullName>
                </value>
                <value>
                    <fullName>Customer Quality Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Supply Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Team Controller</fullName>
                    <isActive>false</isActive>
                    <label>Customer Team Controller</label>
                </value>
                <value>
                    <fullName>E2E Solution Manager</fullName>
                    <isActive>false</isActive>
                    <label>E2E Solution Manager</label>
                </value>
                <value>
                    <fullName>G3 Facilitator</fullName>
                </value>
                <value>
                    <fullName>G4 G5 Facilitator</fullName>
                    <isActive>false</isActive>
                    <label>G4 G5 Facilitator</label>
                </value>
                <value>
                    <fullName>Global Sales Support MU Lead</fullName>
                </value>
                <value>
                    <fullName>Head of Sales</fullName>
                    <isActive>false</isActive>
                    <label>Head of Sales</label>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Offer Controller</fullName>
                </value>
                <value>
                    <fullName>One Customer Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Partner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager (Lead)</fullName>
                </value>
                <value>
                    <fullName>Project Contract Manager</fullName>
                </value>
                <value>
                    <fullName>Project Execution Owner</fullName>
                    <isActive>false</isActive>
                    <label>Project Execution Owner</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/classes/CloneOpportunity.cls
/*******************************
Class Name: CloneOpportunity
Created by: Accenture
Created Date: 20th June 2017
Last modified by: Accenture
Last modified date:  
Description: Requirement 1507: Sales Process: Opportunity Cloning 
*******************************/
public with sharing class CloneOpportunity {
	private static final Id directRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.DIRECT_OPPTY).getRecordTypeId();
	private static final Id inDirectRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.INDIRECT_OPPTY).getRecordTypeId();
	private static final Id directReadOnlyRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.READONLYDIRECT).getRecordTypeId();
	private static final Id inDirectReadOnlyRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.READONLYINDIRECT).getRecordTypeId();
	
	@AuraEnabled
	/*******************************
Method Name: getCloneOpp
Description: Requirement 1507: Sales Process: Opportunity Cloning 
Parameters: Opportunity record id
*******************************/
	public static String getCloneOpp(String recordId) {
		system.debug('recordId>>>>>>>>> ' + recordId);
		// Initialize setup variables
		String returnMessage;
		Schema.DescribeSObjectResult sc = Opportunity.sObjectType.getDescribe();
		Boolean isCreateable = sc.isCreateable();
		opportunity opty = new Opportunity();	 
		system.debug('isCreateable' + isCreateable);
		Id profileId = UserInfo.getProfileId();
		Set<Id> profileIdSet = new Set<Id>();
		String objectName = GlobalConstants.OBJECT_OPPORTUNITY;
		String query = GlobalConstants.SELECT_QUERY;
		
		try {
			List<Id> profiles = System.Label.Clone_Restricted_Profiles.Split(GlobalConstants.COMMA);			
			profileIdSet.addAll(profiles);
			
			if (isCreateable && (!profileIdSet.contains(profileId))) {
				
				opty = [select RecordTypeId from opportunity where id=:recordId Limit 1];
				if(opty.RecordTypeId.equals(directRecordTypeId) || opty.RecordTypeId.equals(directReadOnlyRecordTypeId)) {
					for(cloneObject__c opptyField : [SELECT Field_API__c 
													 FROM cloneObject__c 
													 where Object__c =: GlobalConstants.OBJECT_OPPORTUNITY and Record_Type__c =: GlobalConstants.Direct
													 LIMIT: (Limits.getLimitQueryRows() - Limits.getQueryRows())])
					{
						query += GlobalConstants.SPACE + opptyField.Field_API__c + GlobalConstants.COMMA;
					}
				}else if(opty.RecordTypeId.equals(inDirectRecordTypeId) || opty.RecordTypeId.equals(inDirectReadOnlyRecordTypeId)){
						for(cloneObject__c opptyField : [SELECT Field_API__c 
														 FROM cloneObject__c 
														 where Object__c =: GlobalConstants.OBJECT_OPPORTUNITY and Record_Type__c =: GlobalConstants.Indirect
														 LIMIT: (Limits.getLimitQueryRows() - Limits.getQueryRows())])
						{
							query += GlobalConstants.SPACE + opptyField.Field_API__c + GlobalConstants.COMMA;
						}
					}
				
				system.debug('query.subString(query.Length())?>>>>' + query.Length());				
				system.debug('query.subString(query.Length()-1,query.Length())?>>>>' + query.subString(query.Length() - 1, query.Length()));
				
				// Strip off the last comma if it exists.[from last query statement]
				if (query.subString(query.Length() - 1, query.Length()) == GlobalConstants.COMMA) {
					system.debug('in if... query?>>>>' + query);
					query = query.subString(0, query.Length() - 1);
					system.debug('in if after substring... query?>>>>' + query);
				}
				// Add complete query
				query += GlobalConstants.SOQLFROM + objectName;
				query += GlobalConstants.SOQLWHERE + recordId + GlobalConstants.SOQLLIMIT;
				system.debug(query);
				
				Opportunity opp = database.query(query);
				
				// 2017-12-04 Added By Jingwei for SF Support Ticket '00008286'***start***
				List<RecordType> List_RecordType_Id = [SELECT ID, NAME FROM RecordType WHERE ID=:opp.recordtypeid LIMIT 1];
				String Record_Name;
				if (List_RecordType_Id.size() > 0) {
					Record_Name = List_RecordType_Id.get(0).Name;
				} else {
					returnMessage = system.label.ReadOnlyCloneDenied;
				}
				system.debug('===Record Type Name is' + Record_Name);
				if (!Record_Name.contains(GlobalConstants.Check_Read_Only)) {
					// 2017-12-04 Added By Jingwei for SF Support Ticket '00008286'***end***
					
					system.debug(opp);
					Opportunity newOpp = opp.clone(false, true, false, false);
					newOpp.Name = opp.Name + GlobalConstants.CLONEOPTYNAME;
					newOpp.Amount = 0;
					newOpp.G3_Planned_Date__c = system.today();
					newOpp.G4_Planned_Date__c = system.today();
					newOpp.G5_Planned_Date__c = system.today();
					newOpp.G6_Planned_Date__c = system.today();
					if (opp.Lead_BG__c == GlobalConstants.LEAD_BG_MN && opp.Lead_BU__c != NULL) {
						newOpp.Lead_BU__c = NULL;
						newOpp.IfOpportunityIsCloned__c = True;
					}					
					//database.insert(newOpp,false);
					
						Database.SaveResult savedResults = Database.insert(newOpp, false);
						Boolean someFailure = false;
							if (!savedResults.isSuccess()) {
								someFailure = true;
								for (Database.Error err: savedResults.getErrors()) {
									System.debug('Error occured : ' + err.getStatusCode() + ' : ' + err.getMessage());
									System.debug('Fields that affected this error : ' + err.getFields());
			returnMessage = err.getMessage();
								}
							}
						if (!someFailure) {
							System.debug('newopp Opportunity inserted added successfully');
				returnMessage = newOpp.id;
				cloneOpportunityTeam(newOpp.id, recordId);
						}				  
					
					// 2017-12-04 Added By Jingwei for SF Support Ticket '00008286'***start***
					
				} else { 
					system.debug('===You cannot clone the read only opportunity');
					returnMessage = system.label.ReadOnlyCloneDenied;
				} 
				// 2017-12-04 Added By Jingwei for SF Support Ticket '00008286'***end***
			} else {
				returnMessage = system.label.AccessDenied;
			}
			system.debug('returnMessage' + returnMessage);
			return returnMessage;
		} catch(Exception ex) {
			system.debug('Print Exception' + ex);
			returnMessage = ex.getDmlMessage(0);
			ExceptionHandler.addException(ex, GlobalConstants.CLONE_OPPORTUNITY, GlobalConstants.GET_CLONE_OPPTY);
			return returnMessage;
		}		
	}
	/*******************************
Method Name: cloneOpportunityTeam
Description: Requirement 1507: Sales Process: Opportunity Cloning 
Parameters: old Opportunity id , new Opportunity id
*******************************/
	public static void cloneOpportunityTeam(ID newOpptyId, string oldOpptyID) {
		List < OpportunityTeamMember > opportunityTeamMemberList = new List < OpportunityTeamMember > ();
		List < OpportunityTeamMember > newOpportunityTeamMemberList = null;
		OpportunityTeamMember opportunityTeamMemberObj = new OpportunityTeamMember();
		Id currentUserId = UserInfo.getUserId() ;
		String accManager = System.Label.ACC_MANAGER_TRICON_SCO ;
		Set<String> additionalRole = new Set<String>();
		String roles;
		try {
			opportunityTeamMemberList = [SELECT UserId, User.IsActive, Additional_Team_Role__c, 
										 Name, OpportunityAccessLevel, OpportunityId, TeamMemberRole, Opportunity.OwnerId
										 FROM OpportunityTeamMember where OpportunityId = :oldOpptyID
										 and TeamMemberRole != NULL and User.IsActive = True
										 LIMIT: Limits.getLimitQueryRows() - Limits.getQueryRows()];
			if (!opportunityTeamMemberList.isEmpty()) {
				system.debug('Inside if offerteamlist');
				newOpportunityTeamMemberList = new List < OpportunityTeamMember > ();
				
				for (OpportunityTeamMember obj: opportunityTeamMemberList) {
					system.debug('obj' + obj);
					if(currentUserId != obj.UserId && obj.TeamMemberRole != accManager){
						opportunityTeamMemberObj = new OpportunityTeamMember();
						opportunityTeamMemberObj.Additional_Team_Role__c = obj.Additional_Team_Role__c;
						opportunityTeamMemberObj.UserId = obj.UserId;
						opportunityTeamMemberObj.OpportunityId = newOpptyId;
						opportunityTeamMemberObj.OpportunityAccessLevel = obj.OpportunityAccessLevel;
						opportunityTeamMemberObj.TeamMemberRole = obj.TeamMemberRole;
						newOpportunityTeamMemberList.add(opportunityTeamMemberObj);
					}else if(currentUserId == obj.UserId && obj.Additional_Team_Role__c != Null){
						opportunityTeamMemberObj = new OpportunityTeamMember();
						roles = obj.Additional_Team_Role__c;
						if(roles.contains(accManager)){
							for(String roleVal : roles.split(';'))
							{
								additionalRole.add(roleVal);
							}
							additionalRole.remove(accManager);
							if(additionalRole.size() > 0)
							{
								for(String str : additionalRole)
								{
									if(opportunityTeamMemberObj.Additional_Team_Role__c == null)
									{
										opportunityTeamMemberObj.Additional_Team_Role__c = str;
									}else{
										opportunityTeamMemberObj.Additional_Team_Role__c = opportunityTeamMemberObj.Additional_Team_Role__c+GlobalConstants.SEMICOLON+ str ;  
									}									
								}
							}
							system.debug('opportunityTeamMemberObj.Additional_Team_Role__c'+opportunityTeamMemberObj.Additional_Team_Role__c);
						}else
							opportunityTeamMemberObj.Additional_Team_Role__c = obj.Additional_Team_Role__c;
						opportunityTeamMemberObj.UserId = obj.UserId;
						opportunityTeamMemberObj.OpportunityId = newOpptyId;
						opportunityTeamMemberObj.TeamMemberRole = accManager;
						opportunityTeamMemberObj.OpportunityAccessLevel = GlobalConstants.ALL_ACCESS;
						newOpportunityTeamMemberList.add(opportunityTeamMemberObj);
					}
				}
				
				system.debug('Final newOpportunityTeamMemberList' + newOpportunityTeamMemberList);
				if (!newOpportunityTeamMemberList.isEmpty()) {
					Database.SaveResult[] savedResults = Database.insert(newOpportunityTeamMemberList, false);
					Boolean someFailure = false;
					for (Database.SaveResult sr: savedResults) {
						if (!sr.isSuccess()) {
							someFailure = true;
							for (Database.Error err: sr.getErrors()) {
								System.debug('Error occured : ' + err.getStatusCode() + ' : ' + err.getMessage());
								System.debug('Fields that affected this error : ' + err.getFields());
							}
						}
					}
					if (!someFailure) {
						System.debug('Opty Team added successfully');
					}
				}
				system.debug('OptyTeam Insert successful');
			}
		}
		catch(Exception ex) {
			ExceptionHandler.addException(ex, GlobalConstants.CLONE_OPPORTUNITY, GlobalConstants.GET_CLONE_OPPTY);
		}
	}
}