src/objects/Dated_Exchange_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <description>Enter Exchange rate value (Req:136)</description>
        <inlineHelpText>Please enter the exchange rate from the selected currency to EUR</inlineHelpText>
        <label>Exchange Rate</label>
        <precision>13</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This will refer Start date of Exchange Rate</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Dated Exchange Rates</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dated Exchange Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Map_Enterprise_MUs_and_Market__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map enterprise market unit with market</description>
    <fields>
        <fullName>Enterprise_MU__c</fullName>
        <description>Enterprise Market unit</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Enterprise_MU</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Market level</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Market</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Map Enterprise MUs and Market</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>G4_Approval_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G4 Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LOA_Level__c</fullName>
        <description>LOA Level filled by the value of LOA level of Active offer</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Approval Level (from Active Offer)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L3__c</fullName>
        <formula>Account.L3Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_3</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L4__c</fullName>
        <formula>Account.L4Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_4</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L5__c</fullName>
        <formula>Account.L5Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_5</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_BG_NEN__c</fullName>
        <description>Presales Req#5539 Jan Release - no longer used after March 2021 due to AP2021</description>
        <formula>PSR_Cost_BU_NE_IoT__c + PSR_Cost_BU_NE_DAaaS__c + PSR_Cost_BU_NE_EOP__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG NEN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_AA__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG NSW</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_FN__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG FN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_GS__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG GS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_ION__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <formula>PSR_Cost_BU_ION_IPR_DNI__c +PSR_Cost_BU_ION_IPR_MPC__c + PSR_Cost_BU_ION_IPR_Nuage__c + PSR_Cost_Business_Unit_ION_IPR__c + PSR_Cost_BU_ION_IPR_Services__c + PSR_Cost_Business_Unit_ION_Optics__c + PSR_Cost_BU_ION_Optics_Services__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG ION</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_MN__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG MN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_GateClass__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PSR Gate Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSR_LoA_Level__c</fullName>
        <description>Sales Process &gt; Jan release 18 &gt; Req 5561</description>
        <label>Approval Level Pre-Sales</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Pre_Sales_Risk_Opportunity_Sub_Type__c</fullName>
        <description>PreSales : Sprint 6: Req#2171</description>
        <label>Pre-Sales Risk Opportunity Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PSR_Pre_Sales_Risk_Opportunity_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FoC</fullName>
                </value>
                <value>
                    <fullName>Risk Order Only</fullName>
                </value>
                <value>
                    <fullName>Risk Order With Risk Shipment</fullName>
                    <label>Risk Order with Risk Shipment</label>
                </value>
                <value>
                    <fullName>Commercial Trial</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Trial</fullName>
                </value>
                <value>
                    <fullName>CT Customer</fullName>
                </value>
                <value>
                    <fullName>Multiple Customers</fullName>
                </value>
                <value>
                    <fullName>Contractual Requirement</fullName>
                </value>
                <value>
                    <fullName>Good Will</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Pre_Sales_Risk_Opportunity_Type__c</fullName>
        <description>PreSales : Sprint 6: Req#2171</description>
        <label>Pre-Sales Risk Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk Order</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Free of Charge</fullName>
                    <label>Free of Charge (do not use)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Reference_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Sales Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Sales Risk Opportunities</relationshipLabel>
        <relationshipName>PreSalesOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_Total_Cost_In_Euro__c</fullName>
        <description>Req : 2316 . Cost in Euros</description>
        <label>Total Cost In Euro</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PSR_Gate_Classification_Logic__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>REQ#3457-Update Classification logic.
Used to maintain Gate classification configuration.</description>
    <fields>
        <fullName>BG_Value__c</fullName>
        <description>Maintains BG values</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BG Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOA_Level__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>LOA Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <description>Maintains Oppty Type</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PSR Gate Classification Logic</label>
</CustomObject>

src/objects/PSRO_Market_Threshold__c.object
<CustomObject>
    <description>Contains Threshold and open values from Presales opportunities based on BGs</description>
    <fields>
        <fullName>Business_Group__c</fullName>
        <description>BG</description>
        <label>Business Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_value__c</fullName>
        <description>sum of all the open  presales opportunities value based on BG</description>
        <label>Current value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Market Asia Pacific &amp; Japan</fullName>
                </value>
                <value>
                    <fullName>Market Europe</fullName>
                </value>
                <value>
                    <fullName>Market Greater China</fullName>
                </value>
                <value>
                    <fullName>Market India</fullName>
                </value>
                <value>
                    <fullName>Market Latin America</fullName>
                </value>
                <value>
                    <fullName>Market Middle East and Africa</fullName>
                </value>
                <value>
                    <fullName>Market North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threshold_value__c</fullName>
        <description>Threshold value for Presales opportunities based on BG</description>
        <label>Threshold value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>PSRO Market Threshold</label>
    <nameField>
        <displayFormat>TH-{0000}</displayFormat>
        <label>BG_Threshold Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRO Market Thresholds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Role__c.object
<CustomObject>
    <description>Object that maintains the Nokia Sales Organization Hierarchy</description>
    <fields>
        <fullName>O__c</fullName>
        <description>Used this field in Approval Rules to redecue the query size</description>
        <formula>Organisation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Apttus Organization</label>
        <type>Text</type>
    </fields>
    <label>Sales Role</label>
    <nameField>
        <displayFormat>CMD-{0000}</displayFormat>
        <label>Sales Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/classes/PSRO_Calculate_BG_Cost.cls
public class PSRO_Calculate_BG_Cost {

public static Decimal returnValueOfField(Decimal fieldValue){
  Return fieldValue == Null ? 0 : fieldValue;				   
}
public static Boolean returnexceed(Opportunity NewOppty,Map<String, Decimal> Datedrate, PSRO_Market_Threshold__c BGVal)
{
Boolean exceed;
Decimal BG_Cost = 0;
If(BGVal.Business_Group__c ==  GlobalConstants.Lead_BG_NSW  && returnValueOfField(NewOppty.PSR_Cost_Business_Group_AA__c) != 0)
{   
 BG_Cost = (returnValueOfField(NewOppty.PSR_Cost_Business_Group_AA__c)).divide(datedrate.get(NewOppty.CurrencyIsoCode),2,System.RoundingMode.HALF_UP);
}
If(BGVal.Business_Group__c == GlobalConstants.Lead_BG_FN && returnValueOfField(NewOppty.PSR_Cost_Business_Group_FN__c) != 0)
{
  BG_Cost = (returnValueOfField(NewOppty.PSR_Cost_Business_Group_FN__c)).divide(datedrate.get(NewOppty.CurrencyIsoCode),2,System.RoundingMode.HALF_UP);

}
If(BGVal.Business_Group__c == GlobalConstants.Lead_BG_ION && returnValueOfField(NewOppty.PSR_Cost_Business_Group_ION__c) != 0)
{
BG_Cost = (returnValueOfField(NewOppty.PSR_Cost_Business_Group_ION__c)).divide(datedrate.get(NewOppty.CurrencyIsoCode),2,System.RoundingMode.HALF_UP);

}
If(BGVal.Business_Group__c == GlobalConstants.Lead_BG_MN && returnValueOfField(NewOppty.PSR_Cost_Business_Group_MN__c) != 0)
{
 BG_cost = (returnValueOfField(NewOppty.PSR_Cost_Business_Group_MN__c)).divide(datedrate.get(NewOppty.CurrencyIsoCode),2,System.RoundingMode.HALF_UP);
}
If(BGVal.Business_Group__c == GlobalConstants.Lead_BG_GS && returnValueOfField(NewOppty.PSR_Cost_Business_Group_GS__c) != 0)
{
BG_cost = (returnValueOfField(NewOppty.PSR_Cost_Business_Group_GS__c)).divide(datedrate.get(NewOppty.CurrencyIsoCode),2,System.RoundingMode.HALF_UP);
}
If(BGVal.Business_Group__c == GlobalConstants.Lead_BG_NEN && returnValueOfField(NewOppty.PSR_Cost_BG_NEN__c) != 0)
{
 BG_cost = (returnValueOfField(NewOppty.PSR_Cost_BG_NEN__c)).divide(datedrate.get(NewOppty.CurrencyIsoCode),2,System.RoundingMode.HALF_UP);								  
}
if(BG_cost != 0 && BG_Cost != null && ((returnValueOfField(BGVal.current_value__c) + returnValueOfField(BG_Cost)) > BGVal.Threshold_Value__c))
{ 
exceed = true; 
}
return exceed;
}
public static Opportunity calculateLoAlevel(Opportunity opportunity)
{
		Map<Id, Opportunity> preSalesOptyMapForLoAlevel = new Map<Id, Opportunity>();
		Map <Id, Opportunity> salesOptyWithApprovalDateMap = new Map <Id, Opportunity>();
		 Id PSR_EditRecordTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(GlobalConstants.PRESALESRISKOPPORTUNITY).getRecordTypeId();	
		try{
			List<Map_Enterprise_MUs_and_Market__c> mapL5_L4 = Map_Enterprise_MUs_and_Market__c.getAll().values();
			string orgL4 = opportunity.Org_L4__c;
			If(opportunity.PSR_Pre_Sales_Risk_Opportunity_Type__c.equalsIgnoreCase(GlobalConstants.RISK_ORDER))
			{
			If(opportunity.Org_L3__c == GlobalConstants.Nokia_Enterprise)
			{
				for(Map_Enterprise_MUs_and_Market__c mapobj : mapL5_L4)
				{
				If(mapobj.Enterprise_MU__c == opportunity.org_l5__c)
				{ orgl4 = mapobj.Market__c; }	   
				}
			}
			List<PSRO_Market_Threshold__c> ThresholdList = [Select Id, Market__c, Threshold_Value__c, current_value__c, Business_Group__c 
											  from PSRO_Market_Threshold__c where Market__c = :orgL4];
			
			List<PSRO_Market_Threshold__c>  UpdateList = new List<PSRO_Market_Threshold__c> ();
			List<PSRO_Market_Threshold__c>  sendmail_List = new List<PSRO_Market_Threshold__c> ();
			 Map<String, Decimal> datedrate = new Map<String, Decimal>();
			Boolean exceed;
			Date todayDate = Date.Today();			  
		   
			   for (Dated_Exchange_Rates__c ratecollect:  [select Id, CurrencyIsoCode, Exchange_Rate__c, Start_Date__c
															from Dated_Exchange_Rates__c where CurrencyIsoCode =: opportunity.CurrencyIsoCode  
															AND Start_Date__c<=: todayDate
															Order By Start_Date__c ASC LIMIT: Limits.getLimitQueryRows()]){
																datedrate.put(ratecollect.CurrencyIsoCode, ratecollect.Exchange_Rate__c);
															}
			

					for(PSRO_Market_Threshold__c BGVal : ThresholdList)
					{   
						Decimal BG_cost = 0;
						Decimal current_value = 0;  

							Boolean checkVal = returnexceed(Opportunity,datedrate,BGVal);
							If(checkVal == true)
								exceed = true;						 
					}
					
				   
					If(exceed == true && opportunity.recordTypeId == PSR_EditRecordTypeID)
					{
					opportunity.PSR_LoA_Level__c = GlobalConstants.LOA_Level; //A
					opportunity.PSR_GateClass__c = GlobalConstants.Gate_R4;
					}
					else if(opportunity.recordTypeId == PSR_EditRecordTypeID)
					{ 
						Opportunity ParentOppty = [select id, G4_Approval_Date__c from Opportunity where id = :opportunity.PSR_Reference_Opportunity__c ]; 
							If(parentOppty.G4_Approval_Date__c == null)
							{
							   opportunity.PSR_LoA_Level__c = GlobalConstants.LOA_Level; //A
							   opportunity.PSR_GateClass__c = GlobalConstants.Gate_R4;
						   }
						else
						{
							
							List<PSR_Gate_Classification_Logic__c> objList;
							objList = PSR_Gate_Classification_Logic__c.getall().values();
							objList.sort();
							for(integer i = 0; i< objList.size(); i++){
								system.debug('Cost Value:'+opportunity.PSR_Total_Cost_In_Euro__c+'...'+objList[i].BG_Value__c+'...'+objList[i].LOA_Level__c);
								if(opportunity.PSR_Pre_Sales_Risk_Opportunity_Type__c == objList[i].Opportunity_Type__c && 
								   opportunity.PSR_Pre_Sales_Risk_Opportunity_Sub_Type__c == objList[i].Opportunity_Sub_Type__c &&
								   opportunity.PSR_Lead_Business_Group__c == objList[i].BG_Value__c && ((opportunity.PSR_Total_Cost_In_Euro__c >= objList[i].Min_Value__c && opportunity.PSR_Total_Cost_In_Euro__c <= objList[i].Max_Value__c)  || (opportunity.PSR_Total_Cost_In_Euro__c >= objList[i].Max_Value__c && objList[i].Min_Value__c == Null))){
									   system.debug('Check Logic:');
									   opportunity.PSR_GateClass__c = objList[i].Gate_Classification__c;
									   opportunity.PSR_LoA_Level__c = objList[i].LOA_Level__c;
									   System.debug('PSR_Total_Cost_In_Euro__c>>>>>>>>>' + opportunity.PSR_Total_Cost_In_Euro__c);
									   System.debug('PSR_Total_Cost_In_Euro__c>>>>>>>>>' + opportunity.PSR_GateClass__c);
									   System.debug('objList[i].LOA_Level__c>>>>>>>>>opportunity.PSR_LoA_Level__c' + objList[i].LOA_Level__c+'>>>'+opportunity.PSR_LoA_Level__c);
									   
								   }
							}
						}
					}
				update Opportunity;
				}
			} 
		
		catch(Exception ex) {
			ExceptionHandler.addException(ex, GlobalConstants.CALCULATELOALEVEL, GlobalConstants.CALCULATELOALEVEL);
		}
	   return opportunity; 
	} 
Public static void psroThresholdMail(List<PSRO_Market_Threshold__c> sendmail_List)
{
try
{
EmailTemplate et=[SELECT Id FROM EmailTemplate WHERE developerName =:Label.NF_ThresholdExceededNotification LIMIT 1];		   
List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
String roles = Label.PSRO_Threshold_send_Mail;
List<String> Rolelist = roles.split(';');
set<String> RoleSet = new set<string>();
 RoleSet.addAll(Rolelist);
List<Sales_Role__c> SRList = [Select Id, BG__c, O__c, User__C from Sales_Role__c where Role_Code__c in :RoleSet];
	system.debug('SRList:'+SRList);
for(PSRO_Market_Threshold__c ThRec : sendmail_List)
{
for(Sales_Role__c SRrec : SRList)
{
If(SRrec.Bg__C == ThRec.Business_group__c)
{
Messaging.SingleEmailMessage Participants = new Messaging.SingleEmailMessage();
Participants.setWhatId(ThRec.Id);
participants.setTargetObjectId(SRrec.user__c);
participants.setTemplateId(et.Id);
participants.setSaveAsActivity(false);
system.debug('participants'+participants);
mailList.add(participants);
}
}

}
	
if(!mailList.isEmpty()){
system.debug('Send mail:'+mailList);
		Messaging.SendEmailResult[] results=Messaging.sendEmail(mailList);   
	}
}
catch(Exception ex) {
ExceptionHandler.addException(ex, GlobalConstants.PSROThresholdMail, GlobalConstants.PSROThresholdMail);
}
}
}