src/objects/HWS_AlternateProductCode__c.object
<CustomObject>
    <fields>
        <fullName>HWS_IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HWS_NSNCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Part Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_PartType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PartType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_VersionItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User Story - 1083, to store the version Item.</description>
        <label>Version Item</label>
        <referenceTo>HWS_VersionItem__c</referenceTo>
        <relationshipLabel>Alternate Product Codes</relationshipLabel>
        <relationshipName>Alternate_Product_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Alternate Product Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Alternate Code/Kit Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate Product Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HWS_VersionItem__c.object
<CustomObject>
    <fields>
        <fullName>HWS_Material_Type__c</fullName>
        <description>Created as the part of the US.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Material Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_NSNCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>NSN Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_Serial_Number_Traceable__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Serial Number Traceable</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_Source__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_Version_Code__c</fullName>
        <description>Created as the part of the US.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Version Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Version Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CARE_PartCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CARES Part Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HWS_DoNotConsider__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Consider</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HWS_Material_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Material Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_Source__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>NokiaCPQ_Sales_Product</fullName>
        <active>true</active>
        <label>Sales Product</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HWS_EDP_ProcessAlternateCodes_BATCH_Test.cls
@isTest 

public class HWS_EDP_ProcessAlternateCodes_BATCH_Test {
	
	@isTest 
	static void testproductServicableAltcode5001() 
	{   
		list<hws_versionitem__c> HWVList =new  list<hws_versionitem__c>();
		hws_versionitem__c hwvitem =new  hws_versionitem__c();
		hwvitem.Name='test';
		hwvitem.HWS_Serial_Number_Traceable__c='Yes';
		hwvitem.HWS_Material_Type__c ='123';
		hwvitem.Material_Code__c= '1234';
		hwvitem.HWS_Version_Code__c='test';
		HWVList.add(hwvitem);
		insert HWVList;
		
		list<HWS_AlternateProductCode__c> altcodelist = new list<HWS_AlternateProductCode__c>();
		HWS_AlternateProductCode__c alt = new HWS_AlternateProductCode__c();
		alt.HWS_VersionItem__c=HWVList[0].id;
		alt.HWS_PartType__c='PART';
		alt.Name='test';
		alt.HWS_IsProcessed__c=true;
		alt.HWS_NSNCode__c='NSN123';
		altcodelist.add(alt);
		//insert altcodelist;  
		
		hws_versionitem__c hwvitem1 =new  hws_versionitem__c();
		hwvitem1.Name='test';
		hwvitem1.HWS_Serial_Number_Traceable__c='Yes';
		hwvitem1.HWS_Material_Type__c ='123';
		hwvitem1.Material_Code__c= '1234';
		hwvitem1.HWS_Version_Code__c='test';
		hwvitem1.HWS_NSNCode__c='NSN123';
		hwvitem1.HWS_Source__c='PUMA2';
		insert hwvitem1;
		
		List<product2> prodlist =new List<product2>();
		product2 pr2 = new product2();
		Id rtId = Schema.SObjectType.product2.getRecordTypeInfosByDeveloperName().get('NokiaCPQ_Sales_Product').getRecordTypeId();
		pr2.RecordTypeId =rtId;
		pr2.Name ='ProductCode';
		pr2.IsActive = true;
		pr2.Description='ProductCode';
		pr2.ProductCode = 'NSN123';
		pr2.HWS_DoNotConsider__c=false;
		pr2.CARE_PartCode__c='test';
 		prodlist.add(pr2);
		insert prodlist;
		 
		Test.startTest();
		
		
		HWS_EDP_ProcessAlternateCodes_BATCH batch = new HWS_EDP_ProcessAlternateCodes_BATCH();
		Database.BatchableContext BC;
		SchedulableContext SC;
		batch.start(BC);
		batch.execute(SC);
		batch.execute(BC,altcodelist);		 
		 batch.finish(BC);
		Test.StopTest();
	
		
	}
	
	@isTest 
	static void testproductServicableAltcode5002() 
	{   
		hws_versionitem__c hwvitem =new  hws_versionitem__c();
		hwvitem.Name='test';
		hwvitem.HWS_Serial_Number_Traceable__c='Yes';
		hwvitem.HWS_Material_Type__c ='123';
		hwvitem.Material_Code__c= '1234';
		hwvitem.HWS_Version_Code__c='test';
		 insert hwvitem;
		
		list<HWS_AlternateProductCode__c> altcodelist = new list<HWS_AlternateProductCode__c>();
		HWS_AlternateProductCode__c alt = new HWS_AlternateProductCode__c();
		alt.Name='test';
		alt.HWS_VersionItem__c=hwvitem.id;
		alt.HWS_PartType__c='Material';
		alt.HWS_IsProcessed__c=true;
		alt.HWS_NSNCode__c='NSN123';
		altcodelist.add(alt);
		//insert altcodelist; 

		List<product2> prodlist =new List<product2>();
		product2 pr2 = new product2();
		Id rtId = Schema.SObjectType.product2.getRecordTypeInfosByDeveloperName().get('NokiaCPQ_Sales_Product').getRecordTypeId();
		pr2.RecordTypeId =rtId;
		pr2.Name ='ProductCode';
		pr2.IsActive = true;
		pr2.Description='ProductCode';
		pr2.ProductCode = 'NSN123';
		pr2.HWS_DoNotConsider__c=false;
		pr2.CARE_PartCode__c='test';
 		prodlist.add(pr2);
		insert prodlist;
		
		Test.startTest();
		
		
		HWS_EDP_ProcessAlternateCodes_BATCH batch = new HWS_EDP_ProcessAlternateCodes_BATCH();
		Database.BatchableContext BC;
		SchedulableContext SC;
		batch.start(BC);
		batch.execute(SC);
		batch.execute(BC,altcodelist);		 
		 batch.finish(BC);
		Test.StopTest();
	
		
	}
}