src/objects/HWS_AlternateProductCode__c.object
<CustomObject>
    <fields>
        <fullName>HWS_IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HWS_NSNCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Part Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_PartType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PartType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_VersionItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User Story - 1083, to store the version Item.</description>
        <label>Version Item</label>
        <referenceTo>HWS_VersionItem__c</referenceTo>
        <relationshipLabel>Alternate Product Codes</relationshipLabel>
        <relationshipName>Alternate_Product_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Alternate Product Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Alternate Code/Kit Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate Product Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HWS_VersionItem__c.object
<CustomObject>
    <fields>
        <fullName>HWS_NSNCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>NSN Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_Source__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Version Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Version Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interface_Log__c.object
<CustomObject>
    <description>This object will be used for Interface/error handling</description>
    <fields>
        <fullName>Comment__c</fullName>
        <description>Comment section for Error Log</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comment</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Interface_Type__c</fullName>
        <description>What are the type of Interface</description>
        <label>Interface Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ALCR ACC SYNC</fullName>
                </value>
                <value>
                    <fullName>Business Hours</fullName>
                </value>
                <value>
                    <fullName>CAPSV to SF</fullName>
                </value>
                <value>
                    <fullName>CARES Authorised Entitlement</fullName>
                </value>
                <value>
                    <fullName>CARES Child Service Contract</fullName>
                </value>
                <value>
                    <fullName>CARES Contract Line Item</fullName>
                </value>
                <value>
                    <fullName>CARES Parent Service Contract</fullName>
                </value>
                <value>
                    <fullName>CART Interface</fullName>
                </value>
                <value>
                    <fullName>CDB/CARES Interface Generic Error</fullName>
                </value>
                <value>
                    <fullName>CDB CARE Contract Type</fullName>
                </value>
                <value>
                    <fullName>CDB CARE Service Contract</fullName>
                </value>
                <value>
                    <fullName>CDB ServiceContract</fullName>
                </value>
                <value>
                    <fullName>CDB Supplier</fullName>
                </value>
                <value>
                    <fullName>CMD Pack1 Account Sync</fullName>
                </value>
                <value>
                    <fullName>CMD Pack3 P20ID Sync</fullName>
                </value>
                <value>
                    <fullName>CMD Pack4 Sales Role Sync</fullName>
                </value>
                <value>
                    <fullName>CMD Pack4 User Sync</fullName>
                </value>
                <value>
                    <fullName>CMD Pack 5 Account Sync</fullName>
                </value>
                <value>
                    <fullName>Contract Line Item</fullName>
                </value>
                <value>
                    <fullName>CQ Process Quote</fullName>
                </value>
                <value>
                    <fullName>CQ Sync Offer</fullName>
                </value>
                <value>
                    <fullName>CQ Sync Quote</fullName>
                </value>
                <value>
                    <fullName>CQ UpdateQuote/Pricing</fullName>
                </value>
                <value>
                    <fullName>CQ UpdateQuote/Status</fullName>
                </value>
                <value>
                    <fullName>CSOD Certification Sync</fullName>
                </value>
                <value>
                    <fullName>CSOD Course Sync</fullName>
                </value>
                <value>
                    <fullName>CSOD Curriculum Mapping Table Sync</fullName>
                </value>
                <value>
                    <fullName>Customer S2S</fullName>
                </value>
                <value>
                    <fullName>Customers SSO JIT</fullName>
                </value>
                <value>
                    <fullName>DataHub</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>What is the type of the message</description>
        <label>Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operation_Type__c</fullName>
        <description>What is the type of operation like insert/ delete/update</description>
        <label>Operation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>What is the status of the error/interface log</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Batch Update Opportunity Managers - Apex Batch Logs</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>Partial Success (Race Conditions Occurred)</fullName>
                </value>
                <value>
                    <fullName>Request queued for future callout</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Post Processing Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interface Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interface Log	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interface Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CARE_PartCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CARES Part Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HWS_DoNotConsider__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Consider</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HWS_Source__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HWS_EDP_ProcessAlternateCodes_BATCH.cls
global class HWS_EDP_ProcessAlternateCodes_BATCH implements Database.Batchable<sObject>,Database.Stateful,Schedulable{
	/****************************************
* Name : AletnateCode records process
* Author : TCS
* Description : 
* User Stroy : 

/****************************************
* Name : execute
* Description : executes the batch class using schedulable instance
* Parameters: SchedulableContext
*****************************************/
	global void execute(SchedulableContext sc)	  
	{
		HWS_EDP_ProcessAlternateCodes_BATCH batch= new HWS_EDP_ProcessAlternateCodes_BATCH();
		Database.executebatch(batch,1);			
	} 
	
	/****************************************
* Name : start
* Description : Retrieves the data from ProductAlternateCode
* Parameters: Database.BatchableContext
* Returns : Database.QueryLocator
*****************************************/
	global Database.QueryLocator start(Database.BatchableContext bc)
	{
		
		String squery = 'select Name,HWS_VersionItem__c,HWS_PartType__c , HWS_IsProcessed__c ,HWS_NSNCode__c from HWS_AlternateProductCode__c where HWS_IsProcessed__c = false';
		return database.getQueryLocator(squery);
	}
	
	/****************************************
* Name : execute
* Description : Retrieves the data from product serviceable version item staging object
* Parameters: Database.BatchableContext, List of Product sales item
* Returns : 
*****************************************/	
	global void execute(Database.BatchableContext bc, List<HWS_AlternateProductCode__c> alternatecodes)
	{	 
		try 
		{ 
			List<HWS_AlternateProductCode__c> toUpdateprodSerAltCode = new List<HWS_AlternateProductCode__c>();
			Map<String,Id> nsnVerIdMap = new Map<String,Id>();
			Set<String> nsnCodesforVersion= new Set<String>();
			Map<String,String> nsncaresCodeMap = new Map<String,String>();
			Map<String,HWS_AlternateProductCode__c> alternatecodesmap = new Map<String,HWS_AlternateProductCode__c>();
			
			
			for(HWS_AlternateProductCode__c prodAltCode : alternatecodes){
				nsnCodesforVersion.add(prodAltCode.HWS_NSNCode__c);  
			}
			
			List<HWS_VersionItem__c> versionItemList = [Select id,HWS_NSNCode__c from HWS_VersionItem__c where HWS_NSNCode__c in: nsnCodesforVersion and HWS_Source__c='PUMA2'];		
			if(versionItemList.size()>0){
				for(HWS_VersionItem__c version : versionItemList){
					nsnVerIdMap.put(version.HWS_NSNCode__c,version.Id);
				}
			}
			
			
			for(HWS_AlternateProductCode__c prodAltCode : alternatecodes){
				if(prodAltCode.HWS_PartType__c =='PART'){
					nsnCodesforVersion.add(prodAltCode.HWS_NSNCode__c);
					nsncaresCodeMap.put(prodAltCode.HWS_NSNCode__c,prodAltCode.Name);
					alternatecodesmap.put(prodAltCode.HWS_NSNCode__c,prodAltCode);
				  }else{
					prodAltCode.HWS_VersionItem__c = nsnVerIdMap.get(prodAltCode.HWS_NSNCode__c);
					if(prodAltCode.HWS_VersionItem__c!=null){
						  prodAltCode.HWS_IsProcessed__c=true; 
					}
					toUpdateprodSerAltCode.add(prodAltCode);
					system.debug(nsnVerIdMap.get(prodAltCode.HWS_NSNCode__c));
					
				}
			}
			
			
			List<Product2> listProd = [Select id, ProductCode from Product2 where ProductCode in:nsnCodesforVersion and HWS_DoNotConsider__c=false ];
			List<Product2> listProdNew = new List<Product2>();
			system.debug('List Product Size: '+listProd.size());
			if(listProd.size()>0){
				for(Product2 prod : listProd){
					Product2 newProd = new Product2();
					newProd.Id = prod.Id;
					newProd.CARE_PartCode__c = nsncaresCodeMap.get(prod.ProductCode);
					if(newProd.CARE_PartCode__c !=null)
					{
						HWS_AlternateProductCode__c altcode= alternatecodesmap.get(prod.ProductCode);
						altcode.HWS_IsProcessed__c=true;
						toUpdateprodSerAltCode.add(altcode);
					}
					listProdNew.add(newProd);
				} 
			}
			
			
			List<Database.SaveResult> resultscares = Database.update(listProdNew,false);
			List<Database.SaveResult> resultsalternatecodes = Database.update(toUpdateprodSerAltCode,false);
			
			List<interface_log__c> ilogs = new List<interface_log__c>();
			for(Integer index = 0, size = resultscares.size(); index < size; index++) {
				if(!resultscares[index].isSuccess()) { 
					Interface_Log__c ilogpr = new Interface_Log__c();
					for (Database.Error err : resultscares[index].getErrors()){
						ilogpr.comment__c = 'Fields: '+err.getFields()+'Message: '+err.getMessage()+
							'Status Code: '+err.getStatusCode();
					}
					ilogpr.Interface_Type__c = 'HWS AletnateCode For Part';
					ilogpr.Message_Type__c = 'Inbound';
					ilogpr.Operation_Type__c = 'update';
					ilogpr.Status__c = 'Failure';
					ilogpr.Name = 'Product Serviceable Alternate Code Failure with NSNCode: '+ listProdNew[index].ProductCode;
					ilogs.add(ilogpr);
				} 
				
			}
			
			
			for(Integer index = 0, size = resultsalternatecodes.size(); index < size; index++) {
				if(!resultsalternatecodes[index].isSuccess()) { 
					Interface_Log__c ilogpr = new Interface_Log__c();
					for (Database.Error err : resultsalternatecodes[index].getErrors()){
						ilogpr.comment__c = 'Fields: '+err.getFields()+'Message: '+err.getMessage()+
							'Status Code: '+err.getStatusCode();
					}
					ilogpr.Interface_Type__c = 'HWS AletnateCode For Part Revison';
					ilogpr.Message_Type__c = 'Inbound';
					ilogpr.Operation_Type__c = 'update';
					ilogpr.Status__c = 'Failure';
					ilogpr.Name = 'Product Serviceable Alternate Code Failure with NSNCode: '+ toUpdateprodSerAltCode[index].HWS_NSNCode__c;
					ilogs.add(ilogpr);
					
				} 
				
			}
			
			
			Database.SaveResult[] results = Database.insert(ilogs,false);
			nsnVerIdMap.clear(); 
			nsnCodesforVersion.clear();
			nsnCodesforVersion.clear();
			nsncaresCodeMap.clear();
			resultscares.clear();
			ilogs.clear();
			alternatecodesmap.clear();
			
			
		}	  
		catch (DmlException e) { 
			System.debug('There was an error during the AletnateCode Insert'); 
		} 
		
		
	}
	
	/****************************************
* Name : finish
* Description : 
* Parameters: Database.BatchableContext
* Returns : 
*****************************************/ 
	global void finish(Database.BatchableContext bc)
	{
		HWS_EDP_BuildRelation_Product_Part batch = new HWS_EDP_BuildRelation_Product_Part();
		Database.executebatch(batch,2000);  
	}
	
	
}