src/objects/HWS_Product_Serviceable_Version_Item__c.object
<CustomObject>
    <fields>
        <fullName>HWS_EDP_ActiveStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDP_Active Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HWS_EDP_DeletedAtSource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDP_Deleted At Source</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HWS_FITRate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>FIT Rate</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HWS_MaterialType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Material Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HWS_NSNCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>NSN Code</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HWS_PartRevision__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Part Revision</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Product Serviceable Version Item</label>
    <nameField>
        <displayFormat>SVI-{000000000}</displayFormat>
        <label>Product Serviceable Version Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Serviceable Version Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HWS_Product_Version_Item__c.object
<CustomObject>
    <description>Staging table to store serviceable part revisions</description>
    <fields>
        <fullName>HWS_NSNCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>NSNCode</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Version Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Part Revision Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Version Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HWS_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SettingValue__c</fullName>
        <label>SettingValue</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>HWS_Settings</label>
</CustomObject>

src/objects/HWS_VersionItem__c.object
<CustomObject>
    <fields>
        <fullName>HWS_EDP_ActiveStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDP ActiveStatus</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HWS_EDP_DeletedAtSource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDP DeletedAtSource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HWS_NSNCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>NSN Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Version Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Version Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NokiaCPQ_PMDI_Parameter__c.object
<CustomObject>
    <description>This is the object to store the Product Master Data Integration parameters. This is part of the PoC for the CPQ PMDI Blueprinting.</description>
    <fields>
        <fullName>NokiaCPQ_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_ObjNameSrc__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Object Name Source</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_ObjNameTrg__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Object Name Target</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_ParaFrom__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Parameter From</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_ParaTo__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Parameter To</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_ParaType__c</fullName>
        <description>This is the value list for the PMDI parameters that control the interface EDP -&gt; Salesforce.</description>
        <label>Parameter Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMDI_Parameter_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NokiaCPQ_ReqMap__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Mapping</label>
        <type>Checkbox</type>
    </fields>
    <label>PMDI Parameter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PMDI Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMDI Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>HWS_EDP_ActiveStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDP ActiveStatus</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HWS_EDP_DeletedAtSource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDP DeletedAtSource</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/PMDI_Parameter_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INTERFACE_MODE</fullName>
    </customValue>
    <customValue>
        <fullName>SELECTION_TSTAMP</fullName>
    </customValue>
    <customValue>
        <fullName>MAPPING RULE</fullName>
    </customValue>
    <customValue>
        <fullName>MAPPING_VALUE</fullName>
    </customValue>
    <customValue>
        <fullName>FX_RATE_USD</fullName>
    </customValue>
    <customValue>
        <fullName>DIRECT_VALUE</fullName>
    </customValue>
    <customValue>
        <fullName>FX_RATE_EUR</fullName>
    </customValue>
    <description>This is the picklist for the PMDI parameters.</description>
    <masterLabel>PMDI Parameter Types</masterLabel>
</GlobalValueSet>

src/classes/HWS_EDP_SVItoVersionItem_BATCH_Test.cls
@istest
public class HWS_EDP_SVItoVersionItem_BATCH_Test {
	@istest
	public static  void getTestMethods(){
		
		Test.startTest();	
		
		HWS_Product_Serviceable_Version_Item__c prdSerVitem = new HWS_Product_Serviceable_Version_Item__c();
		
		prdSerVitem.HWS_EDP_ActiveStatus__c = true ;
		prdSerVitem.HWS_EDP_DeletedAtSource__c = true ;
		// prdSerVitem.LastModifiedDate = System.TODAY();  HWS_NSNCode__c
		prdSerVitem.HWS_FITRate__c = 'test';
		prdSerVitem.HWS_MaterialType__c = 'test';
		prdSerVitem.HWS_PartRevision__c = 'test';
		prdSerVitem.HWS_NSNCode__c = 'HWS_NSNCode__c';
		
		List<HWS_Product_Serviceable_Version_Item__c> pslst = new List<HWS_Product_Serviceable_Version_Item__c>();
		pslst.add(prdSerVitem);
		insert pslst;
		System.assertEquals(pslst[0].HWS_FITRate__c, 'test');
		
		//Parmeters for pricelist mapping
		NokiaCPQ_PMDI_Parameter__c lp= new NokiaCPQ_PMDI_Parameter__c();
		lp.Name='Currency Update';
		lp.NokiaCPQ_ObjNameSrc__c='HWS_Product_Version_Item__c';
		lp.NokiaCPQ_ObjNameTrg__c='HWS_Product_Version_Item__c';
		lp.NokiaCPQ_ParaFrom__c='HWS_NSNCode__c';
		lp.NokiaCPQ_ParaTo__c='HWS_NSNCode__c';
		lp.NokiaCPQ_ParaType__c='MAPPING RULE';		
		lp.NokiaCPQ_ReqMap__c=  false;
		lp.NokiaCPQ_Active__c = true;
		
		NokiaCPQ_PMDI_Parameter__c lp1 = new NokiaCPQ_PMDI_Parameter__c();
		lp1.Name='Currency Update';
		lp1.NokiaCPQ_ObjNameSrc__c='HWS_Product_Serviceable_Version_Item__c';
		lp1.NokiaCPQ_ObjNameTrg__c='HWS_Product_Serviceable_Version_Item__c';
		lp1.NokiaCPQ_ParaFrom__c='HWS_NSNCode__c';
		lp1.NokiaCPQ_ParaTo__c='HWS_NSNCode__c';
		lp1.NokiaCPQ_ParaType__c='MAPPING RULE';	   
		lp1.NokiaCPQ_ReqMap__c=  false;
		lp1.NokiaCPQ_Active__c = true;
		
		
		List<NokiaCPQ_PMDI_Parameter__c> lparas = new List<NokiaCPQ_PMDI_Parameter__c>();
		lparas.add(lp);
		lparas.add(lp1);	   
		insert lparas; 
		
		HWS_Settings__c hwsSetSVI = new HWS_Settings__c();
		// hwsSetSVI.Name = 'SVI Batch Size';
		hwsSetSVI.Name = 'SSI_SVI Batch Size';
		hwsSetSVI.SettingValue__c = 2000;
		hwsSetSVI.Description__c = 'test';	  
		insert hwsSetSVI;
		
		HWS_Settings__c hwsSetPVI = new HWS_Settings__c();
		hwsSetPVI.Name = 'PVI Batch Size';
		hwsSetPVI.SettingValue__c = 2000;
		hwsSetPVI.Description__c = 'test';	  
		insert hwsSetPVI;
		
		
		Product2 prod = HWS_DataFactory_TEST.insertproduct2();		
		insert prod;
		
		HWS_VersionItem__c hwsv=HWS_DataFactory_TEST.createVerionsItems(prod.ID);   
		insert hwsv;
		
		List<HWS_VersionItem__c> vi = HWS_ProcessServiceableVersionItem_SVC.updateTarget(pslst, lparas);
		
		HWS_EDP_SVItoVersionItem_BATCH svibatch = new HWS_EDP_SVItoVersionItem_BATCH();
		Database.BatchableContext bc;
		SchedulableContext sc;
		List<HWS_VersionItem__c > hviLst = new List<HWS_VersionItem__c>();
		HWS_VersionItem__c hwsvi = new HWS_VersionItem__c(Id='aCS560000008PRx');
		hviLst.add(hwsvi);
		Database.Error[] errors;
		Database.SaveResult[] results = Database.insert(hviLst,false);
		for (Database.SaveResult sr : results) {			
			if (sr.isSuccess()) {		
			}
			else{
	errors = sr.getErrors();
			}
		}	  
		svibatch.execute(sc);
		svibatch.getFields();
		svibatch.start(bc);	   
		svibatch.execute(bc,pslst);
		if(errors.size()>0){
			svibatch.createErrorLog(errors, hwsvi, 'Update');
		}
		svibatch.finish(bc);
		Test.stopTest();
	}
}