src/objects/NF_FacilitatorCustomQueue__mdt.object
<CustomObject>
    <description>This Custom MetaData is used to Store Rules for selecting the appropriate Queue</description>
    <fields>
        <fullName>Expected_LoA_Level__c</fullName>
        <label>Expected LoA Level</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <label>Lead BG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_BU__c</fullName>
        <label>Lead BU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organisation_Level_5__c</fullName>
        <label>Organisation Level 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Developer_Name__c</fullName>
        <label>Queue Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Request__c</fullName>
        <label>Type of Request</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Facilitator Custom Queue</label>
    <pluralLabel>Facilitator Custom Queues</pluralLabel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_LoA_Approval_Level__c</fullName>
        <description>Expected LoA Approval Level for Offer</description>
        <inlineHelpText>Expected LoA Approval Level for Offer. Currently inactive</inlineHelpText>
        <label>Old Expected LoA Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LoA_G4_Approval_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BG__c</fullName>
        <description>Req 569: User will select Lead BG manually</description>
        <label>Lead BG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_BU__c</fullName>
        <description>Selection of group within MN to lead on approvals. Mandatory selection from drop-down list if MN or ION are chosen as the Lead BG</description>
        <label>Lead BU</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_BG__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Business_Units</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Org_L4__c</fullName>
        <formula>Account.L4Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_4</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L5__c</fullName>
        <formula>Account.L5Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_5</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Request__c</fullName>
        <description>319: Standard Feild for Opportunity to know thw type of the request.</description>
        <label>Type of Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>RFP/RFI</fullName>
                </value>
                <value>
                    <fullName>Simple Offers</fullName>
                </value>
                <value>
                    <fullName>Proactive Bid</fullName>
                </value>
                <value>
                    <fullName>Budgetary Quote</fullName>
                    <isActive>false</isActive>
                    <label>Budgetary Quote</label>
                </value>
                <value>
                    <fullName>Proactive</fullName>
                    <isActive>false</isActive>
                    <label>Proactive</label>
                </value>
                <value>
                    <fullName>RFI</fullName>
                    <isActive>false</isActive>
                    <label>RFI</label>
                </value>
                <value>
                    <fullName>RFQ</fullName>
                    <isActive>false</isActive>
                    <label>RFQ</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/globalValueSets/LoA_G4_Approval_Levels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A+</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>LoA Bypass</fullName>
        <label>G4/G5 Bypass</label>
    </customValue>
    <customValue>
        <fullName>A light</fullName>
        <isActive>false</isActive>
        <label>A light</label>
    </customValue>
    <description>Global picklist for LoA G4 Approval Levels</description>
    <masterLabel>LoA G4 Approval Levels</masterLabel>
</GlobalValueSet>

src/classes/NF_QueueHandler.cls
public abstract  class NF_QueueHandler {
	private static final String QUEUE = 'Queue';
	public String queueException = '';

	public void notifyQueueMembers(String queueId, Id oppId){
		set<Id> queueMembers = getQueueMembers(new set<String>{queueId});
		if(!queueMembers.isEmpty()){
			sendEmail(queueMembers, oppId); 
		}
	}

	private NF_FacilitatorCustomQueue__mdt getFacilitatorSetting(sObject sobjectRec){
		Opportunity myOpp = (Opportunity)sobjectRec;
		List<NF_FacilitatorCustomQueue__mdt> facilitatorSettings = new List<NF_FacilitatorCustomQueue__mdt>();
		
		if(myOpp.Org_L4__c == GlobalConstants.MARKET_LATIN_AMERICA) {
			facilitatorSettings = [SELECT DeveloperName,Queue_Developer_Name__c,Lead_BG__c,Lead_BU__c, Market__c FROM NF_FacilitatorCustomQueue__mdt WHERE Lead_BG__c = :myOpp.Lead_BG__c AND Lead_BU__c = :myOpp.Lead_BU__c AND Market__c = :myOpp.Org_L4__c ];
		} else {
	 facilitatorSettings =[SELECT DeveloperName,Queue_Developer_Name__c,Lead_BG__c,Lead_BU__c, Market__c FROM NF_FacilitatorCustomQueue__mdt WHERE Lead_BG__c = :myOpp.Lead_BG__c AND Lead_BU__c = :myOpp.Lead_BU__c AND Organisation_Level_5__c = :myOpp.Org_L5__c ];
		}
		if(!facilitatorSettings.isEmpty()){
			return facilitatorSettings[0];
		}
		return null;
	}

	public Group getQueue(sObject sobjectRec){
		NF_FacilitatorCustomQueue__mdt facilitatorSetting = getFacilitatorSetting(sobjectRec);
		Group queueLoc = null;
		try{
			if(facilitatorSetting != null){
	queueLoc = [Select Id, Name from Group where type= :QUEUE and Name= :facilitatorSetting.Queue_Developer_Name__c];
			}
		}catch(QueryException e){
			queueLoc = null;
			system.debug('##Query Exception : '+e.getMessage());
		}
		return queueLoc;
	}
	public set<Id> getQueueMembers(set<String> queueIds){
		set<Id> memebersIds = new set<Id>();
		for(GroupMember members : [Select UserOrGroupId From GroupMember where GroupId in :queueIds]){
			memebersIds.add(members.UserOrGroupId);
		}
		return memebersIds;
	}
   
 	 @TestVisible private void sendEmail(set<Id> recipients, ID recordId) {
		//New instance of a single email message
		try{
			EmailTemplate template = [Select Id from EmailTemplate where developername = :GlobalConstants.FACILITATOR_EMAIL_TEMPLATE];
			// Who you are sending the email to
			List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
			for(Id recipient : recipients){
	Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	mail.setTargetObjectId(recipient);
	mail.setWhatId(recordId);
	mail.setTemplateId(template.Id);
	mail.setSaveAsActivity(false);
	mails.add(mail);
			}
			Messaging.sendEmail(mails); 
			
		}catch(QueryException e){
			system.debug('###Exception Email Template Not Found : '+e.getMessage());
			queueException += 'Email not delivered correctly.';
		}

	}
	
	public Group searchForQueue (Opportunity opp){
		
		list<NF_FacilitatorCustomQueue__mdt> facilitatorSetting = new list<NF_FacilitatorCustomQueue__mdt>(); 
		String leadBG = '\'' + opp.Lead_BG__c + '\'';
		String leadBU = opp.Lead_BU__c == null ? 'NULL' : '\'' + opp.Lead_BU__c + + '\'';
		String orgL4 = '\'' + opp.Org_L4__c + '\'';
		String orgL5 = '\'' + opp.Org_L5__c + '\'';
		String expectedLoALevel = '\'' + opp.Expected_LoA_Approval_Level__c + '\'';
		String typeRequest = 'NULL';
		
		string query = 'SELECT Id , DeveloperName,Queue_Developer_Name__c FROM NF_FacilitatorCustomQueue__mdt WHERE '+
			'Lead_BG__c ='+ leadBG + ' AND Lead_BU__c =' + leadBU +' AND Market__c = ' + orgL4 + ' AND Expected_LoA_Level__c = ' + expectedLoALevel;

		if(  opp.Org_L4__c != GlobalConstants.MARKET_NORTH_AMERICA || 
		   ( (GlobalConstants.Lead_BG_NSW == opp.Lead_BG__c || GlobalConstants.LEAD_BG_MN == opp.Lead_BG__c || GlobalConstants.LEAD_BG_GS == opp.Lead_BG__c ) && opp.Type_of_Request__c != GlobalConstants.TYPE_REQUEST_RFP_RFI && (GlobalConstants.LOA_LEVEL_E.equalsIgnoreCase(opp.Expected_LoA_Approval_Level__c) || GlobalConstants.LOA_BYPASS_LEVEL.equalsIgnoreCase(opp.Expected_LoA_Approval_Level__c))) ){
				query += ' AND Organisation_Level_5__c = ' + orgL5 ;
		}
		if( (GlobalConstants.LOA_LEVEL_E.equalsIgnoreCase(opp.Expected_LoA_Approval_Level__c) || GlobalConstants.LOA_BYPASS_LEVEL.equalsIgnoreCase(opp.Expected_LoA_Approval_Level__c)) && opp.Type_of_Request__c == GlobalConstants.TYPE_REQUEST_RFP_RFI){
			typeRequest = '\'' + GlobalConstants.TYPE_REQUEST_RFP_RFI + '\'' ;
		} 
		query += ' AND Type_of_Request__c = ' + typeRequest ;
		
		System.debug(query);	
		facilitatorSetting = database.query(query);
		Group queueLoc = null;
		try{
			if(facilitatorSetting.IsEmpty() == false){
	queueLoc = [Select Id, Name from Group where type= :QUEUE and Name = :facilitatorSetting[0].Queue_Developer_Name__c limit 1];
			}else{
	queueLoc = [Select Id, Name from Group where type= :QUEUE and Name = :Label.NF_Default_Queue limit 1];
			}
		}catch(exception e){
			system.debug('###Exception Email Template Not Found : '+e.getMessage());
		}
		return queueLoc;
	}
}