src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>ActiveOffer__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active Offer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <description>This field will be appended at the end of Offer Number (01, 02)</description>
        <formula>if(
	Opportunity__r.count_offer__c &lt; 9, &apos;0&apos; &amp; TEXT(Opportunity__r.count_offer__c +1 ), TEXT(Opportunity__r.count_offer__c+ 1)
)</formula>
        <label>#Offer</label>
        <type>Text</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Phase_Status__c</fullName>
        <description>305:Set up the following phases for the sales process for standard opportunities: 
- for the single phases refer to the attached file &quot;Sales Process_&lt;latest file version&gt;&quot; / column &quot;Sales Phase&quot;</description>
        <label>Phase Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Submitted for G2 Approval</fullName>
                </value>
                <value>
                    <fullName>Opportunity in Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted for G3 Approval</fullName>
                </value>
                <value>
                    <fullName>Offer in Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted for G4 Approval</fullName>
                </value>
                <value>
                    <fullName>Offer Submitted to Customer (Manual)</fullName>
                </value>
                <value>
                    <fullName>Submitted for G5 Approval</fullName>
                    <label>Submitted for Gate 5 Contract Approval</label>
                </value>
                <value>
                    <fullName>PTA (PROJECT TARGET AGREEMENT) HANDOVER TO DELIVERY/OPERATIONS</fullName>
                </value>
                <value>
                    <fullName>Submitted for G6 Approval</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed(not won)</fullName>
                    <label>Closed (not won)</label>
                </value>
                <value>
                    <fullName>Won (Requested)</fullName>
                </value>
                <value>
                    <fullName>Pending Win/Loss Declaration</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                    <isActive>false</isActive>
                    <label>Closed Lost</label>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                    <isActive>false</isActive>
                    <label>Closed Won</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Outcome_Reason__c</fullName>
        <description>4/25 VL: Adapted to Req 4273
305:Set up the following phases for the sales process for standard opportunities: 
- for the single phases refer to the attached file &quot;Sales Process_&lt;latest file version&gt;&quot; / column &quot;Sales Phase&quot;
567: Renaming the field</description>
        <label>Main Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Delivery &amp; Operations</fullName>
                </value>
                <value>
                    <fullName>Mistake/Redundant/Merged</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Sales and Customer Engagement</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>3rd party suppliers</fullName>
                    <isActive>false</isActive>
                    <label>3rd party suppliers</label>
                </value>
                <value>
                    <fullName>ALu Nokia Integration</fullName>
                    <isActive>false</isActive>
                    <label>ALu Nokia Integration</label>
                </value>
                <value>
                    <fullName>Brand value</fullName>
                    <isActive>false</isActive>
                    <label>Brand value</label>
                </value>
                <value>
                    <fullName>Budget restriction / project suspension</fullName>
                    <isActive>false</isActive>
                    <label>Budget restriction / project suspension</label>
                </value>
                <value>
                    <fullName>Commercial terms not accepted</fullName>
                    <isActive>false</isActive>
                    <label>Commercial terms not accepted</label>
                </value>
                <value>
                    <fullName>Customer Budget too low</fullName>
                    <isActive>false</isActive>
                    <label>Customer Budget too low</label>
                </value>
                <value>
                    <fullName>Customer Relationship / trust</fullName>
                    <isActive>false</isActive>
                    <label>Customer Relationship / trust</label>
                </value>
                <value>
                    <fullName>Customer Relationship/trust</fullName>
                    <isActive>false</isActive>
                    <label>Customer Relationship/trust</label>
                </value>
                <value>
                    <fullName>Customer changed project scope</fullName>
                    <isActive>false</isActive>
                    <label>Customer changed project scope</label>
                </value>
                <value>
                    <fullName>Customer changed technology</fullName>
                    <isActive>false</isActive>
                    <label>Customer changed technology</label>
                </value>
                <value>
                    <fullName>Customer not interested</fullName>
                    <isActive>false</isActive>
                    <label>Customer not interested</label>
                </value>
                <value>
                    <fullName>Customer preferred vendor</fullName>
                    <isActive>false</isActive>
                    <label>Customer preferred vendor</label>
                </value>
                <value>
                    <fullName>Customer relationship</fullName>
                    <isActive>false</isActive>
                    <label>Customer relationship</label>
                </value>
                <value>
                    <fullName>Customer vendor strategy</fullName>
                    <isActive>false</isActive>
                    <label>Customer vendor strategy</label>
                </value>
                <value>
                    <fullName>Delivery Capability / Schedule</fullName>
                    <isActive>false</isActive>
                    <label>Delivery Capability / Schedule</label>
                </value>
                <value>
                    <fullName>Delivery Capability /Schedule</fullName>
                    <isActive>false</isActive>
                    <label>Delivery Capability /Schedule</label>
                </value>
                <value>
                    <fullName>Delivery capability</fullName>
                    <isActive>false</isActive>
                    <label>Delivery capability</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <isActive>false</isActive>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>Embargo</fullName>
                    <isActive>false</isActive>
                    <label>Embargo</label>
                </value>
                <value>
                    <fullName>Financing &amp; payment terms</fullName>
                    <isActive>false</isActive>
                    <label>Financing &amp; payment terms</label>
                </value>
                <value>
                    <fullName>Inadequate resources</fullName>
                    <isActive>false</isActive>
                    <label>Inadequate resources</label>
                </value>
                <value>
                    <fullName>Included / Merged with another case</fullName>
                    <isActive>false</isActive>
                    <label>Included / Merged with another case</label>
                </value>
                <value>
                    <fullName>Included/merged with another case</fullName>
                    <isActive>false</isActive>
                    <label>Included/merged with another case</label>
                </value>
                <value>
                    <fullName>Incumbent position leverage</fullName>
                    <isActive>false</isActive>
                    <label>Incumbent position leverage</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Outcome__c</fullName>
        <description>305:Set up the following phases for the sales process for standard opportunities: 
- for the single phases refer to the attached file &quot;Sales Process_&lt;latest file version&gt;&quot; / column &quot;Sales Phase&quot;</description>
        <label>Sales Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled by Customer</fullName>
                </value>
                <value>
                    <fullName>Lost to Competitor</fullName>
                </value>
                <value>
                    <fullName>Withdrawn by Nokia</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Won (Requested)</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <isActive>false</isActive>
                    <label>N/A</label>
                </value>
                <value>
                    <fullName>ONGOING</fullName>
                    <isActive>false</isActive>
                    <label>ONGOING</label>
                </value>
                <value>
                    <fullName>WITHDRAWN BY NSN</fullName>
                    <isActive>false</isActive>
                    <label>WITHDRAWN BY NSN</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OfferActivationHandlerTest.cls
/****************************************
* Class Name : OfferActivationHandlerTest 
* Created Date: 21st October 2016
* Created By : Accenture
* Last Modified by: Accenture
* Last Modified Date: 28 Nov 2016
* Description : This is the test class to cover OfferActivationHandler
*****************************************/ 
@isTest(seealldata = false)
private class OfferActivationHandlerTest{
	/****************************************
* Method Name: validateOfferActivation
* Description : Test method to cover OfferActivationHandler
*****************************************/	
	static testMethod void validateOfferActivation(){
		user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		System.RunAs(userCreation){
			List<File_Sharing_Custom_Setting__c> fileSharingCustomSettingList = new List<File_Sharing_Custom_Setting__c>();
			fileSharingCustomSettingList = TestDataFactory.create_File_Sharing_Custom_Setting();
			database.insert(fileSharingCustomSettingList);
			List<Account> accList = TestDataFactory.createAccount(2);
			accList[1].Name = 'Test Acc';
			database.insert(accList);
			Test.startTest();
			List<Opportunity> oppList = TestDataFactory.OpportunityCreation(2,accList[0]);
			database.insert(oppList);
			oppList[0].StageName = 'Win the Case (Negotiate)';
			oppList[0].Phase_Status__c = 'Offer Submitted to Customer (Manual)';
			oppList[0].Probability = 10;
			oppList[1].StageName = 'Win the Case (Negotiate)';
			oppList[1].Phase_Status__c = 'Offer Submitted to Customer (Manual)';
			oppList[1].Probability = 10;
			//database.update(oppList);
			Test.stopTest();
			/*Offer__c offerCreation = TestDataFactory.OfferCreation(1,oppList[0])[0];
offerCreation.ActiveOffer__c = true;
offerCreation.Expected_LoA_G4_Approval_Level__c = 'A';
insert offerCreation;*/
			List<Offer__c> offerList = TestDataFactory.OfferCreation(3,oppList[0]);
			offerList[0].Activeoffer__c = true;
			offerList[1].Activeoffer__c = false;
			offerList[2].Activeoffer__c = false;
			offerList[0].Expected_LoA_G4_Approval_Level__c = 'A';
			offerList[1].Expected_LoA_G4_Approval_Level__c = 'A';
			offerList[2].Expected_LoA_G4_Approval_Level__c = 'A';
			database.insert(offerList);  
			offerList[2].Activeoffer__c = true;			
			database.update(offerList);  
			//Exception
			OfferActivationHelper.onBeforeInsert(NULL);
			OfferActivationHelper.validate(NULL,NULL);
			
		}
	}
	
	/******************************
*Method Name: cloneTeamTest
*Description: Test Method to cover CloneOfferTeam class
********************************/
	static testMethod void cloneTeamTest(){
		List<File_Sharing_Custom_Setting__c> fileSharingCustomSettingList = new List<File_Sharing_Custom_Setting__c>();
		user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		user userCreationRead = TestDataFactory.userCreation(1,'System Administrator')[0];
		database.insert(userCreation);
		system.runAs(userCreation){
			
			//fileSharingCustomSettingList = TestDataFactory.create_File_Sharing_Custom_Setting();
			//database.insert(fileSharingCustomSettingList);
			Account accountCreation = TestDataFactory.createAccount(1)[0];
			database.insert(accountCreation);
			Opportunity optyCreation = TestDataFactory.OpportunityCreation(1,accountCreation)[0];
			database.insert(optyCreation);
			optyCreation.StageName = 'Win the Case (Negotiate)';
			optyCreation.Phase_Status__c = 'Offer Submitted to Customer (Manual)';
			optyCreation.Probability = 10;		   
			OpportunityTeamMember optyTeamCreation = TestDataFactory.optyTeamMemberCreation(1,userCreation,optyCreation)[0];
			database.insert(optyTeamCreation);
			test.startTest();
			Offer__c offerCreation = TestDataFactory.OfferCreation(1,optyCreation)[0];
			offerCreation.ActiveOffer__c  = true;
			offerCreation.Expected_LoA_G4_Approval_Level__c = 'A';
			database.insert(offerCreation);
			List<Offer__c> offerList = new List<Offer__c>();
			offerList.add(offerCreation);

			test.stoptest();
		}
	}
	
	/****************************************
* Method Name: insertOffer
* Description : Test method to cover OfferActivationHandler
****************************************   
	static testMethod void insertOffer(){
		user userCreation = TestDataFactory.userCreation(1,'Global Process Admin Profile')[0];
		insert userCreation;
		System.RunAs(userCreation){
			List<File_Sharing_Custom_Setting__c> fileSharingCustomSettingList = new List<File_Sharing_Custom_Setting__c>();
			fileSharingCustomSettingList = TestDataFactory.create_File_Sharing_Custom_Setting();
			database.insert(fileSharingCustomSettingList);
			Account acc = TestDataFactory.createAccount(1)[0];
			database.insert(acc);
			
			Test.startTest();
			List<Opportunity> opptyList = new List<Opportunity>();
			opptyList = TestDataFactory.OpportunityCreation(1,acc);
			opptyList[0].StageName = GlobalConstants.IDENTIFY_OPPORTUNITY;
			opptyList[0].Phase_Status__c = 'Planned';
			opptyList[0].Sales_Outcome__c = 'Obsolete';
			opptyList[0].Sales_Outcome_Reason__c = 'Commercial';
		   // opptyList.add(opp);
			/* opp.Second_Reason__c = '';
opp.Third_Reason__c = '';
			database.insert(opptyList);
			try{				
				Offer__c offerCreation = TestDataFactory.OfferCreation(1,opptyList[0])[0];
				offerCreation.ActiveOffer__c = true;
				offerCreation.Expected_LoA_G4_Approval_Level__c = 'A';
				insert offerCreation;
			}catch(Exception e){
				Boolean expectedExceptionThrown = e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ? true : false; 
				System.assertEquals(expectedExceptionThrown, true);
			}
		}
	}
	*/ 
	/****************************************
* Method Name: deleteOffer
* Description : Test method to cover OfferActivationHandler
*****************************************/	
	static testMethod void deleteOffer(){
		Offer__c offerCreation = new Offer__c();
		user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		database.insert(userCreation);
		user userCreationOtherProfile = TestDataFactory.userCreation(1,'Global Process Admin Profile')[0];
		database.insert(userCreationOtherProfile );
		
		System.runAs(userCreation){			
			Account acc = TestDataFactory.createAccount(1)[0];
			database.insert(acc);
			List<File_Sharing_Custom_Setting__c> fileSharingCustomSettingList = new List<File_Sharing_Custom_Setting__c>();
			fileSharingCustomSettingList = TestDataFactory.create_File_Sharing_Custom_Setting();
			database.insert(fileSharingCustomSettingList);
			
			Opportunity opp = TestDataFactory.OpportunityCreation(1,acc)[0];
			opp.StageName = GlobalConstants.IDENTIFY_OPPORTUNITY;
			opp.Phase_Status__c = 'Planned';
			opp.Sales_Outcome__c = 'Obsolete';
			opp.Sales_Outcome_Reason__c = 'Commercial';
			database.insert(opp);
			
			offerCreation = TestDataFactory.OfferCreation(1,opp)[0];
			offerCreation.ActiveOffer__c = true;
			offerCreation.Expected_LoA_G4_Approval_Level__c = 'A';
			insert offerCreation;										  
		}
		
		Test.startTest();
		System.runAs(userCreationOtherProfile ){
			try{  
				List<Offer__c> offerListDelete = new List<Offer__c>();
				offerListDelete=[Select id from Offer__c where id =: offerCreation.Id ];
				system.debug('offerCreation>>>>'+offerCreation);			  
				delete offerListDelete;
			}catch(Exception e){
				Boolean expectedExceptionThrown = e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ? true : false; 
				System.assertEquals(expectedExceptionThrown, true);
			}
		}
		Test.stopTest();		
	}
		/****************************************
* Method Name: defaultValueForSSOSATOnUpdateToC_Test
* Description : Test method to cover OfferActivationHandler
*****************************************/	
	static testMethod void defaultValueForSSOSATOnUpdateToC_Test(){
		user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		System.RunAs(userCreation){
			Account acc = TestDataFactory.createAccount(1)[0];
			database.insert(acc);  
			
			Opportunity opp = TestDataFactory.OpportunityCreation(1,acc)[0];
			database.insert(opp); 
			
			Offer__c offerCreation = TestDataFactory.OfferCreation(1,opp)[0];
			offerCreation.ActiveOffer__c = true;
			offerCreation.Expected_LoA_G4_Approval_Level__c = 'A';
			insert offerCreation;
			
			Test.startTest();
			offerCreation.Expected_LoA_G4_Approval_Level__c = 'C';
			update offerCreation;
			OfferActivationHelper.defaultValueForSSOOnInsert(null);
			Test.stopTest();
		}
	}
	
	/****************************************
* Method Name: defaultValueForSSOSATOnUpdateToA_Test
* Description : Test method to cover OfferActivationHandler
*****************************************/	
	static testMethod void defaultValueForSSOSATOnUpdateToA_Test(){
		user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		System.RunAs(userCreation){
			Account acc = TestDataFactory.createAccount(1)[0];
			database.insert(acc);  
			
			Opportunity opp = TestDataFactory.OpportunityCreation(1,acc)[0];
			database.insert(opp); 
			
			Offer__c offerCreation = TestDataFactory.OfferCreation(1,opp)[0];
			offerCreation.ActiveOffer__c = true;
			offerCreation.Expected_LoA_G4_Approval_Level__c = 'C';
			insert offerCreation;
			
			Test.startTest();
			offerCreation.Expected_LoA_G4_Approval_Level__c = 'A';
			update offerCreation;
			OfferActivationHelper.defaultValueForSSOOnUpdate(null,null);
			Test.stopTest();
		}
	}
	
		/****************************************
* Method Name: restrictManualChangingSSOTOAttachedTest
* Description : Test method to cover OfferActivationHandler
*****************************************/	
	static testMethod void restrictManualChangingSSOTOAttachedTest(){
		user userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		System.RunAs(userCreation){
			Account acc = TestDataFactory.createAccount(1)[0];
			database.insert(acc);  
			
			Opportunity opp = TestDataFactory.OpportunityCreation(1,acc)[0];
			database.insert(opp); 
			
			Offer__c offerCreation = TestDataFactory.OfferCreation(1,opp)[0];
			offerCreation.ActiveOffer__c = true;
			offerCreation.Expected_LoA_G4_Approval_Level__c = 'C';
			insert offerCreation;
			
			Test.startTest();
			try{
			offerCreation.Solution_Sign_Off_New__c = GlobalConstants.Required_Attached;
			update offerCreation;
			}catch(Exception ex){
			   String message = ex.getMessage();
				system.assert(message.contains('Please attach a Solution Sign-Off document'), 'message=' + message);  
			}
			OfferActivationHelper.restrictManualChangingSSOTOAttached(null,null);
			Test.stopTest();
		}
	}
}