src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Offer__c</fullName>
        <description>This field will be appended at the end of Offer Number (01, 02)</description>
        <formula>if(
	Opportunity__r.count_offer__c &lt; 9, &apos;0&apos; &amp; TEXT(Opportunity__r.count_offer__c +1 ), TEXT(Opportunity__r.count_offer__c+ 1)
)</formula>
        <label>#Offer</label>
        <type>Text</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>G2_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G2 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G3_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G3 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G4_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <label>G4 Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>G5_Planned_Date__c</fullName>
        <description>319:The following fields should be available for standard opportunities</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Expected date for contract signing or other legally binding document (e.g. first PO)</inlineHelpText>
        <label>Win Declaration Planned Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityTeamMember.object
<CustomObject>
    <fields>
        <fullName>Additional_Team_Role__c</fullName>
        <description>Req 665: This will help to add user with different role</description>
        <label>Additional Team Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Account Manager (TRICORN Sales Case Owner (SCO))</fullName>
                </value>
                <value>
                    <fullName>BG Business Controller RBC</fullName>
                </value>
                <value>
                    <fullName>BG Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>BG Sales &amp; Business Development</fullName>
                </value>
                <value>
                    <fullName>Bid Manager</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                    <isActive>false</isActive>
                    <label>Business Development</label>
                </value>
                <value>
                    <fullName>Commercial Contract Manager (L&amp;C)</fullName>
                </value>
                <value>
                    <fullName>Commercial Contract Manager and Legal</fullName>
                    <isActive>false</isActive>
                    <label>Commercial Contract Manager and Legal</label>
                </value>
                <value>
                    <fullName>Commercial Deal Manager Commercial War Room</fullName>
                    <isActive>false</isActive>
                    <label>Commercial Deal Manager Commercial War Room</label>
                </value>
                <value>
                    <fullName>CT Head</fullName>
                </value>
                <value>
                    <fullName>Customer CTO</fullName>
                </value>
                <value>
                    <fullName>Customer Quality Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Supply Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Team Controller</fullName>
                    <isActive>false</isActive>
                    <label>Customer Team Controller</label>
                </value>
                <value>
                    <fullName>E2E Solution Manager</fullName>
                    <isActive>false</isActive>
                    <label>E2E Solution Manager</label>
                </value>
                <value>
                    <fullName>G3 Facilitator</fullName>
                </value>
                <value>
                    <fullName>G4 G5 Facilitator</fullName>
                    <isActive>false</isActive>
                    <label>G4 G5 Facilitator</label>
                </value>
                <value>
                    <fullName>Global Sales Support MU Lead</fullName>
                </value>
                <value>
                    <fullName>Head of Sales</fullName>
                    <isActive>false</isActive>
                    <label>Head of Sales</label>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Offer Controller</fullName>
                </value>
                <value>
                    <fullName>One Customer Delivery Manager</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Partner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager</fullName>
                </value>
                <value>
                    <fullName>Pricing Manager (Lead)</fullName>
                </value>
                <value>
                    <fullName>Project Contract Manager</fullName>
                </value>
                <value>
                    <fullName>Project Execution Owner</fullName>
                    <isActive>false</isActive>
                    <label>Project Execution Owner</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/CreateOfferApexCtlrTest.cls
@isTest
public without sharing class CreateOfferApexCtlrTest {
	
	static testmethod void getOpptyTest()
	{
		User userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		system.runas(userCreation){
			Account accountCreation = TestDataFactory.createAccount(1)[0];
			insert accountCreation;
			Opportunity optyCreation = TestDataFactory.OpportunityCreation(1,accountCreation)[0];
			insert optyCreation;
			Opportunity oppty = CreateOfferApexCtlr.getOppty(optyCreation.Id);
			Opportunity oppty1 = CreateOfferApexCtlr.getOppty(Null);
			List<OpportunityTeamMember> opptyTeamMemberList = TestDataFactory.optyTeamMemberCreation(2,userCreation,optyCreation);
			opptyTeamMemberList[0].OpportunityAccessLevel = GlobalConstants.READ;
			database.insert(opptyTeamMemberList);
			Test.startTest();
			List<OfferTeamWrapper> wrapperList1 = CreateOfferApexCtlr.getOpptyTeam(optyCreation.Id);
			
			opptyTeamMemberList[0].TeamMemberRole = GlobalConstants.PRICING_MANAGER_OFFER_TEAM_ROLE;
			opptyTeamMemberList[1].TeamMemberRole = GlobalConstants.PRICING_MANAGER_OFFER_TEAM_ROLE;
			opptyTeamMemberList[1].Additional_Team_Role__c = GlobalConstants.BID_MANAGER_OFFER_TEAM_ROLE;
			List<OfferTeamWrapper> wrapperList2 = CreateOfferApexCtlr.getOpptyTeam(optyCreation.Id);
			
			Offer__c offerCreation = TestDataFactory.OfferCreation(1,optyCreation)[0];
			String offerId = CreateOfferApexCtlr.saveOffer(offerCreation);
			String offerId1 = CreateOfferApexCtlr.saveOffer(Null);
			Test.stopTest();
		}
	}
	
	static testmethod void saveOpptyTest()
	{
		User userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		system.runas(userCreation){
			Test.startTest();
			Account accountCreation = TestDataFactory.createAccount(1)[0];
			insert accountCreation;
			Opportunity optyCreation = TestDataFactory.OpportunityCreation(1,accountCreation)[0];
			optyCreation.G2_Planned_Date__c = system.today();
			optyCreation.G3_Planned_Date__c = system.today()+1;
			optyCreation.G4_Planned_Date__c = system.today()+2;
			optyCreation.G5_Planned_Date__c = system.today()+3;
			insert optyCreation;
			Test.stopTest();
			optyCreation.G4_Planned_Date__c = system.today()+3;
			String returnMessage = CreateOfferApexCtlr.saveOppty(optyCreation );
			try{
	String returnMessage1 = CreateOfferApexCtlr.saveOppty(null);
				optyCreation.G4_Planned_Date__c = system.today();
	String returnMessage2 = CreateOfferApexCtlr.saveOppty(optyCreation);
			}catch(Exception ex){
	String message = ex.getMessage();
	system.assert(message.contains('The Gate Planned Date entered is either blank, in the past, precedes the date entered for the previous gate or exceeds the date entered for the following gate.'), 'message=' + message);
			}
		}
	}
	
	static testmethod void getUserTest()
	{
		User userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		system.runas(userCreation){
			User usr = CreateOfferApexCtlr.getUser(userCreation.Id);
			List<User> usrList = CreateOfferApexCtlr.getAllUserList(userCreation.Name);
			Test.startTest();
			User usr1 = CreateOfferApexCtlr.getUser(Null);
			List<User> usrList1 = CreateOfferApexCtlr.getAllUserList(Null);
			Test.stopTest();
		}
	}
	
	static testmethod void saveOfferandOfferTeamTest()
	{
		User userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		system.runAs(userCreation){
			Account accountCreation = TestDataFactory.createAccount(1)[0];
			insert accountCreation;
			Opportunity optyCreation = TestDataFactory.OpportunityCreation(1,accountCreation)[0];
			insert optyCreation;
			Opportunity oppty = CreateOfferApexCtlr.getOppty(optyCreation.Id);
			Opportunity oppty1 = CreateOfferApexCtlr.getOppty(Null);
			Offer__c offerCreation = TestDataFactory.OfferCreation(1,optyCreation)[0];
			Test.startTest();
			String offerId = CreateOfferApexCtlr.saveOffer(offerCreation);
			OfferTeamWrapper wrapper= new OfferTeamWrapper();
			wrapper.userId = userCreation.Id;
			wrapper.offerAccess = 'Read/Write';
			wrapper.teamRole = 'Account Manager';
			wrapper.additionalTeamRole = 'Bid Manager';
			wrapper.userName = 'Piyush';
			List<OfferTeamWrapper> wrapperList = new List<OfferTeamWrapper>();
			wrapperList.add(wrapper);
			String wrpLst = JSON.serialize(wrapperList);
			CreateOfferApexCtlr.getAllLeadBGOfOfferTeam();
			CreateOfferApexCtlr.saveOfferTeam(wrpLst,offerId);
			List<OfferTeamWrapper> wrap = CreateOfferApexCtlr.offerTeamPrMValidation(wrpLst,optyCreation.Id);
			Test.stopTest();
		}
	}
	
	static testmethod void coverAllPicklistValuesTest()
	{
		User userCreation = TestDataFactory.userCreation(1,'System Administrator')[0];
		insert userCreation;
		system.runas(userCreation){
			Test.startTest();
			map<String, String> loALevelMap = CreateOfferApexCtlr.getAllExpectedLoALevel();
			map<String, String> teamMemberMap = CreateOfferApexCtlr.getAllTeamMemberRole();
			map<String, String> addTeamMemberMap = CreateOfferApexCtlr.getAllAdditionalTeamMemberRole();
			map<String, String> accessLevelMap = CreateOfferApexCtlr.getAllAccessLevel();
			map<String, String> teamRoleMap = CreateOfferApexCtlr.getAllTeamMemberRoleMap();
			List<OfferTeamWrapper> wrapperList1 = CreateOfferApexCtlr.getOpptyTeam(null);
			Test.StopTest();
		}
	}
}