src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Org_L3__c</fullName>
        <formula>Account.L3Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_3</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L4__c</fullName>
        <formula>Account.L4Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_4</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_L5__c</fullName>
        <formula>Account.L5Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation_Level_5</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_BG_NEN__c</fullName>
        <description>Presales Req#5539 Jan Release - no longer used after March 2021 due to AP2021</description>
        <formula>PSR_Cost_BU_NE_IoT__c + PSR_Cost_BU_NE_DAaaS__c + PSR_Cost_BU_NE_EOP__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG NEN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_AA__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG NSW</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_FN__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG FN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_GS__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG GS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_ION__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <formula>PSR_Cost_BU_ION_IPR_DNI__c +PSR_Cost_BU_ION_IPR_MPC__c + PSR_Cost_BU_ION_IPR_Nuage__c + PSR_Cost_Business_Unit_ION_IPR__c + PSR_Cost_BU_ION_IPR_Services__c + PSR_Cost_Business_Unit_ION_Optics__c + PSR_Cost_BU_ION_Optics_Services__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG ION</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Cost_Business_Group_MN__c</fullName>
        <description>PreSales : Sprint 6: Req#2171
		PreSales, Sprint 10, Requirement: 3099 - no longer used after March 2021 due to AP2021</description>
        <inlineHelpText>Indicate cost of the PSRO. May need to contact Pricing Manager(s) for new products/customers. In case of challenge obtaining true cost, click “Automatically Calculate Estimated Cost” in the sales value section below</inlineHelpText>
        <label>OLD Cost BG MN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Date_PO_Expected__c</fullName>
        <description>PreSales : Sprint 6: Req#2171</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date PO Expected / Contract Signed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSR_Description_Justification__c</fullName>
        <description>PreSales Prototype</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Description/Justification</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PSR_GateClass__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PSR Gate Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSR_Is_BOM_BOQ_Document_Attached__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PReSales :Sprint 10: Req2766</description>
        <label>Is BOM/BOQ Document Attached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSR_Is_Cost_Approved_In_Related_LOA_Opty__c</fullName>
        <description>PreSales : Sprint 6: Req#2171</description>
        <inlineHelpText>Indicate if Cost of a Trial or an FoC is already approved in the G4/G5 Sales Opportunity. This information will assist in the approval process.</inlineHelpText>
        <label>Approved Cost in Sales Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Is_Cost_Reflected_In_Latest_Estimate__c</fullName>
        <description>PreSales : Sprint 6 : Req#2171</description>
        <inlineHelpText>Indicate if cost of the Pre-Sales Risk Opportunity is already in the LE (Latest Estimate) / Financial Forecast.</inlineHelpText>
        <label>Is Cost Reflected in Latest Estimate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Is_Rv_Reflected_In_Latest_Estimate__c</fullName>
        <description>PreSales : Sprint 6: Req#2171</description>
        <inlineHelpText>Risk Orders and Trials: Indicate if Revenue is included in the LE (Latest Estimate) / Financial Forecast</inlineHelpText>
        <label>Is Revenue Reflected in Latest Estimate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Lead_Business_Group__c</fullName>
        <description>no longer used after March 2021 due to AP2021</description>
        <encryptionScheme>None</encryptionScheme>
        <label>OLD Lead BG Pre-Sales</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSR_LoA_Level__c</fullName>
        <description>Sales Process &gt; Jan release 18 &gt; Req 5561</description>
        <label>Approval Level Pre-Sales</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Pre_Sales_Risk_Opportunity_Sub_Type__c</fullName>
        <description>PreSales : Sprint 6: Req#2171</description>
        <label>Pre-Sales Risk Opportunity Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PSR_Pre_Sales_Risk_Opportunity_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FoC</fullName>
                </value>
                <value>
                    <fullName>Risk Order Only</fullName>
                </value>
                <value>
                    <fullName>Risk Order With Risk Shipment</fullName>
                    <label>Risk Order with Risk Shipment</label>
                </value>
                <value>
                    <fullName>Commercial Trial</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Trial</fullName>
                </value>
                <value>
                    <fullName>CT Customer</fullName>
                </value>
                <value>
                    <fullName>Multiple Customers</fullName>
                </value>
                <value>
                    <fullName>Contractual Requirement</fullName>
                </value>
                <value>
                    <fullName>Good Will</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Pre_Sales_Risk_Opportunity_Type__c</fullName>
        <description>PreSales : Sprint 6: Req#2171</description>
        <label>Pre-Sales Risk Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk Order</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Free of Charge</fullName>
                    <label>Free of Charge (do not use)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Reference_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Sales Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Sales Risk Opportunities</relationshipLabel>
        <relationshipName>PreSalesOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_SW_R_D_Justification_Explanation__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Trials only: If Customer Specific R&amp;D SW is required, provide a detailed explanation (e.g., why is functionality not covered in general roadmap or S/W release). Finance will determine treatment of cost (R&amp;D OPEX or Cost of Sales).</inlineHelpText>
        <label>Customer Specific SW R&amp;D Explanation</label>
        <length>1000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PSR_Total_Cost_In_Euro__c</fullName>
        <description>Req : 2316 . Cost in Euros</description>
        <label>Total Cost In Euro</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PSR_Total_Cost_in_Local_Currency__c</fullName>
        <formula>PSR_Cost_BG_NI__c + PSR_Cost_BG_CNS__c + PSR_Cost_BG_MN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost in Local Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Total_Sales_Value_in_Local_Currency__c</fullName>
        <formula>PSR_Sales_Value_BG_NI__c + PSR_Sales_Value_BG_CNS__c + PSR_Sales_Value_BG_MN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Sales Value in Local Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSR_Trial_Agreement_Status__c</fullName>
        <description>PreSales : Sprint 7: Req#2365</description>
        <inlineHelpText>Trials only: Indicate current status of the Trial Agreement.</inlineHelpText>
        <label>Trial Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Trial_Duration__c</fullName>
        <label>Trial/Demo Duration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 month</fullName>
                </value>
                <value>
                    <fullName>2 months</fullName>
                </value>
                <value>
                    <fullName>3 months</fullName>
                </value>
                <value>
                    <fullName>4 months</fullName>
                </value>
                <value>
                    <fullName>5 months</fullName>
                </value>
                <value>
                    <fullName>6 months</fullName>
                </value>
                <value>
                    <fullName>7 months</fullName>
                </value>
                <value>
                    <fullName>8 months</fullName>
                </value>
                <value>
                    <fullName>9 months</fullName>
                </value>
                <value>
                    <fullName>10 months</fullName>
                </value>
                <value>
                    <fullName>11 months</fullName>
                </value>
                <value>
                    <fullName>12 months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Trial_Start_Date__c</fullName>
        <description>Pre-Sales Req : 2344</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Trial/Demo Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NF_PRE_ErrorNotificationCtrl.cls
/**
*   Class used to check the 14 conditions on Pre Sales Opportunity
*/
public with sharing class NF_PRE_ErrorNotificationCtrl{
	Public static integer limitRows=Limits.getLimitQueryRows()- Limits.getQueryRows();
	public Opportunity currentOpp {get;set;}
	public boolean isQueueAssigned {get;set;}
	public Boolean isAlreadyNotified {get;set;}
	public Boolean hasPermissionToredirect {get;set;}
	public Boolean hasNoSubmitForApproval {get;set;}
	public String currentOppId {get;set;}
	public boolean SalesRole {get;set;}
 
	private static String redirectionChoice{get;set;}

	public enum ApprovalsRedirection { APPROVALCONTEXTSUBMIT, MYAPPROVALS , PREVIEWSUBMITAPPROVALS }

   
	 /* @desc	the method used to initiate the VF NF_FacilitatorNotification 
	 * @return   PageReference: 
	 */
	public PageReference init(){
		//Following line used to check wheter the call is from Preview My approvals or Submit&Preview Approvals or Submit from relatedList
		//Modifying exsisting logic as a part of LoA Req 2356 of Sprint 7.
		SalesRole = false;
		PageReference errorMessage; 
		 
		currentOppId = ApexPages.currentPage().getParameters().get('oppId');
				 system.debug('CurrentOppId:'+CurrentOppID);
	  currentOpp=[select id,name,
					PSR_LoA_Level__c,
					PSR_Description_Justification__c,
					PSR_Date_PO_Expected__c,
					PSR_Total_Cost_in_Local_Currency__c,
					PSR_Lead_Business_Group__c,
					org_l4__c, Org_L3__c,Org_L5__c,
					recordTypeId,PSR_GateClass__c,PSR_Reference_Opportunity__c,
					PSR_Total_Sales_Value_in_Local_Currency__c,
					PSR_Trial_Start_Date__c,
					CurrencyIsoCode,
					PSR_Cost_Business_Group_AA__c,
					PSR_Cost_Business_Group_FN__c,
					PSR_Cost_Business_Group_ION__c,
					PSR_Cost_Business_Group_MN__c,		 
					PSR_Cost_Business_Group_GS__c,
					PSR_Cost_BG_NEN__c,
					PSR_Trial_Duration__c,
					PSR_Total_Cost_In_Euro__c,
					PSR_SW_R_D_Justification_Explanation__c,
					PSR_Trial_Agreement_Status__c,
					PSR_Pre_Sales_Risk_Opportunity_Type__c,
					PSR_Is_Cost_Approved_In_Related_LOA_Opty__c, 
					PSR_Is_Cost_Reflected_In_Latest_Estimate__c,
					PSR_Is_Rv_Reflected_In_Latest_Estimate__c,
					PSR_Pre_Sales_Risk_Opportunity_Sub_Type__c,
					PSR_is_BOM_BOQ_document_attached__c 
				from Opportunity Where id=:currentOppId];
	   
		Return ErrorMessage(currentOpp);
	  
		}
		
		
		
		public PageReference ErrorMessage(Opportunity currentOpp ) {
		
		 String Errorinfo=Label.NF_PRE_Required_Filed_Mandatory;
		 Integer Messagecount=0;
			system.debug('CurrentOpp:'+currentOpp);
		 /*Checking Required fields Start*/
		  if(String.IsEmpty(currentOpp.PSR_Description_Justification__c)){
		  Messagecount=Messagecount+1;
		   Errorinfo=Errorinfo+'Description/Justification, ';
		   Errorinfo+=' \r\n';
		   }
		   
		  if(String.IsEmpty(currentOpp.PSR_Lead_Business_Group__c)){
		  Messagecount=Messagecount+1;
		   Errorinfo=Errorinfo+'Cost for any BG/BU, ';
		   Errorinfo+=' \r\n';
		   }
		   //Risk order
		   if(currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c<>NULL && currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c.equals('Risk Order')) {			  
		   if(currentOpp.PSR_Total_Sales_Value_in_Local_Currency__c<=0 ){			  
		   Messagecount=Messagecount+1;
		   //Errorinfo=Errorinfo+'Total Sales Value of Opportunity in local currency, ';
		   Errorinfo=Errorinfo+'Sales Value for any BG/BU, '; // PreSales > Sprint 10 > UAT > D-3952
		   Errorinfo+=' \r\n';
		   }
		   IF(currentOpp.PSR_Date_PO_Expected__c==NULL){
		   Errorinfo=Errorinfo+'Date PO Expected / Contract Signed, ' +'\r\n';
			Messagecount=Messagecount+1;
		   }
		   
		   }
		   
		   //Trial
		   if(currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c<>NULL && currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c.equals('Trial')) {			  
		   
		   if(currentOpp.PSR_Trial_Start_Date__c==NULL){
		  Messagecount=Messagecount+1;
		   Errorinfo=Errorinfo+'Trial/Demo Start Date, ';
		   Errorinfo+=' \r\n';
		   }
			if(currentOpp.PSR_Trial_Duration__c==NULL){
		  Messagecount=Messagecount+1;
		   Errorinfo=Errorinfo+'Trial/Demo Duration, ';
		   Errorinfo+=' \r\n';
		   }
		   IF(currentOpp.PSR_Date_PO_Expected__c==NULL){
		   Errorinfo=Errorinfo+'Date PO Expected / Contract Signed, ' +'\r\n';
			Messagecount=Messagecount+1;
		   }
		   if(String.IsEmpty(currentOpp.PSR_Trial_Agreement_Status__c)){
		  Messagecount=Messagecount+1;
		   Errorinfo=Errorinfo+'Trial Agreement Status, ';
		   Errorinfo+=' \r\n';
		   }
		   if(String.IsEmpty(currentOpp.PSR_Is_Cost_Approved_In_Related_LOA_Opty__c)){
		  Messagecount=Messagecount+1;
		   Errorinfo=Errorinfo+'Is Cost Approved in Related LOA Opportunity, ';
		   Errorinfo+=' \r\n';
		   }
		   }
		   
		   //Demo
			if(currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c<>NULL && currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c.equals('Demo')) {			  
			if(currentOpp.PSR_Trial_Start_Date__c==NULL){
		  Messagecount=Messagecount+1;
		   Errorinfo=Errorinfo+'Trial/Demo Start Date, ';
		   Errorinfo+=' \r\n';
		   }
			if(currentOpp.PSR_Trial_Duration__c==NULL){
		  Messagecount=Messagecount+1;
		   Errorinfo=Errorinfo+'Trial/Demo Duration, ';
		   Errorinfo+=' \r\n';
		   }
		   }
		   
		   
		   //FOC
		   if(currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c<>NULL && currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c.equals('Free of Charge')) {			  
		   if(String.IsEmpty(currentOpp.PSR_Is_Cost_Approved_In_Related_LOA_Opty__c)){
		  Messagecount=Messagecount+1;
		   Errorinfo=Errorinfo+'Is Cost Approved in Related LOA Opportunity, ';
		   Errorinfo+=' \r\n';
		   }
		   }
			
			if(currentOpp.PSR_is_BOM_BOQ_document_attached__c == false){
			   Messagecount=Messagecount+1;
			   Errorinfo=Errorinfo+ GlobalConstants.PRESALES_UPLOAD_FILE_ERROR;
			   Errorinfo+=' \r\n';
		   }	
		  /*Checking Required fields End*/  
			
		 String New_Loa_level;
		 String existing_LoA = currentopp.PSR_LoA_Level__c;
		 //PSRO_Calculate_BG_Cost calculateLoA = new PSRO_Calculate_BG_Cost();
		 currentOpp = PSRO_Calculate_BG_Cost.calculateLoAlevel(currentopp);

		   /*Other Validations start*/		  
			if(Messagecount==0)
		   {	 
			   //Req.5782 - Approval submission for level A PSRO limited by user role(offer controller)
			   if(GlobalConstants.LOA_Level.equalsIgnoreCase(currentOpp.PSR_LoA_Level__c)&& !UserInfo.getProfileId().equalsIgnoreCase(Label.System_Admin_Profile_ID) && !UserInfo.getProfileId().equalsIgnoreCase(Label.Nokia_Admin_Profile_Id) && !UserInfo.getProfileId().equalsIgnoreCase(Label.Global_Process_Admin_Profile_Id)){
				  Integer optyTeamMembercount = [SELECT count() FROM OpportunityTeamMember WHERE TeamMemberRole=:GlobalConstants.OFFER_CONTROL AND OpportunityId=:currentOpp.Id AND UserId=:Userinfo.getUserId() Limit : limitRows]; 
				if(optyTeamMembercount==0){
					Messagecount=Messagecount+1;
					if(currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c<>NULL && currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c.equals('Risk Order'))
						Errorinfo= Label.NF_PSRO_OC_RO;
					if(currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c<>NULL && (currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c.equals('Trial') || currentOpp.PSR_Pre_Sales_Risk_Opportunity_Type__c.equals('Demo')))
						Errorinfo= Label.NF_PSRO_OC_TD;
				}
			   }				  
			}
			/*Other Validations End */
			
			
				if(Messagecount>0){
				isAlreadyNotified = true;
			   ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,Errorinfo));
					   System.debug('Loop---'+Errorinfo);
					   return null;
				   }  
				   else 
				   {
					 PageReference myPAge;
					 if(existing_LoA != currentopp.PSR_LoA_Level__c)
					   {
						new_loa_level = currentopp.PSR_LoA_Level__c;
					   }
					 myPAge= Page.APTSCU_PreviewApproval;
					 myPAge.getParameters().put('sObjectId', currentOpp.Id);
					 mypage.getparameters().put('PSRLoAlevel',new_loa_level); 
					  
				   System.debug('NF_PRE_Error'+currentOpp.Id); 
				   return myPAge;				
				   }  
					   
		}   
					
					
					 
   
		
		
		
		 public PageReference cancel() {
		return new PageReference('/'+currentOppId);
		  }
	
	
	
	
	}