src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Group__c</fullName>
        <description>Select the Business Group (Req:152)</description>
        <label>Business Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Group_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Line_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Line Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NokiaCPQ_Portfolio_Package_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio Package Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Hierarchy</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This object stores Product Financial Structure data</description>
    <fields>
        <fullName>Business_Group_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Group Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Line_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Line Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Unit Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Package_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio Package Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>Product Financial Structure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Financial Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Business_Group_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CNS</fullName>
    </customValue>
    <customValue>
        <fullName>NI</fullName>
    </customValue>
    <customValue>
        <fullName>FN</fullName>
        <isActive>false</isActive>
        <label>FN</label>
    </customValue>
    <customValue>
        <fullName>ION</fullName>
        <isActive>false</isActive>
        <label>ION</label>
    </customValue>
    <customValue>
        <fullName>Financial Organization</fullName>
        <isActive>false</isActive>
        <label>Financial Organization</label>
    </customValue>
    <customValue>
        <fullName>GCVERT</fullName>
        <isActive>false</isActive>
        <label>GCVERT</label>
    </customValue>
    <customValue>
        <fullName>RB</fullName>
        <isActive>false</isActive>
        <label>RB</label>
    </customValue>
    <customValue>
        <fullName>GCMO</fullName>
        <isActive>false</isActive>
        <label>GCMO</label>
    </customValue>
    <customValue>
        <fullName>GCCTO</fullName>
        <isActive>false</isActive>
        <label>GCCTO</label>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
        <isActive>false</isActive>
        <label>GS</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <isActive>false</isActive>
        <label>NSW</label>
    </customValue>
    <customValue>
        <fullName>NEN</fullName>
        <isActive>false</isActive>
        <label>NEN</label>
    </customValue>
    <customValue>
        <fullName>RW</fullName>
        <isActive>false</isActive>
        <label>RW</label>
    </customValue>
    <customValue>
        <fullName>MNI</fullName>
        <isActive>false</isActive>
        <label>MNI</label>
    </customValue>
    <description>BG Values : Used in Opportunity, Product (Req :152) (Req:5537) Changed</description>
    <masterLabel>Business Group Values</masterLabel>
</GlobalValueSet>

src/classes/ProductTriggerHandler.cls
/*******************************
Class Name: ProductTriggerHandler
Created By: Accenture - October 2019
Last Modified By: Accenture
Last Modified Date: 10-10-2019
Description: Handler Class for Product Trigger 
*******************************/

public class ProductTriggerHandler {
	
	/*****************************
*Method Name: updateproductdata
*Description: This method is used to update product fields when product hierarchy is changed
*Parameters: Product List,Old Product Map,New Product Map  
*Created By: Accenture - October 2019
*Last Modified By: Accenture
*Last Modified Date: 10-10-2019
*******************************/
	
	public static void updateproductdata(map<Id,Product2> oldprodmap, map<Id,Product2> newprodmap){
		List<Product2> ProductList = new List<Product2>();
		Map<Id,Product_Hierarchy__c> hiermap = new Map<Id,Product_Hierarchy__c>();
		
		Set<Id> Producthierset=new Set<Id>();
		try{
			
			for(Product2 prod:newprodmap.values())
			{
				if(newprodmap.get(prod.Id).Product_Hierarchy__c <> oldprodmap.get(prod.Id).Product_Hierarchy__c)
				{
					Producthierset.add(prod.Product_Hierarchy__c);
					
				}
			}
			
			if(!Producthierset.isempty()){
				for(Product_Hierarchy__c Prodhierrec: [select Id, Business_Group_Code__c, Business_Unit_Code__c,Portfolio_Package_Code__c,Business_Line_Code__c from Product_Hierarchy__c where Id in :(Producthierset)])
				{
					hiermap.put(Prodhierrec.Id,Prodhierrec);
				}
			}
			
			for(Product2 pro:newprodmap.values())
			{
				if(hiermap.containskey(pro.Product_Hierarchy__c))
				{
					pro.Business_Group__c=hiermap.get(pro.Product_Hierarchy__c).Business_Group_Code__c;
					pro.Family=hiermap.get(pro.Product_Hierarchy__c).Business_Unit_Code__c;
					pro.NokiaCPQ_Portfolio_Package_Code__c=hiermap.get(pro.Product_Hierarchy__c).Portfolio_Package_Code__c;
					pro.Business_Line_Code__c=hiermap.get(pro.Product_Hierarchy__c).Business_Line_Code__c;
				}
			}
			
			/*if(!ProductList.isEmpty())
{
List<database.SaveResult> Updateresult = database.update(ProductList,false);
system.debug('Updateresult: '+Updateresult); 
}*/
			
		}
		
		catch(exception ex)
		{
			system.debug('exception'+ex.getMessage());
			ExceptionHandler.addException(ex,GlobalConstants.ProductTriggerHandler, GlobalConstants.PTH_updateproductdata);
		}   
	}
}